// Copyright (c) 2026 ScratchBird Software Inc.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// SPDX-License-Identifier: MPL-2.0

#include "postgresql_dialect.hpp"

#include <array>

namespace scratchbird::parser::postgresql {
namespace {

using scratchbird::parser::donor::MappingDisposition;
using scratchbird::parser::donor::OperationPattern;
using scratchbird::parser::donor::PatternMatch;
using scratchbird::parser::donor::SurfaceDescriptor;

constexpr std::string_view kSblrFamily = "sblr.donor.postgresql.profile.v1";

constexpr OperationPattern kPatterns[] = {
    {"COPY|| PROGRAM ", PatternMatch::kPrefixAndContains, "bulk_io",
     "postgresql.bulk_io.copy_program",
     MappingDisposition::kPolicyRefusal, "postgresql.policy.copy_program", "",
     "", "POSTGRESQL.AUTHORITY.PROGRAM_DENIED",
     "COPY PROGRAM cannot spawn host programs from parser authority.", true, false},
    {"COPY|| TO '", PatternMatch::kPrefixAndContains, "bulk_io",
     "postgresql.bulk_io.copy_to_file",
     MappingDisposition::kPolicyRefusal, "postgresql.policy.copy_to_file", "",
     "", "POSTGRESQL.AUTHORITY.FILE_IO_DENIED",
     "COPY TO file cannot perform donor filesystem writes.", true, false},
    {"COPY|| TO :'", PatternMatch::kPrefixAndContains, "bulk_io",
     "postgresql.bulk_io.copy_to_file",
     MappingDisposition::kPolicyRefusal, "postgresql.policy.copy_to_file", "",
     "", "POSTGRESQL.AUTHORITY.FILE_IO_DENIED",
     "COPY TO file cannot perform donor filesystem writes.", true, false},
    {"COPY|| FROM '", PatternMatch::kPrefixAndContains, "bulk_io",
     "postgresql.bulk_io.copy_from_file",
     MappingDisposition::kPolicyRefusal, "postgresql.policy.copy_from_file", "",
     "", "POSTGRESQL.AUTHORITY.FILE_IO_DENIED",
     "COPY FROM file requires a trusted ScratchBird import service.", true, false},
    {"COPY|| FROM :'", PatternMatch::kPrefixAndContains, "bulk_io",
     "postgresql.bulk_io.copy_from_file",
     MappingDisposition::kPolicyRefusal, "postgresql.policy.copy_from_file", "",
     "", "POSTGRESQL.AUTHORITY.FILE_IO_DENIED",
     "COPY FROM file requires a trusted ScratchBird import service.", true, false},
    {"COPY|| TO STDOUT", PatternMatch::kPrefixAndContains,
     "logical_stream_backup_restore", "postgresql.logical_stream.copy_to_stdout",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.copy_to_stdout",
     "SBLR_DONOR_POSTGRESQL_COPY_ROUTE", "ParserSupportCopyRoute",
     "POSTGRESQL.EMULATION.COPY_ROUTE",
     "COPY TO STDOUT is a remote logical export stream routed through trusted package policy.",
     true, false},
    {"COPY|| FROM STDIN", PatternMatch::kPrefixAndContains,
     "logical_stream_backup_restore",
     "postgresql.logical_stream.copy_from_stdin",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.copy_from_stdin",
     "SBLR_DONOR_POSTGRESQL_COPY_ROUTE", "ParserSupportCopyRoute",
     "POSTGRESQL.EMULATION.COPY_ROUTE",
     "COPY FROM STDIN is a remote logical import stream routed through trusted package policy.",
     true, false},
    {"COPY", PatternMatch::kPrefix, "bulk_io", "postgresql.bulk_io.copy",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.copy",
     "SBLR_DONOR_POSTGRESQL_COPY_ROUTE", "ParserSupportCopyRoute",
     "POSTGRESQL.EMULATION.COPY_ROUTE",
     "COPY routes through trusted package policy and cannot bypass engine admission.", true, false},
    {"LO_IMPORT", PatternMatch::kContainsFunctionCall, "large_object", "postgresql.large_object.lo_import",
     MappingDisposition::kPolicyRefusal, "postgresql.policy.large_object.import", "",
     "", "POSTGRESQL.AUTHORITY.FILE_IO_DENIED",
     "lo_import cannot read host files from parser authority.", true, false},
    {"LO_EXPORT", PatternMatch::kContainsFunctionCall, "large_object", "postgresql.large_object.lo_export",
     MappingDisposition::kPolicyRefusal, "postgresql.policy.large_object.export", "",
     "", "POSTGRESQL.AUTHORITY.FILE_IO_DENIED",
     "lo_export cannot write host files from parser authority.", true, false},
    {"LO_CREATE", PatternMatch::kContainsFunctionCall, "large_object", "postgresql.large_object.api",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.large_object",
     "SBLR_DONOR_POSTGRESQL_LARGE_OBJECT_ROUTE", "ParserSupportLargeObjectRoute",
     "POSTGRESQL.EMULATION.LARGE_OBJECT_ROUTE",
     "Large object APIs route through trusted package policy.", true, true},
    {"LO_CREAT", PatternMatch::kContainsFunctionCall, "large_object", "postgresql.large_object.api",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.large_object",
     "SBLR_DONOR_POSTGRESQL_LARGE_OBJECT_ROUTE", "ParserSupportLargeObjectRoute",
     "POSTGRESQL.EMULATION.LARGE_OBJECT_ROUTE",
     "Large object APIs route through trusted package policy.", true, true},
    {"LO_UNLINK", PatternMatch::kContainsFunctionCall, "large_object", "postgresql.large_object.api",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.large_object",
     "SBLR_DONOR_POSTGRESQL_LARGE_OBJECT_ROUTE", "ParserSupportLargeObjectRoute",
     "POSTGRESQL.EMULATION.LARGE_OBJECT_ROUTE",
     "Large object APIs route through trusted package policy.", true, true},
    {"LO_OPEN", PatternMatch::kContainsFunctionCall, "large_object", "postgresql.large_object.api",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.large_object",
     "SBLR_DONOR_POSTGRESQL_LARGE_OBJECT_ROUTE", "ParserSupportLargeObjectRoute",
     "POSTGRESQL.EMULATION.LARGE_OBJECT_ROUTE",
     "Large object APIs route through trusted package policy.", true, true},
    {"LO_CLOSE", PatternMatch::kContainsFunctionCall, "large_object", "postgresql.large_object.api",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.large_object",
     "SBLR_DONOR_POSTGRESQL_LARGE_OBJECT_ROUTE", "ParserSupportLargeObjectRoute",
     "POSTGRESQL.EMULATION.LARGE_OBJECT_ROUTE",
     "Large object APIs route through trusted package policy.", true, true},
    {"LO_READ", PatternMatch::kContainsFunctionCall, "large_object", "postgresql.large_object.api",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.large_object",
     "SBLR_DONOR_POSTGRESQL_LARGE_OBJECT_ROUTE", "ParserSupportLargeObjectRoute",
     "POSTGRESQL.EMULATION.LARGE_OBJECT_ROUTE",
     "Large object APIs route through trusted package policy.", true, true},
    {"LO_WRITE", PatternMatch::kContainsFunctionCall, "large_object", "postgresql.large_object.api",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.large_object",
     "SBLR_DONOR_POSTGRESQL_LARGE_OBJECT_ROUTE", "ParserSupportLargeObjectRoute",
     "POSTGRESQL.EMULATION.LARGE_OBJECT_ROUTE",
     "Large object APIs route through trusted package policy.", true, true},
    {"LO_LSEEK", PatternMatch::kContainsFunctionCall, "large_object", "postgresql.large_object.api",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.large_object",
     "SBLR_DONOR_POSTGRESQL_LARGE_OBJECT_ROUTE", "ParserSupportLargeObjectRoute",
     "POSTGRESQL.EMULATION.LARGE_OBJECT_ROUTE",
     "Large object APIs route through trusted package policy.", true, true},
    {"LO_LSEEK64", PatternMatch::kContainsFunctionCall, "large_object", "postgresql.large_object.api",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.large_object",
     "SBLR_DONOR_POSTGRESQL_LARGE_OBJECT_ROUTE", "ParserSupportLargeObjectRoute",
     "POSTGRESQL.EMULATION.LARGE_OBJECT_ROUTE",
     "Large object APIs route through trusted package policy.", true, true},
    {"LO_TELL", PatternMatch::kContainsFunctionCall, "large_object", "postgresql.large_object.api",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.large_object",
     "SBLR_DONOR_POSTGRESQL_LARGE_OBJECT_ROUTE", "ParserSupportLargeObjectRoute",
     "POSTGRESQL.EMULATION.LARGE_OBJECT_ROUTE",
     "Large object APIs route through trusted package policy.", true, true},
    {"LO_TELL64", PatternMatch::kContainsFunctionCall, "large_object", "postgresql.large_object.api",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.large_object",
     "SBLR_DONOR_POSTGRESQL_LARGE_OBJECT_ROUTE", "ParserSupportLargeObjectRoute",
     "POSTGRESQL.EMULATION.LARGE_OBJECT_ROUTE",
     "Large object APIs route through trusted package policy.", true, true},
    {"LO_TRUNCATE", PatternMatch::kContainsFunctionCall, "large_object", "postgresql.large_object.api",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.large_object",
     "SBLR_DONOR_POSTGRESQL_LARGE_OBJECT_ROUTE", "ParserSupportLargeObjectRoute",
     "POSTGRESQL.EMULATION.LARGE_OBJECT_ROUTE",
     "Large object APIs route through trusted package policy.", true, true},
    {"LO_TRUNCATE64", PatternMatch::kContainsFunctionCall, "large_object", "postgresql.large_object.api",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.large_object",
     "SBLR_DONOR_POSTGRESQL_LARGE_OBJECT_ROUTE", "ParserSupportLargeObjectRoute",
     "POSTGRESQL.EMULATION.LARGE_OBJECT_ROUTE",
     "Large object APIs route through trusted package policy.", true, true},
    {"LO_FROM_BYTEA", PatternMatch::kContainsFunctionCall, "large_object", "postgresql.large_object.api",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.large_object",
     "SBLR_DONOR_POSTGRESQL_LARGE_OBJECT_ROUTE", "ParserSupportLargeObjectRoute",
     "POSTGRESQL.EMULATION.LARGE_OBJECT_ROUTE",
     "Large object APIs route through trusted package policy.", true, true},
    {"LO_GET", PatternMatch::kContainsFunctionCall, "large_object", "postgresql.large_object.api",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.large_object",
     "SBLR_DONOR_POSTGRESQL_LARGE_OBJECT_ROUTE", "ParserSupportLargeObjectRoute",
     "POSTGRESQL.EMULATION.LARGE_OBJECT_ROUTE",
     "Large object APIs route through trusted package policy.", true, true},
    {"LO_PUT", PatternMatch::kContainsFunctionCall, "large_object", "postgresql.large_object.api",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.large_object",
     "SBLR_DONOR_POSTGRESQL_LARGE_OBJECT_ROUTE", "ParserSupportLargeObjectRoute",
     "POSTGRESQL.EMULATION.LARGE_OBJECT_ROUTE",
     "Large object APIs route through trusted package policy.", true, true},
    {"LOREAD", PatternMatch::kContainsFunctionCall, "large_object", "postgresql.large_object.api",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.large_object",
     "SBLR_DONOR_POSTGRESQL_LARGE_OBJECT_ROUTE", "ParserSupportLargeObjectRoute",
     "POSTGRESQL.EMULATION.LARGE_OBJECT_ROUTE",
     "Large object APIs route through trusted package policy.", true, true},
    {"LOWRITE", PatternMatch::kContainsFunctionCall, "large_object", "postgresql.large_object.api",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.large_object",
     "SBLR_DONOR_POSTGRESQL_LARGE_OBJECT_ROUTE", "ParserSupportLargeObjectRoute",
     "POSTGRESQL.EMULATION.LARGE_OBJECT_ROUTE",
     "Large object APIs route through trusted package policy.", true, true},
    {"CREATE EXTENSION", PatternMatch::kPrefix, "extension", "postgresql.extension.create",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.extension.create",
     "SBLR_DONOR_POSTGRESQL_EXTENSION_ROUTE", "ParserSupportExtensionRoute",
     "POSTGRESQL.EMULATION.EXTENSION_ROUTE",
     "Extension installation routes through trusted package policy.", true, false},
    {"ALTER EXTENSION", PatternMatch::kPrefix, "extension", "postgresql.extension.alter",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.extension.alter",
     "SBLR_DONOR_POSTGRESQL_EXTENSION_ROUTE", "ParserSupportExtensionRoute",
     "POSTGRESQL.EMULATION.EXTENSION_ROUTE",
     "Extension changes route through trusted package policy.", true, false},
    {"DROP EXTENSION", PatternMatch::kPrefix, "extension", "postgresql.extension.drop",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.extension.drop",
     "SBLR_DONOR_POSTGRESQL_EXTENSION_ROUTE", "ParserSupportExtensionRoute",
     "POSTGRESQL.EMULATION.EXTENSION_ROUTE",
     "Extension removal routes through trusted package policy.", true, false},
    {"CREATE FOREIGN DATA WRAPPER", PatternMatch::kPrefix, "connector", "postgresql.connector.fdw.create",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.connector.fdw.create",
     "SBLR_DONOR_POSTGRESQL_CONNECTOR_ROUTE", "ParserSupportConnectorRoute",
     "POSTGRESQL.EMULATION.CONNECTOR_ROUTE",
     "Foreign data wrapper operations route through the PostgreSQL donor UDR.", true, false},
    {"CREATE SERVER", PatternMatch::kPrefix, "connector", "postgresql.connector.server.create",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.connector.server.create",
     "SBLR_DONOR_POSTGRESQL_CONNECTOR_ROUTE", "ParserSupportConnectorRoute",
     "POSTGRESQL.EMULATION.CONNECTOR_ROUTE",
     "Foreign server operations route through the PostgreSQL donor UDR.", true, false},
    {"CREATE USER MAPPING", PatternMatch::kPrefix, "connector", "postgresql.connector.user_mapping.create",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.connector.user_mapping.create",
     "SBLR_DONOR_POSTGRESQL_CONNECTOR_ROUTE", "ParserSupportConnectorRoute",
     "POSTGRESQL.EMULATION.CONNECTOR_ROUTE",
     "Foreign user mapping operations route through the PostgreSQL donor UDR.", true, false},
    {"IMPORT FOREIGN SCHEMA", PatternMatch::kPrefix, "connector", "postgresql.connector.import_foreign_schema",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.connector.import_foreign_schema",
     "SBLR_DONOR_POSTGRESQL_CONNECTOR_ROUTE", "ParserSupportConnectorRoute",
     "POSTGRESQL.EMULATION.CONNECTOR_ROUTE",
     "Foreign schema import routes through the PostgreSQL donor UDR.", true, false},
    {"CREATE FOREIGN TABLE", PatternMatch::kPrefix, "connector", "postgresql.connector.foreign_table.create",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.connector.foreign_table.create",
     "SBLR_DONOR_POSTGRESQL_CONNECTOR_ROUTE", "ParserSupportConnectorRoute",
     "POSTGRESQL.EMULATION.CONNECTOR_ROUTE",
     "Foreign table creation routes through the PostgreSQL donor UDR.", true, false},
    {"CREATE PUBLICATION", PatternMatch::kPrefix, "logical_replication", "postgresql.replication.publication.create",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.replication.publication.create",
     "SBLR_DONOR_POSTGRESQL_REPLICATION_ROUTE", "ParserSupportReplicationRoute",
     "POSTGRESQL.EMULATION.REPLICATION_ROUTE",
     "Logical publication requests route through the PostgreSQL donor UDR.", true, false},
    {"CREATE SUBSCRIPTION", PatternMatch::kPrefix, "logical_replication", "postgresql.replication.subscription.create",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.replication.subscription.create",
     "SBLR_DONOR_POSTGRESQL_REPLICATION_ROUTE", "ParserSupportReplicationRoute",
     "POSTGRESQL.EMULATION.REPLICATION_ROUTE",
     "Logical subscription requests route through the PostgreSQL donor UDR.", true, false},
    {"ALTER SUBSCRIPTION", PatternMatch::kPrefix, "logical_replication", "postgresql.replication.subscription.alter",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.replication.subscription.alter",
     "SBLR_DONOR_POSTGRESQL_REPLICATION_ROUTE", "ParserSupportReplicationRoute",
     "POSTGRESQL.EMULATION.REPLICATION_ROUTE",
     "Logical subscription changes route through the PostgreSQL donor UDR.", true, false},
    {"DROP SUBSCRIPTION", PatternMatch::kPrefix, "logical_replication", "postgresql.replication.subscription.drop",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.replication.subscription.drop",
     "SBLR_DONOR_POSTGRESQL_REPLICATION_ROUTE", "ParserSupportReplicationRoute",
     "POSTGRESQL.EMULATION.REPLICATION_ROUTE",
     "Logical subscription removal routes through the PostgreSQL donor UDR.", true, false},
    {"CREATE TABLESPACE", PatternMatch::kPrefix, "storage_admin", "postgresql.storage.tablespace.create",
     MappingDisposition::kPolicyRefusal, "postgresql.policy.tablespace.create", "",
     "", "POSTGRESQL.AUTHORITY.TABLESPACE_DENIED",
     "Tablespace physical storage administration is not parser authority.", true, false},
    {"ALTER TABLESPACE", PatternMatch::kPrefix, "storage_admin", "postgresql.storage.tablespace.alter",
     MappingDisposition::kPolicyRefusal, "postgresql.policy.tablespace.alter", "",
     "", "POSTGRESQL.AUTHORITY.TABLESPACE_DENIED",
     "Tablespace physical storage administration is not parser authority.", true, false},
    {"DROP TABLESPACE", PatternMatch::kPrefix, "storage_admin", "postgresql.storage.tablespace.drop",
     MappingDisposition::kPolicyRefusal, "postgresql.policy.tablespace.drop", "",
     "", "POSTGRESQL.AUTHORITY.TABLESPACE_DENIED",
     "Tablespace physical storage administration is not parser authority.", true, false},
    {"ALTER SYSTEM", PatternMatch::kPrefix, "system_admin", "postgresql.system.alter_system",
     MappingDisposition::kPolicyRefusal, "postgresql.policy.alter_system", "",
     "", "POSTGRESQL.AUTHORITY.SYSTEM_DENIED",
     "ALTER SYSTEM is blocked from parser authority.", true, false},
    {"CHECKPOINT", PatternMatch::kPrefix, "system_admin", "postgresql.system.checkpoint",
     MappingDisposition::kUnsupportedRefusal, "postgresql.policy.unsupported.checkpoint",
     "", "", "POSTGRESQL.AUTHORITY.UNSUPPORTED_DENIED",
     "PostgreSQL CHECKPOINT is a donor low-level utility surface and is outside donor parser authority.",
     true, false},
    {"CREATE DATABASE", PatternMatch::kPrefix, "database_lifecycle", "postgresql.lifecycle.create_database",
     MappingDisposition::kScratchBirdLifecycleApi, "postgresql.lifecycle.create_database",
     "SBLR_LIFECYCLE_CREATE_DATABASE", "EngineCreateLifecycle", "", "", false, false},
    {"DROP DATABASE", PatternMatch::kPrefix, "database_lifecycle", "postgresql.lifecycle.drop_database",
     MappingDisposition::kScratchBirdLifecycleApi, "postgresql.lifecycle.drop_database",
     "SBLR_LIFECYCLE_DROP_DATABASE", "EngineDropLifecycle", "", "", true, false},
    {"CREATE ROLE", PatternMatch::kPrefix, "security", "postgresql.security.create_role",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.security.create_role",
     "SBLR_DONOR_POSTGRESQL_SECURITY_ROUTE", "ParserSupportSecurityRoute",
     "POSTGRESQL.EMULATION.SECURITY_ROUTE",
     "Role management routes through trusted security policy.", true, false},
    {"ALTER ROLE", PatternMatch::kPrefix, "security", "postgresql.security.alter_role",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.security.alter_role",
     "SBLR_DONOR_POSTGRESQL_SECURITY_ROUTE", "ParserSupportSecurityRoute",
     "POSTGRESQL.EMULATION.SECURITY_ROUTE",
     "Role management routes through trusted security policy.", true, false},
    {"DROP ROLE", PatternMatch::kPrefix, "security", "postgresql.security.drop_role",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.security.drop_role",
     "SBLR_DONOR_POSTGRESQL_SECURITY_ROUTE", "ParserSupportSecurityRoute",
     "POSTGRESQL.EMULATION.SECURITY_ROUTE",
     "Role management routes through trusted security policy.", true, false},
    {"CREATE USER", PatternMatch::kPrefix, "security", "postgresql.security.create_user",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.security.create_user",
     "SBLR_DONOR_POSTGRESQL_SECURITY_ROUTE", "ParserSupportSecurityRoute",
     "POSTGRESQL.EMULATION.SECURITY_ROUTE",
     "User management routes through trusted security policy.", true, false},
    {"GRANT", PatternMatch::kPrefix, "security", "postgresql.security.grant",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.security.grant",
     "SBLR_DONOR_POSTGRESQL_SECURITY_ROUTE", "ParserSupportSecurityRoute",
     "POSTGRESQL.EMULATION.SECURITY_ROUTE",
     "Privilege changes route through trusted security policy.", true, false},
    {"REVOKE", PatternMatch::kPrefix, "security", "postgresql.security.revoke",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.security.revoke",
     "SBLR_DONOR_POSTGRESQL_SECURITY_ROUTE", "ParserSupportSecurityRoute",
     "POSTGRESQL.EMULATION.SECURITY_ROUTE",
     "Privilege changes route through trusted security policy.", true, false},
    {"CREATE POLICY", PatternMatch::kPrefix, "security", "postgresql.security.row_policy.create",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.security.policy.create",
     "SBLR_DONOR_POSTGRESQL_SECURITY_ROUTE", "ParserSupportSecurityRoute",
     "POSTGRESQL.EMULATION.SECURITY_ROUTE",
     "Row-level security policy routes through trusted security policy.", true, false},
    {"CREATE FUNCTION", PatternMatch::kPrefix, "routine", "postgresql.routine.function.create",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.routine.function.create",
     "SBLR_DONOR_POSTGRESQL_ROUTINE_ROUTE", "ParserSupportRoutineRoute",
     "POSTGRESQL.EMULATION.ROUTINE_ROUTE",
     "Functions route through trusted routine package policy.", true, false},
    {"CREATE PROCEDURE", PatternMatch::kPrefix, "routine", "postgresql.routine.procedure.create",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.routine.procedure.create",
     "SBLR_DONOR_POSTGRESQL_ROUTINE_ROUTE", "ParserSupportRoutineRoute",
     "POSTGRESQL.EMULATION.ROUTINE_ROUTE",
     "Procedures route through trusted routine package policy.", true, false},
    {"CREATE TRIGGER", PatternMatch::kPrefix, "routine", "postgresql.routine.trigger.create",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.routine.trigger.create",
     "SBLR_DONOR_POSTGRESQL_ROUTINE_ROUTE", "ParserSupportRoutineRoute",
     "POSTGRESQL.EMULATION.ROUTINE_ROUTE",
     "Triggers route through trusted routine package policy.", true, false},
    {"CREATE RULE", PatternMatch::kPrefix, "routine", "postgresql.routine.rule.create",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.routine.rule.create",
     "SBLR_DONOR_POSTGRESQL_ROUTINE_ROUTE", "ParserSupportRoutineRoute",
     "POSTGRESQL.EMULATION.ROUTINE_ROUTE",
     "Rules route through trusted routine package policy.", true, false},
    {"DO", PatternMatch::kPrefix, "routine", "postgresql.routine.do_block",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.routine.do_block",
     "SBLR_DONOR_POSTGRESQL_ROUTINE_ROUTE", "ParserSupportRoutineRoute",
     "POSTGRESQL.EMULATION.ROUTINE_ROUTE",
     "Anonymous code blocks route through trusted routine package policy.", true, false},
    {"CALL", PatternMatch::kPrefix, "routine", "postgresql.routine.call",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.routine.call",
     "SBLR_DONOR_POSTGRESQL_ROUTINE_ROUTE", "ParserSupportRoutineRoute",
     "POSTGRESQL.EMULATION.ROUTINE_ROUTE",
     "Procedure calls route through trusted routine package policy.", true, true},
    {"LISTEN", PatternMatch::kPrefix, "events", "postgresql.events.listen",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.events.listen",
     "SBLR_DONOR_POSTGRESQL_EVENT_ROUTE", "ParserSupportEventRoute",
     "POSTGRESQL.EMULATION.EVENT_ROUTE",
     "LISTEN routes through trusted event policy.", true, false},
    {"NOTIFY", PatternMatch::kPrefix, "events", "postgresql.events.notify",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.events.notify",
     "SBLR_DONOR_POSTGRESQL_EVENT_ROUTE", "ParserSupportEventRoute",
     "POSTGRESQL.EMULATION.EVENT_ROUTE",
     "NOTIFY routes through trusted event policy.", true, true},
    {"UNLISTEN", PatternMatch::kPrefix, "events", "postgresql.events.unlisten",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.events.unlisten",
     "SBLR_DONOR_POSTGRESQL_EVENT_ROUTE", "ParserSupportEventRoute",
     "POSTGRESQL.EMULATION.EVENT_ROUTE",
     "UNLISTEN routes through trusted event policy.", true, false},
    {"VACUUM", PatternMatch::kPrefix, "maintenance", "postgresql.maintenance.vacuum",
     MappingDisposition::kUnsupportedRefusal, "postgresql.policy.unsupported.vacuum",
     "", "", "POSTGRESQL.AUTHORITY.UNSUPPORTED_DENIED",
     "PostgreSQL VACUUM is a donor low-level utility surface and is outside donor parser authority.",
     true, false},
    {"ANALYZE", PatternMatch::kPrefix, "maintenance", "postgresql.maintenance.analyze",
     MappingDisposition::kUnsupportedRefusal, "postgresql.policy.unsupported.analyze",
     "", "", "POSTGRESQL.AUTHORITY.UNSUPPORTED_DENIED",
     "PostgreSQL ANALYZE is a donor low-level utility surface and is outside donor parser authority.",
     true, false},
    {"REINDEX", PatternMatch::kPrefix, "maintenance", "postgresql.maintenance.reindex",
     MappingDisposition::kUnsupportedRefusal, "postgresql.policy.unsupported.reindex",
     "", "", "POSTGRESQL.AUTHORITY.UNSUPPORTED_DENIED",
     "PostgreSQL REINDEX is a donor low-level utility surface and is outside donor parser authority.",
     true, false},
    {"CLUSTER", PatternMatch::kPrefix, "maintenance", "postgresql.maintenance.cluster",
     MappingDisposition::kUnsupportedRefusal, "postgresql.policy.unsupported.cluster",
     "", "", "POSTGRESQL.AUTHORITY.UNSUPPORTED_DENIED",
     "PostgreSQL CLUSTER is a donor low-level utility surface and is outside donor parser authority.",
     true, false},
    {"REFRESH MATERIALIZED VIEW", PatternMatch::kPrefix, "maintenance", "postgresql.maintenance.refresh_materialized_view",
     MappingDisposition::kUnsupportedRefusal,
     "postgresql.policy.unsupported.refresh_materialized_view",
     "", "", "POSTGRESQL.AUTHORITY.UNSUPPORTED_DENIED",
     "PostgreSQL REFRESH MATERIALIZED VIEW is a donor low-level utility surface and is outside donor parser authority.",
     true, true},
    {"EXPLAIN", PatternMatch::kPrefix, "optimizer", "postgresql.optimizer.explain",
     MappingDisposition::kCatalogProjection, "postgresql.optimizer.explain",
     "SBLR_DONOR_POSTGRESQL_EXPLAIN", "EngineExplainPlan", "", "", false, false},
    {"SHOW", PatternMatch::kPrefix, "catalog_overlay", "postgresql.catalog_overlay.show",
     MappingDisposition::kCatalogProjection, "postgresql.catalog.show",
     "SBLR_DONOR_POSTGRESQL_CATALOG_PROJECT", "EngineCatalogProjection", "", "", false, false},
    {"SET", PatternMatch::kPrefix, "session", "postgresql.session.set",
     MappingDisposition::kAdmittedSblr, "postgresql.session.set",
     "SBLR_DONOR_POSTGRESQL_SET", "EngineSessionSet", "", "", false, false},
    {"RESET", PatternMatch::kPrefix, "session", "postgresql.session.reset",
     MappingDisposition::kAdmittedSblr, "postgresql.session.reset",
     "SBLR_DONOR_POSTGRESQL_RESET", "EngineSessionReset", "", "", false, false},
    {"DISCARD", PatternMatch::kPrefix, "session", "postgresql.session.discard",
     MappingDisposition::kAdmittedSblr, "postgresql.session.discard",
     "SBLR_DONOR_POSTGRESQL_DISCARD", "EngineSessionDiscard", "", "", false, false},
    {"BEGIN", PatternMatch::kPrefix, "transaction", "postgresql.transaction.begin",
     MappingDisposition::kAdmittedSblr, "postgresql.transaction.begin",
     "SBLR_TRANSACTION_BEGIN", "EngineBeginTransaction", "", "", false, false},
    {"START TRANSACTION", PatternMatch::kPrefix, "transaction", "postgresql.transaction.start",
     MappingDisposition::kAdmittedSblr, "postgresql.transaction.start",
     "SBLR_TRANSACTION_BEGIN", "EngineBeginTransaction", "", "", false, false},
    {"COMMIT", PatternMatch::kPrefix, "transaction", "postgresql.transaction.commit",
     MappingDisposition::kAdmittedSblr, "postgresql.transaction.commit",
     "SBLR_TRANSACTION_COMMIT", "EngineCommitTransaction", "", "", false, true},
    {"ROLLBACK TO SAVEPOINT", PatternMatch::kPrefix, "transaction", "postgresql.transaction.rollback_to_savepoint",
     MappingDisposition::kAdmittedSblr, "postgresql.transaction.rollback_to_savepoint",
     "SBLR_TRANSACTION_ROLLBACK_TO_SAVEPOINT", "EngineRollbackToSavepoint", "", "", false, true},
    {"ROLLBACK WORK TO SAVEPOINT", PatternMatch::kPrefix, "transaction", "postgresql.transaction.rollback_to_savepoint",
     MappingDisposition::kAdmittedSblr, "postgresql.transaction.rollback_to_savepoint",
     "SBLR_TRANSACTION_ROLLBACK_TO_SAVEPOINT", "EngineRollbackToSavepoint", "", "", false, true},
    {"ROLLBACK WORK TO", PatternMatch::kPrefix, "transaction", "postgresql.transaction.rollback_to_savepoint",
     MappingDisposition::kAdmittedSblr, "postgresql.transaction.rollback_to_savepoint",
     "SBLR_TRANSACTION_ROLLBACK_TO_SAVEPOINT", "EngineRollbackToSavepoint", "", "", false, true},
    {"ROLLBACK TRANSACTION TO SAVEPOINT", PatternMatch::kPrefix, "transaction", "postgresql.transaction.rollback_to_savepoint",
     MappingDisposition::kAdmittedSblr, "postgresql.transaction.rollback_to_savepoint",
     "SBLR_TRANSACTION_ROLLBACK_TO_SAVEPOINT", "EngineRollbackToSavepoint", "", "", false, true},
    {"ROLLBACK TRANSACTION TO", PatternMatch::kPrefix, "transaction", "postgresql.transaction.rollback_to_savepoint",
     MappingDisposition::kAdmittedSblr, "postgresql.transaction.rollback_to_savepoint",
     "SBLR_TRANSACTION_ROLLBACK_TO_SAVEPOINT", "EngineRollbackToSavepoint", "", "", false, true},
    {"ROLLBACK TO", PatternMatch::kPrefix, "transaction", "postgresql.transaction.rollback_to_savepoint",
     MappingDisposition::kAdmittedSblr, "postgresql.transaction.rollback_to_savepoint",
     "SBLR_TRANSACTION_ROLLBACK_TO_SAVEPOINT", "EngineRollbackToSavepoint", "", "", false, true},
    {"ROLLBACK", PatternMatch::kPrefix, "transaction", "postgresql.transaction.rollback",
     MappingDisposition::kAdmittedSblr, "postgresql.transaction.rollback",
     "SBLR_TRANSACTION_ROLLBACK", "EngineRollbackTransaction", "", "", false, true},
    {"SAVEPOINT", PatternMatch::kPrefix, "transaction", "postgresql.transaction.savepoint",
     MappingDisposition::kAdmittedSblr, "postgresql.transaction.savepoint",
     "SBLR_TRANSACTION_SAVEPOINT", "EngineSavepoint", "", "", false, true},
    {"RELEASE SAVEPOINT", PatternMatch::kPrefix, "transaction", "postgresql.transaction.release_savepoint",
     MappingDisposition::kAdmittedSblr, "postgresql.transaction.release_savepoint",
     "SBLR_TRANSACTION_RELEASE_SAVEPOINT", "EngineReleaseSavepoint", "", "", false, true},
    {"PREPARE TRANSACTION", PatternMatch::kPrefix, "transaction", "postgresql.transaction.prepare_transaction",
     MappingDisposition::kUnsupportedRefusal, "postgresql.policy.transaction.prepare_transaction",
     "", "", "POSTGRESQL.AUTHORITY.PREPARE_TRANSACTION_DENIED",
     "Two-phase transaction finality is not admitted by the parser.", true, true},
    {"PREPARE", PatternMatch::kPrefix, "prepared_statement", "postgresql.prepared.prepare",
     MappingDisposition::kAdmittedSblr, "postgresql.prepared.prepare",
     "SBLR_DONOR_POSTGRESQL_PREPARE", "EnginePrepareStatement", "", "", false, false},
    {"EXECUTE", PatternMatch::kPrefix, "prepared_statement", "postgresql.prepared.execute",
     MappingDisposition::kAdmittedSblr, "postgresql.prepared.execute",
     "SBLR_DONOR_POSTGRESQL_EXECUTE", "EngineExecuteStatement", "", "", false, true},
    {"DEALLOCATE", PatternMatch::kPrefix, "prepared_statement", "postgresql.prepared.deallocate",
     MappingDisposition::kAdmittedSblr, "postgresql.prepared.deallocate",
     "SBLR_DONOR_POSTGRESQL_DEALLOCATE", "EngineDeallocateStatement", "", "", false, false},
    {"DECLARE", PatternMatch::kPrefix, "cursor", "postgresql.cursor.declare",
     MappingDisposition::kAdmittedSblr, "postgresql.cursor.declare",
     "SBLR_DONOR_POSTGRESQL_CURSOR_DECLARE", "EngineCursorDeclare", "", "", false, true},
    {"FETCH", PatternMatch::kPrefix, "cursor", "postgresql.cursor.fetch",
     MappingDisposition::kAdmittedSblr, "postgresql.cursor.fetch",
     "SBLR_DONOR_POSTGRESQL_CURSOR_FETCH", "EngineCursorFetch", "", "", false, true},
    {"MOVE", PatternMatch::kPrefix, "cursor", "postgresql.cursor.move",
     MappingDisposition::kAdmittedSblr, "postgresql.cursor.move",
     "SBLR_DONOR_POSTGRESQL_CURSOR_MOVE", "EngineCursorMove", "", "", false, true},
    {"CLOSE", PatternMatch::kPrefix, "cursor", "postgresql.cursor.close",
     MappingDisposition::kAdmittedSblr, "postgresql.cursor.close",
     "SBLR_DONOR_POSTGRESQL_CURSOR_CLOSE", "EngineCursorClose", "", "", false, true},
    {"LOCK TABLE", PatternMatch::kPrefix, "locking", "postgresql.locking.lock_table",
     MappingDisposition::kAdmittedSblr, "postgresql.locking.lock_table",
     "SBLR_DONOR_POSTGRESQL_LOCK_TABLE", "EngineLockTable", "", "", true, true},
    {"SECURITY LABEL", PatternMatch::kPrefix, "security", "postgresql.security.security_label",
     MappingDisposition::kParserSupportUdr, "postgresql.udr.security.security_label",
     "SBLR_DONOR_POSTGRESQL_SECURITY_ROUTE", "ParserSupportSecurityRoute",
     "POSTGRESQL.EMULATION.SECURITY_ROUTE",
     "Security labels route through trusted security policy.", true, true},
    {"CREATE UNIQUE INDEX", PatternMatch::kPrefix, "ddl", "postgresql.ddl.create.unique_index",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.create.unique_index",
     "SBLR_DONOR_POSTGRESQL_INDEX_CREATE", "EngineDdlCreateIndex", "", "", true, true},
    {"CREATE INDEX", PatternMatch::kPrefix, "ddl", "postgresql.ddl.create.index",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.create.index",
     "SBLR_DONOR_POSTGRESQL_INDEX_CREATE", "EngineDdlCreateIndex", "", "", true, true},
    {"ALTER INDEX", PatternMatch::kPrefix, "ddl", "postgresql.ddl.alter.index",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.alter.index",
     "SBLR_DONOR_POSTGRESQL_INDEX_ALTER", "EngineDdlAlterIndex", "", "", true, true},
    {"CREATE OR REPLACE VIEW", PatternMatch::kPrefix, "ddl", "postgresql.ddl.create_or_replace.view",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.create_or_replace.view",
     "SBLR_DONOR_POSTGRESQL_VIEW_CREATE_OR_REPLACE", "EngineDdlCreateOrReplaceView",
     "", "", true, true},
    {"CREATE MATERIALIZED VIEW", PatternMatch::kPrefix, "ddl", "postgresql.ddl.create.materialized_view",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.create.materialized_view",
     "SBLR_DONOR_POSTGRESQL_MATERIALIZED_VIEW_CREATE", "EngineDdlCreateMaterializedView",
     "", "", true, true},
    {"CREATE VIEW", PatternMatch::kPrefix, "ddl", "postgresql.ddl.create.view",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.create.view",
     "SBLR_DONOR_POSTGRESQL_VIEW_CREATE", "EngineDdlCreateView", "", "", true, true},
    {"CREATE LOCAL TEMPORARY TABLE", PatternMatch::kPrefix, "ddl", "postgresql.ddl.create.local_temporary_table",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.create.local_temporary_table",
     "SBLR_DONOR_POSTGRESQL_TEMPORARY_TABLE_CREATE", "EngineDdlCreateTemporaryTable",
     "", "", true, true},
    {"CREATE LOCAL TEMP TABLE", PatternMatch::kPrefix, "ddl", "postgresql.ddl.create.local_temporary_table",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.create.local_temporary_table",
     "SBLR_DONOR_POSTGRESQL_TEMPORARY_TABLE_CREATE", "EngineDdlCreateTemporaryTable",
     "", "", true, true},
    {"CREATE GLOBAL TEMPORARY TABLE", PatternMatch::kPrefix, "ddl", "postgresql.ddl.create.global_temporary_table",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.create.global_temporary_table",
     "SBLR_DONOR_POSTGRESQL_TEMPORARY_TABLE_CREATE", "EngineDdlCreateTemporaryTable",
     "", "", true, true},
    {"CREATE GLOBAL TEMP TABLE", PatternMatch::kPrefix, "ddl", "postgresql.ddl.create.global_temporary_table",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.create.global_temporary_table",
     "SBLR_DONOR_POSTGRESQL_TEMPORARY_TABLE_CREATE", "EngineDdlCreateTemporaryTable",
     "", "", true, true},
    {"CREATE TEMPORARY TABLE", PatternMatch::kPrefix, "ddl", "postgresql.ddl.create.temporary_table",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.create.temporary_table",
     "SBLR_DONOR_POSTGRESQL_TEMPORARY_TABLE_CREATE", "EngineDdlCreateTemporaryTable",
     "", "", true, true},
    {"CREATE TEMP TABLE", PatternMatch::kPrefix, "ddl", "postgresql.ddl.create.temporary_table",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.create.temporary_table",
     "SBLR_DONOR_POSTGRESQL_TEMPORARY_TABLE_CREATE", "EngineDdlCreateTemporaryTable",
     "", "", true, true},
    {"CREATE", PatternMatch::kPrefix, "ddl", "postgresql.ddl.create",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.create",
     "SBLR_DONOR_POSTGRESQL_DDL_CREATE", "EngineDdlCreate", "", "", true, true},
    {"ALTER MATERIALIZED VIEW", PatternMatch::kPrefix, "ddl", "postgresql.ddl.alter.materialized_view",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.alter.materialized_view",
     "SBLR_DONOR_POSTGRESQL_MATERIALIZED_VIEW_ALTER", "EngineDdlAlterMaterializedView",
     "", "", true, true},
    {"ALTER VIEW", PatternMatch::kPrefix, "ddl", "postgresql.ddl.alter.view",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.alter.view",
     "SBLR_DONOR_POSTGRESQL_VIEW_ALTER", "EngineDdlAlterView", "", "", true, true},
    {"ALTER", PatternMatch::kPrefix, "ddl", "postgresql.ddl.alter",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.alter",
     "SBLR_DONOR_POSTGRESQL_DDL_ALTER", "EngineDdlAlter", "", "", true, true},
    {"DROP TABLE PG_TEMP.", PatternMatch::kContains, "ddl", "postgresql.ddl.drop.temporary_table",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.drop.temporary_table",
     "SBLR_DONOR_POSTGRESQL_TEMPORARY_TABLE_DROP", "EngineDdlDropTemporaryTable",
     "", "", true, true},
    {"DROP MATERIALIZED VIEW", PatternMatch::kPrefix, "ddl", "postgresql.ddl.drop.materialized_view",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.drop.materialized_view",
     "SBLR_DONOR_POSTGRESQL_MATERIALIZED_VIEW_DROP", "EngineDdlDropMaterializedView",
     "", "", true, true},
    {"DROP VIEW", PatternMatch::kPrefix, "ddl", "postgresql.ddl.drop.view",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.drop.view",
     "SBLR_DONOR_POSTGRESQL_VIEW_DROP", "EngineDdlDropView", "", "", true, true},
    {"DROP", PatternMatch::kPrefix, "ddl", "postgresql.ddl.drop",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.drop",
     "SBLR_DONOR_POSTGRESQL_DDL_DROP", "EngineDdlDrop", "", "", true, true},
    {"COMMENT", PatternMatch::kPrefix, "ddl", "postgresql.ddl.comment",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.comment",
     "SBLR_DONOR_POSTGRESQL_DDL_COMMENT", "EngineDdlComment", "", "", true, true},
    {"TRUNCATE", PatternMatch::kPrefix, "ddl", "postgresql.ddl.truncate",
     MappingDisposition::kAdmittedSblr, "postgresql.ddl.truncate",
     "SBLR_DONOR_POSTGRESQL_DDL_TRUNCATE", "EngineDdlTruncate", "", "", true, true},
    {"MERGE", PatternMatch::kPrefix, "dml", "postgresql.dml.merge",
     MappingDisposition::kAdmittedSblr, "postgresql.dml.merge",
     "SBLR_DONOR_POSTGRESQL_MERGE", "EngineDmlMerge", "", "", false, true},
    {"INSERT", PatternMatch::kPrefix, "dml", "postgresql.dml.insert",
     MappingDisposition::kAdmittedSblr, "postgresql.dml.insert",
     "SBLR_DONOR_POSTGRESQL_INSERT", "EngineDmlInsert", "", "", false, true},
    {"UPDATE", PatternMatch::kPrefix, "dml", "postgresql.dml.update",
     MappingDisposition::kAdmittedSblr, "postgresql.dml.update",
     "SBLR_DONOR_POSTGRESQL_UPDATE", "EngineDmlUpdate", "", "", false, true},
    {"DELETE", PatternMatch::kPrefix, "dml", "postgresql.dml.delete",
     MappingDisposition::kAdmittedSblr, "postgresql.dml.delete",
     "SBLR_DONOR_POSTGRESQL_DELETE", "EngineDmlDelete", "", "", false, true},
    {"SELECT", PatternMatch::kPrefix, "query", "postgresql.query.select",
     MappingDisposition::kAdmittedSblr, "postgresql.query.select",
     "SBLR_DONOR_POSTGRESQL_SELECT", "EngineQuerySelect", "", "", false, false},
    {"WITH", PatternMatch::kPrefix, "query", "postgresql.query.with",
     MappingDisposition::kAdmittedSblr, "postgresql.query.with",
     "SBLR_DONOR_POSTGRESQL_SELECT", "EngineQuerySelect", "", "", false, false},
};

const std::array<SurfaceDescriptor, 12> kDatatypeSurfaces{{
    {"numeric", "SMALLINT;INTEGER;BIGINT;NUMERIC;DECIMAL;REAL;DOUBLE PRECISION;MONEY", "descriptor"},
    {"serial_identity", "SMALLSERIAL;SERIAL;BIGSERIAL;IDENTITY", "descriptor_policy"},
    {"text", "CHAR;VARCHAR;TEXT;NAME", "descriptor"},
    {"binary", "BYTEA", "descriptor"},
    {"temporal", "DATE;TIME;TIMETZ;TIMESTAMP;TIMESTAMPTZ;INTERVAL", "descriptor"},
    {"boolean_uuid", "BOOLEAN;UUID", "descriptor"},
    {"json_xml", "JSON;JSONB;JSONPATH;XML", "descriptor"},
    {"array", "ARRAY;[]", "descriptor"},
    {"range_multirange", "INT4RANGE;INT8RANGE;NUMRANGE;DATERANGE;TSRANGE;TSTZRANGE", "parser_support_udr"},
    {"network", "CIDR;INET;MACADDR;MACADDR8", "descriptor"},
    {"geometric", "POINT;LINE;LSEG;BOX;PATH;POLYGON;CIRCLE", "parser_support_udr"},
    {"domain_enum_composite", "DOMAIN;ENUM;COMPOSITE", "catalog_policy"},
}};

const std::array<SurfaceDescriptor, 13> kBuiltinSurfaces{{
    {"aggregate", "COUNT;SUM;AVG;MIN;MAX;STRING_AGG;ARRAY_AGG;JSON_AGG", "sblr"},
    {"window", "ROW_NUMBER;RANK;DENSE_RANK;LAG;LEAD;NTILE", "sblr"},
    {"string", "LOWER;UPPER;SUBSTRING;TRIM;POSITION;OVERLAY", "sblr"},
    {"numeric", "ABS;ROUND;POWER;SQRT;MOD;WIDTH_BUCKET", "sblr"},
    {"temporal", "NOW;CURRENT_TIMESTAMP;DATE_PART;DATE_TRUNC;EXTRACT", "sblr"},
    {"json", "JSONB_*;JSON_*", "parser_support_udr"},
    {"array", "ARRAY_APPEND;ARRAY_REMOVE;UNNEST", "parser_support_udr"},
    {"fulltext", "TO_TSVECTOR;TO_TSQUERY;TS_RANK", "sblr_optional"},
    {"uuid", "GEN_RANDOM_UUID;UUID_*", "parser_support_udr"},
    {"large_object", "LO_*", "parser_support_udr"},
    {"security", "CURRENT_USER;SESSION_USER;CURRENT_ROLE", "catalog_projection"},
    {"catalog", "PG_*_IS_VISIBLE;FORMAT_TYPE", "catalog_projection"},
    {"extension", "extension-defined functions", "trusted_package_or_refusal"},
}};

const std::array<SurfaceDescriptor, 9> kCatalogSurfaces{{
    {"pg_catalog", "PG_CATALOG.", "catalog_projection"},
    {"information_schema", "INFORMATION_SCHEMA.", "catalog_projection"},
    {"statistics", "PG_STAT_;PG_STATIO_;PG_STATISTIC", "catalog_projection"},
    {"roles_security", "PG_AUTHID;PG_ROLES;PG_POLICY", "catalog_projection"},
    {"namespace_relation", "PG_NAMESPACE;PG_CLASS;PG_ATTRIBUTE;PG_TYPE", "catalog_projection"},
    {"proc_language", "PG_PROC;PG_LANGUAGE;PG_TRIGGER;PG_REWRITE", "catalog_projection"},
    {"extension", "PG_EXTENSION;PG_DEPEND;PG_DESCRIPTION", "catalog_projection"},
    {"replication", "PG_PUBLICATION;PG_SUBSCRIPTION;PG_REPLICATION_SLOTS", "catalog_projection"},
    {"fdw", "PG_FOREIGN_DATA_WRAPPER;PG_FOREIGN_SERVER;PG_USER_MAPPING", "catalog_projection"},
}};

const std::array<SurfaceDescriptor, 12> kDiagnosticSurfaces{{
    {"parse", "POSTGRESQL.PARSE.INVALID_INPUT;POSTGRESQL.PARSE.UNSUPPORTED_SURFACE", "parser"},
    {"file", "POSTGRESQL.AUTHORITY.FILE_IO_DENIED", "fail_closed"},
    {"program", "POSTGRESQL.AUTHORITY.PROGRAM_DENIED", "fail_closed"},
    {"tablespace", "POSTGRESQL.AUTHORITY.TABLESPACE_DENIED", "fail_closed"},
    {"system", "POSTGRESQL.AUTHORITY.SYSTEM_DENIED;POSTGRESQL.AUTHORITY.UNSUPPORTED_DENIED", "fail_closed"},
    {"copy", "POSTGRESQL.EMULATION.COPY_ROUTE", "parser_support_udr"},
    {"extension", "POSTGRESQL.EMULATION.EXTENSION_ROUTE", "parser_support_udr"},
    {"connector", "POSTGRESQL.EMULATION.CONNECTOR_ROUTE", "parser_support_udr"},
    {"replication", "POSTGRESQL.EMULATION.REPLICATION_ROUTE", "parser_support_udr"},
    {"maintenance", "POSTGRESQL.AUTHORITY.UNSUPPORTED_DENIED", "fail_closed"},
    {"security", "POSTGRESQL.EMULATION.SECURITY_ROUTE", "parser_support_udr"},
    {"transaction", "POSTGRESQL.AUTHORITY.PREPARE_TRANSACTION_DENIED", "fail_closed"},
}};

const scratchbird::parser::donor::DialectProfile kProfile{
    "postgresql",
    "PostgreSQL",
    "sbp_postgresql",
    "sbup_postgresql",
    "18.3",
    "POSTGRESQL",
    kSblrFamily,
    kPatterns,
    kDatatypeSurfaces,
    kBuiltinSurfaces,
    kCatalogSurfaces,
    kDiagnosticSurfaces,
    19,
    2406,
    2286,
    108,
    0,
    12,
    0,
    0,
    0,
};

} // namespace

const scratchbird::parser::donor::DialectProfile& Profile() {
  return kProfile;
}

std::string TrimAscii(std::string_view text) {
  return scratchbird::parser::donor::TrimAscii(text);
}

std::string NormalizeWhitespace(std::string_view text) {
  return scratchbird::parser::donor::NormalizeWhitespace(text);
}

std::string ToUpperAscii(std::string_view text) {
  return scratchbird::parser::donor::ToUpperAscii(text);
}

std::string MessageVectorToJson(const std::vector<Diagnostic>& diagnostics) {
  return scratchbird::parser::donor::MessageVectorToJson(diagnostics);
}

std::vector<Token> LexTokens(std::string_view sql_text) {
  return scratchbird::parser::donor::LexTokens(sql_text);
}

ParseResult ParseStatement(std::string_view sql_text) {
  return scratchbird::parser::donor::ParseStatement(sql_text, kProfile);
}

std::span<const SurfaceDescriptor> DatatypeSurfaces() {
  return kDatatypeSurfaces;
}

std::span<const SurfaceDescriptor> BuiltinFunctionSurfaces() {
  return kBuiltinSurfaces;
}

std::span<const SurfaceDescriptor> CatalogOverlaySurfaces() {
  return kCatalogSurfaces;
}

std::span<const SurfaceDescriptor> DiagnosticSurfaces() {
  return kDiagnosticSurfaces;
}

std::string PostgresqlPackageIdentityJson() {
  return scratchbird::parser::donor::PackageIdentityJson(kProfile);
}

std::string PostgresqlSurfaceReportJson() {
  return scratchbird::parser::donor::SurfaceReportJson(kProfile);
}

} // namespace scratchbird::parser::postgresql
