#include "sblr_temporary_instance_cleanup_coordinator.hpp"
#include "api_diagnostics.hpp"
#include "engine/sblr/sblr_temporary_instance_cleanup_runtime.hpp"
#include "hash_digest.hpp"
#include "uuid.hpp"
#include <algorithm>
#include <chrono>
#include <fstream>
#include <mutex>
#include <unordered_map>
namespace scratchbird::engine::internal_api {namespace {std::mutex m;std::unordered_map<std::string,SblrTemporaryInstanceSnapshot> rows;std::uint64_t generation=0;EngineApiDiagnostic D(std::string c,std::string k){return MakeEngineApiDiagnostic(std::move(c),std::move(k),{});}bool tag(const EngineRequestContext&c,const char*t){return c.security_context_present&&std::find(c.trace_tags.begin(),c.trace_tags.end(),t)!=c.trace_tags.end();}std::string id(){auto ms=static_cast<std::uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count());auto u=scratchbird::core::uuid::GenerateEngineIdentityV7(scratchbird::core::platform::UuidKind::object,ms+(++generation));return u.ok()?scratchbird::core::uuid::UuidToString(u.value.value):std::string{};}std::string hash(const std::string&s){auto d=scratchbird::core::hash::ComputeSha256Digest(std::vector<std::uint8_t>(s.begin(),s.end())).digest;return "sha256:"+scratchbird::core::hash::HexLower(d);}bool journal(const EngineRequestContext&c,const SblrTemporaryInstanceSnapshot&s,char event){std::ofstream o(c.database_path+".sb.sblr_temporary_instance.v1",std::ios::app);if(!o)return false;o<<event<<'\t'<<s.descriptor_uuid<<'\t'<<s.descriptor_generation<<'\t'<<s.instance_uuid<<'\t'<<s.instance_generation<<'\t'<<unsigned(s.state)<<'\t'<<s.cleanup_sequence<<'\n';o.flush();return bool(o);}}
SblrTemporaryInstanceResult PublishSblrTemporaryInstance(const EngineRequestContext&c,const std::string&receipt,std::uint64_t occurrence,std::uint8_t retention){std::lock_guard l(m);SblrTemporaryInstanceResult o;if(!tag(c,"private_temporary_instance_compiler")||!c.statement_metadata_snapshot_engine_owned){o.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.temporary_instance.compiler_hidden");return o;}if(receipt!=c.statement_uuid.canonical||!occurrence||(retention!=1&&retention!=2)||c.session_uuid.canonical.empty()){o.diagnostic=D("SBLR.OPERAND_INVALID","sblr.temporary_instance.publish_invalid");return o;}SblrTemporaryInstanceSnapshot s;s.receipt_uuid=receipt;s.structural_occurrence_id=occurrence;s.descriptor_uuid=id();s.definition_uuid=id();s.instance_uuid=id();s.owner_session_uuid=c.session_uuid.canonical;s.owner_transaction_uuid=retention==1?c.transaction_uuid.canonical:std::string{};s.descriptor_generation=++generation;s.instance_generation=++generation;s.catalog_generation=std::max<std::uint64_t>(1,c.statement_metadata_snapshot_visible_through_local_transaction_id);s.security_generation=std::max<std::uint64_t>(1,c.local_transaction_id);s.policy_generation=++generation;s.retention=retention;s.descriptor_evidence_sha256=hash("ScratchBird.SblrTemporaryInstanceCleanupDescriptor.V1"+s.descriptor_uuid+s.instance_uuid);if(!journal(c,s,'P')){o.diagnostic=D("TEMP.TABLE.CLEANUP_FAILED","sblr.temporary_instance.publish_failed");return o;}rows[s.descriptor_uuid]=s;o.ok=true;o.snapshot=s;o.diagnostic=D("OK","ok");return o;}
SblrTemporaryInstanceResult CoordinateSblrTemporaryInstanceCleanup(const EngineRequestContext&c,const std::string&receipt,std::uint64_t occurrence,std::uint8_t trigger,std::uint64_t availability){std::lock_guard l(m);SblrTemporaryInstanceResult o;if(!tag(c,"private_temporary_instance_cleanup")){o.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.temporary_instance.hidden");return o;}for(auto&[_,s]:rows)if(s.receipt_uuid==receipt&&s.structural_occurrence_id==occurrence&&s.owner_session_uuid==c.session_uuid.canonical){if(s.state!=SblrTemporaryInstanceState::active){o.diagnostic=D("TEMP.TABLE.INSTANCE_STALE","sblr.temporary_instance.stale");return o;}if((s.retention==1&&trigger!=1)||(s.retention==2&&trigger!=2)){o.diagnostic=D("TEMP.TABLE.INVALID_RETENTION_MODE","sblr.temporary_instance.retention_mismatch");return o;}s.trigger=trigger;s.availability_generation=availability;scratchbird::engine::sblr::SblrTemporaryInstanceCleanupDescriptorV1 d;const auto du=scratchbird::core::uuid::ParseUuid(s.descriptor_uuid),df=scratchbird::core::uuid::ParseUuid(s.definition_uuid),in=scratchbird::core::uuid::ParseUuid(s.instance_uuid),os=scratchbird::core::uuid::ParseUuid(s.owner_session_uuid);if(!du.ok()||!df.ok()||!in.ok()||!os.ok()){o.diagnostic=D("TEMP.TABLE.CLEANUP_FAILED","sblr.temporary_instance.identity_invalid");return o;}d.descriptor=du.value.bytes;d.definition=df.value.bytes;d.instance=in.value.bytes;d.owner_session=os.value.bytes;if(!s.owner_transaction_uuid.empty()){const auto ot=scratchbird::core::uuid::ParseUuid(s.owner_transaction_uuid);if(!ot.ok()){o.diagnostic=D("TEMP.TABLE.CLEANUP_FAILED","sblr.temporary_instance.identity_invalid");return o;}d.owner_transaction=ot.value.bytes;}d.descriptor_generation=s.descriptor_generation;d.instance_generation=s.instance_generation;d.retention=s.retention;d.trigger=s.trigger;d.state=1;d.catalog_generation=s.catalog_generation;d.security_generation=s.security_generation;d.policy_generation=s.policy_generation;d.availability_generation=s.availability_generation;const auto bytes=scratchbird::engine::sblr::EncodeSblrTemporaryInstanceCleanupDescriptorV1(d);if(bytes.size()!=184){o.diagnostic=D("TEMP.TABLE.CLEANUP_FAILED","sblr.temporary_instance.evidence_failed");return o;}s.descriptor_evidence_sha256="sha256:";static constexpr char hx[]="0123456789abcdef";for(size_t i=144;i<176;++i){s.descriptor_evidence_sha256.push_back(hx[bytes[i]>>4]);s.descriptor_evidence_sha256.push_back(hx[bytes[i]&15]);}o.ok=true;o.snapshot=s;o.diagnostic=D("OK","ok");return o;}o.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.temporary_instance.hidden");return o;}
SblrTemporaryInstanceResult CleanupSblrTemporaryInstance(const EngineRequestContext&c,const std::string&descriptor,std::uint64_t generation_id,const std::string&evidence,std::uint64_t availability){std::lock_guard l(m);SblrTemporaryInstanceResult o;if(!tag(c,"private_temporary_instance_cleanup")){o.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.temporary_instance.hidden");return o;}auto it=rows.find(descriptor);if(it==rows.end()||it->second.owner_session_uuid!=c.session_uuid.canonical){o.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.temporary_instance.hidden");return o;}auto&s=it->second;if(s.state!=SblrTemporaryInstanceState::active||s.descriptor_generation!=generation_id||s.descriptor_evidence_sha256!=evidence||s.availability_generation!=availability){o.diagnostic=D("TEMP.TABLE.INSTANCE_STALE","sblr.temporary_instance.stale");return o;}s.state=SblrTemporaryInstanceState::cleaned;s.cleanup_sequence=++generation;s.cleanup_evidence_sha256=hash("ScratchBird.SblrTemporaryInstanceCleanup.V1"+s.instance_uuid+std::to_string(s.cleanup_sequence));if(!journal(c,s,'C')){o.diagnostic=D("TEMP.TABLE.CLEANUP_FAILED","sblr.temporary_instance.cleanup_failed");return o;}o.ok=true;o.snapshot=s;o.diagnostic=D("OK","ok");return o;}
EngineApiDiagnostic RecoverSblrTemporaryInstances(const EngineRequestContext&c){std::lock_guard l(m);if(!tag(c,"right:SBLR_TEMPORARY_INSTANCE_ADMIN"))return D("SECURITY.ACCESS_DENIED","sblr.temporary_instance.recovery_denied");for(auto&[_,s]:rows)if(s.state==SblrTemporaryInstanceState::active){s.state=SblrTemporaryInstanceState::revoked;s.cleanup_sequence=++generation;if(!journal(c,s,'X'))return D("TEMP.TABLE.CLEANUP_FAILED","sblr.temporary_instance.recovery_failed");}return D("OK","ok");}}
