#include "sblr_reservation_release_coordinator.hpp"
#include "api_diagnostics.hpp"
#include "hash_digest.hpp"
#include "uuid.hpp"
#include "engine/sblr/sblr_reservation_release_runtime.hpp"
#include <algorithm>
#include <chrono>
#include <fstream>
#include <mutex>
#include <unordered_map>
namespace scratchbird::engine::internal_api {namespace {std::mutex m;std::unordered_map<std::string,SblrRelationReservationSnapshot> rows;std::uint64_t generation=0;EngineApiDiagnostic D(std::string c,std::string k){return MakeEngineApiDiagnostic(std::move(c),std::move(k),{});}bool tag(const EngineRequestContext&c,const char*t){return c.security_context_present&&std::find(c.trace_tags.begin(),c.trace_tags.end(),t)!=c.trace_tags.end();}std::string id(){auto ms=static_cast<std::uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count());auto u=scratchbird::core::uuid::GenerateEngineIdentityV7(scratchbird::core::platform::UuidKind::object,ms+(++generation));return u.ok()?scratchbird::core::uuid::UuidToString(u.value.value):std::string{};}std::string hash(const std::string&s){auto d=scratchbird::core::hash::ComputeSha256Digest(std::vector<std::uint8_t>(s.begin(),s.end())).digest;return "sha256:"+scratchbird::core::hash::HexLower(d);}bool publish(const EngineRequestContext&c,const SblrRelationReservationSnapshot&s,char event){std::ofstream o(c.database_path+".sb.sblr_relation_reservation.v1",std::ios::app);if(!o)return false;o<<event<<'\t'<<s.reservation_uuid<<'\t'<<s.reservation_generation<<'\t'<<s.transaction_uuid<<'\t'<<s.local_transaction_id<<'\t'<<s.relation_uuid<<'\t'<<unsigned(s.mode)<<'\t'<<unsigned(s.state)<<'\t'<<s.release_sequence<<'\n';o.flush();return bool(o);}}
SblrRelationReservationResult PublishSblrRelationReservation(const EngineRequestContext&c,const std::string&receipt,const std::string&relation,std::uint8_t mode,std::uint64_t catalog,std::uint64_t policy){std::lock_guard l(m);SblrRelationReservationResult o;if(!tag(c,"private_transaction_relation_reservation")||!c.statement_metadata_snapshot_engine_owned){o.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.reservation.hidden");return o;}if(receipt!=c.statement_uuid.canonical||c.transaction_uuid.canonical.empty()||relation.empty()||mode<1||mode>4||!catalog||!policy){o.diagnostic=D("SBLR.OPERAND_INVALID","sblr.reservation.publish_invalid");return o;}SblrRelationReservationSnapshot s;s.receipt_uuid=receipt;s.reservation_uuid=id();s.reservation_generation=++generation;s.transaction_uuid=c.transaction_uuid.canonical;s.local_transaction_id=c.local_transaction_id;s.relation_uuid=relation;s.mode=mode;s.catalog_generation=catalog;s.policy_generation=policy;s.state=SblrRelationReservationState::active;scratchbird::engine::sblr::SblrReservationReleaseDescriptorV1 wire;const auto reservation_uuid=scratchbird::core::uuid::ParseUuid(s.reservation_uuid),transaction_uuid=scratchbird::core::uuid::ParseUuid(s.transaction_uuid),relation_uuid=scratchbird::core::uuid::ParseUuid(s.relation_uuid);if(!reservation_uuid.ok()||!transaction_uuid.ok()||!relation_uuid.ok()){o.diagnostic=D("TX.RESERVATION.RELEASE_FAILED","sblr.reservation.identity_invalid");return o;}wire.reservation=reservation_uuid.value.bytes;wire.reservation_generation=s.reservation_generation;wire.transaction=transaction_uuid.value.bytes;wire.local_transaction_id=s.local_transaction_id;wire.relation=relation_uuid.value.bytes;wire.mode=s.mode;wire.catalog_generation=s.catalog_generation;wire.policy_generation=s.policy_generation;wire.availability_generation=1;const auto canonical=scratchbird::engine::sblr::EncodeSblrReservationReleaseDescriptorV1(wire);if(canonical.size()!=144){o.diagnostic=D("TX.RESERVATION.RELEASE_FAILED","sblr.reservation.evidence_failed");return o;}s.reservation_evidence_sha256="sha256:";static constexpr char hx[]="0123456789abcdef";for(size_t i=104;i<136;++i){s.reservation_evidence_sha256.push_back(hx[canonical[i]>>4]);s.reservation_evidence_sha256.push_back(hx[canonical[i]&15]);}if(s.reservation_uuid.empty()||!publish(c,s,'P')){o.diagnostic=D("TX.RESERVATION.RELEASE_FAILED","sblr.reservation.publish_failed");return o;}rows[s.reservation_uuid]=s;o.ok=true;o.snapshot=s;o.diagnostic=D("OK","ok");return o;}
SblrRelationReservationResult CompileAndPublishSblrRelationReservation(const EngineRequestContext&c,const std::string&receipt,std::uint64_t occurrence){SblrRelationReservationResult o;if(!tag(c,"private_transaction_relation_reservation_compiler")||!c.statement_metadata_snapshot_engine_owned||receipt!=c.statement_uuid.canonical||!occurrence||c.transaction_uuid.canonical.empty()){o.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.reservation.compiler_hidden");return o;}auto compiler_context=c;compiler_context.trace_tags.push_back("private_transaction_relation_reservation");const auto relation=id();if(relation.empty()){o.diagnostic=D("TX.RESERVATION.RELEASE_FAILED","sblr.reservation.relation_identity_failed");return o;}o=PublishSblrRelationReservation(compiler_context,receipt,relation,1,std::max<std::uint64_t>(1,c.statement_metadata_snapshot_visible_through_local_transaction_id),std::max<std::uint64_t>(1,c.local_transaction_id));if(o.ok)o.snapshot.structural_occurrence_id=occurrence;return o;}
SblrRelationReservationResult CoordinateSblrReservationRelease(const EngineRequestContext&c,const std::string&receipt,const std::string&relation,std::uint64_t occurrence,std::uint64_t availability){std::lock_guard l(m);SblrRelationReservationResult o;if(!tag(c,"private_transaction_relation_reservation")){o.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.reservation.hidden");return o;}for(auto&[_,s]:rows)if(s.receipt_uuid==receipt&&s.transaction_uuid==c.transaction_uuid.canonical&&s.relation_uuid==relation){if(s.state!=SblrRelationReservationState::active){o.diagnostic=D("MGA.TRANSACTION.STALE","sblr.reservation.stale");return o;}s.structural_occurrence_id=occurrence;s.availability_generation=availability;o.ok=true;o.snapshot=s;o.diagnostic=D("OK","ok");return o;}o.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.reservation.hidden");return o;}
SblrRelationReservationResult ReleaseSblrRelationReservation(const EngineRequestContext&c,const std::string&idv,std::uint64_t gen,const std::string&relation,const std::string&evidence,std::uint64_t availability){std::lock_guard l(m);SblrRelationReservationResult o;if(!tag(c,"private_transaction_relation_reservation")){o.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.reservation.hidden");return o;}auto it=rows.find(idv);if(it==rows.end()||it->second.transaction_uuid!=c.transaction_uuid.canonical||it->second.relation_uuid!=relation){o.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.reservation.hidden");return o;}auto&s=it->second;if(s.state!=SblrRelationReservationState::active||s.reservation_generation!=gen||s.reservation_evidence_sha256!=evidence||s.availability_generation!=availability){o.diagnostic=D("MGA.TRANSACTION.STALE","sblr.reservation.stale");return o;}s.state=SblrRelationReservationState::released;s.release_sequence=++generation;s.release_evidence_sha256=hash("ScratchBird.SblrTransactionReservationRelease.V1"+s.reservation_evidence_sha256+std::to_string(s.release_sequence));if(!publish(c,s,'R')){o.diagnostic=D("TX.RESERVATION.RELEASE_FAILED","sblr.reservation.release_publish_failed");return o;}o.ok=true;o.snapshot=s;o.diagnostic=D("OK","ok");return o;}
EngineApiDiagnostic RecoverSblrRelationReservations(const EngineRequestContext&c){std::lock_guard l(m);if(!tag(c,"right:SBLR_TRANSACTION_RESERVATION_ADMIN"))return D("SECURITY.ACCESS_DENIED","sblr.reservation.recovery_denied");for(auto&[_,s]:rows)if(s.state==SblrRelationReservationState::active){s.state=SblrRelationReservationState::revoked;s.release_sequence=++generation;if(!publish(c,s,'X'))return D("TX.RESERVATION.RELEASE_FAILED","sblr.reservation.recovery_failed");}return D("OK","ok");}}
