// Copyright (c) 2026 ScratchBird Software Inc.
// SPDX-License-Identifier: MPL-2.0
#include "sblr_variable_descriptor_registry.hpp"

#include "api_diagnostics.hpp"
#include "hash_digest.hpp"
#include "uuid.hpp"

#include <algorithm>
#include <chrono>
#include <cctype>
#include <filesystem>
#include <fstream>
#include <limits>
#include <mutex>
#include <sstream>
#include <string_view>
#include <unordered_map>

#if defined(_WIN32)
#include <windows.h>
#else
#include <fcntl.h>
#include <unistd.h>
#endif

namespace scratchbird::engine::internal_api {
namespace {
constexpr std::string_view kMagic="SBVDR1";
constexpr std::string_view kRowDomain="ScratchBird.SblrVariableDescriptorRow.V1";
constexpr std::string_view kEvidenceDomain="ScratchBird.SblrVariableDescriptorRegistry.V1";
std::mutex g_mutex;
std::unordered_map<std::string,SblrVariableDescriptorRow> g_live;
std::unordered_map<std::string,std::uint64_t> g_high;

EngineApiDiagnostic Diag(std::string c,std::string k,std::string d){return MakeEngineApiDiagnostic(std::move(c),std::move(k),std::move(d));}
EngineApiDiagnostic Ok(){return MakeEngineApiDiagnostic("OK","ok",{},false);}
bool Authority(const EngineRequestContext& c){return c.security_context_present&&c.statement_metadata_snapshot_engine_owned&&std::find(c.trace_tags.begin(),c.trace_tags.end(),"private_variable_registry")!=c.trace_tags.end();}
bool Admin(const EngineRequestContext& c){return c.security_context_present&&std::find(c.trace_tags.begin(),c.trace_tags.end(),"right:SBLR_VARIABLE_REGISTRY_ADMIN")!=c.trace_tags.end();}
bool CanonicalAuthority(const EngineRequestContext& c){return Authority(c)&&std::find(c.trace_tags.begin(),c.trace_tags.end(),"canonical_datatype_value_validated")!=c.trace_tags.end();}
bool Uuid(std::string_view s,scratchbird::core::platform::UuidKind k){if(k==scratchbird::core::platform::UuidKind::session)return scratchbird::core::uuid::ParseTypedUuid(k,std::string(s)).ok();return scratchbird::core::uuid::ParseDurableEngineIdentityUuid(k,std::string(s)).ok();}
std::string NewUuid(std::uint64_t salt){const auto now=static_cast<std::uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count());const auto v=scratchbird::core::uuid::GenerateEngineIdentityV7(scratchbird::core::platform::UuidKind::object,now+salt);return v.ok()?scratchbird::core::uuid::UuidToString(v.value.value):std::string{};}
std::string Hash(std::string_view v){const auto d=scratchbird::core::hash::ComputeSha256Digest(reinterpret_cast<const scratchbird::core::platform::byte*>(v.data()),v.size());return d.ok()?"sha256:"+scratchbird::core::hash::HexLower(d.digest):std::string{};}
bool Reason(std::string_view v){return !v.empty()&&v.size()<=128&&std::all_of(v.begin(),v.end(),[](unsigned char c){return std::isalnum(c)||c=='.'||c=='_'||c==':'||c=='-';});}
std::string Path(const EngineRequestContext& c){return c.database_path+".sb.sblr_variable_registry.v1";}
void Field(std::string* out,std::string_view v){out->append(std::to_string(v.size()));out->push_back(':');out->append(v);}
std::string Immutable(const SblrVariableDescriptorRow& r){std::string v(kRowDomain);for(const auto& x:{r.variable_descriptor_uuid,r.statement_receipt_uuid,r.database_uuid,r.session_uuid,r.transaction_uuid,r.scope_uuid,r.frame_uuid,r.datatype_descriptor_uuid})Field(&v,x);for(auto n:{r.variable_descriptor_generation,r.scope_generation,r.frame_generation,static_cast<std::uint64_t>(r.variable_ordinal),r.datatype_descriptor_generation,static_cast<std::uint64_t>(r.nullable),static_cast<std::uint64_t>(r.mutability)})Field(&v,std::to_string(n));return v;}
std::string Material(const SblrVariableDescriptorRow& r,std::uint64_t prior,std::string_view reason){std::string v(kEvidenceDomain);Field(&v,r.row_identity_sha256);Field(&v,r.canonical_value_sha256);Field(&v,r.canonical_value_bytes);Field(&v,std::to_string(r.value_generation));Field(&v,std::to_string(r.registry_generation));Field(&v,std::to_string(prior));Field(&v,std::to_string(static_cast<unsigned>(r.value_state)));Field(&v,std::to_string(static_cast<unsigned>(r.lifecycle)));Field(&v,reason);return v;}
std::string Hex(std::string_view v){static constexpr char h[]="0123456789abcdef";std::string o;o.reserve(v.size()*2);for(unsigned char c:v){o.push_back(h[c>>4]);o.push_back(h[c&15]);}return o;}
bool Unhex(std::string_view v,std::string* o){if(v.size()%2)return false;o->clear();o->reserve(v.size()/2);auto n=[](char c)->int{if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;return -1;};for(std::size_t i=0;i<v.size();i+=2){int a=n(v[i]),b=n(v[i+1]);if(a<0||b<0)return false;o->push_back(static_cast<char>((a<<4)|b));}return true;}
std::string Record(std::string_view kind,const SblrVariableDescriptorRow& r,std::uint64_t prior,std::string_view reason){std::ostringstream o;o<<kMagic<<'\t'<<kind<<'\t'<<r.variable_descriptor_uuid<<'\t'<<r.variable_descriptor_generation<<'\t'<<r.statement_receipt_uuid<<'\t'<<r.database_uuid<<'\t'<<r.session_uuid<<'\t'<<r.transaction_uuid<<'\t'<<r.scope_uuid<<'\t'<<r.scope_generation<<'\t'<<r.frame_uuid<<'\t'<<r.frame_generation<<'\t'<<r.variable_ordinal<<'\t'<<r.datatype_descriptor_uuid<<'\t'<<r.datatype_descriptor_generation<<'\t'<<(r.nullable?1:0)<<'\t'<<static_cast<unsigned>(r.mutability)<<'\t'<<r.value_generation<<'\t'<<static_cast<unsigned>(r.value_state)<<'\t'<<Hex(r.canonical_value_bytes)<<'\t'<<r.canonical_value_sha256<<'\t'<<r.row_identity_sha256<<'\t'<<r.registry_generation<<'\t'<<static_cast<unsigned>(r.lifecycle)<<'\t'<<prior<<'\t'<<reason<<'\t'<<r.decision_evidence_sha256;return o.str();}
bool Append(const std::string& p,const std::string& line){{std::ofstream o(p,std::ios::binary|std::ios::app);if(!o)return false;o<<line<<'\n';o.flush();if(!o)return false;}
#if defined(_WIN32)
HANDLE h=CreateFileA(p.c_str(),GENERIC_WRITE,FILE_SHARE_READ,nullptr,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,nullptr);if(h==INVALID_HANDLE_VALUE)return false;const bool ok=FlushFileBuffers(h)!=0;CloseHandle(h);return ok;
#else
const int fd=::open(p.c_str(),O_WRONLY|O_CLOEXEC);if(fd<0)return false;const bool ok=::fsync(fd)==0;::close(fd);return ok;
#endif
}
bool Publish(const EngineRequestContext& c,const SblrVariableDescriptorRow& r,std::uint64_t prior,std::string_view reason){return Append(Path(c),Record("EVIDENCE",r,prior,reason))&&Append(Path(c),Record("SNAPSHOT",r,prior,reason));}
bool PublishBatch(const EngineRequestContext& c,const std::vector<SblrVariableDescriptorRow>& rows,const std::vector<std::uint64_t>& priors){
  if(rows.empty()||rows.size()!=priors.size())return false;
  std::string block;
  for(std::size_t i=0;i<rows.size();++i){block+=Record("EVIDENCE",rows[i],priors[i],"value.assign.batch");block.push_back('\n');block+=Record("SNAPSHOT",rows[i],priors[i],"value.assign.batch");block.push_back('\n');}
  if(block.empty())return false;
  // Append performs one durable write barrier for the canonical batch. Replay
  // rejects a torn odd/incomplete record set before restoring any row.
  block.pop_back(); return Append(Path(c),block);
}
std::vector<std::string> Split(std::string_view v){std::vector<std::string> r;std::size_t b=0;while(b<=v.size()){auto e=v.find('\t',b);r.emplace_back(v.substr(b,e==std::string_view::npos?v.size()-b:e-b));if(e==std::string_view::npos)break;b=e+1;}return r;}
bool N(std::string_view v,std::uint64_t* n){if(v.empty())return false;std::uint64_t x=0;for(char c:v){if(c<'0'||c>'9'||x>(std::numeric_limits<std::uint64_t>::max()-(c-'0'))/10)return false;x=x*10+(c-'0');}*n=x;return true;}
bool Decode(const std::string& line,std::string_view kind,SblrVariableDescriptorRow* r,std::uint64_t* prior,std::string* reason){auto f=Split(line);std::uint64_t ordinal=0,nullable=0,mutability=0,state=0,life=0;if(f.size()!=27||f[0]!=kMagic||f[1]!=kind||!N(f[3],&r->variable_descriptor_generation)||!N(f[9],&r->scope_generation)||!N(f[11],&r->frame_generation)||!N(f[12],&ordinal)||ordinal>UINT32_MAX||!N(f[14],&r->datatype_descriptor_generation)||!N(f[15],&nullable)||nullable>1||!N(f[16],&mutability)||mutability>1||!N(f[17],&r->value_generation)||!N(f[18],&state)||state<1||state>3||!N(f[22],&r->registry_generation)||!N(f[23],&life)||life<1||life>2||!N(f[24],prior)||!Unhex(f[19],&r->canonical_value_bytes))return false;r->variable_descriptor_uuid=f[2];r->statement_receipt_uuid=f[4];r->database_uuid=f[5];r->session_uuid=f[6];r->transaction_uuid=f[7];r->scope_uuid=f[8];r->frame_uuid=f[10];r->variable_ordinal=static_cast<std::uint32_t>(ordinal);r->datatype_descriptor_uuid=f[13];r->nullable=nullable;r->mutability=static_cast<SblrVariableMutability>(mutability);r->value_state=static_cast<SblrVariableValueState>(state);r->canonical_value_sha256=f[20];r->row_identity_sha256=f[21];r->lifecycle=static_cast<SblrVariableLifecycle>(life);*reason=f[25];r->decision_evidence_sha256=f[26];return Uuid(r->variable_descriptor_uuid,scratchbird::core::platform::UuidKind::object)&&Uuid(r->statement_receipt_uuid,scratchbird::core::platform::UuidKind::object)&&Uuid(r->database_uuid,scratchbird::core::platform::UuidKind::database)&&Uuid(r->session_uuid,scratchbird::core::platform::UuidKind::session)&&Uuid(r->scope_uuid,scratchbird::core::platform::UuidKind::object)&&Uuid(r->frame_uuid,scratchbird::core::platform::UuidKind::object)&&Uuid(r->datatype_descriptor_uuid,scratchbird::core::platform::UuidKind::object)&&r->variable_descriptor_generation&&r->scope_generation&&r->frame_generation&&r->datatype_descriptor_generation&&r->value_generation&&r->registry_generation&&Reason(*reason)&&r->canonical_value_sha256==Hash(r->canonical_value_bytes)&&r->row_identity_sha256==Hash(Immutable(*r))&&r->decision_evidence_sha256==Hash(Material(*r,*prior,*reason))&&((r->value_state==SblrVariableValueState::null_value||r->value_state==SblrVariableValueState::uninitialized)?r->canonical_value_bytes.empty():true)&&!(r->value_state==SblrVariableValueState::null_value&&!r->nullable);}
bool SameImmutable(const SblrVariableDescriptorRow&a,const SblrVariableDescriptorRow&b){return a.row_identity_sha256==b.row_identity_sha256;}
bool Replay(const EngineRequestContext& c,std::unordered_map<std::string,SblrVariableDescriptorRow>* rows,std::uint64_t* high){rows->clear();*high=0;std::ifstream in(Path(c),std::ios::binary);if(!in)return !std::filesystem::exists(Path(c));std::vector<std::string> lines;std::string line;while(std::getline(in,line))lines.push_back(line);if(!in.eof()||lines.size()%2)return false;for(std::size_t i=0;i<lines.size();i+=2){SblrVariableDescriptorRow e,s;std::uint64_t ep=0,sp=0;std::string er,sr;if(!Decode(lines[i],"EVIDENCE",&e,&ep,&er)||!Decode(lines[i+1],"SNAPSHOT",&s,&sp,&sr)||lines[i].substr(lines[i].find('\t',lines[i].find('\t')+1))!=lines[i+1].substr(lines[i+1].find('\t',lines[i+1].find('\t')+1))||ep!=sp||er!=sr||s.database_uuid!=c.database_uuid.canonical||s.registry_generation<=*high)return false;auto it=rows->find(s.variable_descriptor_uuid);if((it==rows->end()&&(sp!=0||s.variable_descriptor_generation!=1||s.value_generation!=1||s.lifecycle!=SblrVariableLifecycle::active))||(it!=rows->end()&&(sp!=it->second.registry_generation||!SameImmutable(it->second,s)||s.value_generation!=it->second.value_generation+1)))return false;(*rows)[s.variable_descriptor_uuid]=s;*high=s.registry_generation;}return true;}
std::uint64_t Next(const std::string& db){auto& n=g_high[db];return n==UINT64_MAX?0:++n;}
bool Bound(const EngineRequestContext& c,const SblrVariableDescriptorRow&r,const std::string& receipt,const std::string& scope,std::uint64_t sg,const std::string& frame,std::uint64_t fg){return r.database_uuid==c.database_uuid.canonical&&r.session_uuid==c.session_uuid.canonical&&r.transaction_uuid==c.transaction_uuid.canonical&&r.statement_receipt_uuid==receipt&&r.scope_uuid==scope&&r.scope_generation==sg&&r.frame_uuid==frame&&r.frame_generation==fg;}
SblrVariableRegistryResult Hidden(){SblrVariableRegistryResult r;r.diagnostic=Diag("SECURITY.ACCESS_DENIED","sblr.variable.hidden","variable descriptor is not visible");return r;}
} // namespace

SblrVariableRegistryResult PublishSblrVariableFrame(const EngineRequestContext& c,const std::string& receipt,const std::string& scope,std::uint64_t sg,const std::string& frame,std::uint64_t fg,const std::vector<SblrVariableDemand>& demands){std::lock_guard lock(g_mutex);SblrVariableRegistryResult out;if(!CanonicalAuthority(c))return Hidden();if(c.database_path.empty()||!Uuid(c.database_uuid.canonical,scratchbird::core::platform::UuidKind::database)||!Uuid(c.session_uuid.canonical,scratchbird::core::platform::UuidKind::session)||!Uuid(c.transaction_uuid.canonical,scratchbird::core::platform::UuidKind::object)||!Uuid(receipt,scratchbird::core::platform::UuidKind::object)||!Uuid(scope,scratchbird::core::platform::UuidKind::object)||!Uuid(frame,scratchbird::core::platform::UuidKind::object)||!sg||!fg||demands.empty()||demands.size()>4096){out.diagnostic=Diag("SBLR.OPERAND_INVALID","sblr.variable.frame_invalid","exact nonempty frame demands required");return out;}auto& high=g_high[c.database_uuid.canonical];if(high==0&&std::filesystem::exists(Path(c))){std::unordered_map<std::string,SblrVariableDescriptorRow> rows;if(!Replay(c,&rows,&high)){out.diagnostic=Diag("SBLR.VARIABLE.STALE","sblr.variable.recovery_required","registry recovery required");return out;}for(const auto&[id,r]:rows)if(r.lifecycle==SblrVariableLifecycle::active){out.diagnostic=Diag("SBLR.VARIABLE.STALE","sblr.variable.recovery_required","live recovered frame must be revoked");return out;}}
for(std::size_t i=0;i<demands.size();++i){const auto&d=demands[i];if(!Uuid(d.datatype_descriptor_uuid,scratchbird::core::platform::UuidKind::object)||!d.datatype_descriptor_generation||static_cast<unsigned>(d.mutability)>1||static_cast<unsigned>(d.initial_state)<1||static_cast<unsigned>(d.initial_state)>3||(d.initial_state==SblrVariableValueState::null_value&&!d.nullable)||((d.initial_state==SblrVariableValueState::null_value||d.initial_state==SblrVariableValueState::uninitialized)&&!d.canonical_value_bytes.empty())){out.diagnostic=Diag("DATATYPE.DESCRIPTOR_INVALID","sblr.variable.demand_invalid","canonical datatype value demand required");return out;}SblrVariableDescriptorRow r;r.variable_descriptor_uuid=NewUuid(high+i+1);r.variable_descriptor_generation=1;r.statement_receipt_uuid=receipt;r.database_uuid=c.database_uuid.canonical;r.session_uuid=c.session_uuid.canonical;r.transaction_uuid=c.transaction_uuid.canonical;r.scope_uuid=scope;r.scope_generation=sg;r.frame_uuid=frame;r.frame_generation=fg;r.variable_ordinal=static_cast<std::uint32_t>(i);r.datatype_descriptor_uuid=d.datatype_descriptor_uuid;r.datatype_descriptor_generation=d.datatype_descriptor_generation;r.nullable=d.nullable;r.mutability=d.mutability;r.value_generation=1;r.value_state=d.initial_state;r.canonical_value_bytes=d.canonical_value_bytes;r.canonical_value_sha256=Hash(r.canonical_value_bytes);r.row_identity_sha256=Hash(Immutable(r));r.registry_generation=Next(r.database_uuid);r.lifecycle=SblrVariableLifecycle::active;r.decision_evidence_sha256=Hash(Material(r,0,"frame.publish"));if(r.variable_descriptor_uuid.empty()||!r.registry_generation||!Publish(c,r,0,"frame.publish")){out.diagnostic=Diag("SBLR.EXECUTION_FAILED","sblr.variable.publish_failed","durable descriptor publication failed");return out;}out.rows.push_back(r);}for(const auto&r:out.rows)g_live[r.variable_descriptor_uuid]=r;out.ok=true;out.diagnostic=Ok();for(const auto&r:out.rows)out.evidence.push_back({"sblr.variable.descriptor.publish",r.decision_evidence_sha256});return out;}

SblrVariableRegistryResult LookupSblrVariable(const EngineRequestContext& c,const std::string& receipt,const std::string& scope,std::uint64_t sg,const std::string& frame,std::uint64_t fg,const std::string& uuid,std::uint64_t dg,std::uint64_t vg){std::lock_guard lock(g_mutex);if(!Authority(c))return Hidden();auto it=g_live.find(uuid);if(it==g_live.end()||!Bound(c,it->second,receipt,scope,sg,frame,fg))return Hidden();SblrVariableRegistryResult out;if(it->second.variable_descriptor_generation!=dg||it->second.value_generation!=vg||it->second.lifecycle!=SblrVariableLifecycle::active){out.diagnostic=Diag("SBLR.VARIABLE.STALE","sblr.variable.generation_stale","descriptor or value generation changed");return out;}if(it->second.value_state==SblrVariableValueState::uninitialized){out.diagnostic=Diag("SBLR.VARIABLE.UNINITIALIZED","sblr.variable.uninitialized","variable has no value");return out;}out.ok=true;out.row=it->second;out.diagnostic=Ok();return out;}

SblrVariableRegistryResult AssignSblrVariable(const EngineRequestContext& c,const std::string& receipt,const std::string& scope,std::uint64_t sg,const std::string& frame,std::uint64_t fg,const std::string& uuid,std::uint64_t dg,std::uint64_t expected,SblrVariableValueState state,const std::string& bytes){std::lock_guard lock(g_mutex);if(!CanonicalAuthority(c))return Hidden();auto it=g_live.find(uuid);if(it==g_live.end()||!Bound(c,it->second,receipt,scope,sg,frame,fg))return Hidden();SblrVariableRegistryResult out;if(it->second.mutability!=SblrVariableMutability::mutable_value){out.diagnostic=Diag("SECURITY.ACCESS_DENIED","sblr.variable.immutable","immutable variable cannot be assigned");return out;}if(it->second.variable_descriptor_generation!=dg||it->second.value_generation!=expected||it->second.lifecycle!=SblrVariableLifecycle::active){out.diagnostic=Diag("SBLR.VARIABLE.STALE","sblr.variable.assign_stale","assignment compare failed");return out;}if(static_cast<unsigned>(state)<1||static_cast<unsigned>(state)>3||(state==SblrVariableValueState::null_value&&!it->second.nullable)||((state==SblrVariableValueState::null_value||state==SblrVariableValueState::uninitialized)&&!bytes.empty())){out.diagnostic=Diag("DATATYPE.DESCRIPTOR_INVALID","sblr.variable.value_invalid","canonical value state invalid");return out;}auto r=it->second;const auto prior=r.registry_generation;++r.value_generation;r.registry_generation=Next(r.database_uuid);r.value_state=state;r.canonical_value_bytes=bytes;r.canonical_value_sha256=Hash(bytes);r.decision_evidence_sha256=Hash(Material(r,prior,"value.assign"));if(!r.registry_generation||!Publish(c,r,prior,"value.assign")){out.diagnostic=Diag("SBLR.EXECUTION_FAILED","sblr.variable.assign_failed","durable assignment failed");return out;}g_live[uuid]=r;out.ok=true;out.row=r;out.diagnostic=Ok();out.evidence.push_back({"sblr.variable.value.assign",r.decision_evidence_sha256});return out;}

SblrVariableRegistryResult AssignSblrVariableBatch(const EngineRequestContext& c,const std::string& receipt,const std::string& scope,std::uint64_t sg,const std::string& frame,std::uint64_t fg,const std::vector<SblrVariableAssignment>& assignments){
  std::lock_guard lock(g_mutex);if(!CanonicalAuthority(c))return Hidden();SblrVariableRegistryResult out;
  if(assignments.empty()||assignments.size()>4096){out.diagnostic=Diag("SBLR.OPERAND_INVALID","sblr.variable.assignment_batch_invalid","nonempty bounded assignment batch required");return out;}
  std::vector<SblrVariableDescriptorRow> rows;std::vector<std::uint64_t> priors;rows.reserve(assignments.size());priors.reserve(assignments.size());std::vector<std::string> ids;ids.reserve(assignments.size());
  for(const auto&a:assignments){if(std::find(ids.begin(),ids.end(),a.variable_descriptor_uuid)!=ids.end()){out.diagnostic=Diag("SBLR.OPERAND_INVALID","sblr.variable.assignment_duplicate","descriptor assigned more than once");return out;}ids.push_back(a.variable_descriptor_uuid);}
  for(const auto&a:assignments){auto it=g_live.find(a.variable_descriptor_uuid);if(it==g_live.end()||!Bound(c,it->second,receipt,scope,sg,frame,fg))return Hidden();const auto& prior_row=it->second;if(prior_row.mutability!=SblrVariableMutability::mutable_value){out.diagnostic=Diag("SECURITY.ACCESS_DENIED","sblr.variable.immutable","immutable variable cannot be assigned");return out;}if(prior_row.variable_descriptor_generation!=a.variable_descriptor_generation||prior_row.value_generation!=a.expected_value_generation||prior_row.lifecycle!=SblrVariableLifecycle::active){out.diagnostic=Diag("SBLR.VARIABLE.STALE","sblr.variable.assign_stale","assignment compare failed");return out;}if(static_cast<unsigned>(a.value_state)<1||static_cast<unsigned>(a.value_state)>3||(a.value_state==SblrVariableValueState::null_value&&!prior_row.nullable)||((a.value_state==SblrVariableValueState::null_value||a.value_state==SblrVariableValueState::uninitialized)&&!a.canonical_value_bytes.empty())){out.diagnostic=Diag("DATATYPE.DESCRIPTOR_INVALID","sblr.variable.value_invalid","canonical value state invalid");return out;}auto r=prior_row;priors.push_back(r.registry_generation);++r.value_generation;r.registry_generation=Next(r.database_uuid);r.value_state=a.value_state;r.canonical_value_bytes=a.canonical_value_bytes;r.canonical_value_sha256=Hash(r.canonical_value_bytes);r.decision_evidence_sha256=Hash(Material(r,priors.back(),"value.assign.batch"));if(!r.registry_generation){out.diagnostic=Diag("SBLR.EXECUTION_FAILED","sblr.variable.assign_failed","registry generation exhausted");return out;}rows.push_back(std::move(r));}
  if(!PublishBatch(c,rows,priors)){out.diagnostic=Diag("SBLR.EXECUTION_FAILED","sblr.variable.assign_failed","durable assignment batch failed");return out;}for(const auto&r:rows)g_live[r.variable_descriptor_uuid]=r;out.ok=true;out.rows=rows;out.row=rows.back();out.diagnostic=Ok();for(const auto&r:rows)out.evidence.push_back({"sblr.variable.value.assign",r.decision_evidence_sha256});return out;
}

EngineApiDiagnostic RevokeSblrVariableFrame(const EngineRequestContext& c,const std::string& receipt,const std::string& scope,std::uint64_t sg,const std::string& frame,std::uint64_t fg,const std::string& reason){std::lock_guard lock(g_mutex);if(!Authority(c))return Diag("SECURITY.ACCESS_DENIED","sblr.variable.revoke_denied","variable frame authority required");if(!Reason(reason))return Diag("SBLR.OPERAND_INVALID","sblr.variable.reason_invalid","canonical reason required");std::vector<std::string> ids;for(const auto&[id,r]:g_live)if(Bound(c,r,receipt,scope,sg,frame,fg))ids.push_back(id);if(ids.empty())return Diag("SECURITY.ACCESS_DENIED","sblr.variable.frame_hidden","variable frame is not visible");std::sort(ids.begin(),ids.end(),[](const auto&a,const auto&b){return g_live[a].variable_ordinal<g_live[b].variable_ordinal;});for(const auto&id:ids){auto r=g_live[id];const auto prior=r.registry_generation;++r.value_generation;r.registry_generation=Next(r.database_uuid);r.lifecycle=SblrVariableLifecycle::revoked;r.canonical_value_bytes.clear();r.canonical_value_sha256=Hash({});r.value_state=SblrVariableValueState::uninitialized;r.decision_evidence_sha256=Hash(Material(r,prior,reason));if(!r.registry_generation||!Publish(c,r,prior,reason))return Diag("SBLR.EXECUTION_FAILED","sblr.variable.revoke_failed","durable frame revocation failed");g_live.erase(id);}return Ok();}

EngineApiDiagnostic RecoverSblrVariableDescriptorRegistry(const EngineRequestContext& c){std::lock_guard lock(g_mutex);if(!Admin(c))return Diag("SECURITY.ACCESS_DENIED","sblr.variable.recovery_denied","startup registry authority required");if(c.database_path.empty()||!Uuid(c.database_uuid.canonical,scratchbird::core::platform::UuidKind::database))return Diag("SBLR.OPERAND_INVALID","sblr.variable.recovery_invalid","database identity required");std::unordered_map<std::string,SblrVariableDescriptorRow> rows;std::uint64_t high=0;if(!Replay(c,&rows,&high))return Diag("SBLR.VARIABLE.STALE","sblr.variable.registry_corrupt","torn or contradictory registry evidence");g_high[c.database_uuid.canonical]=high;std::vector<std::string> ids;for(const auto&[id,r]:rows)if(r.lifecycle==SblrVariableLifecycle::active)ids.push_back(id);std::sort(ids.begin(),ids.end(),[&](const auto&a,const auto&b){return rows[a].registry_generation<rows[b].registry_generation;});for(const auto&id:ids){auto r=rows[id];const auto prior=r.registry_generation;++r.value_generation;r.registry_generation=Next(r.database_uuid);r.lifecycle=SblrVariableLifecycle::revoked;r.value_state=SblrVariableValueState::uninitialized;r.canonical_value_bytes.clear();r.canonical_value_sha256=Hash({});r.decision_evidence_sha256=Hash(Material(r,prior,"recovery.revoke"));if(!r.registry_generation||!Publish(c,r,prior,"recovery.revoke"))return Diag("SBLR.EXECUTION_FAILED","sblr.variable.recovery_publish_failed","durable recovery revoke failed");}for(auto it=g_live.begin();it!=g_live.end();)if(it->second.database_uuid==c.database_uuid.canonical)it=g_live.erase(it);else++it;return Ok();}
} // namespace scratchbird::engine::internal_api
