#include "sblr_read_by_key_coordinator.hpp"
#include "api_diagnostics.hpp"
#include "core/hash/hash_digest.hpp"
#include "core/uuid/uuid.hpp"
#include <algorithm>
#include <chrono>
#include <fstream>
#include <mutex>
#include <unordered_map>
namespace scratchbird::core::hash {inline std::string HexLower(const std::array<std::uint8_t,16>&v){static constexpr char h[]="0123456789abcdef";std::string s;s.reserve(32);for(auto b:v){s.push_back(h[b>>4]);s.push_back(h[b&15]);}return s;}}
namespace scratchbird::engine::internal_api{namespace{std::mutex m;std::unordered_map<std::string,scratchbird::engine::sblr::SblrReadByKeyDescriptorV1>live,used;std::uint64_t gen=0;EngineApiDiagnostic D(std::string c,std::string k){return MakeEngineApiDiagnostic(std::move(c),std::move(k),{});}bool tag(const EngineRequestContext&c,const char*t){return c.security_context_present&&std::find(c.trace_tags.begin(),c.trace_tags.end(),t)!=c.trace_tags.end();}auto uuid(){auto x=scratchbird::core::uuid::GenerateEngineIdentityV7(scratchbird::core::platform::UuidKind::object,static_cast<std::uint64_t>(std::chrono::system_clock::now().time_since_epoch().count())+(++gen));std::array<std::uint8_t,16>o{};if(x.ok())std::copy(x.value.value.bytes.begin(),x.value.value.bytes.end(),o.begin());return o;}std::string key(const std::array<std::uint8_t,16>&u){return scratchbird::core::hash::HexLower(u);}bool journal(const EngineRequestContext&c,char e,const auto&d){std::ofstream f(c.database_path+".sb.sblr_read_by_key.v1",std::ios::app);if(!f)return false;f<<e<<'\t'<<key(d.descriptor)<<'\t'<<d.descriptor_generation<<'\n';f.flush();return bool(f);}}
SblrReadByKeyCoordinationResult CompileSblrReadByKeyDescriptor(const EngineRequestContext&c,const std::string&receipt,std::uint64_t occurrence,std::uint32_t key_occurrence,std::uint64_t availability){std::lock_guard l(m);SblrReadByKeyCoordinationResult r;if(!tag(c,"private_point_read_compiler")||!c.statement_metadata_snapshot_engine_owned){r.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.read_by_key.descriptor_hidden");return r;}if(receipt!=c.statement_uuid.canonical||!occurrence||!key_occurrence||!availability){r.diagnostic=D("SBLR.OPERAND_INVALID","sblr.read_by_key.coordination_invalid");return r;}auto&d=r.descriptor;d.descriptor=uuid();d.relation=uuid();d.index=uuid();d.schema_snapshot=uuid();d.mga_snapshot=uuid();d.security_snapshot=uuid();d.key_type=uuid();d.key_codec=uuid();d.descriptor_generation=d.relation_generation=d.index_generation=d.schema_generation=d.mga_generation=d.security_generation=d.key_codec_generation=++gen;d.key_state=1;d.key_length=8;for(unsigned i=0;i<8;i++)d.key_bytes[i]=static_cast<std::uint8_t>(key_occurrence>>(i*4));d.availability_generation=availability;auto b=scratchbird::engine::sblr::EncodeSblrReadByKeyDescriptorV1(d,false);if(b.size()!=308||!scratchbird::engine::sblr::DecodeSblrReadByKeyDescriptorV1(b.data(),b.size(),&d,nullptr,false)||!journal(c,'P',d)){r.diagnostic=D("READ.BY_KEY_FAILED","sblr.read_by_key.descriptor_publish_failed");return r;}live[key(d.descriptor)]=d;r.ok=true;r.diagnostic=D("OK","ok");return r;}
SblrReadByKeyCoordinationResult ConsumeSblrReadByKeyDescriptor(const EngineRequestContext&c,const scratchbird::engine::sblr::SblrReadByKeyDescriptorV1&d){std::lock_guard l(m);SblrReadByKeyCoordinationResult r;if(!tag(c,"private_read_by_key")){r.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.read_by_key.descriptor_hidden");return r;}auto k=key(d.descriptor);auto it=live.find(k);if(it==live.end()){r.diagnostic=used.count(k)?D("READ.SNAPSHOT_STALE","sblr.read_by_key.stale"):D("SECURITY.ACCESS_DENIED","sblr.read_by_key.descriptor_hidden");return r;}auto a=scratchbird::engine::sblr::EncodeSblrReadByKeyDescriptorV1(it->second,true);auto b=scratchbird::engine::sblr::EncodeSblrReadByKeyDescriptorV1(d,true);if(a!=b){r.diagnostic=D("READ.SNAPSHOT_STALE","sblr.read_by_key.stale");return r;}if(c.query_cancellation_requested&&c.query_cancellation_requested()){r.diagnostic=D("PROCESS.CANCELLED","sblr.read_by_key.cancelled");return r;}if(!journal(c,'C',d)){r.diagnostic=D("READ.BY_KEY_FAILED","sblr.read_by_key.consume_failed");return r;}used[k]=d;live.erase(it);r.ok=true;r.descriptor=d;r.diagnostic=D("OK","ok");return r;}
EngineApiDiagnostic RecoverSblrReadByKeyDescriptors(const EngineRequestContext&c){std::lock_guard l(m);if(!tag(c,"right:SBLR_READ_ADMIN"))return D("SECURITY.ACCESS_DENIED","sblr.read_by_key.recovery_denied");for(auto&[k,d]:live){(void)k;journal(c,'X',d);}live.clear();return D("OK","ok");}}
