#include "sblr_function_call_coordinator.hpp"
#include "api_diagnostics.hpp"
#include <algorithm>
#include <map>
#include <mutex>
namespace scratchbird::engine::internal_api { namespace { std::mutex mutex;std::map<std::string,scratchbird::engine::sblr::SblrFunctionCallDescriptorV1> live,used;std::string key(const scratchbird::engine::sblr::FunctionCallSha& value){return{reinterpret_cast<const char*>(value.data()),value.size()};}bool has_tag(const EngineRequestContext& context,const char* tag){return context.security_context_present&&std::find(context.trace_tags.begin(),context.trace_tags.end(),tag)!=context.trace_tags.end();}EngineApiDiagnostic diagnostic(std::string code,std::string message){return MakeEngineApiDiagnostic(std::move(code),std::move(message),{});} }
SblrFunctionCallCoordinationResult CompileSblrFunctionCallDescriptor(const EngineRequestContext& context,const std::string& receipt,std::uint64_t occurrence,std::uint32_t function_occurrence,std::uint64_t availability){std::lock_guard lock(mutex);SblrFunctionCallCoordinationResult result;if(!has_tag(context,"private_function_call_binder")||!context.statement_metadata_snapshot_engine_owned||receipt!=context.statement_uuid.canonical||occurrence==0||function_occurrence==0||availability==0){result.diagnostic=diagnostic("SBLR.OPERAND_INVALID","sblr.function_call.coordination_invalid");return result;}result.descriptor.canonical_body[0]=1;result.descriptor.canonical_body[1]=static_cast<std::uint8_t>(occurrence);result.descriptor.canonical_body[2]=static_cast<std::uint8_t>(function_occurrence);result.descriptor.availability_generation=availability;auto encoded=scratchbird::engine::sblr::EncodeSblrFunctionCallDescriptorV1(result.descriptor,false);if(encoded.empty()||!scratchbird::engine::sblr::DecodeSblrFunctionCallDescriptorV1(encoded.data(),encoded.size(),&result.descriptor,nullptr,false)){result.diagnostic=diagnostic("SBLR.OPERAND_INVALID","sblr.function_call.descriptor_invalid");return result;}live[key(result.descriptor.evidence)]=result.descriptor;result.ok=true;result.diagnostic=diagnostic("OK","ok");return result;}
SblrFunctionCallCoordinationResult ConsumeSblrFunctionCallDescriptor(const EngineRequestContext& context,const scratchbird::engine::sblr::SblrFunctionCallDescriptorV1& descriptor){std::lock_guard lock(mutex);SblrFunctionCallCoordinationResult result;auto descriptor_key=key(descriptor.evidence);auto found=live.find(descriptor_key);if(!has_tag(context,"private_function_call")){result.diagnostic=diagnostic("SECURITY.ACCESS_DENIED","sblr.function_call.hidden");return result;}if(found==live.end()){result.diagnostic=used.count(descriptor_key)?diagnostic("MGA.TRANSACTION.STALE","sblr.function_call.stale"):diagnostic("SECURITY.ACCESS_DENIED","sblr.function_call.hidden");return result;}if(context.query_cancellation_requested&&context.query_cancellation_requested()){result.diagnostic=diagnostic("PROCESS.CANCELLED","sblr.function_call.cancelled");return result;}used[descriptor_key]=descriptor;live.erase(found);result.ok=true;result.descriptor=descriptor;result.diagnostic=diagnostic("OK","ok");return result;}
}
