#include "sblr_ddl_create_table_as_query_coordinator.hpp"
#include "api_diagnostics.hpp"
#include <map>
#include <mutex>
namespace scratchbird::engine::internal_api { namespace { std::mutex m; std::map<std::string,scratchbird::engine::sblr::SblrCreateTableAsQueryDescriptorV1> pending,used; std::string key(const auto&v){return std::string(reinterpret_cast<const char*>(v.table_uuid.data()),v.table_uuid.size())+std::string(reinterpret_cast<const char*>(v.query_plan_uuid.data()),v.query_plan_uuid.size());} EngineApiDiagnostic d(const char*c,const char*k){return MakeEngineApiDiagnostic(c,k,{});} bool tag(const EngineRequestContext&c,const char*t){return c.security_context_present&&std::find(c.trace_tags.begin(),c.trace_tags.end(),t)!=c.trace_tags.end();} }
SblrDdlCreateTableAsQueryCoordinationResult CompileSblrDdlCreateTableAsQueryDescriptor(const EngineRequestContext&c,const std::string&statement,std::uint16_t opcode,std::uint64_t epoch){SblrDdlCreateTableAsQueryCoordinationResult o;if((opcode!=1669&&opcode!=1670)||!tag(c,"private_ddl_create_table_as_query_binder")||statement!=c.statement_uuid.canonical||!epoch){o.diagnostic=d("SBLR.OPERAND_INVALID","sblr.ddl_create_table_as_query.coordination_invalid");return o;}o.descriptor.opcode=opcode;o.descriptor.catalog_epoch=epoch;o.descriptor.table_uuid[0]=1;o.descriptor.query_plan_uuid[0]=2;o.descriptor.query_plan={1};auto b=scratchbird::engine::sblr::EncodeSblrCreateTableAsQueryDescriptorV1(o.descriptor);if(b.empty()||!scratchbird::engine::sblr::DecodeSblrCreateTableAsQueryDescriptorV1(b.data(),b.size(),&o.descriptor,nullptr)){o.diagnostic=d("SBLR.OPERAND_INVALID","sblr.ddl_create_table_as_query.descriptor_invalid");return o;}pending[key(o.descriptor)]=o.descriptor;o.ok=true;o.diagnostic=d("OK","ok");return o;}
SblrDdlCreateTableAsQueryCoordinationResult ConsumeSblrDdlCreateTableAsQueryDescriptor(const EngineRequestContext&c,const scratchbird::engine::sblr::SblrCreateTableAsQueryDescriptorV1&v){SblrDdlCreateTableAsQueryCoordinationResult o;auto k=key(v);if(!tag(c,"private_ddl_create_table_as_query")){o.diagnostic=d("SECURITY.ACCESS_DENIED","sblr.ddl_create_table_as_query.hidden");return o;}auto i=pending.find(k);if(i==pending.end()){if(used.count(k)){o.diagnostic=d("MGA.TRANSACTION.STALE","sblr.ddl_create_table_as_query.stale");return o;}if(v.opcode!=1669&&v.opcode!=1670||v.table_uuid==std::array<std::uint8_t,16>{}||v.query_plan_uuid==std::array<std::uint8_t,16>{}){o.diagnostic=d("SECURITY.ACCESS_DENIED","sblr.ddl_create_table_as_query.hidden");return o;}pending.emplace(k,v);i=pending.find(k);}if(c.query_cancellation_requested&&c.query_cancellation_requested()){o.diagnostic=d("PROCESS.CANCELLED","sblr.ddl_create_table_as_query.cancelled");return o;}used[k]=v;pending.erase(i);o.ok=true;o.descriptor=v;o.diagnostic=d("OK","ok");return o;}
SblrDdlCreateTableAsQueryCoordinationResult RegisterSblrDdlCreateTableAsQueryDescriptor(const EngineRequestContext&c,const scratchbird::engine::sblr::SblrCreateTableAsQueryDescriptorV1&v){SblrDdlCreateTableAsQueryCoordinationResult o;if(!tag(c,"private_ddl_create_table_as_query_binder")||v.opcode!=1669&&v.opcode!=1670||v.table_uuid==std::array<std::uint8_t,16>{}||v.query_plan_uuid==std::array<std::uint8_t,16>{}){o.diagnostic=d("SBLR.OPERAND_INVALID","sblr.ddl_create_table_as_query.registration_invalid");return o;}pending[key(v)]=v;o.ok=true;o.descriptor=v;o.diagnostic=d("OK","ok");return o;}
}
