#include "sblr_session_setting_set_coordinator.hpp"
#include "../../core/uuid/uuid.hpp"
#include "api_diagnostics.hpp"
#include <map>
#include <mutex>
#include <algorithm>
namespace scratchbird::engine::internal_api { namespace { std::mutex m; using D=scratchbird::engine::sblr::SblrSessionSettingSetDescriptorV1; using Key=std::pair<EngineUuid,decltype(D::key)>; std::map<Key,D> live,used; Key k(const D&d){return {EngineUuid{d.receipt},d.key};} EngineApiDiagnostic diag(std::string c,std::string m){return MakeEngineApiDiagnostic(std::move(c),std::move(m),{});} }
SblrSessionSettingSetCoordinationResult CompileSblrSessionSettingSetDescriptor(const EngineRequestContext&c,const EngineUuid&r,uint64_t o,uint64_t a){SblrSessionSettingSetCoordinationResult x;if(!c.security_context_present||!scratchbird::core::uuid::IsEngineIdentityUuid(r) || r != c.statement_uuid||!o||!a){x.diagnostic=diag("SBLR.OPERAND.INVALID","sblr.session_setting_set.coordination_invalid");return x;}x.descriptor.receipt=r.bytes;x.descriptor.expected_generation=o;x.descriptor.availability=a;std::lock_guard l(m);live[k(x.descriptor)]=x.descriptor;x.ok=true;return x;}
SblrSessionSettingSetCoordinationResult ConsumeSblrSessionSettingSetDescriptor(const EngineRequestContext&c,const D&v){SblrSessionSettingSetCoordinationResult x;if(!c.security_context_present||!scratchbird::core::uuid::IsEngineIdentityUuid(EngineUuid{v.receipt})||EngineUuid{v.receipt}!=c.statement_uuid){x.diagnostic=diag("SECURITY.ACCESS_DENIED","sblr.session_setting_set.hidden");return x;}std::lock_guard l(m);auto q=k(v);if(!live.count(q)){x.diagnostic=diag(used.count(q)?"MGA.TRANSACTION.STALE":"SECURITY.ACCESS_DENIED","sblr.session_setting_set.replay");return x;}if(c.query_cancellation_requested&&c.query_cancellation_requested()){x.diagnostic=diag("PROCESS.CANCELLED","sblr.session_setting_set.cancelled");return x;}used[q]=v;live.erase(q);x.ok=true;return x;}}
