#include "sblr_read_stream_coordinator.hpp"
#include "api_diagnostics.hpp"
#include "core/uuid/uuid.hpp"
#include <algorithm>
#include <chrono>
#include <fstream>
#include <mutex>
#include <unordered_map>
namespace scratchbird::engine::internal_api{namespace{std::mutex m;std::unordered_map<std::string,scratchbird::engine::sblr::SblrReadStreamDescriptorV1>live,used;std::uint64_t gen=0;EngineApiDiagnostic D(std::string c,std::string k){return MakeEngineApiDiagnostic(std::move(c),std::move(k),{});}bool tag(const EngineRequestContext&c,const char*t){return c.security_context_present&&std::find(c.trace_tags.begin(),c.trace_tags.end(),t)!=c.trace_tags.end();}auto uuid(){auto x=scratchbird::core::uuid::GenerateEngineIdentityV7(scratchbird::core::platform::UuidKind::object,static_cast<std::uint64_t>(std::chrono::system_clock::now().time_since_epoch().count())+(++gen));scratchbird::engine::sblr::StreamUuid o{};if(x.ok())std::copy(x.value.value.bytes.begin(),x.value.value.bytes.end(),o.begin());return o;}std::string key(const auto&u){static constexpr char h[]="0123456789abcdef";std::string s;for(auto b:u){s.push_back(h[b>>4]);s.push_back(h[b&15]);}return s;}bool journal(const EngineRequestContext&c,char e,const auto&d){std::ofstream f(c.database_path+".sb.sblr_read_stream.v1",std::ios::app);if(!f)return false;f<<e<<'\t'<<key(d.descriptor)<<'\t'<<d.descriptor_generation<<'\n';f.flush();return bool(f);}}
SblrReadStreamCoordinationResult CompileSblrReadStreamDescriptor(const EngineRequestContext&c,const std::string&receipt,std::uint64_t occurrence,std::uint32_t stream_occurrence,std::uint64_t availability){std::lock_guard l(m);SblrReadStreamCoordinationResult r;if(!tag(c,"private_stream_read_compiler")||!c.statement_metadata_snapshot_engine_owned){r.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.read_stream.descriptor_hidden");return r;}if(receipt!=c.statement_uuid.canonical||!occurrence||!stream_occurrence||!availability){r.diagnostic=D("SBLR.OPERAND_INVALID","sblr.read_stream.coordination_invalid");return r;}auto&d=r.descriptor;d.descriptor=uuid();d.relation=uuid();d.schema=uuid();d.mga=uuid();d.security=uuid();d.row_shape=uuid();d.policy=uuid();d.descriptor_generation=d.relation_generation=d.schema_generation=d.mga_generation=d.security_generation=d.row_shape_generation=d.policy_generation=++gen;d.mode=1;d.redaction=1;d.maximum_rows=64;d.maximum_bytes=65536;d.availability_generation=availability;auto b=scratchbird::engine::sblr::EncodeSblrReadStreamDescriptorV1(d,false);if(b.size()!=240||!scratchbird::engine::sblr::DecodeSblrReadStreamDescriptorV1(b.data(),b.size(),&d,nullptr,false)||!journal(c,'P',d)){r.diagnostic=D("READ.STREAM_FAILED","sblr.read_stream.publish_failed");return r;}live[key(d.descriptor)]=d;r.ok=true;r.diagnostic=D("OK","ok");return r;}
SblrReadStreamCoordinationResult ConsumeSblrReadStreamDescriptor(const EngineRequestContext&c,const scratchbird::engine::sblr::SblrReadStreamDescriptorV1&d){std::lock_guard l(m);SblrReadStreamCoordinationResult r;if(!tag(c,"private_read_stream")){r.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.read_stream.descriptor_hidden");return r;}auto k=key(d.descriptor);auto it=live.find(k);if(it==live.end()){r.diagnostic=used.count(k)?D("READ.SNAPSHOT_STALE","sblr.read_stream.stale"):D("SECURITY.ACCESS_DENIED","sblr.read_stream.descriptor_hidden");return r;}if(scratchbird::engine::sblr::EncodeSblrReadStreamDescriptorV1(it->second,true)!=scratchbird::engine::sblr::EncodeSblrReadStreamDescriptorV1(d,true)){r.diagnostic=D("READ.SNAPSHOT_STALE","sblr.read_stream.stale");return r;}if(c.query_cancellation_requested&&c.query_cancellation_requested()){r.diagnostic=D("PROCESS.CANCELLED","sblr.read_stream.cancelled");return r;}if(!journal(c,'C',d)){r.diagnostic=D("READ.STREAM_FAILED","sblr.read_stream.consume_failed");return r;}used[k]=d;live.erase(it);r.ok=true;r.descriptor=d;r.diagnostic=D("OK","ok");return r;}
EngineApiDiagnostic RecoverSblrReadStreamDescriptors(const EngineRequestContext&c){std::lock_guard l(m);if(!tag(c,"right:SBLR_READ_ADMIN"))return D("SECURITY.ACCESS_DENIED","sblr.read_stream.recovery_denied");for(auto&[k,d]:live){(void)k;journal(c,'X',d);}live.clear();return D("OK","ok");}}
