#include "sblr_error_vector_descriptor_registry.hpp"
#include "api_diagnostics.hpp"
#include "hash_digest.hpp"
#include "uuid.hpp"
#include <algorithm>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <mutex>
#include <sstream>
#include <unordered_map>
namespace scratchbird::engine::internal_api {namespace{
std::mutex m;std::unordered_map<std::string,SblrErrorVectorDescriptorSnapshotV1> live;std::unordered_map<std::string,std::uint64_t> high;
EngineApiDiagnostic D(std::string c,std::string k,std::string d={}){return MakeEngineApiDiagnostic(std::move(c),std::move(k),std::move(d));}bool Tag(const EngineRequestContext&c,std::string_view t){return std::find(c.trace_tags.begin(),c.trace_tags.end(),t)!=c.trace_tags.end();}bool Auth(const EngineRequestContext&c){return c.security_context_present&&c.statement_metadata_snapshot_engine_owned&&Tag(c,"private_error_vector_registry");}std::string Path(const EngineRequestContext&c){return c.database_path+".sb.sblr_error_vector_registry.v1";}std::string New(std::uint64_t salt){auto n=static_cast<std::uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count());auto u=scratchbird::core::uuid::GenerateEngineIdentityV7(scratchbird::core::platform::UuidKind::object,n+salt);return u.ok()?scratchbird::core::uuid::UuidToString(u.value.value):"";}std::string Hex(const std::vector<std::uint8_t>&v){static const char h[]="0123456789abcdef";std::string o;for(auto b:v){o+=h[b>>4];o+=h[b&15];}return o;}std::string Hash(std::string_view s){auto d=scratchbird::core::hash::ComputeSha256Digest(reinterpret_cast<const scratchbird::core::platform::byte*>(s.data()),s.size());return d.ok()?"sha256:"+scratchbird::core::hash::HexLower(d.digest):"";}std::string Record(const SblrErrorVectorDescriptorSnapshotV1&s,std::string_view reason){std::ostringstream o;o<<s.descriptor_uuid<<'\t'<<s.descriptor_generation<<'\t'<<s.registry_snapshot_uuid<<'\t'<<s.registry_generation<<'\t'<<s.statement_receipt_uuid<<'\t'<<s.diagnostic_registry_snapshot_uuid<<'\t'<<s.diagnostic_registry_generation<<'\t'<<s.database_uuid<<'\t'<<s.session_uuid<<'\t'<<unsigned(s.lifecycle)<<'\t'<<s.vector_sha256<<'\t'<<reason<<'\t'<<Hex(s.canonical_ervd);return o.str();}bool Publish(const EngineRequestContext&c,SblrErrorVectorDescriptorSnapshotV1*s,std::string_view reason){auto r=Record(*s,reason);s->evidence_sha256=Hash("ScratchBird.SblrErrorVectorRegistryEvidence.V1"+r);std::ofstream f(Path(c),std::ios::binary|std::ios::app);if(!f)return false;f<<"E\t"<<s->evidence_sha256<<'\t'<<r<<'\n';f.flush();if(!f)return false;f<<"S\t"<<s->evidence_sha256<<'\t'<<r<<'\n';f.flush();return bool(f);}
std::vector<std::string> Split(std::string_view v){std::vector<std::string>o;size_t b=0;while(b<=v.size()){auto e=v.find('\t',b);o.emplace_back(v.substr(b,e==std::string_view::npos?v.size()-b:e-b));if(e==std::string_view::npos)break;b=e+1;}return o;}
bool Number(std::string_view v,std::uint64_t*out){if(v.empty())return false;std::uint64_t n=0;for(char c:v){if(c<'0'||c>'9'||n>(UINT64_MAX-static_cast<unsigned>(c-'0'))/10)return false;n=n*10+static_cast<unsigned>(c-'0');}*out=n;return true;}
bool Unhex(std::string_view v,std::vector<std::uint8_t>*out){if(v.size()%2)return false;auto d=[](char c){return c>='0'&&c<='9'?c-'0':c>='a'&&c<='f'?c-'a'+10:-1;};out->clear();for(size_t i=0;i<v.size();i+=2){int a=d(v[i]),b=d(v[i+1]);if(a<0||b<0)return false;out->push_back(static_cast<std::uint8_t>((a<<4)|b));}return true;}
std::string Uuid(const std::array<std::uint8_t,16>&b){static const char h[]="0123456789abcdef";std::string o;for(size_t i=0;i<16;++i){if(i==4||i==6||i==8||i==10)o.push_back('-');o.push_back(h[b[i]>>4]);o.push_back(h[b[i]&15]);}return o;}
std::string Sha(const std::array<std::uint8_t,32>&b){static const char h[]="0123456789abcdef";std::string o="sha256:";for(auto x:b){o.push_back(h[x>>4]);o.push_back(h[x&15]);}return o;}
bool DecodeLine(const std::string&line,char tag,SblrErrorVectorDescriptorSnapshotV1*out){auto f=Split(line);std::uint64_t life=0;if(f.size()!=16||f[0]!=std::string(1,tag)||!Number(f[3],&out->descriptor_generation)||!Number(f[5],&out->registry_generation)||!Number(f[8],&out->diagnostic_registry_generation)||!Number(f[11],&life)||life<1||life>2||!Unhex(f[15],&out->canonical_ervd))return false;out->evidence_sha256=f[1];out->descriptor_uuid=f[2];out->registry_snapshot_uuid=f[4];out->statement_receipt_uuid=f[6];out->diagnostic_registry_snapshot_uuid=f[7];out->database_uuid=f[9];out->session_uuid=f[10];out->lifecycle=static_cast<SblrErrorVectorLifecycleV1>(life);out->vector_sha256=f[12];scratchbird::engine::sblr::SblrErrorVectorDescriptorV1 decoded;std::string error;if(!scratchbird::engine::sblr::DecodeSblrErrorVectorDescriptorV1(out->canonical_ervd.data(),out->canonical_ervd.size(),&decoded,&error))return false;auto record=line.substr(line.find('\t',2)+1);return Uuid(decoded.descriptor_uuid)==out->descriptor_uuid&&decoded.descriptor_generation==out->descriptor_generation&&Uuid(decoded.registry_snapshot_uuid)==out->registry_snapshot_uuid&&decoded.registry_generation<=out->registry_generation&&Uuid(decoded.statement_receipt_uuid)==out->statement_receipt_uuid&&Uuid(decoded.diagnostic_registry_snapshot_uuid)==out->diagnostic_registry_snapshot_uuid&&decoded.diagnostic_registry_generation==out->diagnostic_registry_generation&&Sha(decoded.vector_sha256)==out->vector_sha256&&out->evidence_sha256==Hash("ScratchBird.SblrErrorVectorRegistryEvidence.V1"+record);}
bool Replay(const EngineRequestContext&c,std::unordered_map<std::string,SblrErrorVectorDescriptorSnapshotV1>*states,std::uint64_t*highest){states->clear();*highest=0;std::ifstream in(Path(c),std::ios::binary);if(!in)return !std::filesystem::exists(Path(c));std::vector<std::string>lines;std::string line;while(std::getline(in,line))lines.push_back(line);if(!in.eof()||lines.size()%2)return false;for(size_t i=0;i<lines.size();i+=2){SblrErrorVectorDescriptorSnapshotV1 e,s;if(!DecodeLine(lines[i],'E',&e)||!DecodeLine(lines[i+1],'S',&s)||lines[i].substr(2)!=lines[i+1].substr(2)||s.database_uuid!=c.database_uuid.canonical||s.registry_generation<=*highest)return false;auto prior=states->find(s.descriptor_uuid);if(prior==states->end()){if(s.descriptor_generation!=1||s.lifecycle!=SblrErrorVectorLifecycleV1::active)return false;}else if(s.lifecycle!=SblrErrorVectorLifecycleV1::revoked||prior->second.lifecycle!=SblrErrorVectorLifecycleV1::active||s.statement_receipt_uuid!=prior->second.statement_receipt_uuid||s.registry_snapshot_uuid!=prior->second.registry_snapshot_uuid||s.diagnostic_registry_snapshot_uuid!=prior->second.diagnostic_registry_snapshot_uuid||s.vector_sha256!=prior->second.vector_sha256||s.canonical_ervd!=prior->second.canonical_ervd)return false;(*states)[s.descriptor_uuid]=s;*highest=s.registry_generation;}return true;}
}
SblrErrorVectorRegistryResultV1 IssueSblrErrorVectorDescriptorV1(const EngineRequestContext&c,const std::string&receipt,const std::string&rs,std::uint64_t rg,const std::string&ds,std::uint64_t dg,std::vector<scratchbird::engine::sblr::SblrErrorVectorEntryV1> entries){std::lock_guard l(m);SblrErrorVectorRegistryResultV1 out;if(!Auth(c)){out.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.error_vector.hidden");return out;}if(receipt.empty()||rs.empty()||!rg||ds.empty()||!dg||entries.empty()){out.diagnostic=D("SBLR.OPERAND_INVALID","sblr.error_vector.issue_invalid");return out;}SblrErrorVectorDescriptorSnapshotV1 s;s.descriptor_uuid=New(++high[c.database_uuid.canonical]);s.descriptor_generation=1;s.registry_snapshot_uuid=rs;s.registry_generation=high[c.database_uuid.canonical];s.statement_receipt_uuid=receipt;s.diagnostic_registry_snapshot_uuid=ds;s.diagnostic_registry_generation=dg;s.database_uuid=c.database_uuid.canonical;s.session_uuid=c.session_uuid.canonical;scratchbird::engine::sblr::SblrErrorVectorDescriptorV1 v;auto put=[](const std::string&t,auto*a){auto p=scratchbird::core::uuid::ParseUuid(t);if(p.ok())std::copy(p.value.bytes.begin(),p.value.bytes.end(),a->begin());};put(s.descriptor_uuid,&v.descriptor_uuid);v.descriptor_generation=1;put(rs,&v.registry_snapshot_uuid);v.registry_generation=s.registry_generation;put(receipt,&v.statement_receipt_uuid);put(ds,&v.diagnostic_registry_snapshot_uuid);v.diagnostic_registry_generation=dg;v.entries=std::move(entries);s.canonical_ervd=scratchbird::engine::sblr::EncodeSblrErrorVectorDescriptorV1(&v);if(s.canonical_ervd.empty()){out.diagnostic=D("SBLR.OPERAND_INVALID","sblr.error_vector.vector_invalid");return out;}s.vector_sha256="sha256:"+scratchbird::core::hash::HexLower(v.vector_sha256);if(!Publish(c,&s,"issue")){out.diagnostic=D("SBLR.EXECUTION_FAILED","sblr.error_vector.publish_failed");return out;}live[s.descriptor_uuid]=s;out.ok=true;out.snapshot=s;out.diagnostic=D("OK","ok");out.evidence.push_back({"sblr.error_vector.issue",s.evidence_sha256});return out;}
SblrErrorVectorRegistryResultV1 LookupSblrErrorVectorDescriptorV1(const EngineRequestContext&c,const std::string&r,const std::string&id,std::uint64_t g){std::lock_guard l(m);SblrErrorVectorRegistryResultV1 out;if(!Auth(c)){out.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.error_vector.hidden");return out;}auto i=live.find(id);if(i==live.end()||i->second.statement_receipt_uuid!=r||i->second.session_uuid!=c.session_uuid.canonical){out.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.error_vector.hidden");return out;}if(i->second.descriptor_generation!=g||i->second.lifecycle!=SblrErrorVectorLifecycleV1::active){out.diagnostic=D("SBLR.ERROR_VECTOR.STALE","sblr.error_vector.stale");return out;}out.ok=true;out.snapshot=i->second;out.diagnostic=D("OK","ok");return out;}
EngineApiDiagnostic RevokeSblrErrorVectorDescriptorsV1(const EngineRequestContext&c,const std::string&r,const std::string&reason){std::lock_guard l(m);if(!Auth(c))return D("SECURITY.ACCESS_DENIED","sblr.error_vector.revoke_denied");for(auto i=live.begin();i!=live.end();)if(i->second.statement_receipt_uuid==r){auto s=i->second;s.lifecycle=SblrErrorVectorLifecycleV1::revoked;s.registry_generation=++high[c.database_uuid.canonical];if(!Publish(c,&s,reason))return D("SBLR.EXECUTION_FAILED","sblr.error_vector.revoke_failed");i=live.erase(i);}else ++i;return D("OK","ok");}
EngineApiDiagnostic RecoverSblrErrorVectorDescriptorRegistryV1(const EngineRequestContext&c){if(!c.security_context_present||!Tag(c,"right:SBLR_ERROR_VECTOR_REGISTRY_ADMIN"))return D("SECURITY.ACCESS_DENIED","sblr.error_vector.recovery_denied");std::lock_guard l(m);std::unordered_map<std::string,SblrErrorVectorDescriptorSnapshotV1> states;std::uint64_t highest=0;if(!Replay(c,&states,&highest))return D("SBLR.ERROR_VECTOR.STALE","sblr.error_vector.registry_corrupt","torn or contradictory registry evidence");high[c.database_uuid.canonical]=highest;for(auto&[id,s]:states)if(s.lifecycle==SblrErrorVectorLifecycleV1::active){s.lifecycle=SblrErrorVectorLifecycleV1::revoked;s.registry_generation=++high[c.database_uuid.canonical];if(!Publish(c,&s,"recovery.revoke"))return D("SBLR.EXECUTION_FAILED","sblr.error_vector.recovery_failed");}for(auto i=live.begin();i!=live.end();)if(i->second.database_uuid==c.database_uuid.canonical)i=live.erase(i);else++i;return D("OK","ok");}
}
