#include "sblr_diagnostic_identity_registry.hpp"
#include "api_diagnostics.hpp"
#include "hash_digest.hpp"
#include "uuid.hpp"
#include <algorithm>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <mutex>
#include <sstream>
namespace scratchbird::engine::internal_api {
EngineApiDiagnostic MakeEngineApiDiagnostic(std::string code,
                                            std::string message_key) {
  return MakeEngineApiDiagnostic(std::move(code), std::move(message_key), {});
}
namespace{
std::mutex mutex;std::string H(std::string_view v){auto d=scratchbird::core::hash::ComputeSha256Digest(reinterpret_cast<const scratchbird::core::platform::byte*>(v.data()),v.size());return d.ok()?"sha256:"+scratchbird::core::hash::HexLower(d.digest):"";}EngineApiDiagnostic D(std::string c,std::string k){return MakeEngineApiDiagnostic(std::move(c),std::move(k));}std::string P(const EngineRequestContext&c){return c.database_path+".sb.sblr_diagnostic_identity_registry.v1";}std::string New(std::uint64_t salt){auto n=static_cast<std::uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count());auto u=scratchbird::core::uuid::GenerateEngineIdentityV7(scratchbird::core::platform::UuidKind::object,n+salt);return u.ok()?scratchbird::core::uuid::UuidToString(u.value.value):"";}std::string RowMaterial(const SblrDiagnosticIdentityRowV1&r){std::ostringstream o;o<<"ScratchBird.DiagnosticIdentityRegistryRow.V1"<<r.diagnostic_uuid<<'\t'<<r.diagnostic_generation<<'\t'<<r.precedence_ordinal<<'\t'<<unsigned(r.severity_code)<<'\t'<<unsigned(r.redaction_class)<<'\t'<<r.maximum_safe_field_count;return o.str();}std::string Material(const SblrDiagnosticIdentitySnapshotV1&s){std::string o="ScratchBird.DiagnosticIdentityRegistrySnapshot.V1"+s.snapshot_uuid+"\t"+std::to_string(s.generation);for(const auto&r:s.rows)o+='\t'+r.row_identity_sha256;return o;}bool Save(const EngineRequestContext&c,SblrDiagnosticIdentitySnapshotV1*s){s->evidence_sha256=H(Material(*s));std::ofstream f(P(c),std::ios::binary|std::ios::trunc);if(!f)return false;f<<s->snapshot_uuid<<'\t'<<s->generation<<'\t'<<s->evidence_sha256<<'\n';for(const auto&r:s->rows)f<<r.diagnostic_uuid<<'\t'<<r.diagnostic_generation<<'\t'<<r.precedence_ordinal<<'\t'<<unsigned(r.severity_code)<<'\t'<<unsigned(r.redaction_class)<<'\t'<<r.maximum_safe_field_count<<'\t'<<r.row_identity_sha256<<'\n';f.flush();return bool(f);}bool Load(const EngineRequestContext&c,SblrDiagnosticIdentitySnapshotV1*s){std::ifstream f(P(c),std::ios::binary);if(!f)return false;std::string line;if(!std::getline(f,line))return false;std::istringstream h(line);if(!std::getline(h,s->snapshot_uuid,'\t')||!(h>>s->generation)||h.get()!='\t'||!std::getline(h,s->evidence_sha256))return false;while(std::getline(f,line)){std::istringstream x(line);SblrDiagnosticIdentityRowV1 r;unsigned sev=0,red=0;if(!std::getline(x,r.diagnostic_uuid,'\t')||!(x>>r.diagnostic_generation)||x.get()!='\t'||!(x>>r.precedence_ordinal)||x.get()!='\t'||!(x>>sev)||x.get()!='\t'||!(x>>red)||x.get()!='\t'||!(x>>r.maximum_safe_field_count)||x.get()!='\t'||!std::getline(x,r.row_identity_sha256)||sev<1||sev>4||red>4)return false;r.severity_code=sev;r.redaction_class=red;if(r.row_identity_sha256!=H(RowMaterial(r)))return false;s->rows.push_back(r);}return !s->rows.empty()&&s->evidence_sha256==H(Material(*s));}
}
SblrDiagnosticIdentityResultV1 LoadSblrDiagnosticIdentitySnapshotV1(const EngineRequestContext&c){std::lock_guard l(mutex);SblrDiagnosticIdentityResultV1 o;if(!c.security_context_present||!c.statement_metadata_snapshot_engine_owned||c.database_path.empty()){o.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.diagnostic_registry.hidden");return o;}SblrDiagnosticIdentitySnapshotV1 s;if(std::filesystem::exists(P(c))){if(!Load(c,&s)){o.diagnostic=D("SBLR.ERROR_VECTOR.STALE","sblr.diagnostic_registry.corrupt");return o;}}else{s.snapshot_uuid=New(1);s.generation=1;for(std::uint32_t i=1;i<=4;++i){SblrDiagnosticIdentityRowV1 r;r.diagnostic_uuid=New(i+1);r.diagnostic_generation=1;r.precedence_ordinal=i;r.severity_code=static_cast<std::uint8_t>(i);r.redaction_class=1;r.maximum_safe_field_count=16;r.row_identity_sha256=H(RowMaterial(r));s.rows.push_back(r);}if(!Save(c,&s)){o.diagnostic=D("SBLR.EXECUTION_FAILED","sblr.diagnostic_registry.publish_failed");return o;}}o.ok=true;o.snapshot=std::move(s);o.diagnostic=D("OK","ok");return o;}
SblrDiagnosticIdentityResultV1 LookupSblrDiagnosticIdentityV1(const EngineRequestContext&c,const SblrDiagnosticIdentitySnapshotV1&s,const std::string&id,std::uint64_t gen){auto loaded=LoadSblrDiagnosticIdentitySnapshotV1(c);if(!loaded.ok)return loaded;SblrDiagnosticIdentityResultV1 o;if(loaded.snapshot.snapshot_uuid!=s.snapshot_uuid||loaded.snapshot.generation!=s.generation){o.diagnostic=D("SBLR.ERROR_VECTOR.STALE","sblr.diagnostic_registry.stale");return o;}auto it=std::find_if(loaded.snapshot.rows.begin(),loaded.snapshot.rows.end(),[&](const auto&r){return r.diagnostic_uuid==id&&r.diagnostic_generation==gen;});if(it==loaded.snapshot.rows.end()){o.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.diagnostic_registry.hidden");return o;}o.ok=true;o.snapshot=loaded.snapshot;o.row=*it;o.diagnostic=D("OK","ok");return o;}
}
