#include "sblr_transaction_begin_authority.hpp"
#include "api_diagnostics.hpp"
#include "uuid.hpp"
#include <chrono>
#include <filesystem>
#include <fstream>
namespace scratchbird::engine::internal_api {namespace{std::string New(std::uint64_t salt){auto n=static_cast<std::uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count());auto u=scratchbird::core::uuid::GenerateEngineIdentityV7(scratchbird::core::platform::UuidKind::object,n+salt);return u.ok()?scratchbird::core::uuid::UuidToString(u.value.value):"";}std::string Path(const EngineRequestContext&c){return c.database_path+".sb.sblr_txn_begin_authority.v1";}EngineApiDiagnostic D(std::string c,std::string k){return MakeEngineApiDiagnostic(std::move(c),std::move(k),{});}}
SblrTransactionBeginAuthorityResultV1 LoadSblrTransactionBeginAuthorityV1(const EngineRequestContext&c){SblrTransactionBeginAuthorityResultV1 out;if(!c.security_context_present||!c.statement_metadata_snapshot_engine_owned||c.database_path.empty()){out.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.txn_begin.authority_hidden");return out;}auto path=Path(c);if(std::filesystem::exists(path)){std::ifstream f(path);if(!(f>>out.authority.isolation_profile_uuid>>out.authority.isolation_profile_generation>>out.authority.transaction_policy_snapshot_uuid>>out.authority.transaction_policy_generation)){out.diagnostic=D("MGA.TRANSACTION.STALE","sblr.txn_begin.authority_corrupt");return out;}}else{out.authority.isolation_profile_uuid=New(1);out.authority.isolation_profile_generation=1;out.authority.transaction_policy_snapshot_uuid=New(2);out.authority.transaction_policy_generation=1;std::ofstream f(path,std::ios::trunc);if(!f||!(f<<out.authority.isolation_profile_uuid<<' '<<out.authority.isolation_profile_generation<<' '<<out.authority.transaction_policy_snapshot_uuid<<' '<<out.authority.transaction_policy_generation<<'\n')){out.diagnostic=D("SBLR.EXECUTION_FAILED","sblr.txn_begin.authority_publish_failed");return out;}}out.ok=true;out.diagnostic=D("OK","ok");return out;}
}
