#include "sblr_ddl_create_operator_coordinator.hpp"
#include "api_diagnostics.hpp"
#include <algorithm>
#include <map>
#include <mutex>
namespace scratchbird::engine::internal_api { namespace { std::mutex m; using D=scratchbird::engine::sblr::SblrDdlCreateOperatorDescriptorV1; std::map<std::string,D> live,used; std::string key(const D&d){return{reinterpret_cast<const char*>(d.body.data()),d.body.size()};} bool tag(const EngineRequestContext&c,const char*t){return c.security_context_present&&std::find(c.trace_tags.begin(),c.trace_tags.end(),t)!=c.trace_tags.end();} EngineApiDiagnostic dg(std::string c,std::string x){return MakeEngineApiDiagnostic(std::move(c),std::move(x),{});} }
SblrDdlCreateOperatorCoordinationResult CompileSblrDdlCreateOperatorDescriptor(const EngineRequestContext&c,const std::string&n,std::uint64_t a){std::lock_guard l(m);SblrDdlCreateOperatorCoordinationResult o;if(!tag(c,"private_ddl_create_operator_binder")||!c.statement_metadata_snapshot_engine_owned||n!=c.statement_uuid.canonical||!a||!tag(c,"cluster_provider_admitted")||!tag(c,"cluster_route_fence_admitted")){o.diagnostic=dg("CLUSTER.GATEWAY_CLUSTER_FALLTHROUGH_FORBIDDEN","sblr.ddl_create_operator.cluster_gate");return o;}o.descriptor.body[0]=1;o.descriptor.body[16]=1;for(int i=0;i<8;++i)o.descriptor.body[136+i]=std::uint8_t(a>>(8*i));auto b=scratchbird::engine::sblr::EncodeSblrDdlCreateOperatorDescriptorV1(o.descriptor);if(b.empty()||!scratchbird::engine::sblr::DecodeSblrDdlCreateOperatorDescriptorV1(b.data(),b.size(),&o.descriptor,nullptr)){o.diagnostic=dg("SBLR.OPERAND.INVALID","sblr.ddl_create_operator.descriptor_invalid");return o;}live[key(o.descriptor)]=o.descriptor;o.ok=true;o.diagnostic=dg("OK","ok");return o;}
SblrDdlCreateOperatorCoordinationResult ConsumeSblrDdlCreateOperatorDescriptor(const EngineRequestContext&c,const D&d){std::lock_guard l(m);SblrDdlCreateOperatorCoordinationResult o;auto k=key(d);if(!tag(c,"private_ddl_create_operator")){o.diagnostic=dg("SECURITY.ACCESS_DENIED","sblr.ddl_create_operator.hidden");return o;}auto i=live.find(k);if(i==live.end()){o.diagnostic=used.count(k)?dg("MGA.TRANSACTION.STALE","sblr.ddl_create_operator.stale"):dg("SECURITY.ACCESS_DENIED","sblr.ddl_create_operator.hidden");return o;}if(c.query_cancellation_requested&&c.query_cancellation_requested()){o.diagnostic=dg("PROCESS.CANCELLED","sblr.ddl_create_operator.cancelled");return o;}used[k]=d;live.erase(i);o.ok=true;o.descriptor=d;o.diagnostic=dg("OK","ok");return o;}
}
