#include "sblr_read_range_coordinator.hpp"
#include "api_diagnostics.hpp"
#include "core/hash/hash_digest.hpp"
#include "core/uuid/uuid.hpp"
#include <algorithm>
#include <chrono>
#include <fstream>
#include <mutex>
#include <unordered_map>
namespace scratchbird::engine::internal_api { namespace {
std::mutex mutex; std::unordered_map<std::string,scratchbird::engine::sblr::SblrReadRangeDescriptorV1> live,used; std::uint64_t generation=0;
EngineApiDiagnostic diag(std::string c,std::string k){return MakeEngineApiDiagnostic(std::move(c),std::move(k),{});}
bool tag(const EngineRequestContext&c,const char*t){return c.security_context_present&&std::find(c.trace_tags.begin(),c.trace_tags.end(),t)!=c.trace_tags.end();}
auto uuid(){auto x=scratchbird::core::uuid::GenerateEngineIdentityV7(scratchbird::core::platform::UuidKind::object,static_cast<std::uint64_t>(std::chrono::system_clock::now().time_since_epoch().count())+(++generation));scratchbird::engine::sblr::RangeUuid out{};if(x.ok())std::copy(x.value.value.bytes.begin(),x.value.value.bytes.end(),out.begin());return out;}
std::string key(const auto&u){static constexpr char h[]="0123456789abcdef";std::string s;for(auto b:u){s.push_back(h[b>>4]);s.push_back(h[b&15]);}return s;}
bool journal(const EngineRequestContext&c,char event,const auto&d){std::ofstream f(c.database_path+".sb.sblr_read_range.v1",std::ios::app);if(!f)return false;f<<event<<'\t'<<key(d.descriptor)<<'\t'<<d.descriptor_generation<<'\n';f.flush();return bool(f);}
}
SblrReadRangeCoordinationResult CompileSblrReadRangeDescriptor(const EngineRequestContext&c,const std::string&receipt,std::uint64_t occurrence,std::uint32_t range_occurrence,std::uint64_t availability){std::lock_guard lock(mutex);SblrReadRangeCoordinationResult r;if(!tag(c,"private_range_read_compiler")||!c.statement_metadata_snapshot_engine_owned){r.diagnostic=diag("SECURITY.ACCESS_DENIED","sblr.read_range.descriptor_hidden");return r;}if(receipt!=c.statement_uuid.canonical||!occurrence||!range_occurrence||!availability){r.diagnostic=diag("SBLR.OPERAND_INVALID","sblr.read_range.coordination_invalid");return r;}auto&d=r.descriptor;d.descriptor=uuid();d.relation=uuid();d.index=uuid();d.schema=uuid();d.mga=uuid();d.security=uuid();d.key_type=uuid();d.codec=uuid();d.collation=uuid();d.descriptor_generation=d.relation_generation=d.index_generation=d.schema_generation=d.mga_generation=d.security_generation=d.codec_generation=d.collation_generation=++generation;d.lower_state=d.upper_state=1;d.lower_length=d.upper_length=8;for(unsigned i=0;i<8;i++){d.lower[i]=static_cast<std::uint8_t>(range_occurrence>>(i*4));d.upper[i]=static_cast<std::uint8_t>((range_occurrence+1)>>(i*4));}d.inclusivity=3;d.direction=1;d.maximum_rows=64;d.availability_generation=availability;auto bytes=scratchbird::engine::sblr::EncodeSblrReadRangeDescriptorV1(d,false);if(bytes.size()!=404||!scratchbird::engine::sblr::DecodeSblrReadRangeDescriptorV1(bytes.data(),bytes.size(),&d,nullptr,false)||!journal(c,'P',d)){r.diagnostic=diag("READ.RANGE_FAILED","sblr.read_range.descriptor_publish_failed");return r;}live[key(d.descriptor)]=d;r.ok=true;r.diagnostic=diag("OK","ok");return r;}
SblrReadRangeCoordinationResult ConsumeSblrReadRangeDescriptor(const EngineRequestContext&c,const scratchbird::engine::sblr::SblrReadRangeDescriptorV1&d){std::lock_guard lock(mutex);SblrReadRangeCoordinationResult r;if(!tag(c,"private_read_range")){r.diagnostic=diag("SECURITY.ACCESS_DENIED","sblr.read_range.descriptor_hidden");return r;}auto k=key(d.descriptor);auto it=live.find(k);if(it==live.end()){r.diagnostic=used.count(k)?diag("READ.SNAPSHOT_STALE","sblr.read_range.stale"):diag("SECURITY.ACCESS_DENIED","sblr.read_range.descriptor_hidden");return r;}if(scratchbird::engine::sblr::EncodeSblrReadRangeDescriptorV1(it->second,true)!=scratchbird::engine::sblr::EncodeSblrReadRangeDescriptorV1(d,true)){r.diagnostic=diag("READ.SNAPSHOT_STALE","sblr.read_range.stale");return r;}if(c.query_cancellation_requested&&c.query_cancellation_requested()){r.diagnostic=diag("PROCESS.CANCELLED","sblr.read_range.cancelled");return r;}if(!journal(c,'C',d)){r.diagnostic=diag("READ.RANGE_FAILED","sblr.read_range.consume_failed");return r;}used[k]=d;live.erase(it);r.ok=true;r.descriptor=d;r.diagnostic=diag("OK","ok");return r;}
EngineApiDiagnostic RecoverSblrReadRangeDescriptors(const EngineRequestContext&c){std::lock_guard lock(mutex);if(!tag(c,"right:SBLR_READ_ADMIN"))return diag("SECURITY.ACCESS_DENIED","sblr.read_range.recovery_denied");for(auto&[k,d]:live){(void)k;journal(c,'X',d);}live.clear();return diag("OK","ok");}
}
