#include "sblr_database_create_template_clone_coordinator.hpp"
#include "api_diagnostics.hpp"
#include <map>
#include <mutex>
#include <algorithm>
namespace scratchbird::engine::internal_api { namespace {std::mutex m;using D=scratchbird::engine::sblr::SblrDatabaseCreateTemplateCloneDescriptorV1;std::map<std::string,D> live,used;std::string k(const std::array<std::uint8_t,32>&x){return{reinterpret_cast<const char*>(x.data()),x.size()};}bool tag(const EngineRequestContext&c,const char*t){return c.security_context_present&&std::find(c.trace_tags.begin(),c.trace_tags.end(),t)!=c.trace_tags.end();}EngineApiDiagnostic d(std::string c,std::string q){return MakeEngineApiDiagnostic(std::move(c),std::move(q),{});}}
SblrDatabaseCreateTemplateCloneCoordinationResult CompileSblrDatabaseCreateTemplateCloneDescriptor(const EngineRequestContext&c,const std::string&r,std::uint64_t o,std::uint32_t t,std::uint64_t a){std::lock_guard l(m);SblrDatabaseCreateTemplateCloneCoordinationResult x;if(!tag(c,"private_database_create_template_clone_binder")||!c.statement_metadata_snapshot_engine_owned||r!=c.statement_uuid.canonical||!o||!t||!a){x.diagnostic=d("SBLR.OPERAND.INVALID","database_template_clone.invalid");return x;}x.descriptor.body[0]=1;x.descriptor.availability=a;auto b=scratchbird::engine::sblr::EncodeSblrDatabaseCreateTemplateCloneDescriptorV1(x.descriptor,false);if(b.empty()||!scratchbird::engine::sblr::DecodeSblrDatabaseCreateTemplateCloneDescriptorV1(b.data(),b.size(),&x.descriptor,nullptr,false)){x.diagnostic=d("SBLR.OPERAND.INVALID","database_template_clone.descriptor_invalid");return x;}live[k(x.descriptor.evidence)]=x.descriptor;x.ok=true;return x;}
SblrDatabaseCreateTemplateCloneCoordinationResult ConsumeSblrDatabaseCreateTemplateCloneDescriptor(const EngineRequestContext&c,const D&v){std::lock_guard l(m);SblrDatabaseCreateTemplateCloneCoordinationResult x;if(!tag(c,"private_database_create_template_clone")){x.diagnostic=d("SECURITY.ACCESS_DENIED","database_template_clone.hidden");return x;}auto i=live.find(k(v.evidence));if(i==live.end()){x.diagnostic=d(used.count(k(v.evidence))?"MGA.TRANSACTION.STALE":"SECURITY.ACCESS_DENIED","database_template_clone.replay");return x;}if(c.query_cancellation_requested&&c.query_cancellation_requested()){x.diagnostic=d("PROCESS.CANCELLED","database_template_clone.cancelled");return x;}used[k(v.evidence)]=v;live.erase(i);x.ok=true;x.descriptor=v;return x;}
}
