#include "sblr_savepoint_coordinator.hpp"

#include "api_diagnostics.hpp"
#include "hash_digest.hpp"
#include "uuid.hpp"

#include <algorithm>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <mutex>
#include <sstream>
#include <string_view>
#include <unordered_map>

namespace scratchbird::engine::internal_api {
namespace {
std::mutex mutex;
std::unordered_map<std::string,SblrSavepointSnapshot> live;
std::unordered_map<std::string,std::uint64_t> high;
EngineApiDiagnostic D(std::string c,std::string k){return MakeEngineApiDiagnostic(std::move(c),std::move(k),{});}
bool Tag(const EngineRequestContext&c,std::string_view t){return c.security_context_present&&std::find(c.trace_tags.begin(),c.trace_tags.end(),t)!=c.trace_tags.end();}
bool Authority(const EngineRequestContext&c){return Tag(c,"private_savepoint_coordination")&&c.statement_metadata_snapshot_engine_owned;}
bool Admin(const EngineRequestContext&c){return Tag(c,"right:SBLR_SAVEPOINT_COORDINATOR_ADMIN");}
bool H(std::string_view v){return v.size()==71&&v.substr(0,7)=="sha256:"&&std::all_of(v.begin()+7,v.end(),[](char c){return (c>='0'&&c<='9')||(c>='a'&&c<='f');});}
std::string Hash(std::string_view v){auto d=scratchbird::core::hash::ComputeSha256Digest(reinterpret_cast<const scratchbird::core::platform::byte*>(v.data()),v.size());return d.ok()?"sha256:"+scratchbird::core::hash::HexLower(d.digest):std::string{};}
std::string U(std::uint64_t salt){auto ms=static_cast<std::uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count());auto u=scratchbird::core::uuid::GenerateEngineIdentityV7(scratchbird::core::platform::UuidKind::object,ms+salt);return u.ok()?scratchbird::core::uuid::UuidToString(u.value.value):std::string{};}
std::string Path(const EngineRequestContext&c){return c.database_path+".sb.sblr_savepoint_coordinator.v1";}
std::uint64_t Next(const std::string&db){auto&n=high[db];return n==UINT64_MAX?0:++n;}
std::string CanonicalDescriptorEvidence(const SblrSavepointSnapshot&s){
  std::vector<std::uint8_t> bytes{'S','P','C','D',1,0,160,0,160,0,0,0,0,0,0,0};
  const auto append_uuid=[&](const std::string&text){auto p=scratchbird::core::uuid::ParseUuid(text);if(!p.ok())return false;bytes.insert(bytes.end(),p.value.bytes.begin(),p.value.bytes.end());return true;};
  const auto append_u64=[&](std::uint64_t v){for(unsigned i=0;i<8;++i)bytes.push_back(static_cast<std::uint8_t>(v>>(8*i)));};
  const auto append_sha=[&](std::string_view text){if(!H(text))return false;for(std::size_t i=7;i<71;i+=2){const auto nib=[](char c){return c<='9'?c-'0':c-'a'+10;};bytes.push_back(static_cast<std::uint8_t>((nib(text[i])<<4)|nib(text[i+1])));}return true;};
  if(!append_uuid(s.statement_receipt_uuid)||!append_uuid(s.descriptor_uuid))return{};
  append_u64(s.descriptor_generation);if(!append_uuid(s.savepoint_uuid))return{};
  append_u64(s.savepoint_generation);append_u64(s.transaction_ordinal);
  append_u64(s.symbol_occurrence_id);if(!append_sha(s.canonical_symbol_sha256)||bytes.size()!=128)return{};
  std::vector<std::uint8_t> material;
  constexpr std::string_view domain="ScratchBird.SblrSavepointCoordination.V1";
  material.insert(material.end(),domain.begin(),domain.end());material.insert(material.end(),bytes.begin(),bytes.end());
  const auto digest=scratchbird::core::hash::ComputeSha256Digest(material);
  return digest.ok()?"sha256:"+scratchbird::core::hash::HexLower(digest.digest):std::string{};
}
std::string Record(std::string_view kind,const SblrSavepointSnapshot&s){std::ostringstream o;o<<"SBSPC1\t"<<kind<<'\t'<<s.descriptor_uuid<<'\t'<<s.descriptor_generation<<'\t'<<s.savepoint_uuid<<'\t'<<s.savepoint_generation<<'\t'<<s.transaction_uuid<<'\t'<<s.local_transaction_id<<'\t'<<s.transaction_ordinal<<'\t'<<s.statement_receipt_uuid<<'\t'<<s.symbol_occurrence_id<<'\t'<<s.canonical_symbol_sha256<<'\t'<<s.transaction_handle_evidence_sha256<<'\t'<<s.descriptor_evidence_sha256<<'\t'<<s.stack_generation<<'\t'<<static_cast<unsigned>(s.state);return o.str();}
bool Append(const std::string&p,const std::string&v){std::ofstream o(p,std::ios::binary|std::ios::app);if(!o)return false;o<<v<<'\n';o.flush();return static_cast<bool>(o);}
bool Publish(const EngineRequestContext&c,const SblrSavepointSnapshot&s){return Append(Path(c),Record("EVIDENCE",s))&&Append(Path(c),Record("SNAPSHOT",s));}
SblrSavepointCoordinatorResult Hidden(){SblrSavepointCoordinatorResult r;r.diagnostic=D("SECURITY.ACCESS_DENIED","sblr.savepoint.hidden");return r;}
bool Bound(const EngineRequestContext&c,const SblrSavepointSnapshot&s,const std::string&r){return s.statement_receipt_uuid==r&&s.transaction_uuid==c.transaction_uuid.canonical&&s.local_transaction_id==c.local_transaction_id;}
}

SblrSavepointCoordinatorResult ReserveSblrSavepoint(const EngineRequestContext&c,const std::string&r,const std::string&txh,std::uint64_t occurrence,const std::string&symbol){std::lock_guard l(mutex);if(!Authority(c))return Hidden();SblrSavepointCoordinatorResult out;if(c.database_path.empty()||r!=c.statement_uuid.canonical||c.transaction_uuid.canonical.empty()||!c.local_transaction_id||!H(txh)||!occurrence||!H(symbol)){out.diagnostic=D("SBLR.OPERAND_INVALID","sblr.savepoint.reserve_invalid");return out;}SblrSavepointSnapshot s;s.statement_receipt_uuid=r;s.transaction_uuid=c.transaction_uuid.canonical;s.local_transaction_id=c.local_transaction_id;s.descriptor_generation=Next(c.database_uuid.canonical);s.savepoint_generation=Next(c.database_uuid.canonical);s.transaction_ordinal=Next("ordinal:"+s.transaction_uuid);s.descriptor_uuid=U(s.descriptor_generation);s.savepoint_uuid=U(s.savepoint_generation);s.symbol_occurrence_id=occurrence;s.canonical_symbol_sha256=symbol;s.transaction_handle_evidence_sha256=txh;s.state=SblrSavepointState::reserved;s.descriptor_evidence_sha256=CanonicalDescriptorEvidence(s);if(!s.descriptor_generation||!s.savepoint_generation||!s.transaction_ordinal||s.descriptor_uuid.empty()||s.savepoint_uuid.empty()||s.descriptor_evidence_sha256.empty()||!Publish(c,s)){out.diagnostic=D("SBLR.EXECUTION_FAILED","sblr.savepoint.reserve_publish_failed");return out;}live[s.descriptor_uuid]=s;out.ok=true;out.snapshot=s;out.diagnostic=D("OK","ok");out.evidence.push_back({"sblr.savepoint.reserved",s.descriptor_evidence_sha256});return out;}
SblrSavepointCoordinatorResult LookupSblrSavepoint(const EngineRequestContext&c,const std::string&r,const std::string&id,std::uint64_t gen,const std::string&e){std::lock_guard l(mutex);if(!Authority(c))return Hidden();auto it=live.find(id);if(it==live.end()||it->second.transaction_uuid!=c.transaction_uuid.canonical||it->second.local_transaction_id!=c.local_transaction_id)return Hidden();SblrSavepointCoordinatorResult out;if(it->second.statement_receipt_uuid!=r||it->second.descriptor_generation!=gen||it->second.descriptor_evidence_sha256!=e||it->second.state!=SblrSavepointState::reserved){out.diagnostic=D("MGA.SAVEPOINT.STALE","sblr.savepoint.stale");return out;}out.ok=true;out.snapshot=it->second;out.diagnostic=D("OK","ok");return out;}
SblrSavepointCoordinatorResult ActivateSblrSavepoint(const EngineRequestContext&c,const std::string&r,const std::string&id,std::uint64_t gen,const std::string&e,std::uint64_t availability){std::lock_guard l(mutex);if(!Authority(c))return Hidden();auto it=live.find(id);if(it==live.end()||!Bound(c,it->second,r))return Hidden();SblrSavepointCoordinatorResult out;if(it->second.descriptor_generation!=gen||it->second.descriptor_evidence_sha256!=e||it->second.state!=SblrSavepointState::reserved||!availability){out.diagnostic=D("MGA.SAVEPOINT.STALE","sblr.savepoint.activate_stale");return out;}auto s=it->second;s.state=SblrSavepointState::active;s.stack_generation=Next("stack:"+s.transaction_uuid);if(!s.stack_generation||!Publish(c,s)){out.diagnostic=D("SBLR.EXECUTION_FAILED","sblr.savepoint.activate_publish_failed");return out;}live[id]=s;out.ok=true;out.snapshot=s;out.diagnostic=D("OK","ok");out.evidence.push_back({"sblr.savepoint.active",s.descriptor_evidence_sha256});return out;}
SblrSavepointCoordinatorResult ReleaseSblrSavepoint(const EngineRequestContext&c,const std::string&sp,std::uint64_t generation,std::uint64_t ordinal,std::uint64_t stack,const std::string&evidence,std::uint64_t availability){std::lock_guard l(mutex);if(!Authority(c))return Hidden();auto it=std::find_if(live.begin(),live.end(),[&](const auto&row){return row.second.savepoint_uuid==sp;});if(it==live.end()||it->second.transaction_uuid!=c.transaction_uuid.canonical||it->second.local_transaction_id!=c.local_transaction_id)return Hidden();SblrSavepointCoordinatorResult out;auto&s=it->second;if(s.state!=SblrSavepointState::active||s.savepoint_generation!=generation||s.transaction_ordinal!=ordinal||s.stack_generation!=stack||!H(evidence)||!availability){out.diagnostic=D("MGA.SAVEPOINT.STALE","sblr.savepoint.release_stale");return out;}auto released=s;released.state=SblrSavepointState::released;released.stack_generation=Next("stack:"+released.transaction_uuid);if(!released.stack_generation||!Publish(c,released)){out.diagnostic=D("MGA.SAVEPOINT.RELEASE_FAILED","sblr.savepoint.release_publish_failed");return out;}s=released;out.ok=true;out.snapshot=released;out.diagnostic=D("OK","ok");out.evidence.push_back({"sblr.savepoint.released",Hash(sp+":"+std::to_string(released.stack_generation))});return out;}
SblrSavepointCoordinatorResult RollbackToSblrSavepoint(const EngineRequestContext&c,const std::string&sp,std::uint64_t generation,std::uint64_t ordinal,std::uint64_t stack,const std::string&evidence,std::uint64_t availability){std::lock_guard l(mutex);if(!Authority(c))return Hidden();auto it=std::find_if(live.begin(),live.end(),[&](const auto&row){return row.second.savepoint_uuid==sp;});if(it==live.end()||it->second.transaction_uuid!=c.transaction_uuid.canonical||it->second.local_transaction_id!=c.local_transaction_id)return Hidden();SblrSavepointCoordinatorResult out;auto target=it->second;if(target.state!=SblrSavepointState::active||target.savepoint_generation!=generation||target.transaction_ordinal!=ordinal||target.stack_generation!=stack||!H(evidence)||!availability){out.diagnostic=D("MGA.SAVEPOINT.STALE","sblr.savepoint.rollback_stale");return out;}const auto next=Next("stack:"+target.transaction_uuid);if(!next){out.diagnostic=D("MGA.SAVEPOINT.ROLLBACK_FAILED","sblr.savepoint.rollback_generation_exhausted");return out;}for(auto&row:live){auto&s=row.second;if(s.transaction_uuid==target.transaction_uuid&&s.local_transaction_id==target.local_transaction_id&&s.state==SblrSavepointState::active&&s.transaction_ordinal>target.transaction_ordinal){s.state=SblrSavepointState::revoked;s.stack_generation=next;if(!Publish(c,s)){out.diagnostic=D("MGA.SAVEPOINT.ROLLBACK_FAILED","sblr.savepoint.rollback_descendant_publish_failed");return out;}}}target.stack_generation=next;target.state=SblrSavepointState::active;if(!Publish(c,target)){out.diagnostic=D("MGA.SAVEPOINT.ROLLBACK_FAILED","sblr.savepoint.rollback_target_publish_failed");return out;}it->second=target;out.ok=true;out.snapshot=target;out.diagnostic=D("OK","ok");out.evidence.push_back({"sblr.savepoint.rollback",Hash(sp+":"+std::to_string(next))});return out;}
EngineApiDiagnostic RecoverSblrSavepointCoordinator(const EngineRequestContext&c){std::lock_guard l(mutex);if(!Admin(c))return D("SECURITY.ACCESS_DENIED","sblr.savepoint.recovery_denied");for(auto it=live.begin();it!=live.end();){if(it->second.transaction_uuid==c.transaction_uuid.canonical||c.transaction_uuid.canonical.empty()){auto s=it->second;s.state=SblrSavepointState::revoked;s.stack_generation=Next("stack:"+s.transaction_uuid);if(!Publish(c,s))return D("SBLR.EXECUTION_FAILED","sblr.savepoint.recovery_publish_failed");it=live.erase(it);}else ++it;}return D("OK","ok");}
}  // namespace scratchbird::engine::internal_api
