#include "sblr_ddl_drop_timeseries_value_cache_coordinator.hpp"
#include "api_diagnostics.hpp"
#include <map>
#include <mutex>
namespace scratchbird::engine::internal_api { namespace { std::mutex g; std::map<std::string,bool> live,used; std::string key(const scratchbird::engine::sblr::SblrDdlDropTimeseriesValueCacheDescriptorV1&d){return std::string(reinterpret_cast<const char*>(d.evidence.data()),d.evidence.size());} }
SblrDdlDropTimeseriesValueCacheCoordinationResult CompileSblrDdlDropTimeseriesValueCacheDescriptor(const EngineRequestContext&c,const std::string&r,std::uint64_t occ,std::uint64_t cache,std::uint64_t av){SblrDdlDropTimeseriesValueCacheCoordinationResult x;if(!c.security_context_present||!c.statement_metadata_snapshot_engine_owned||r!=c.statement_uuid.canonical||!occ||!cache||!av){x.diagnostic=MakeEngineApiDiagnostic("SBLR.OPERAND.INVALID","sblr.ddl_drop_timeseries_value_cache.coordination_invalid",{},false);return x;}x.descriptor.body[0]=1;x.descriptor.body[1]=std::uint8_t(occ);x.descriptor.body[2]=std::uint8_t(cache);x.descriptor.evidence[0]=std::uint8_t(occ);x.descriptor.evidence[1]=std::uint8_t(cache);x.descriptor.availability=av;std::lock_guard l(g);live[key(x.descriptor)]=true;x.ok=true;return x;}
SblrDdlDropTimeseriesValueCacheCoordinationResult ConsumeSblrDdlDropTimeseriesValueCacheDescriptor(const EngineRequestContext&c,const scratchbird::engine::sblr::SblrDdlDropTimeseriesValueCacheDescriptorV1&d){SblrDdlDropTimeseriesValueCacheCoordinationResult x;if(!c.security_context_present){x.diagnostic=MakeEngineApiDiagnostic("SECURITY.ACCESS_DENIED","sblr.ddl_drop_timeseries_value_cache.hidden",{},false);return x;}std::lock_guard l(g);auto k=key(d);if(!live[k]){x.diagnostic=MakeEngineApiDiagnostic(used[k]?"MGA.TRANSACTION.STALE":"SECURITY.ACCESS_DENIED",used[k]?"sblr.ddl_drop_timeseries_value_cache.stale":"sblr.ddl_drop_timeseries_value_cache.hidden",{},false);return x;}if(c.query_cancellation_requested&&c.query_cancellation_requested()){x.diagnostic=MakeEngineApiDiagnostic("PROCESS.CANCELLED","sblr.ddl_drop_timeseries_value_cache.cancelled",{},false);return x;}live.erase(k);used[k]=true;x.ok=true;x.descriptor=d;return x;}
}

