#include "sblr_ddl_validate_constraint_coordinator.hpp"
#include "api_diagnostics.hpp"
#include <algorithm>
#include <map>
#include <mutex>
namespace scratchbird::engine::internal_api { namespace { std::mutex m; std::map<std::string,scratchbird::engine::sblr::SblrDdlValidateConstraintDescriptorV1> live,used; std::string key(const scratchbird::engine::sblr::DdlValidateConstraintSha& x){return {reinterpret_cast<const char*>(x.data()),x.size()};} bool private_tag(const EngineRequestContext& c,const char* tag){return c.security_context_present&&std::find(c.trace_tags.begin(),c.trace_tags.end(),tag)!=c.trace_tags.end();} EngineApiDiagnostic diag(std::string c,std::string k){return MakeEngineApiDiagnostic(std::move(c),std::move(k),{});} }
SblrDdlValidateConstraintCoordinationResult CompileSblrDdlValidateConstraintDescriptor(const EngineRequestContext& c,const std::string& receipt,std::uint64_t occurrence,std::uint32_t constraint_occurrence,std::uint64_t availability){std::lock_guard lock(m);SblrDdlValidateConstraintCoordinationResult r;if(!private_tag(c,"private_ddl_validate_constraint_binder")||!c.statement_metadata_snapshot_engine_owned||receipt!=c.statement_uuid.canonical||!occurrence||!constraint_occurrence||!availability){r.diagnostic=diag("SBLR.OPERAND.INVALID","sblr.ddl_validate_constraint.coordination_invalid");return r;}r.descriptor.body[0]=1;r.descriptor.availability=availability;auto b=scratchbird::engine::sblr::EncodeSblrDdlValidateConstraintDescriptorV1(r.descriptor,false);if(b.empty()||!scratchbird::engine::sblr::DecodeSblrDdlValidateConstraintDescriptorV1(b.data(),b.size(),&r.descriptor,nullptr,false)){r.diagnostic=diag("SBLR.OPERAND.INVALID","sblr.ddl_validate_constraint.descriptor_invalid");return r;}live[key(r.descriptor.evidence)]=r.descriptor;r.ok=true;return r;}
SblrDdlValidateConstraintCoordinationResult ConsumeSblrDdlValidateConstraintDescriptor(const EngineRequestContext& c,const scratchbird::engine::sblr::SblrDdlValidateConstraintDescriptorV1& v){std::lock_guard lock(m);SblrDdlValidateConstraintCoordinationResult r;if(!private_tag(c,"private_ddl_validate_constraint")){r.diagnostic=diag("SECURITY.ACCESS_DENIED","sblr.ddl_validate_constraint.hidden");return r;}auto i=live.find(key(v.evidence));if(i==live.end()){r.diagnostic=diag(used.count(key(v.evidence))?"MGA.TRANSACTION.STALE":"SECURITY.ACCESS_DENIED","sblr.ddl_validate_constraint.replay");return r;}if(c.query_cancellation_requested&&c.query_cancellation_requested()){r.diagnostic=diag("PROCESS.CANCELLED","sblr.ddl_validate_constraint.cancelled");return r;}used[key(v.evidence)]=v;live.erase(i);r.ok=true;r.descriptor=v;return r;}
}
