#include "sblr_security_alter_privilege_template_coordinator.hpp"
#include "api_diagnostics.hpp"
#include <algorithm>
#include <map>
#include <mutex>
namespace scratchbird::engine::internal_api { namespace { std::mutex m; using D=scratchbird::engine::sblr::SblrSecurityAlterPrivilegeTemplateDescriptorV1; std::map<std::string,D> live,used; std::string key(const scratchbird::engine::sblr::PrivilegeTemplateSha&x){return {reinterpret_cast<const char*>(x.data()),x.size()};} bool tag(const EngineRequestContext&c,const char*t){return c.security_context_present&&std::find(c.trace_tags.begin(),c.trace_tags.end(),t)!=c.trace_tags.end();} EngineApiDiagnostic diag(std::string c,std::string k){return MakeEngineApiDiagnostic(std::move(c),std::move(k),{});} }
SblrSecurityAlterPrivilegeTemplateCoordinationResult CompileSblrSecurityAlterPrivilegeTemplateDescriptor(const EngineRequestContext&c,const std::string&receipt,std::uint64_t occurrence,std::uint32_t template_occurrence,std::uint64_t availability){std::lock_guard lock(m);SblrSecurityAlterPrivilegeTemplateCoordinationResult r;if(!tag(c,"private_security_alter_privilege_template_binder")||!c.statement_metadata_snapshot_engine_owned||receipt!=c.statement_uuid.canonical||!occurrence||!template_occurrence||!availability){r.diagnostic=diag("SBLR.OPERAND.INVALID","sblr.security_alter_privilege_template.coordination_invalid");return r;}r.descriptor.body[0]=1;r.descriptor.availability=availability;auto b=scratchbird::engine::sblr::EncodeSblrSecurityAlterPrivilegeTemplateDescriptorV1(r.descriptor,false);if(b.empty()||!scratchbird::engine::sblr::DecodeSblrSecurityAlterPrivilegeTemplateDescriptorV1(b.data(),b.size(),&r.descriptor,nullptr,false)){r.diagnostic=diag("SBLR.OPERAND.INVALID","sblr.security_alter_privilege_template.descriptor_invalid");return r;}live[key(r.descriptor.evidence)]=r.descriptor;r.ok=true;return r;}
SblrSecurityAlterPrivilegeTemplateCoordinationResult ConsumeSblrSecurityAlterPrivilegeTemplateDescriptor(const EngineRequestContext&c,const D&v){std::lock_guard lock(m);SblrSecurityAlterPrivilegeTemplateCoordinationResult r;if(!tag(c,"private_security_alter_privilege_template")){r.diagnostic=diag("SECURITY.ACCESS_DENIED","sblr.security_alter_privilege_template.hidden");return r;}auto i=live.find(key(v.evidence));if(i==live.end()){r.diagnostic=diag(used.count(key(v.evidence))?"MGA.TRANSACTION.STALE":"SECURITY.ACCESS_DENIED","sblr.security_alter_privilege_template.replay");return r;}if(c.query_cancellation_requested&&c.query_cancellation_requested()){r.diagnostic=diag("PROCESS.CANCELLED","sblr.security_alter_privilege_template.cancelled");return r;}used[key(v.evidence)]=v;live.erase(i);r.ok=true;r.descriptor=v;return r;}
}
