// Copyright (c) 2026 ScratchBird Software Inc.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// SPDX-License-Identifier: MPL-2.0

#pragma once

/**
 * ScratchBird SBLR v2.0 - Bytecode Generator
 *
 * This module generates SBLR bytecode from the resolved AST produced by
 * SemanticAnalyzerV2. The generated bytecode is executed by the SBLR Executor.
 *
 * Key features:
 * - Works with resolved AST (UUIDs, resolved types)
 * - Supports all DML operations (SELECT, INSERT, UPDATE, DELETE)
 * - Supports DDL operations (CREATE, DROP, ALTER)
 * - Optimization passes (constant folding, expression simplification)
 *
 * See: docs/planning/PARSER_V2_IMPLEMENTATION_PLAN.md Phase 8
 */

#include "scratchbird/sblr/resolved_ast_v2.h"
#include "scratchbird/sblr/opcodes.h"
#include "scratchbird/parser/parser_v2.h"
#include <vector>
#include <string>
#include <string_view>
#include <memory>
#include <unordered_map>
#include <unordered_set>
#include <cstring>

// Forward declaration
namespace scratchbird::core {
class CatalogManager;
}

namespace scratchbird::parser::v2 {

/**
 * Result of bytecode generation
 */
class BytecodeResultV2 {
public:
    BytecodeResultV2() = default;

    bool success() const { return errors_.empty() && !bytecode_.empty(); }
    const std::vector<uint8_t>& bytecode() const { return bytecode_; }
    std::vector<uint8_t>& bytecode() { return bytecode_; }
    const std::vector<std::string>& errors() const { return errors_; }
    const std::vector<std::string>& warnings() const { return warnings_; }

    // Error/warning reporting
    void addError(const std::string& error) { errors_.push_back(error); }
    void addWarning(const std::string& warning) { warnings_.push_back(warning); }

    // Bytecode writing helpers
    void writeByte(uint8_t byte) { bytecode_.push_back(byte); }
    void writeOpcode(sblr::Opcode op) { writeByte(static_cast<uint8_t>(op)); }

    void writeUVarint(uint64_t value) {
        uint8_t buffer[10];
        size_t count = sblr::writeUVarint(buffer, value);
        bytecode_.insert(bytecode_.end(), buffer, buffer + count);
    }

    void writeListCount(uint64_t count) { writeUVarint(count); }

    void writeExtendedOpcode(uint16_t ext_op) {
        writeOpcode(sblr::Opcode::EXTENDED_OPCODE);
        writeInt16(ext_op);
    }

    void writeExtendedOpcode(sblr::ExtendedOpcode ext_op) {
        writeExtendedOpcode(static_cast<uint16_t>(ext_op));
    }

    void writeInt16(uint16_t value) {
        bytecode_.resize(bytecode_.size() + 2);
        sblr::writeInt16(&bytecode_[bytecode_.size() - 2], value);
    }

    void writeInt32(uint32_t value) {
        bytecode_.resize(bytecode_.size() + 4);
        sblr::writeInt32(&bytecode_[bytecode_.size() - 4], value);
    }

    void writeInt64(uint64_t value) {
        bytecode_.resize(bytecode_.size() + 8);
        sblr::writeInt64(&bytecode_[bytecode_.size() - 8], value);
    }

    void writeDouble(double value) {
        uint64_t bits;
        std::memcpy(&bits, &value, sizeof(double));
        writeInt64(bits);
    }

    void writeString(const std::string& str) {
        if (str.size() > UINT64_MAX) {
            addError("String length exceeds maximum allowed size (UVARINT)");
            writeUVarint(0);
            return;
        }
        writeUVarint(static_cast<uint64_t>(str.size()));
        bytecode_.insert(bytecode_.end(), str.begin(), str.end());
    }

    void writeUUID(const core::ID& uuid) {
        // Write 16-byte UUID
        bytecode_.insert(bytecode_.end(), uuid.bytes.begin(), uuid.bytes.end());
    }

    // Get current bytecode offset (for jump patching)
    size_t currentOffset() const { return bytecode_.size(); }

    // Patch a 32-bit value at a specific offset
    void patchInt32(size_t offset, uint32_t value) {
        if (offset + 4 <= bytecode_.size()) {
            sblr::writeInt32(&bytecode_[offset], value);
        }
    }

private:
    std::vector<uint8_t> bytecode_;
    std::vector<std::string> errors_;
    std::vector<std::string> warnings_;
};

/**
 * Bytecode Generator V2
 *
 * Generates SBLR bytecode from resolved AST nodes.
 */
class BytecodeGeneratorV2 {
public:
    /**
     * Create generator with string pool access
     */
    explicit BytecodeGeneratorV2(const StringPool& string_pool);
    ~BytecodeGeneratorV2();

    // Non-copyable
    BytecodeGeneratorV2(const BytecodeGeneratorV2&) = delete;
    BytecodeGeneratorV2& operator=(const BytecodeGeneratorV2&) = delete;

    /**
     * Generate bytecode from a resolved statement
     */
    BytecodeResultV2 generate(ResolvedStatement* stmt);
    BytecodeResultV2 generatePsql(ResolvedPsqlBlock* block);

    /**
     * Enable/disable optimization passes
     */
    void setOptimizationsEnabled(bool enabled) { optimizations_enabled_ = enabled; }
    void setSourceSql(std::string_view sql) { source_sql_ = sql; }

private:
    const StringPool& string_pool_;
    BytecodeResultV2* current_result_ = nullptr;
    bool optimizations_enabled_ = true;
    std::string_view source_sql_;
    struct PsqlLoopContext {
        size_t loop_start = 0;
        size_t loop_end_patch = 0;
        size_t loop_end = 0;
        StringPool::StringId label = StringPool::INVALID_ID;
        std::vector<size_t> break_patches;
        std::vector<size_t> continue_patches;
    };
    std::vector<PsqlLoopContext> psql_loop_stack_;

    // ==========================================================================
    // Statement Generation
    // ==========================================================================

    void generateStatement(ResolvedStatement* stmt);
    void emitDebugSpan(const SourceSpan& span);

    // DML
    void generateSelect(ResolvedSelectStmt* stmt);
    void generateSelectCore(ResolvedSelectStmt* stmt, bool emit_set_ops);
    void generateInsert(ResolvedInsertStmt* stmt);
    void generateUpdate(ResolvedUpdateStmt* stmt);
    void generateDelete(ResolvedDeleteStmt* stmt);
    void generateMerge(ResolvedMergeStmt* stmt);
    void generateCopy(ResolvedCopyStmt* stmt);
    void generateComment(ResolvedCommentStmt* stmt);
    void generateWithClause(ResolvedWithClause* with);

    // DDL
    void generateCreateTable(ResolvedCreateTableStmt* stmt);
    void generateCreateIndex(ResolvedCreateIndexStmt* stmt);
    void generateCreateView(ResolvedCreateViewStmt* stmt);
    void generateCreateSequence(ResolvedCreateSequenceStmt* stmt);
    void generateAlterSequence(ResolvedAlterSequenceStmt* stmt);
    void generateCreateSchema(ResolvedCreateSchemaStmt* stmt);
    void generateDropSchema(ResolvedDropSchemaStmt* stmt);
    void generateAlterSchema(ResolvedAlterSchemaStmt* stmt);
    void generateCreateDatabase(ResolvedCreateDatabaseStmt* stmt);
    void generateCreateTablespace(ResolvedCreateTablespaceStmt* stmt);
    void generateAlterTablespace(ResolvedAlterTablespaceStmt* stmt);
    void generateDropTablespace(ResolvedDropTablespaceStmt* stmt);
    void generateAttachTablespace(ResolvedAttachTablespaceStmt* stmt);
    void generateDetachTablespace(ResolvedDetachTablespaceStmt* stmt);
    void generateCreateFunction(ResolvedCreateFunctionStmt* stmt);
    void generateCreateProcedure(ResolvedCreateProcedureStmt* stmt);
    void generateCreateTrigger(ResolvedCreateTriggerStmt* stmt);
    void generateExecuteBlock(ResolvedExecuteBlockStmt* stmt);
    void generateExecuteProcedure(ResolvedExecuteProcedureStmt* stmt);
    void generateExecuteStatement(ResolvedExecuteStatementStmt* stmt);
    void generateCreatePackage(ResolvedCreatePackageStmt* stmt);
    void generateCreateUser(ResolvedCreateUserStmt* stmt);
    void generateCreateRole(ResolvedCreateRoleStmt* stmt);
    void generateCreateGroup(ResolvedCreateGroupStmt* stmt);
    void generateCreatePolicy(ResolvedCreatePolicyStmt* stmt);
    void generateAlterPolicy(ResolvedAlterPolicyStmt* stmt);
    void generateDropPolicy(ResolvedDropPolicyStmt* stmt);
    void generateCreateJob(ResolvedCreateJobStmt* stmt);
    void generateCreateException(ResolvedCreateExceptionStmt* stmt);
    void generateCreateDomain(ResolvedCreateDomainStmt* stmt);
    void generateCreateForeignServer(ResolvedCreateForeignServerStmt* stmt);
    void generateCreateForeignTable(ResolvedCreateForeignTableStmt* stmt);
    void generateCreateUserMapping(ResolvedCreateUserMappingStmt* stmt);
    void generateCreateSynonym(ResolvedCreateSynonymStmt* stmt);
    void generateCreateUdr(ResolvedCreateUdrStmt* stmt);
    void generateAlterType(ResolvedAlterTypeStmt* stmt);
    void generateDropDatabase(ResolvedDropDatabaseStmt* stmt);
    void generateAlterDomain(ResolvedAlterDomainStmt* stmt);
    void generateDropType(ResolvedDropTypeStmt* stmt);
    void generateDropDomain(ResolvedDropDomainStmt* stmt);
    void generateDropForeignServer(ResolvedDropForeignServerStmt* stmt);
    void generateDropForeignTable(ResolvedDropForeignTableStmt* stmt);
    void generateDropUserMapping(ResolvedDropUserMappingStmt* stmt);
    void generateDropSynonym(ResolvedDropSynonymStmt* stmt);
    void generateDropUdr(ResolvedDropUdrStmt* stmt);
    void generateAlterDatabase(ResolvedAlterDatabaseStmt* stmt);
    void generateAlterTable(ResolvedAlterTableStmt* stmt);
    void generateAlterIndex(ResolvedAlterIndexStmt* stmt);
    void generateAlterJob(ResolvedAlterJobStmt* stmt);
    void generateRenameObject(ResolvedRenameObjectStmt* stmt);
    void generateMoveObject(ResolvedMoveObjectStmt* stmt);
    void generateDrop(ResolvedDropStmt* stmt);
    void generateDropJob(ResolvedDropJobStmt* stmt);
    void generateDropGroup(ResolvedDropGroupStmt* stmt);
    void generateExecuteJob(ResolvedExecuteJobStmt* stmt);
    void generateCancelJobRun(ResolvedCancelJobRunStmt* stmt);

    // Transaction/Session
    void generateStartTransaction(ResolvedStartTransactionStmt* stmt);
    void generatePrepareTransaction(ResolvedPrepareTransactionStmt* stmt);
    void generateCommit(ResolvedCommitStmt* stmt);
    void generateRollback(ResolvedRollbackStmt* stmt);
    void generateSavepoint(ResolvedSavepointStmt* stmt);
    void generateReleaseSavepoint(ResolvedReleaseSavepointStmt* stmt);
    void generateConnect(ResolvedConnectStmt* stmt);
    void generateDisconnect(ResolvedDisconnectStmt* stmt);
    void generateSet(ResolvedSetStmt* stmt);
    void generateAlterSystem(ResolvedAlterSystemStmt* stmt);
    void generateShow(ResolvedShowStmt* stmt);
    void generateAnalyze(ResolvedAnalyzeStmt* stmt);
    void generateSweepDatabase(ResolvedSweepDatabaseStmt* stmt);
    void generateGrant(ResolvedGrantStmt* stmt);
    void generateRevoke(ResolvedRevokeStmt* stmt);
    void generateTruncateTable(ResolvedTruncateTableStmt* stmt);
    void generateExplain(ResolvedExplainStmt* stmt);

    // ==========================================================================
    // PSQL Generation
    // ==========================================================================

    void generatePsqlBlock(ResolvedPsqlBlock* block);
    void generatePsqlStatement(ResolvedPsqlStatement* stmt);
    void generatePsqlExpressionPayload(ResolvedExpression* expr);

    // ==========================================================================
    // Expression Generation
    // ==========================================================================

    void generateExpression(ResolvedExpression* expr);

    void generateLiteral(ResolvedLiteral* expr);
    void generateColumnRef(ResolvedColumnRefExpr* expr);
    void generateBinaryExpr(ResolvedBinaryExpr* expr);
    void generateUnaryExpr(ResolvedUnaryExpr* expr);
    void generateFunctionCall(ResolvedFunctionCall* expr);
    void generateCast(ResolvedCast* expr);
    void generateCase(ResolvedCase* expr);
    void generateSubquery(ResolvedSubqueryExpr* expr);
    void generateExists(ResolvedExistsExpr* expr);
    void generateIn(ResolvedInExpr* expr);
    void generateBetween(ResolvedBetweenExpr* expr);
    void generateLike(ResolvedLikeExpr* expr);
    void generateIsNull(ResolvedIsNullExpr* expr);
    void generateArray(ResolvedArrayExpr* expr);
    void generateExtract(ResolvedExtractExpr* expr);
    void generateAlterElement(ResolvedAlterElementExpr* expr);

    // Aggregate helpers
    struct AggregateSpec {
        const ResolvedFunctionCall* expr = nullptr;
        sblr::Opcode opcode{};
        std::vector<ResolvedExpression*> args;
        std::string output_name;
    };

    void collectAggregates(ResolvedExpression* expr,
                           std::vector<AggregateSpec>& aggregates,
                           std::unordered_set<const ResolvedFunctionCall*>& seen);
    bool buildAggregateSpec(const ResolvedFunctionCall* expr, AggregateSpec& out);
    void writeColumnRefName(const std::string& name);

    // ==========================================================================
    // Clause Generation
    // ==========================================================================

    void generateSelectList(const std::vector<ResolvedSelectItem>& items);
    void generateFromClause(const std::vector<ResolvedTableRef*>& tables,
                           const std::vector<ResolvedJoin*>& joins);
    void generateWhereClause(ResolvedExpression* where);
    void generateGroupByClause(const ResolvedSelectStmt& stmt);
    void generateHavingClause(ResolvedExpression* having);
    void generateOrderByClause(const std::vector<ResolvedOrderByItem*>& order_by);
    void generateLimitOffset(ResolvedExpression* limit, ResolvedExpression* offset);

    // ==========================================================================
    // Type Generation
    // ==========================================================================

    void generateDataType(const ResolvedType& type);
    sblr::Opcode dataTypeToOpcode(DataType type);
    void writeTypeRef(const ResolvedType& type);

    // ==========================================================================
    // Utility Methods
    // ==========================================================================

    /**
     * Get string from pool
     */
    std::string_view getString(StringPool::StringId id) const;

    /**
     * Write string from pool
     */
    void writeStringId(StringPool::StringId id);
    void writeString16(std::string_view str);
    void writeObjectPath(const SchemaPath& path);
    void writeTableRefPayload(const ResolvedTableRef& table_ref);
    void writeTableRefPayload(const core::ID& table_uuid,
                              StringPool::StringId name,
                              bool has_alias,
                              StringPool::StringId alias);

    /**
     * Map binary operator to opcode
     */
    sblr::Opcode binaryOpToOpcode(BinaryOp op);

    // ==========================================================================
    // Optimization Passes
    // ==========================================================================

    /**
     * Apply constant folding to expressions
     * Returns nullptr if expression can't be folded, or a new folded literal
     */
    ResolvedLiteral* tryConstantFold(ResolvedExpression* expr);

    /**
     * Check if expression is a constant (can be evaluated at compile time)
     */
    bool isConstant(ResolvedExpression* expr);

    bool aggregate_ref_mode_ = false;
    std::unordered_map<const ResolvedFunctionCall*, std::string> aggregate_output_map_;
};

/**
 * Convenience function to generate bytecode from SQL
 */
BytecodeResultV2 generateBytecode(
    std::string_view sql,
    core::CatalogManager& catalog,
    StringPool& string_pool);

/**
 * Debug helper - disassemble bytecode to readable format
 */
class BytecodeDisassemblerV2 {
public:
    static std::string disassemble(const std::vector<uint8_t>& bytecode);
};

} // namespace scratchbird::parser::v2
