# Copyright (c) 2026 ScratchBird Software Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0

"""ScratchBird DB-API 2.0 driver."""

from .connection import (
    AuthMethodSurface,
    AuthProbeResult,
    Connection,
    connect,
    canonical_isolation_label,
    canonical_read_committed_mode_label,
    probe_auth_surface,
    ResolvedAuthContext,
)
from .errors import (
    Warning,
    Error,
    InterfaceError,
    DatabaseError,
    DataError,
    OperationalError,
    IntegrityError,
    InternalError,
    ProgrammingError,
    NotSupportedError,
    RETRY_SCOPE_NONE,
    RETRY_SCOPE_RECONNECT,
    RETRY_SCOPE_STATEMENT,
    RETRY_SCOPE_TRANSACTION,
    extract_sqlstate,
    retry_scope_for_sqlstate,
    is_retryable_sqlstate,
)
from .types import Blob, Clob, Geometry, Json, Jsonb, Range, RawValue, Ref, RowId, SqlXml
from .protocol import (
    COPY_FORMAT_TEXT,
    COPY_FORMAT_BINARY,
    READ_COMMITTED_MODE_DEFAULT,
    READ_COMMITTED_MODE_READ_CONSISTENCY,
    READ_COMMITTED_MODE_RECORD_VERSION,
    READ_COMMITTED_MODE_NO_RECORD_VERSION,
)
from .pool import (
    ConnectionPool,
    PoolConfig,
    StatementCache,
    CachingConnection,
    retry_with_backoff,
)
from .metadata import (
    SchemaTreeNode,
    schemas_query,
    tables_query,
    columns_query,
    indexes_query,
    index_columns_query,
    constraints_query,
    procedures_query,
    functions_query,
    routines_query,
    catalogs_query,
    primary_keys_query,
    foreign_keys_query,
    table_privileges_query,
    column_privileges_query,
    type_info_query,
    normalize_collection_name,
    normalize_restrictions,
    resolve_collection_query,
    filter_rows_by_restrictions,
    schema_name_matches_pattern,
    schema_paths_for_navigation,
    expand_schema_parent_paths,
    build_schema_tree,
    build_ddl_editor_schema_payload,
)
from .readiness import (
    DRIVER_COMPONENT_ID,
    DRIVER_PACKAGE_UUID,
    DRIVER_READINESS_SCHEMA_VERSION,
    AdvisoryCacheContext,
    LanguageProfileResolution,
    LanguageResourceState,
    PreparedBundleContext,
    ReadinessDiagnostic,
    beta_driver_readiness_status,
    resolve_language_profile,
    validate_advisory_cache_context,
    validate_language_resource_state,
    validate_prepared_bundle_reuse,
)

apilevel = "2.0"
threadsafety = 2
paramstyle = "named"

__all__ = [
    "connect",
    "Connection",
    "canonical_isolation_label",
    "canonical_read_committed_mode_label",
    "probe_auth_surface",
    "AuthMethodSurface",
    "AuthProbeResult",
    "ResolvedAuthContext",
    "ConnectionPool",
    "PoolConfig",
    "StatementCache",
    "CachingConnection",
    "retry_with_backoff",
    "Warning",
    "Error",
    "InterfaceError",
    "DatabaseError",
    "DataError",
    "OperationalError",
    "IntegrityError",
    "InternalError",
    "ProgrammingError",
    "NotSupportedError",
    "RETRY_SCOPE_NONE",
    "RETRY_SCOPE_RECONNECT",
    "RETRY_SCOPE_STATEMENT",
    "RETRY_SCOPE_TRANSACTION",
    "extract_sqlstate",
    "retry_scope_for_sqlstate",
    "is_retryable_sqlstate",
    "Json",
    "Jsonb",
    "Blob",
    "Clob",
    "RowId",
    "Ref",
    "SqlXml",
    "Geometry",
    "Range",
    "RawValue",
    "COPY_FORMAT_TEXT",
    "COPY_FORMAT_BINARY",
    "READ_COMMITTED_MODE_DEFAULT",
    "READ_COMMITTED_MODE_READ_CONSISTENCY",
    "READ_COMMITTED_MODE_RECORD_VERSION",
    "READ_COMMITTED_MODE_NO_RECORD_VERSION",
    "SchemaTreeNode",
    "schemas_query",
    "tables_query",
    "columns_query",
    "indexes_query",
    "index_columns_query",
    "constraints_query",
    "procedures_query",
    "functions_query",
    "routines_query",
    "catalogs_query",
    "primary_keys_query",
    "foreign_keys_query",
    "table_privileges_query",
    "column_privileges_query",
    "type_info_query",
    "normalize_collection_name",
    "normalize_restrictions",
    "resolve_collection_query",
    "filter_rows_by_restrictions",
    "schema_name_matches_pattern",
    "schema_paths_for_navigation",
    "expand_schema_parent_paths",
    "build_schema_tree",
    "build_ddl_editor_schema_payload",
    "DRIVER_COMPONENT_ID",
    "DRIVER_PACKAGE_UUID",
    "DRIVER_READINESS_SCHEMA_VERSION",
    "ReadinessDiagnostic",
    "AdvisoryCacheContext",
    "PreparedBundleContext",
    "LanguageProfileResolution",
    "LanguageResourceState",
    "beta_driver_readiness_status",
    "validate_advisory_cache_context",
    "validate_prepared_bundle_reuse",
    "resolve_language_profile",
    "validate_language_resource_state",
]
