-- Copyright (c) 2026 ScratchBird Software Inc.
--
-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at https://mozilla.org/MPL/2.0/.
--
-- SPDX-License-Identifier: MPL-2.0

-- ScratchBird migration mapping baseline for UserEntity
CREATE TABLE IF NOT EXISTS sys.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_email ON sys.users (email);
