#!/usr/bin/env python3
# Copyright (c) 2026 ScratchBird Software Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0

"""Author deterministic SBsql authenticated-route and SBLR round-trip fixtures.

This creates a bounded tranche of YAML fixtures from the generated matrices.
It does not promote row implementation state. Authored fixtures remain explicit
release risk until a later executable route/round-trip gate promotes them to
``e2e_passed``.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path


DEFAULT_ARTIFACT_ROOT = "project/tests/sbsql_parser_worker/fixtures/surface_to_sblr/artifacts"
AUTH_MATRIX_NAME = "AUTHENTICATED_FULL_ROUTE_MATRIX.csv"
ROUND_MATRIX_NAME = "SBLR_BINARY_ROUND_TRIP_MATRIX.csv"
PER_ROW_MANIFEST_NAME = "PER_ROW_EVIDENCE_MANIFEST.csv"


def fail(message: str) -> None:
    print(message, file=sys.stderr)
    raise SystemExit(1)


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.is_file():
        fail(f"required CSV missing: {path}")
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def index_by_surface(rows: list[dict[str, str]]) -> dict[str, dict[str, str]]:
    out: dict[str, dict[str, str]] = {}
    for row in rows:
        surface_id = row.get("surface_id", "")
        if surface_id in out:
            fail(f"duplicate surface_id in input: {surface_id}")
        out[surface_id] = row
    return out


def q(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def write_fixture(path: Path, rows: list[tuple[str, str]], refresh: bool) -> bool:
    if path.exists() and not refresh:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = "# Generated by author_route_and_round_trip_fixtures.py. Do not hand edit.\n"
    payload += "\n".join(f"{key}: {q(value)}" for key, value in rows)
    payload += "\n"
    path.write_text(payload, encoding="utf-8")
    return True


def route_fixture_rows(auth: dict[str, str], manifest: dict[str, str]) -> list[tuple[str, str]]:
    return [
        ("fixture_kind", "authenticated_route"),
        ("fixture_status", "fixture_authored"),
        ("surface_id", auth["surface_id"]),
        ("canonical_name", auth["canonical_name"]),
        ("surface_kind", auth["surface_kind"]),
        ("status", auth["status"]),
        ("cluster_scope", auth["cluster_scope"]),
        ("sblr_operation_family", auth["sblr_operation_family"]),
        ("credential_profile_accepted", auth["credential_profile_accepted"]),
        ("credential_profile_refused", auth["credential_profile_refused"]),
        ("auth_policy", auth["auth_policy"]),
        ("session_profile", auth["session_profile"]),
        ("transaction_profile", auth["transaction_profile"]),
        ("transport_route", auth["transport_route"]),
        ("tls_profile_ref", auth["tls_profile_ref"]),
        ("listener_path", auth["listener_path"]),
        ("ipc_admission_path", auth["ipc_admission_path"]),
        ("engine_admission_authority", auth["engine_admission_authority"]),
        ("mga_execution_authority", auth["mga_execution_authority"]),
        ("expected_authorization_accepted_outcome", auth["expected_authorization_accepted_outcome"]),
        ("expected_authorization_refused_outcome", auth["expected_authorization_refused_outcome"]),
        ("expected_diagnostic_codes", auth["expected_diagnostic_codes"]),
        ("per_row_final_state", manifest["final_state"]),
        ("per_row_ctest_label", manifest["ctest_label"]),
        ("per_row_fixture_path", manifest["fixture_path"]),
        ("implementation_refs", manifest["implementation_refs"]),
        ("diagnostic_proof", manifest["diagnostic_proof"]),
        ("result_proof", manifest["result_proof"]),
        ("fixture_layer_note", "authored_tranche_fixture_pending_executable_route_promotion"),
    ]


def round_trip_fixture_rows(round_trip: dict[str, str], manifest: dict[str, str]) -> list[tuple[str, str]]:
    return [
        ("fixture_kind", "sblr_binary_round_trip"),
        ("fixture_status", "fixture_authored"),
        ("surface_id", round_trip["surface_id"]),
        ("canonical_name", round_trip["canonical_name"]),
        ("surface_kind", round_trip["surface_kind"]),
        ("status", round_trip["status"]),
        ("cluster_scope", round_trip["cluster_scope"]),
        ("sblr_operation_family", round_trip["sblr_operation_family"]),
        ("oracle_authority_status", round_trip["oracle_authority_status"]),
        ("expected_canonical_function_or_api_operation_id", round_trip["expected_canonical_function_or_api_operation_id"]),
        ("parse_phase_expectation", round_trip["parse_phase_expectation"]),
        ("bind_phase_expectation", round_trip["bind_phase_expectation"]),
        ("lower_phase_expectation", round_trip["lower_phase_expectation"]),
        ("binary_serialize_phase_expectation", round_trip["binary_serialize_phase_expectation"]),
        ("verify_phase_expectation", round_trip["verify_phase_expectation"]),
        ("binary_deserialize_phase_expectation", round_trip["binary_deserialize_phase_expectation"]),
        ("dispatch_phase_expectation", round_trip["dispatch_phase_expectation"]),
        ("execute_phase_expectation", round_trip["execute_phase_expectation"]),
        ("render_phase_expectation", round_trip["render_phase_expectation"]),
        ("canonical_container_magic", round_trip["canonical_container_magic"]),
        ("canonical_container_header_size_bytes", round_trip["canonical_container_header_size_bytes"]),
        ("byte_identical_round_trip_required", round_trip["byte_identical_round_trip_required"]),
        ("crc32c_check_required", round_trip["crc32c_check_required"]),
        ("engine_anchored_uuids_required", round_trip["engine_anchored_uuids_required"]),
        ("forbidden_authority_sources", round_trip["forbidden_authority_sources"]),
        ("execution_authority_model", round_trip["execution_authority_model"]),
        ("per_row_final_state", manifest["final_state"]),
        ("per_row_ctest_label", manifest["ctest_label"]),
        ("per_row_fixture_path", manifest["fixture_path"]),
        ("implementation_refs", manifest["implementation_refs"]),
        ("diagnostic_proof", manifest["diagnostic_proof"]),
        ("result_proof", manifest["result_proof"]),
        ("fixture_layer_note", "authored_tranche_fixture_pending_binary_execution_promotion"),
    ]


def selectable(auth: dict[str, str], round_trip: dict[str, str], manifest: dict[str, str]) -> bool:
    if auth.get("fixture_status") != "pending_authoring":
        return False
    if round_trip.get("fixture_status") != "pending_authoring":
        return False

    round_trip_required = round_trip.get("byte_identical_round_trip_required", "")
    operation_id = round_trip.get("expected_canonical_function_or_api_operation_id", "")
    if auth.get("cluster_scope") == "cluster_private":
        return (
            manifest.get("final_state") in {"exact_refusal_passed", "cluster_provider_route_passed"}
            and round_trip_required == "not_applicable_no_round_trip_in_public_build"
        )

    return (
        auth.get("status") == "native_now"
        and auth.get("cluster_scope") == "noncluster_or_profile_scoped"
        and manifest.get("final_state") == "e2e_passed"
        and round_trip_required == "yes"
        and operation_id
        and operation_id != "pending_canonical_authority_entry"
        and not operation_id.startswith("not_applicable_")
    )


def refreshable(auth: dict[str, str], round_trip: dict[str, str], manifest: dict[str, str]) -> bool:
    round_trip_required = round_trip.get("byte_identical_round_trip_required", "")
    operation_id = round_trip.get("expected_canonical_function_or_api_operation_id", "")
    if auth.get("cluster_scope") == "cluster_private":
        return (
            manifest.get("final_state") in {"exact_refusal_passed", "cluster_provider_route_passed"}
            and round_trip_required == "not_applicable_no_round_trip_in_public_build"
        )
    return (
        auth.get("status") == "native_now"
        and auth.get("cluster_scope") == "noncluster_or_profile_scoped"
        and manifest.get("final_state") == "e2e_passed"
        and round_trip_required == "yes"
        and operation_id
        and operation_id != "pending_canonical_authority_entry"
        and not operation_id.startswith("not_applicable_")
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", required=True)
    parser.add_argument("--artifact-root", default=DEFAULT_ARTIFACT_ROOT)
    parser.add_argument("--limit", type=int, default=50)
    parser.add_argument("--refresh", action="store_true")
    parser.add_argument(
        "--surface-id",
        action="append",
        default=[],
        help="Refresh a specific surface id from current matrices; may be repeated.",
    )
    args = parser.parse_args()
    root = Path(args.repo_root).resolve()
    artifact_root = Path(args.artifact_root)
    if not artifact_root.is_absolute():
        artifact_root = root / artifact_root
    if args.limit <= 0:
        fail("--limit must be positive")

    auth_rows = read_csv(artifact_root / AUTH_MATRIX_NAME)
    round_rows = read_csv(artifact_root / ROUND_MATRIX_NAME)
    manifest_rows = read_csv(artifact_root / PER_ROW_MANIFEST_NAME)

    auth_by_id = index_by_surface(auth_rows)
    round_by_id = index_by_surface(round_rows)
    manifest_by_id = index_by_surface(manifest_rows)

    selected: list[str] = []
    if args.surface_id:
        seen: set[str] = set()
        for surface_id in args.surface_id:
            if surface_id in seen:
                continue
            seen.add(surface_id)
            if surface_id not in auth_by_id or surface_id not in round_by_id or surface_id not in manifest_by_id:
                fail(f"requested surface id is not present in all fixture matrices: {surface_id}")
            if not refreshable(auth_by_id[surface_id], round_by_id[surface_id], manifest_by_id[surface_id]):
                fail(f"requested surface id is not eligible for fixture refresh: {surface_id}")
            selected.append(surface_id)
    else:
        for surface_id in sorted(set(auth_by_id) & set(round_by_id) & set(manifest_by_id)):
            if selectable(auth_by_id[surface_id], round_by_id[surface_id], manifest_by_id[surface_id]):
                selected.append(surface_id)
            if len(selected) >= args.limit:
                break
    if not selected:
        fail("no eligible pending rows found for fixture authoring")

    authored_route = 0
    authored_round_trip = 0
    for surface_id in selected:
        auth = auth_by_id[surface_id]
        round_trip = round_by_id[surface_id]
        manifest = manifest_by_id[surface_id]
        if write_fixture(root / auth["fixture_path"], route_fixture_rows(auth, manifest), args.refresh):
            authored_route += 1
        if write_fixture(root / round_trip["fixture_path"], round_trip_fixture_rows(round_trip, manifest), args.refresh):
            authored_round_trip += 1

    print(
        "sbsql_fixture_tranche=authored "
        f"selected={len(selected)} "
        f"authenticated_route_files={authored_route} "
        f"sblr_round_trip_files={authored_round_trip} "
        f"first={selected[0]} last={selected[-1]}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
