#!/usr/bin/env python3
# Copyright (c) 2026 ScratchBird Software Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0

"""Generate the SML-029..SML-032 SQL feature closure proof manifest.

The manifest is a deterministic index over existing executable/refusal proof.
It records route, expected result or diagnostic hash, transaction visibility,
resource limits, and parser authority boundaries for CTEs, windows, joins, and
datatype operator/cast matrices. It does not add execution behavior.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
from pathlib import Path


DEFAULT_OUTPUT = (
    "project/tests/sbsql_parser_worker/fixtures/sml_029_032_feature_closure/"
    "SML_029_032_SQL_FEATURE_CLOSURE_MANIFEST.csv"
)

COLUMNS = [
    "sml_id",
    "gate_id",
    "row_id",
    "feature_family",
    "coverage_class",
    "proof_kind",
    "closure_status",
    "route",
    "sblr_operation",
    "expected_result_contract",
    "expected_result_hash",
    "expected_diagnostic_contract",
    "expected_diagnostic_hash",
    "transaction_visibility_class",
    "resource_limits",
    "parser_executes_sql",
    "parser_owns_finality",
    "finality_authority",
    "evidence_paths",
    "evidence_tokens",
]

ROWS = [
    {
        "sml_id": "SML-029",
        "gate_id": "SML-GATE-029",
        "row_id": "SML-029-CTE-MATERIALIZED-POSITIVE",
        "feature_family": "cte_recursive_cte",
        "coverage_class": "positive",
        "proof_kind": "executable",
        "closure_status": "closed_executable",
        "route": "ctest:sbsql_dml_exact_route_conformance;ctest:sbsql_dml_mga_row_result_conformance;server_public_abi;engine:EnginePlanOperation",
        "sblr_operation": "query.plan_operation/SBLR_QUERY_PLAN_OPERATION",
        "expected_result_contract": "materialized CTE rowset rows=3 evidence=query_cte:materialized relation_count=1",
        "expected_diagnostic_contract": "none",
        "transaction_visibility_class": "engine_owned_mga_snapshot_read",
        "resource_limits": "max_rows=3;max_relations=1;max_cte_defs=1;max_recursion_depth=0;network=0;parser_execution=0",
        "parser_executes_sql": "false",
        "parser_owns_finality": "false",
        "finality_authority": "engine_mga_transaction_inventory",
        "evidence_paths": "project/tests/sbsql_parser_worker/sbsql_dml_exact_route_conformance.cpp;project/tests/sbsql_parser_worker/sbsql_dml_mga_row_result_conformance.cpp",
        "evidence_tokens": "\"query_envelope_kind\":\"table_materialized_cte\";\"cte_strategy\":\"materialized\";evidence=query_cte:materialized;authority.parser.no_sql_text_execution;authority.parser.no_storage_or_finality",
    },
    {
        "sml_id": "SML-029",
        "gate_id": "SML-GATE-029",
        "row_id": "SML-029-CTE-RECURSIVE-POSITIVE",
        "feature_family": "cte_recursive_cte",
        "coverage_class": "positive",
        "proof_kind": "executable",
        "closure_status": "closed_executable",
        "route": "ctest:sbsql_dml_exact_route_conformance;ctest:sbsql_dml_mga_row_result_conformance;server_public_abi;engine:EnginePlanOperation",
        "sblr_operation": "query.plan_operation/SBLR_QUERY_PLAN_OPERATION",
        "expected_result_contract": "recursive CTE fixed point rowset rows=3 values=1,2,3 evidence=query_cte:recursive_fixed_point_materialized",
        "expected_diagnostic_contract": "none",
        "transaction_visibility_class": "engine_owned_mga_snapshot_read",
        "resource_limits": "max_rows=3;max_relations=2;max_cte_defs=1;max_recursion_depth=2;network=0;parser_execution=0",
        "parser_executes_sql": "false",
        "parser_owns_finality": "false",
        "finality_authority": "engine_mga_transaction_inventory",
        "evidence_paths": "project/tests/sbsql_parser_worker/sbsql_dml_exact_route_conformance.cpp;project/tests/sbsql_parser_worker/sbsql_dml_mga_row_result_conformance.cpp",
        "evidence_tokens": "\"query_envelope_kind\":\"values_recursive_cte\";\"cte_strategy\":\"recursive_fixed_point_materialized\";evidence=query_cte:recursive_fixed_point_materialized;authority.parser.no_sql_text_execution;authority.parser.no_storage_or_finality",
    },
    {
        "sml_id": "SML-029",
        "gate_id": "SML-GATE-029",
        "row_id": "SML-029-CTE-RECURSIVE-DEPTH-BOUNDARY",
        "feature_family": "cte_recursive_cte",
        "coverage_class": "nested_depth",
        "proof_kind": "executable",
        "closure_status": "closed_executable",
        "route": "ctest:sbsql_dml_exact_route_conformance;server_public_abi;engine:EnginePlanOperation",
        "sblr_operation": "query.plan_operation/SBLR_QUERY_PLAN_OPERATION",
        "expected_result_contract": "recursive CTE relation_count=2 anchor_rows=1 recursive_rows=2 max_depth=2",
        "expected_diagnostic_contract": "none",
        "transaction_visibility_class": "engine_owned_mga_snapshot_read",
        "resource_limits": "max_rows=3;max_relations=2;max_cte_defs=1;max_recursion_depth=2;network=0;parser_execution=0",
        "parser_executes_sql": "false",
        "parser_owns_finality": "false",
        "finality_authority": "engine_mga_transaction_inventory",
        "evidence_paths": "project/tests/sbsql_parser_worker/sbsql_dml_exact_route_conformance.cpp",
        "evidence_tokens": "\"relation_count\":\"2\";\"relation_0_row_count\":\"1\";\"relation_1_row_count\":\"2\";\"row_storage_touched\":false;\"sql_text_included\":false",
    },
    {
        "sml_id": "SML-029",
        "gate_id": "SML-GATE-029",
        "row_id": "SML-029-CTE-UNION-ALL-REFUSAL",
        "feature_family": "cte_recursive_cte",
        "coverage_class": "refusal",
        "proof_kind": "refusal",
        "closure_status": "closed_refusal",
        "route": "ctest:sbsql_dml_exact_route_conformance;parser_verifier_fail_closed",
        "sblr_operation": "query.plan_operation/SBLR_QUERY_PLAN_OPERATION",
        "expected_result_contract": "not_applicable",
        "expected_diagnostic_contract": "recursive CTE UNION ALL duplicate-preserving route fails closed with parser message vector",
        "transaction_visibility_class": "no_transaction_visibility_parser_refusal",
        "resource_limits": "max_rows=0;max_relations=0;max_cte_defs=1;max_recursion_depth=0;network=0;parser_execution=0",
        "parser_executes_sql": "false",
        "parser_owns_finality": "false",
        "finality_authority": "not_reached_parser_refusal",
        "evidence_paths": "project/tests/sbsql_parser_worker/sbsql_dml_exact_route_conformance.cpp",
        "evidence_tokens": "WITH RECURSIVE c(n) AS (VALUES (1) UNION ALL VALUES (1)) SELECT * FROM c;recursive CTE UNION ALL duplicate-preserving route did not fail closed;recursive CTE UNION ALL route did not report parser message vector",
    },
    {
        "sml_id": "SML-029",
        "gate_id": "SML-GATE-029",
        "row_id": "SML-029-CTE-UNSUPPORTED-SHAPES-NEGATIVE",
        "feature_family": "cte_recursive_cte",
        "coverage_class": "negative",
        "proof_kind": "refusal",
        "closure_status": "closed_refusal",
        "route": "ctest:sbsql_dml_exact_route_conformance;unsupported_query_families_fail_closed",
        "sblr_operation": "query.plan_operation/SBLR_QUERY_PLAN_OPERATION",
        "expected_result_contract": "not_applicable",
        "expected_diagnostic_contract": "unsupported CTE shapes with source table recursion, alias lists, non-star bodies, and non-star outer projections fail closed",
        "transaction_visibility_class": "no_transaction_visibility_parser_refusal",
        "resource_limits": "max_rows=0;max_relations=0;max_cte_defs=1;max_recursion_depth=0;network=0;parser_execution=0",
        "parser_executes_sql": "false",
        "parser_owns_finality": "false",
        "finality_authority": "not_reached_parser_refusal",
        "evidence_paths": "project/tests/sbsql_parser_worker/sbsql_dml_exact_route_conformance.cpp",
        "evidence_tokens": "WITH RECURSIVE c AS (SELECT * FROM customer) SELECT * FROM c;WITH c(id) AS (SELECT * FROM customer) SELECT * FROM c;WITH c AS (SELECT id FROM customer) SELECT * FROM c;WITH c AS (SELECT * FROM customer) SELECT id FROM c;unsupported query row family did not fail closed",
    },
    {
        "sml_id": "SML-030",
        "gate_id": "SML-GATE-030",
        "row_id": "SML-030-WINDOW-ROW-NUMBER-POSITIVE",
        "feature_family": "window_functions_frames",
        "coverage_class": "positive",
        "proof_kind": "executable",
        "closure_status": "closed_executable",
        "route": "ctest:sbsql_dml_exact_route_conformance;ctest:sbsql_dml_mga_row_result_conformance;server_public_abi;engine:EnginePlanOperation",
        "sblr_operation": "query.plan_operation/SBLR_QUERY_PLAN_OPERATION",
        "expected_result_contract": "row_number window rowset rows=3 ordered ids and ordinals 1,2,3",
        "expected_diagnostic_contract": "none",
        "transaction_visibility_class": "engine_owned_mga_snapshot_read",
        "resource_limits": "max_rows=3;max_relations=1;max_window_frames=0;network=0;parser_execution=0",
        "parser_executes_sql": "false",
        "parser_owns_finality": "false",
        "finality_authority": "engine_mga_transaction_inventory",
        "evidence_paths": "project/tests/sbsql_parser_worker/sbsql_dml_exact_route_conformance.cpp;project/tests/sbsql_parser_worker/sbsql_dml_mga_row_result_conformance.cpp",
        "evidence_tokens": "\"query_envelope_kind\":\"table_row_number_window\";\"query_operation\":\"row_number_window\";evidence=query_window:row_number;evidence=query_window_binding:descriptor_field;authority.engine.mga_snapshot_visibility_required",
    },
    {
        "sml_id": "SML-030",
        "gate_id": "SML-GATE-030",
        "row_id": "SML-030-WINDOW-FRAME-BOUNDARY",
        "feature_family": "window_functions_frames",
        "coverage_class": "boundary",
        "proof_kind": "executable",
        "closure_status": "closed_executable",
        "route": "ctest:sbsql_sbsfc_063_window_grammar_exact_route_conformance;engine:EnginePlanOperation",
        "sblr_operation": "query.plan_operation/SBLR_QUERY_PLAN_OPERATION",
        "expected_result_contract": "ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE NO OTHERS frame accepted and records frame metadata",
        "expected_diagnostic_contract": "none",
        "transaction_visibility_class": "engine_owned_mga_snapshot_read",
        "resource_limits": "max_rows=3;max_relations=1;max_window_frames=1;network=0;parser_execution=0",
        "parser_executes_sql": "false",
        "parser_owns_finality": "false",
        "finality_authority": "engine_mga_transaction_inventory",
        "evidence_paths": "project/tests/sbsql_parser_worker/sbsql_sbsfc_063_window_grammar_exact_route_conformance.cpp",
        "evidence_tokens": "ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE NO OTHERS;\"window_frame_clause_present\":true;\"window_frame_mode\":\"rows\";\"window_frame_start\":\"unbounded_preceding\";\"window_exclude_target\":\"no_others\"",
    },
    {
        "sml_id": "SML-030",
        "gate_id": "SML-GATE-030",
        "row_id": "SML-030-WINDOW-NAMED-NESTED",
        "feature_family": "window_functions_frames",
        "coverage_class": "nested_depth",
        "proof_kind": "executable",
        "closure_status": "closed_executable",
        "route": "ctest:sbsql_sbsfc_063_window_grammar_exact_route_conformance;parser_lowering;engine:EnginePlanOperation",
        "sblr_operation": "query.plan_operation/SBLR_QUERY_PLAN_OPERATION",
        "expected_result_contract": "named window reference and definition lower to descriptor named_window_0 without carrying source name text",
        "expected_diagnostic_contract": "none",
        "transaction_visibility_class": "engine_owned_mga_snapshot_read",
        "resource_limits": "max_rows=3;max_relations=1;max_window_definitions=1;max_window_reference_depth=1;network=0;parser_execution=0",
        "parser_executes_sql": "false",
        "parser_owns_finality": "false",
        "finality_authority": "engine_mga_transaction_inventory",
        "evidence_paths": "project/tests/sbsql_parser_worker/sbsql_sbsfc_063_window_grammar_exact_route_conformance.cpp",
        "evidence_tokens": "SELECT row_number() OVER win FROM customer WINDOW win AS (ORDER BY id);\"window_named_reference_present\":true;\"window_named_definition_present\":true;\"window_name_text_included\":false;\"window_name_ref_descriptor\":\"named_window_0\"",
    },
    {
        "sml_id": "SML-030",
        "gate_id": "SML-GATE-030",
        "row_id": "SML-030-WINDOW-LAG-OFFSET-NEGATIVE",
        "feature_family": "window_functions_frames",
        "coverage_class": "negative",
        "proof_kind": "refusal",
        "closure_status": "closed_refusal",
        "route": "ctest:sbsql_dml_exact_route_conformance;unsupported_query_families_fail_closed",
        "sblr_operation": "query.plan_operation/SBLR_QUERY_PLAN_OPERATION",
        "expected_result_contract": "not_applicable",
        "expected_diagnostic_contract": "lag with explicit offset outside current bounded route fails closed",
        "transaction_visibility_class": "no_transaction_visibility_parser_refusal",
        "resource_limits": "max_rows=0;max_relations=0;max_window_frames=0;network=0;parser_execution=0",
        "parser_executes_sql": "false",
        "parser_owns_finality": "false",
        "finality_authority": "not_reached_parser_refusal",
        "evidence_paths": "project/tests/sbsql_parser_worker/sbsql_dml_exact_route_conformance.cpp",
        "evidence_tokens": "SELECT lag(id, 2) OVER (ORDER BY id) FROM customer;unsupported query row family did not fail closed",
    },
    {
        "sml_id": "SML-030",
        "gate_id": "SML-GATE-030",
        "row_id": "SML-030-WINDOW-NTILE-ZERO-REFUSAL",
        "feature_family": "window_functions_frames",
        "coverage_class": "refusal",
        "proof_kind": "refusal",
        "closure_status": "closed_refusal",
        "route": "ctest:sbsql_dml_exact_route_conformance;unsupported_query_families_fail_closed",
        "sblr_operation": "query.plan_operation/SBLR_QUERY_PLAN_OPERATION",
        "expected_result_contract": "not_applicable",
        "expected_diagnostic_contract": "ntile zero bucket count fails closed before execution",
        "transaction_visibility_class": "no_transaction_visibility_parser_refusal",
        "resource_limits": "max_rows=0;max_relations=0;max_window_frames=0;network=0;parser_execution=0",
        "parser_executes_sql": "false",
        "parser_owns_finality": "false",
        "finality_authority": "not_reached_parser_refusal",
        "evidence_paths": "project/tests/sbsql_parser_worker/sbsql_dml_exact_route_conformance.cpp",
        "evidence_tokens": "SELECT ntile(0) OVER (ORDER BY id) FROM customer;unsupported query row family did not fail closed",
    },
    {
        "sml_id": "SML-031",
        "gate_id": "SML-GATE-031",
        "row_id": "SML-031-JOIN-INNER-POSITIVE",
        "feature_family": "join_forms_depth",
        "coverage_class": "positive",
        "proof_kind": "executable",
        "closure_status": "closed_executable",
        "route": "ctest:sbsql_dml_exact_route_conformance;ctest:sbsql_dml_mga_row_result_conformance;server_public_abi;engine:EnginePlanOperation",
        "sblr_operation": "query.plan_operation/SBLR_QUERY_PLAN_OPERATION",
        "expected_result_contract": "inner join rowset rows=3 evidence=query_join:inner hash descriptor-field binding",
        "expected_diagnostic_contract": "none",
        "transaction_visibility_class": "engine_owned_mga_snapshot_read",
        "resource_limits": "max_rows=3;max_relations=2;max_join_depth=1;network=0;parser_execution=0",
        "parser_executes_sql": "false",
        "parser_owns_finality": "false",
        "finality_authority": "engine_mga_transaction_inventory",
        "evidence_paths": "project/tests/sbsql_parser_worker/sbsql_dml_exact_route_conformance.cpp;project/tests/sbsql_parser_worker/sbsql_dml_mga_row_result_conformance.cpp",
        "evidence_tokens": "\"query_envelope_kind\":\"table_inner_join\";\"query_operation\":\"inner_join\";\"join_binding_model\":\"engine_row_descriptor_field\";join_algorithm=hash;authority.engine.mga_snapshot_visibility_required",
    },
    {
        "sml_id": "SML-031",
        "gate_id": "SML-GATE-031",
        "row_id": "SML-031-JOIN-CONTEXTUAL-BOUNDARY",
        "feature_family": "join_forms_depth",
        "coverage_class": "boundary",
        "proof_kind": "executable",
        "closure_status": "closed_executable",
        "route": "ctest:sbsql_dml_exact_route_conformance;parser_contextual_keyword;engine:EnginePlanOperation",
        "sblr_operation": "query.plan_operation/SBLR_QUERY_PLAN_OPERATION",
        "expected_result_contract": "JOIN contextual keyword row SBSQL-B18D3DA70CBB proves bounded INNER JOIN route",
        "expected_diagnostic_contract": "none",
        "transaction_visibility_class": "engine_owned_mga_snapshot_read",
        "resource_limits": "max_rows=3;max_relations=2;max_join_depth=1;network=0;parser_execution=0",
        "parser_executes_sql": "false",
        "parser_owns_finality": "false",
        "finality_authority": "engine_mga_transaction_inventory",
        "evidence_paths": "project/tests/sbsql_parser_worker/sbsql_dml_exact_route_conformance.cpp;project/tests/sbsql_parser_worker/fixtures/surface_to_sblr/TRACKER.csv",
        "evidence_tokens": "SBSQL-B18D3DA70CBB;contextual JOIN keyword verifier rejected exact route;\"query_operation\":\"inner_join\";Bounded JOIN contextual keyword function route",
    },
    {
        "sml_id": "SML-031",
        "gate_id": "SML-GATE-031",
        "row_id": "SML-031-JOIN-THREE-TABLE-DEPTH",
        "feature_family": "join_forms_depth",
        "coverage_class": "nested_depth",
        "proof_kind": "executable",
        "closure_status": "closed_executable",
        "route": "ctest:cdp_route_split_benchmark_gate;fixture:execution_plan10_join_shape",
        "sblr_operation": "query.plan_operation/SBLR_QUERY_PLAN_OPERATION",
        "expected_result_contract": "three-table join fixture joins customer orders order_items under execution_plan10 shape",
        "expected_diagnostic_contract": "none",
        "transaction_visibility_class": "engine_owned_mga_snapshot_read",
        "resource_limits": "max_rows=1000;max_relations=3;max_join_depth=2;network=0;parser_execution=0",
        "parser_executes_sql": "false",
        "parser_owns_finality": "false",
        "finality_authority": "engine_mga_transaction_inventory",
        "evidence_paths": "project/tests/sbsql_parser_worker/cdp_benchmark_fixture_support.py;project/tests/sbsql_parser_worker/cdp_route_split_benchmark_gate.py",
        "evidence_tokens": "cdp_join_execution_plan10_shape;JOIN users.public.cdp_orders o ON o.customer_id = c.id;JOIN users.public.cdp_order_items oi ON oi.order_id = o.id;execution_plan10_joins",
    },
    {
        "sml_id": "SML-031",
        "gate_id": "SML-GATE-031",
        "row_id": "SML-031-JOIN-LEFT-NEGATIVE",
        "feature_family": "join_forms_depth",
        "coverage_class": "negative",
        "proof_kind": "refusal",
        "closure_status": "closed_refusal",
        "route": "ctest:sbsql_dml_exact_route_conformance;unsupported_query_families_fail_closed",
        "sblr_operation": "query.plan_operation/SBLR_QUERY_PLAN_OPERATION",
        "expected_result_contract": "not_applicable",
        "expected_diagnostic_contract": "LEFT JOIN remains outside current bounded join route and fails closed",
        "transaction_visibility_class": "no_transaction_visibility_parser_refusal",
        "resource_limits": "max_rows=0;max_relations=0;max_join_depth=0;network=0;parser_execution=0",
        "parser_executes_sql": "false",
        "parser_owns_finality": "false",
        "finality_authority": "not_reached_parser_refusal",
        "evidence_paths": "project/tests/sbsql_parser_worker/sbsql_dml_exact_route_conformance.cpp",
        "evidence_tokens": "SELECT * FROM customer LEFT JOIN orders ON customer.id = orders.id;unsupported query row family did not fail closed",
    },
    {
        "sml_id": "SML-031",
        "gate_id": "SML-GATE-031",
        "row_id": "SML-031-JOIN-TEXT-KEY-REFUSAL",
        "feature_family": "join_forms_depth",
        "coverage_class": "refusal",
        "proof_kind": "refusal",
        "closure_status": "closed_refusal",
        "route": "ctest:sbsql_dml_exact_route_conformance;unsupported_query_families_fail_closed",
        "sblr_operation": "query.plan_operation/SBLR_QUERY_PLAN_OPERATION",
        "expected_result_contract": "not_applicable",
        "expected_diagnostic_contract": "text-key table join outside current UUID/int64 descriptor route fails closed",
        "transaction_visibility_class": "no_transaction_visibility_parser_refusal",
        "resource_limits": "max_rows=0;max_relations=0;max_join_depth=0;network=0;parser_execution=0",
        "parser_executes_sql": "false",
        "parser_owns_finality": "false",
        "finality_authority": "not_reached_parser_refusal",
        "evidence_paths": "project/tests/sbsql_parser_worker/sbsql_dml_exact_route_conformance.cpp",
        "evidence_tokens": "SELECT * FROM customer JOIN orders ON customer.note = orders.note;unsupported query row family did not fail closed",
    },
    {
        "sml_id": "SML-032",
        "gate_id": "SML-GATE-032",
        "row_id": "SML-032-OPERATOR-MULTIPLY-POSITIVE",
        "feature_family": "datatype_operator_cast_matrix",
        "coverage_class": "positive",
        "proof_kind": "executable",
        "closure_status": "closed_executable",
        "route": "ctest:sbsql_multiplicative_expr_exact_route_conformance;server_public_abi;engine:EngineEvaluateProjection",
        "sblr_operation": "query.evaluate_projection/SBLR_QUERY_EVALUATE_PROJECTION",
        "expected_result_contract": "multiplicative operator projection product_value int64=42 evidence=operator_runtime:op_mul",
        "expected_diagnostic_contract": "none",
        "transaction_visibility_class": "engine_projection_transaction_context",
        "resource_limits": "max_rows=1;max_operator_args=2;max_projection_count=1;network=0;parser_execution=0",
        "parser_executes_sql": "false",
        "parser_owns_finality": "false",
        "finality_authority": "engine_mga_transaction_inventory",
        "evidence_paths": "project/tests/sbsql_parser_worker/sbsql_multiplicative_expr_exact_route_conformance.cpp",
        "evidence_tokens": "\"projection_0_expr_kind\":\"operator\";\"projection_0_operator_id\":\"op_mul\";\"projection_0_canonical_operator_id\":\"sb.operator.multiply\";operator_runtime\", \"op_mul\";product_value",
    },
    {
        "sml_id": "SML-032",
        "gate_id": "SML-GATE-032",
        "row_id": "SML-032-CAST-EXPLICIT-POSITIVE",
        "feature_family": "datatype_operator_cast_matrix",
        "coverage_class": "positive",
        "proof_kind": "executable",
        "closure_status": "closed_executable",
        "route": "ctest:sbsql_cast_value_exact_route_conformance;server_public_abi;engine:EngineCastValue",
        "sblr_operation": "query.cast_value/SBLR_QUERY_CAST_VALUE",
        "expected_result_contract": "CAST character 42 to int64 returns 42 with datatype_cast evidence",
        "expected_diagnostic_contract": "none",
        "transaction_visibility_class": "transaction_context_not_required",
        "resource_limits": "max_rows=1;max_casts=1;max_descriptor_changes=1;network=0;parser_execution=0",
        "parser_executes_sql": "false",
        "parser_owns_finality": "false",
        "finality_authority": "engine_cast_api_no_finality",
        "evidence_paths": "project/tests/sbsql_parser_worker/sbsql_cast_value_exact_route_conformance.cpp",
        "evidence_tokens": "\"query_envelope_kind\":\"cast_value\";\"operation_id\":\"query.cast_value\";\"source_descriptor_type\":\"character\";\"target_descriptor_type\":\"int64\";EngineCastValue dispatch missing datatype cast evidence",
    },
    {
        "sml_id": "SML-032",
        "gate_id": "SML-GATE-032",
        "row_id": "SML-032-DESCRIPTOR-DIVIDE-BY-ZERO-BOUNDARY",
        "feature_family": "datatype_operator_cast_matrix",
        "coverage_class": "boundary",
        "proof_kind": "refusal",
        "closure_status": "closed_refusal",
        "route": "ctest:sbsql_advanced_datatype_operation_closure_conformance;engine:descriptor_value_runtime",
        "sblr_operation": "descriptor.expression/SBLR_DESCRIPTOR_RUNTIME",
        "expected_result_contract": "not_applicable",
        "expected_diagnostic_contract": "int64 divide by zero refuses with SB_EXECUTOR_DIVIDE_BY_ZERO",
        "transaction_visibility_class": "transaction_context_not_required",
        "resource_limits": "max_rows=0;max_operator_args=2;max_projection_count=1;network=0;parser_execution=0",
        "parser_executes_sql": "false",
        "parser_owns_finality": "false",
        "finality_authority": "engine_descriptor_runtime_no_finality",
        "evidence_paths": "project/tests/sbsql_parser_worker/sbsql_advanced_datatype_operation_closure_conformance.cpp",
        "evidence_tokens": "DescriptorExpressionOperator::kInt64Divide;SB_EXECUTOR_DIVIDE_BY_ZERO;descriptor divide-by-zero diagnostic drifted",
    },
    {
        "sml_id": "SML-032",
        "gate_id": "SML-GATE-032",
        "row_id": "SML-032-SAFE-TRY-CAST-NESTED",
        "feature_family": "datatype_operator_cast_matrix",
        "coverage_class": "nested_depth",
        "proof_kind": "executable",
        "closure_status": "closed_executable",
        "route": "ctest:sbsql_cast_value_exact_route_conformance;server_public_abi;engine:EngineCastValue",
        "sblr_operation": "query.cast_value/SBLR_QUERY_CAST_VALUE",
        "expected_result_contract": "SAFE_CAST and TRY_CAST lower through canonical cast route with function id and semantic surface ids",
        "expected_diagnostic_contract": "none",
        "transaction_visibility_class": "transaction_context_not_required",
        "resource_limits": "max_rows=1;max_casts=2;max_descriptor_changes=1;network=0;parser_execution=0",
        "parser_executes_sql": "false",
        "parser_owns_finality": "false",
        "finality_authority": "engine_cast_api_no_finality",
        "evidence_paths": "project/tests/sbsql_parser_worker/sbsql_cast_value_exact_route_conformance.cpp",
        "evidence_tokens": "SELECT SAFE_CAST('123' AS int64) AS safe_value;SELECT TRY_CAST('bad' AS int64) AS try_value;\"cast_function_id\":\";\"cast_semantic_surface_ids\";SAFE/TRY CAST verifier rejected exact route",
    },
    {
        "sml_id": "SML-032",
        "gate_id": "SML-GATE-032",
        "row_id": "SML-032-VECTOR-OPERATOR-REFUSAL",
        "feature_family": "datatype_operator_cast_matrix",
        "coverage_class": "refusal",
        "proof_kind": "refusal",
        "closure_status": "closed_refusal",
        "route": "ctest:sbsql_advanced_datatype_operation_closure_conformance;engine:sblr_operator_runtime",
        "sblr_operation": "operator.vector/SBLR_OPERATOR_RUNTIME",
        "expected_result_contract": "not_applicable",
        "expected_diagnostic_contract": "invalid vector operator operator.vector.teleport refuses with SB_DIAG_OPERATOR_INVALID_INPUT",
        "transaction_visibility_class": "transaction_context_not_required",
        "resource_limits": "max_rows=0;max_operator_args=2;max_projection_count=1;network=0;parser_execution=0",
        "parser_executes_sql": "false",
        "parser_owns_finality": "false",
        "finality_authority": "engine_operator_runtime_no_finality",
        "evidence_paths": "project/tests/sbsql_parser_worker/sbsql_advanced_datatype_operation_closure_conformance.cpp",
        "evidence_tokens": "operator.vector.teleport;SB_DIAG_OPERATOR_INVALID_INPUT;invalid vector operator diagnostic drifted",
    },
]


def stable_hash(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def emit_rows() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for source in ROWS:
        row = dict(source)
        row["expected_result_hash"] = stable_hash(row["expected_result_contract"])
        row["expected_diagnostic_hash"] = stable_hash(row["expected_diagnostic_contract"])
        rows.append(row)
    return sorted(rows, key=lambda item: item["row_id"])


def write_csv(path: Path, rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=COLUMNS, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    write_csv(Path(args.output), emit_rows())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
