#include "sblr_database_create_template_clone_runtime.hpp"
#include "core/hash/hash_digest.hpp"
#include <algorithm>
#include <cstring>
namespace scratchbird::engine::sblr { namespace { void put(std::vector<std::uint8_t>&o,std::uint64_t v,std::size_t n){for(std::size_t i=0;i<n;++i)o.push_back((v>>(8*i))&255);} std::uint64_t get(const std::uint8_t*b,std::size_t n){std::uint64_t v=0;for(std::size_t i=0;i<n;++i)v|=std::uint64_t(b[i])<<(8*i);return v;} template<class T>bool nz(const T&x){return std::any_of(x.begin(),x.end(),[](auto v){return v!=0;});} std::vector<std::uint8_t> h(const char*m,std::size_t z){std::vector<std::uint8_t>o(m,m+4);put(o,1,2);put(o,z,2);put(o,z,4);put(o,0,4);return o;} bool vh(const std::uint8_t*b,std::size_t n,const char*m,std::size_t z){return b&&n==z&&std::equal(b,b+4,m)&&get(b+4,2)==1&&get(b+6,2)==z&&get(b+8,4)==z&&std::all_of(b+12,b+16,[](auto v){return !v;});} std::array<std::uint8_t,32> sha(const char*d,const std::uint8_t*b,std::size_t n){std::vector<std::uint8_t>x(d,d+std::strlen(d));x.insert(x.end(),b,b+n);return scratchbird::core::hash::ComputeSha256Digest(x).digest;} }
std::vector<std::uint8_t> EncodeSblrDatabaseCreateTemplateCloneRequestV1(const SblrDatabaseCreateTemplateCloneRequestV1&v){if(!nz(v.receipt)||!v.occurrence||!v.template_clone_occurrence)return{};auto o=h("TCRQ",64);o.insert(o.end(),v.receipt.begin(),v.receipt.end());put(o,v.occurrence,8);put(o,v.template_clone_occurrence,4);o.insert(o.end(),20,0);return o;} bool DecodeSblrDatabaseCreateTemplateCloneRequestV1(const std::uint8_t*b,std::size_t n,SblrDatabaseCreateTemplateCloneRequestV1*o,std::string*d){if(!o||!vh(b,n,"TCRQ",64)||std::any_of(b+44,b+64,[](auto v){return v;})){if(d)*d="TCRQ invalid";return false;}std::copy_n(b+16,16,o->receipt.begin());o->occurrence=get(b+32,8);o->template_clone_occurrence=get(b+40,4);return true;}
std::vector<std::uint8_t> EncodeSblrDatabaseCreateTemplateCloneDescriptorV1(const SblrDatabaseCreateTemplateCloneDescriptorV1&v,bool operand){if(!nz(v.body)||!v.availability)return{};auto o=h(operand?"TCDO":"TCDD",488);o.insert(o.end(),v.body.begin(),v.body.end());auto e=sha("ScratchBird.SblrDatabaseCreateTemplateCloneDescriptor.V1",o.data()+16,400);if(nz(v.evidence)&&e!=v.evidence)return{};o.insert(o.end(),e.begin(),e.end());put(o,v.availability,8);o.insert(o.end(),32,0);return o;} bool DecodeSblrDatabaseCreateTemplateCloneDescriptorV1(const std::uint8_t*b,std::size_t n,SblrDatabaseCreateTemplateCloneDescriptorV1*o,std::string*d,bool operand){if(!o||!vh(b,n,operand?"TCDO":"TCDD",488)||std::any_of(b+456,b+488,[](auto v){return v;})){if(d)*d="TCD invalid";return false;}std::copy_n(b+16,400,o->body.begin());std::copy_n(b+416,32,o->evidence.begin());o->availability=get(b+448,8);return true;}
std::vector<std::uint8_t> EncodeSblrDatabaseCreateTemplateCloneResultV1(const SblrDatabaseCreateTemplateCloneResultV1&v){if(!nz(v.body)||!v.availability||!nz(v.publication_barrier))return{};auto o=h("TCRS",320);o.insert(o.end(),v.body.begin(),v.body.end());auto e=sha("ScratchBird.SblrDatabaseCreateTemplateCloneResult.V1",o.data()+16,240);if(nz(v.evidence)&&e!=v.evidence)return{};o.insert(o.end(),e.begin(),e.end());put(o,v.availability,8);o.insert(o.end(),v.publication_barrier.begin(),v.publication_barrier.end());o.insert(o.end(),8,0);return o;} bool DecodeSblrDatabaseCreateTemplateCloneResultV1(const std::uint8_t*b,std::size_t n,SblrDatabaseCreateTemplateCloneResultV1*o,std::string*d){if(!o||!vh(b,n,"TCRS",320)||std::any_of(b+312,b+320,[](auto v){return v;})){if(d)*d="TCRS invalid";return false;}std::copy_n(b+16,240,o->body.begin());std::copy_n(b+256,32,o->evidence.begin());o->availability=get(b+288,8);std::copy_n(b+296,16,o->publication_barrier.begin());return true;}
}
