#include "sblr_ddl_alter_trigger_runtime.hpp"
#include "core/hash/hash_digest.hpp"
#include <algorithm>
#include <cstring>
namespace scratchbird::engine::sblr { namespace { void p(std::vector<uint8_t>&o,uint64_t v,size_t n){for(size_t i=0;i<n;i++)o.push_back(uint8_t(v>>(8*i)));} uint64_t g(const uint8_t*b,size_t n){uint64_t v=0;for(size_t i=0;i<n;i++)v|=uint64_t(b[i])<<(8*i);return v;} template<class T>bool nz(const T&x){return std::any_of(x.begin(),x.end(),[](auto v){return v!=0;});} std::vector<uint8_t> h(const char*m,size_t n){std::vector<uint8_t>o(m,m+4);p(o,1,2);p(o,n,2);p(o,n,4);p(o,0,4);return o;} bool vh(const uint8_t*b,size_t n,const char*m,size_t z){return b&&n==z&&std::equal(b,b+4,m)&&g(b+4,2)==1&&g(b+6,2)==z&&g(b+8,4)==z&&std::all_of(b+12,b+16,[](auto v){return v==0;});} DdlAlterTriggerSha sha(const char*d,const uint8_t*b,size_t n){std::vector<uint8_t>x(d,d+strlen(d));x.insert(x.end(),b,b+n);return scratchbird::core::hash::ComputeSha256Digest(x).digest;} }
std::vector<uint8_t> EncodeSblrDdlAlterTriggerRequestV1(const SblrDdlAlterTriggerRequestV1&v){if(!nz(v.receipt)||!v.occurrence||!v.trigger_occurrence)return{};auto o=h("TAQX",64);o.insert(o.end(),v.receipt.begin(),v.receipt.end());p(o,v.occurrence,8);p(o,v.trigger_occurrence,4);o.insert(o.end(),20,0);return o;}
bool DecodeSblrDdlAlterTriggerRequestV1(const uint8_t*b,size_t n,SblrDdlAlterTriggerRequestV1*out,std::string*d){if(!out||!vh(b,n,"TAQX",64)||std::any_of(b+44,b+64,[](auto v){return v;})){if(d)*d="TAQX invalid";return false;}SblrDdlAlterTriggerRequestV1 v;std::copy_n(b+16,16,v.receipt.begin());v.occurrence=g(b+32,8);v.trigger_occurrence=g(b+40,4);if(EncodeSblrDdlAlterTriggerRequestV1(v).empty())return false;*out=v;return true;}
std::vector<uint8_t> EncodeSblrDdlAlterTriggerDescriptorV1(const SblrDdlAlterTriggerDescriptorV1&v,bool op){if(!nz(v.body)||!v.availability)return{};auto o=h(op?"TADO":"TADX",488);o.insert(o.end(),v.body.begin(),v.body.end());auto e=sha("ScratchBird.SblrDdlAlterTriggerDescriptor.V1",o.data()+16,400);if(nz(v.evidence)&&e!=v.evidence)return{};o.insert(o.end(),e.begin(),e.end());p(o,v.availability,8);o.insert(o.end(),32,0);return o;}
bool DecodeSblrDdlAlterTriggerDescriptorV1(const uint8_t*b,size_t n,SblrDdlAlterTriggerDescriptorV1*out,std::string*d,bool op){if(!out||!vh(b,n,op?"TADO":"TADX",488)||std::any_of(b+456,b+488,[](auto v){return v;})){if(d)*d="TADO invalid";return false;}SblrDdlAlterTriggerDescriptorV1 v;std::copy_n(b+16,400,v.body.begin());std::copy_n(b+416,32,v.evidence.begin());v.availability=g(b+448,8);if(EncodeSblrDdlAlterTriggerDescriptorV1(v,op).empty())return false;*out=v;return true;}
std::vector<uint8_t> EncodeSblrDdlAlterTriggerResultV1(const SblrDdlAlterTriggerResultV1&v){if(!nz(v.body)||v.body[24]!=1||v.body[25]>1||!g(v.body.data()+56,8)||!v.availability||!nz(v.publication_barrier))return{};auto o=h("TARS",320);o.insert(o.end(),v.body.begin(),v.body.end());auto e=sha("ScratchBird.SblrDdlAlterTriggerExecutorEvidence.V1",o.data()+16,240);if(nz(v.evidence)&&e!=v.evidence)return{};o.insert(o.end(),e.begin(),e.end());p(o,v.availability,8);o.insert(o.end(),v.publication_barrier.begin(),v.publication_barrier.end());o.insert(o.end(),8,0);return o;}
bool DecodeSblrDdlAlterTriggerResultV1(const uint8_t*b,size_t n,SblrDdlAlterTriggerResultV1*out,std::string*d){if(!out||!vh(b,n,"TARS",320)||std::any_of(b+312,b+320,[](auto v){return v;})){if(d)*d="TARS invalid";return false;}SblrDdlAlterTriggerResultV1 v;std::copy_n(b+16,240,v.body.begin());std::copy_n(b+256,32,v.evidence.begin());v.availability=g(b+288,8);std::copy_n(b+296,16,v.publication_barrier.begin());if(EncodeSblrDdlAlterTriggerResultV1(v).empty())return false;*out=v;return true;}
}
