#include "sblr_sec_drop_role_runtime.hpp"
#include <cstring>
namespace scratchbird::engine::sblr { static void w16(std::vector<uint8_t>&b,size_t o,uint16_t v){b[o]=v;b[o+1]=v>>8;} static void w32(std::vector<uint8_t>&b,size_t o,uint32_t v){for(int i=0;i<4;i++)b[o+i]=v>>(8*i);} static void w64(std::vector<uint8_t>&b,size_t o,uint64_t v){for(int i=0;i<8;i++)b[o+i]=v>>(8*i);} static uint64_t r64(const uint8_t*p,size_t o){uint64_t v=0;for(int i=0;i<8;i++)v|=uint64_t(p[o+i])<<(8*i);return v;} static void cp(std::vector<uint8_t>&b,size_t o,const void*p,size_t n){std::memcpy(b.data()+o,p,n);} static bool head(const uint8_t*p,size_t n,const char*m,size_t z,std::string*d){const uint32_t len=p?uint32_t(p[8])|(uint32_t(p[9])<<8)|(uint32_t(p[10])<<16)|(uint32_t(p[11])<<24):0;if(!p||n!=z||std::memcmp(p,m,4)!=0||p[4]!=1||p[6]!=z||len!=z){if(d)*d="SDRQ/SDRD/SDRO fixed-size header invalid";return false;}return true;}
std::vector<uint8_t> EncodeSblrSecDropRoleRequestV1(const SblrSecDropRoleRequestV1&v){std::vector<uint8_t>b(64);cp(b,0,"SDRQ",4);w16(b,4,1);w16(b,6,64);w32(b,8,64);cp(b,16,v.receipt.data(),16);w64(b,32,v.occurrence);return b;}
bool DecodeSblrSecDropRoleRequestV1(const uint8_t*p,size_t n,SblrSecDropRoleRequestV1*o,std::string*d){if(!head(p,n,"SDRQ",64,d))return false;std::memcpy(o->receipt.data(),p+16,16);o->occurrence=r64(p,32);return o->occurrence!=0;}
std::vector<uint8_t> EncodeSblrSecDropRoleDescriptorV1(const SblrSecDropRoleDescriptorV1&v,bool op){std::vector<uint8_t>b(128);cp(b,0,op?"SDRO":"SDRD",4);w16(b,4,1);w16(b,6,128);w32(b,8,128);cp(b,16,v.role_uuid.data(),16);w64(b,32,v.expected_generation);w64(b,40,v.catalog_generation);w64(b,48,v.security_generation);w64(b,56,v.availability);cp(b,64,v.descriptor_evidence.data(),16);return b;}
bool DecodeSblrSecDropRoleDescriptorV1(const uint8_t*p,size_t n,SblrSecDropRoleDescriptorV1*o,std::string*d,bool op){if(!head(p,n,op?"SDRO":"SDRD",128,d))return false;std::memcpy(o->role_uuid.data(),p+16,16);o->expected_generation=r64(p,32);o->catalog_generation=r64(p,40);o->security_generation=r64(p,48);o->availability=r64(p,56);std::memcpy(o->descriptor_evidence.data(),p+64,16);return true;}
std::vector<uint8_t> EncodeSblrSecDropRoleResultV1(const SblrSecDropRoleResultV1&v){std::vector<uint8_t>b(128);cp(b,0,"SDRR",4);w16(b,4,1);w16(b,6,128);w32(b,8,128);b[16]=v.status;b[17]=v.publication_barrier;cp(b,24,v.role_uuid.data(),16);w64(b,40,v.generation);w64(b,48,v.security_generation);w64(b,56,v.availability);cp(b,64,v.effect_evidence.data(),32);return b;}
bool DecodeSblrSecDropRoleResultV1(const uint8_t*p,size_t n,SblrSecDropRoleResultV1*o,std::string*d){if(!head(p,n,"SDRR",128,d))return false;o->status=p[16];o->publication_barrier=p[17];std::memcpy(o->role_uuid.data(),p+24,16);o->generation=r64(p,40);o->security_generation=r64(p,48);o->availability=r64(p,56);std::memcpy(o->effect_evidence.data(),p+64,32);return true;}}
