#include "sblr_ddl_create_continuous_view_runtime.hpp"
#include <cstring>
namespace scratchbird::engine::sblr { namespace { constexpr std::uint32_t REQ=0x43565251, DESC=0x43564444, OPER=0x4356444f, RES=0x43565253; void put(std::vector<std::uint8_t>&b,std::size_t o,std::uint64_t v){for(int i=0;i<8;i++)b[o+i]=static_cast<std::uint8_t>(v>>(i*8));} std::uint64_t get(const std::uint8_t*p,std::size_t o){std::uint64_t v=0;for(int i=0;i<8;i++)v|=std::uint64_t(p[o+i])<<(i*8);return v;} }
std::vector<std::uint8_t> EncodeSblrDdlCreateContinuousViewRequestV1(const SblrDdlCreateContinuousViewRequestV1&x){std::vector<std::uint8_t>b(64);std::memcpy(b.data(),&REQ,4);std::memcpy(b.data()+16,x.receipt.data(),16);put(b,32,x.occurrence);put(b,40,x.view_occurrence);return b;}
bool DecodeSblrDdlCreateContinuousViewRequestV1(const std::uint8_t*p,std::size_t n,SblrDdlCreateContinuousViewRequestV1*x,std::string*d){if(!p||n!=64||!x){if(d)*d="request size";return false;}if(std::memcmp(p,&REQ,4)!=0){if(d)*d="request magic";return false;}std::memcpy(x->receipt.data(),p+16,16);x->occurrence=get(p,32);x->view_occurrence=get(p,40);return x->occurrence&&x->view_occurrence;}
std::vector<std::uint8_t> EncodeSblrDdlCreateContinuousViewDescriptorV1(const SblrDdlCreateContinuousViewDescriptorV1&x,bool operand){std::vector<std::uint8_t>b(488);std::uint32_t m=operand?OPER:DESC;std::memcpy(b.data(),&m,4);std::memcpy(b.data()+16,x.body.data()+16,400);std::memcpy(b.data()+416,x.evidence.data(),32);put(b,448,x.availability);return b;}
bool DecodeSblrDdlCreateContinuousViewDescriptorV1(const std::uint8_t*p,std::size_t n,SblrDdlCreateContinuousViewDescriptorV1*x,std::string*d,bool operand){if(!p||n!=488||!x){if(d)*d="descriptor size";return false;}std::uint32_t m=0;std::memcpy(&m,p,4);if(m!=(operand?OPER:DESC)){if(d)*d="descriptor magic";return false;}std::memcpy(x->body.data()+16,p+16,400);std::memcpy(x->evidence.data(),p+416,32);x->availability=get(p,448);return x->availability!=0;}
std::vector<std::uint8_t> EncodeSblrDdlCreateContinuousViewResultV1(const SblrDdlCreateContinuousViewResultV1&x){std::vector<std::uint8_t>b(320);std::uint32_t m=RES;std::memcpy(b.data(),&m,4);std::memcpy(b.data()+16,x.body.data(),240);std::memcpy(b.data()+256,x.evidence.data(),32);put(b,288,x.availability);std::memcpy(b.data()+296,x.publication_barrier.data(),16);return b;}
bool DecodeSblrDdlCreateContinuousViewResultV1(const std::uint8_t*p,std::size_t n,SblrDdlCreateContinuousViewResultV1*x,std::string*d){if(!p||n!=320||!x){if(d)*d="result size";return false;}std::uint32_t m=0;std::memcpy(&m,p,4);if(m!=RES){if(d)*d="result magic";return false;}std::memcpy(x->body.data(),p+16,240);std::memcpy(x->evidence.data(),p+256,32);x->availability=get(p,288);std::memcpy(x->publication_barrier.data(),p+296,16);return x->availability!=0;}
}
