#include "sblr_security_drop_privilege_template_runtime.hpp"
#include "core/hash/hash_digest.hpp"
#include <algorithm>
#include <cstring>
namespace scratchbird::engine::sblr { namespace {
void put(std::vector<std::uint8_t>& o,std::uint64_t v,std::size_t n){for(std::size_t i=0;i<n;++i)o.push_back(static_cast<std::uint8_t>(v>>(8*i)));}
std::uint64_t get(const std::uint8_t* b,std::size_t n){std::uint64_t v=0;for(std::size_t i=0;i<n;++i)v|=std::uint64_t(b[i])<<(8*i);return v;}
template<class T> bool nonzero(const T& x){return std::any_of(x.begin(),x.end(),[](auto v){return v!=0;});}
std::vector<std::uint8_t> hdr(const char* m,std::size_t n){std::vector<std::uint8_t> o(m,m+4);put(o,1,2);put(o,n,2);put(o,n,4);put(o,0,4);return o;}
bool vh(const std::uint8_t* b,std::size_t n,const char* m,std::size_t z){return b&&n==z&&std::equal(b,b+4,m)&&get(b+4,2)==1&&get(b+6,2)==z&&get(b+8,4)==z&&std::all_of(b+12,b+16,[](auto v){return v==0;});}
std::array<std::uint8_t,32> sha(const char* d,const std::uint8_t* b,std::size_t n){std::vector<std::uint8_t>x(d,d+std::strlen(d));x.insert(x.end(),b,b+n);return scratchbird::core::hash::ComputeSha256Digest(x).digest;}
}
std::vector<std::uint8_t> EncodeSblrSecurityDropPrivilegeTemplateRequestV1(const SblrSecurityDropPrivilegeTemplateRequestV1& v){if(!nonzero(v.receipt)||!v.occurrence||!v.template_occurrence)return{};auto o=hdr("PTDQ",64);o.insert(o.end(),v.receipt.begin(),v.receipt.end());put(o,v.occurrence,8);put(o,v.template_occurrence,4);o.insert(o.end(),20,0);return o;}
bool DecodeSblrSecurityDropPrivilegeTemplateRequestV1(const std::uint8_t*b,std::size_t n,SblrSecurityDropPrivilegeTemplateRequestV1*o,std::string*d){if(!o||!vh(b,n,"PTDQ",64)||std::any_of(b+44,b+64,[](auto v){return v;})){if(d)*d="PTQX invalid";return false;}SblrSecurityDropPrivilegeTemplateRequestV1 v;std::copy_n(b+16,16,v.receipt.begin());v.occurrence=get(b+32,8);v.template_occurrence=get(b+40,4);*o=v;return !EncodeSblrSecurityDropPrivilegeTemplateRequestV1(v).empty();}
std::vector<std::uint8_t> EncodeSblrSecurityDropPrivilegeTemplateDescriptorV1(const SblrSecurityDropPrivilegeTemplateDescriptorV1&v,bool operand){if(!nonzero(v.body)||!v.availability)return{};auto o=hdr(operand?"PTDO":"PTDD",488);o.insert(o.end(),v.body.begin(),v.body.end());auto e=sha("ScratchBird.SblrSecurityDropPrivilegeTemplateDescriptor.V1",o.data()+16,400);if(nonzero(v.evidence)&&e!=v.evidence)return{};o.insert(o.end(),e.begin(),e.end());put(o,v.availability,8);o.insert(o.end(),32,0);return o;}
bool DecodeSblrSecurityDropPrivilegeTemplateDescriptorV1(const std::uint8_t*b,std::size_t n,SblrSecurityDropPrivilegeTemplateDescriptorV1*o,std::string*d,bool operand){if(!o||!(vh(b,n,operand?"PTDO":"PTDD",488)||(!operand&&vh(b,n,"PTDO",488)))||std::any_of(b+456,b+488,[](auto v){return v;})){if(d)*d="PT descriptor invalid";return false;}SblrSecurityDropPrivilegeTemplateDescriptorV1 v;std::copy_n(b+16,400,v.body.begin());std::copy_n(b+416,32,v.evidence.begin());v.availability=get(b+448,8);*o=v;return !EncodeSblrSecurityDropPrivilegeTemplateDescriptorV1(v,operand).empty();}
std::vector<std::uint8_t> EncodeSblrSecurityDropPrivilegeTemplateResultV1(const SblrSecurityDropPrivilegeTemplateResultV1&v){if(!nonzero(v.body)||!v.availability||!nonzero(v.publication_barrier))return{};auto o=hdr("PTRS",320);o.insert(o.end(),v.body.begin(),v.body.end());auto e=sha("ScratchBird.SblrSecurityDropPrivilegeTemplateResult.V1",o.data()+16,240);if(nonzero(v.evidence)&&e!=v.evidence)return{};o.insert(o.end(),e.begin(),e.end());put(o,v.availability,8);o.insert(o.end(),v.publication_barrier.begin(),v.publication_barrier.end());o.insert(o.end(),8,0);return o;}
bool DecodeSblrSecurityDropPrivilegeTemplateResultV1(const std::uint8_t*b,std::size_t n,SblrSecurityDropPrivilegeTemplateResultV1*o,std::string*d){if(!o||!vh(b,n,"PTRS",320)||std::any_of(b+312,b+320,[](auto v){return v;})){if(d)*d="PTRS invalid";return false;}SblrSecurityDropPrivilegeTemplateResultV1 v;std::copy_n(b+16,240,v.body.begin());std::copy_n(b+256,32,v.evidence.begin());v.availability=get(b+288,8);std::copy_n(b+296,16,v.publication_barrier.begin());*o=v;return !EncodeSblrSecurityDropPrivilegeTemplateResultV1(v).empty();}
}
