#include "engine/sblr/sblr_ddl_alter_subscription_runtime.hpp"
#include "core/hash/hash_digest.hpp"
#include <algorithm>
#include <cstring>
namespace scratchbird::engine::sblr{namespace{template<class A>bool nz(const A&a){return std::any_of(a.begin(),a.end(),[](auto b){return b;});}void p(std::vector<std::uint8_t>&o,std::uint64_t v,std::size_t n){for(std::size_t i=0;i<n;++i)o.push_back(v>>(8*i));}std::uint64_t g(const std::uint8_t*b,std::size_t n){std::uint64_t v=0;for(std::size_t i=0;i<n;++i)v|=std::uint64_t(b[i])<<(8*i);return v;}std::array<std::uint8_t,32>sha(const char*d,const std::vector<std::uint8_t>&b){std::vector<std::uint8_t>x(d,d+std::strlen(d));x.insert(x.end(),b.begin(),b.end());return scratchbird::core::hash::ComputeSha256Digest(x).digest;}}
std::vector<std::uint8_t>EncodeSblrDdlAlterSubscriptionRequestV1(const SblrDdlAlterSubscriptionRequestV1&v){if(!nz(v.operation)||!nz(v.receipt)||v.descriptor_length!=384)return{};std::vector<std::uint8_t>o={'S','A','U','Q'};p(o,1,2);p(o,8,2);p(o,7559,4);p(o,546,4);o.insert(o.end(),v.operation.begin(),v.operation.end());o.insert(o.end(),v.receipt.begin(),v.receipt.end());p(o,384,4);o.insert(o.end(),12,0);return o;}bool DecodeSblrDdlAlterSubscriptionRequestV1(const std::uint8_t*b,std::size_t n,SblrDdlAlterSubscriptionRequestV1*o,std::string*d){if(!o||n!=64||std::memcmp(b,"SAUQ",4)||g(b+4,2)!=1||g(b+6,2)!=8||g(b+8,4)!=7559||g(b+12,4)!=546||std::any_of(b+52,b+64,[](auto x){return x;})){if(d)*d="SAUQ invalid";return false;}SblrDdlAlterSubscriptionRequestV1 v;std::copy_n(b+16,16,v.operation.begin());std::copy_n(b+32,16,v.receipt.begin());v.descriptor_length=g(b+48,4);if(EncodeSblrDdlAlterSubscriptionRequestV1(v).empty())return false;*o=v;return true;}
std::vector<std::uint8_t>enc(const char*m,const std::array<std::uint8_t,376>&b,const char*d){std::vector<std::uint8_t>o={m[0],m[1],m[2],m[3],1,0,0,0};o.insert(o.end(),b.begin(),b.end());std::fill(o.begin()+8+344,o.begin()+8+376,0);auto h=sha(d,o);std::copy(h.begin(),h.end(),o.begin()+8+344);return o;}
bool dec(const std::uint8_t*b,std::size_t n,const char*m,std::array<std::uint8_t,376>*out,const char*d,std::string*e){if(!out||n!=384||std::memcmp(b,m,4)||b[4]!=1||b[5]||b[6]||b[7]){if(e)*e="descriptor invalid";return false;}std::copy_n(b+8,376,out->begin());auto x=enc(m,*out,d);if(!std::equal(x.begin(),x.end(),b)){if(e)*e="descriptor hash invalid";return false;}return true;}
std::vector<std::uint8_t>EncodeSblrDdlAlterSubscriptionDescriptorV1(const SblrDdlAlterSubscriptionDescriptorV1&v){return nz(v.body)?enc("SAUD",v.body,"SBOD|SAUD|v1"):std::vector<std::uint8_t>{};}bool DecodeSblrDdlAlterSubscriptionDescriptorV1(const std::uint8_t*b,std::size_t n,SblrDdlAlterSubscriptionDescriptorV1*o,std::string*d){return o&&dec(b,n,"SAUD",&o->body,"SBOD|SAUD|v1",d);}
std::vector<std::uint8_t>EncodeSblrDdlAlterSubscriptionResultV1(const SblrDdlAlterSubscriptionResultV1&v){return nz(v.body)?enc("SLRR",v.body,"ScratchBird.SblrDdlAlterSubscription.Result.V1"):std::vector<std::uint8_t>{};}bool DecodeSblrDdlAlterSubscriptionResultV1(const std::uint8_t*b,std::size_t n,SblrDdlAlterSubscriptionResultV1*o,std::string*d){return o&&dec(b,n,"SLRR",&o->body,"ScratchBird.SblrDdlAlterSubscription.Result.V1",d);}}
