#include "sblr_reservation_release_runtime.hpp"
#include "hash_digest.hpp"
#include <algorithm>
namespace scratchbird::engine::sblr {namespace {template<class A>bool nz(const A&a){return std::any_of(a.begin(),a.end(),[](auto x){return x;});}template<class A>void put(std::vector<std::uint8_t>&o,const A&a){o.insert(o.end(),a.begin(),a.end());}template<class A>void get(const std::uint8_t*p,A&a){std::copy_n(p,a.size(),a.begin());}void p16(std::vector<std::uint8_t>&o,unsigned v){o.push_back(v);o.push_back(v>>8);}void p32(std::vector<std::uint8_t>&o,unsigned v){for(int i=0;i<4;i++)o.push_back(v>>(8*i));}void p64(std::vector<std::uint8_t>&o,std::uint64_t v){for(int i=0;i<8;i++)o.push_back(v>>(8*i));}std::uint64_t u64(const std::uint8_t*p){std::uint64_t v=0;for(int i=0;i<8;i++)v|=std::uint64_t(p[i])<<(8*i);return v;}RrSha hash(const char*d,const std::vector<std::uint8_t>&b){std::vector<std::uint8_t>x(d,d+std::char_traits<char>::length(d));x.insert(x.end(),b.begin(),b.end());return scratchbird::core::hash::ComputeSha256Digest(x).digest;}bool head(const std::uint8_t*b,size_t n,const char*m,size_t z){return b&&n==z&&std::equal(b,b+4,m)&&b[4]==1&&!b[5]&&b[6]==(z&255)&&b[7]==(z>>8)&&std::all_of(b+12,b+16,[](auto x){return !x;});}}
std::vector<std::uint8_t> EncodeSblrReservationReleaseRequestV1(const SblrReservationReleaseRequestV1&v){if(!nz(v.receipt)||!nz(v.transaction)||!nz(v.relation)||!v.occurrence)return{};std::vector<std::uint8_t>o{'R','R','C','R'};p16(o,1);p16(o,80);p32(o,80);p32(o,0);put(o,v.receipt);put(o,v.transaction);put(o,v.relation);p64(o,v.occurrence);o.insert(o.end(),8,0);return o;}
bool DecodeSblrReservationReleaseRequestV1(const std::uint8_t*b,size_t n,SblrReservationReleaseRequestV1*out,std::string*d){if(!out||!head(b,n,"RRCR",80)){if(d)*d="RRCR invalid";return false;}SblrReservationReleaseRequestV1 v;get(b+16,v.receipt);get(b+32,v.transaction);get(b+48,v.relation);v.occurrence=u64(b+64);if(std::any_of(b+72,b+80,[](auto x){return x;})||EncodeSblrReservationReleaseRequestV1(v).empty())return false;*out=v;return true;}
std::vector<std::uint8_t> EncodeSblrReservationReleaseDescriptorV1(const SblrReservationReleaseDescriptorV1&v,bool operand){if(!nz(v.reservation)||!v.reservation_generation||!nz(v.transaction)||!v.local_transaction_id||!nz(v.relation)||v.mode<1||v.mode>4||!v.catalog_generation||!v.policy_generation||!v.availability_generation)return{};std::vector<std::uint8_t>o{'R','R',static_cast<std::uint8_t>(operand?'D':'C'),static_cast<std::uint8_t>(operand?'O':'D')};p16(o,1);p16(o,144);p32(o,144);p32(o,0);put(o,v.reservation);p64(o,v.reservation_generation);put(o,v.transaction);p64(o,v.local_transaction_id);put(o,v.relation);o.push_back(v.mode);o.insert(o.end(),7,0);p64(o,v.catalog_generation);p64(o,v.policy_generation);std::vector<std::uint8_t>material(o.begin()+16,o.end());auto e=hash("ScratchBird.SblrTransactionReservationReleaseDescriptor.V1",material);if(nz(v.reservation_evidence)&&v.reservation_evidence!=e)return{};put(o,e);p64(o,v.availability_generation);return o;}
bool DecodeSblrReservationReleaseDescriptorV1(const std::uint8_t*b,size_t n,SblrReservationReleaseDescriptorV1*out,std::string*d,bool operand){if(!out||!head(b,n,operand?"RRDO":"RRCD",144)){if(d)*d="RRCD invalid";return false;}SblrReservationReleaseDescriptorV1 v;get(b+16,v.reservation);v.reservation_generation=u64(b+32);get(b+40,v.transaction);v.local_transaction_id=u64(b+56);get(b+64,v.relation);v.mode=b[80];v.catalog_generation=u64(b+88);v.policy_generation=u64(b+96);get(b+104,v.reservation_evidence);v.availability_generation=u64(b+136);if(std::any_of(b+81,b+88,[](auto x){return x;})||EncodeSblrReservationReleaseDescriptorV1(v,operand).empty())return false;*out=v;return true;}
std::vector<std::uint8_t> EncodeSblrReservationReleaseResultV1(const SblrReservationReleaseResultV1&v){if(!nz(v.transaction)||!v.local_transaction_id||!nz(v.reservation)||!v.reservation_generation||!nz(v.relation)||!v.release_sequence||v.final_state!=1||!nz(v.release_evidence)||!v.availability_generation)return{};std::vector<std::uint8_t>o{'R','R','R','S'};p16(o,1);p16(o,168);p32(o,168);p32(o,0);put(o,v.transaction);p64(o,v.local_transaction_id);put(o,v.reservation);p64(o,v.reservation_generation);put(o,v.relation);p64(o,v.release_sequence);o.push_back(v.final_state);o.insert(o.end(),7,0);put(o,v.release_evidence);p64(o,v.availability_generation);auto e=hash("ScratchBird.SblrTransactionReservationReleaseResult.V1",o);if(nz(v.result_evidence)&&v.result_evidence!=e)return{};put(o,e);return o;}
bool DecodeSblrReservationReleaseResultV1(const std::uint8_t*b,size_t n,SblrReservationReleaseResultV1*out,std::string*d){if(!out||!head(b,n,"RRRS",168)){if(d)*d="RRRS invalid";return false;}SblrReservationReleaseResultV1 v;get(b+16,v.transaction);v.local_transaction_id=u64(b+32);get(b+40,v.reservation);v.reservation_generation=u64(b+56);get(b+64,v.relation);v.release_sequence=u64(b+80);v.final_state=b[88];get(b+96,v.release_evidence);v.availability_generation=u64(b+128);get(b+136,v.result_evidence);if(std::any_of(b+89,b+96,[](auto x){return x;})||EncodeSblrReservationReleaseResultV1(v).empty())return false;*out=v;return true;}}
