#include "engine/sblr/sblr_ddl_drop_publication_runtime.hpp"
#include "core/hash/hash_digest.hpp"
#include <algorithm>
#include <cstring>
namespace scratchbird::engine::sblr{namespace{template<class A>bool nz(const A&a){return std::any_of(a.begin(),a.end(),[](auto b){return b!=0;});}void p(std::vector<std::uint8_t>&o,std::uint64_t v,std::size_t n){for(std::size_t i=0;i<n;++i)o.push_back(static_cast<std::uint8_t>(v>>(8*i)));}std::uint64_t g(const std::uint8_t*b,std::size_t n){std::uint64_t v=0;for(std::size_t i=0;i<n;++i)v|=std::uint64_t(b[i])<<(8*i);return v;}std::vector<std::uint8_t>h(const char*m){std::vector<std::uint8_t>o(m,m+4);p(o,1,2);p(o,0,2);return o;}bool vh(const std::uint8_t*b,std::size_t n,const char*m,std::size_t z){return b&&n==z&&std::equal(b,b+4,m)&&g(b+4,2)==1&&g(b+6,2)==0;}std::array<std::uint8_t,32>sha(const char*d,const std::vector<std::uint8_t>&b){std::vector<std::uint8_t>x(d,d+std::strlen(d));x.insert(x.end(),b.begin(),b.end());return scratchbird::core::hash::ComputeSha256Digest(x).digest;}}
std::vector<std::uint8_t>EncodeSblrDdlDropPublicationRequestV1(const SblrDdlDropPublicationRequestV1&v){if(!nz(v.operation)||!nz(v.receipt)||v.descriptor_length!=320)return{};std::vector<std::uint8_t>o={'S','B','A','Q'};p(o,1,2);p(o,8,2);p(o,7555,4);p(o,542,4);o.insert(o.end(),v.operation.begin(),v.operation.end());o.insert(o.end(),v.receipt.begin(),v.receipt.end());p(o,v.descriptor_length,4);o.insert(o.end(),12,0);return o;}
bool DecodeSblrDdlDropPublicationRequestV1(const std::uint8_t*b,std::size_t n,SblrDdlDropPublicationRequestV1*o,std::string*d){if(!o||n!=64||std::equal(b,b+4,"SBAQ")==false||g(b+4,2)!=1||g(b+6,2)!=8||g(b+8,4)!=7555||g(b+12,4)!=542||std::any_of(b+52,b+64,[](auto x){return x;})){if(d)*d="SBAQ invalid";return false;}SblrDdlDropPublicationRequestV1 v;std::copy_n(b+16,16,v.operation.begin());std::copy_n(b+32,16,v.receipt.begin());v.descriptor_length=g(b+48,4);if(EncodeSblrDdlDropPublicationRequestV1(v).empty())return false;*o=v;return true;}
std::vector<std::uint8_t>EncodeSblrDdlDropPublicationDescriptorV1(const SblrDdlDropPublicationDescriptorV1&v){if(!nz(v.body))return{};auto o=h("SLDP");o.insert(o.end(),v.body.begin(),v.body.end());std::fill(o.begin()+8+248,o.begin()+8+280,0);auto d=sha("ScratchBird.SblrDdlDropPublicationDescriptor.V1",o);std::copy(d.begin(),d.end(),o.begin()+8+248);return o;}
bool DecodeSblrDdlDropPublicationDescriptorV1(const std::uint8_t*b,std::size_t n,SblrDdlDropPublicationDescriptorV1*o,std::string*d){if(!o||!vh(b,n,"SLDP",320)){if(d)*d="SLDP invalid";return false;}SblrDdlDropPublicationDescriptorV1 v;std::copy_n(b+8,312,v.body.begin());auto e=EncodeSblrDdlDropPublicationDescriptorV1(v);if(e.size()!=320||!std::equal(e.begin(),e.end(),b)){if(d)*d="SLDP hash invalid";return false;}*o=v;return true;}
std::vector<std::uint8_t>EncodeSblrDdlDropPublicationResultV1(const SblrDdlDropPublicationResultV1&v){if(!nz(v.body))return{};auto o=h("SLRR");o.insert(o.end(),v.body.begin(),v.body.end());std::fill(o.begin()+8+116,o.begin()+8+148,0);auto d=sha("ScratchBird.SblrDdlDropPublicationResult.V1",o);std::copy(d.begin(),d.end(),o.begin()+8+116);return o;}
bool DecodeSblrDdlDropPublicationResultV1(const std::uint8_t*b,std::size_t n,SblrDdlDropPublicationResultV1*o,std::string*d){if(!o||!vh(b,n,"SLRR",192)){if(d)*d="SLRR invalid";return false;}SblrDdlDropPublicationResultV1 v;std::copy_n(b+8,184,v.body.begin());auto e=EncodeSblrDdlDropPublicationResultV1(v);if(e.size()!=192||!std::equal(e.begin(),e.end(),b)){if(d)*d="SLRR hash invalid";return false;}*o=v;return true;}
}
