#include "sblr_sec_alter_user_runtime.hpp"
#include <cstring>
namespace scratchbird::engine::sblr { namespace { void w16(std::vector<std::uint8_t>&b,size_t p,uint16_t v){b[p]=v;b[p+1]=v>>8;} void w32(std::vector<std::uint8_t>&b,size_t p,uint32_t v){for(int i=0;i<4;i++)b[p+i]=v>>(8*i);} void w64(std::vector<std::uint8_t>&b,size_t p,uint64_t v){for(int i=0;i<8;i++)b[p+i]=v>>(8*i);} uint16_t r16(const uint8_t*b,size_t p){return b[p]|uint16_t(b[p+1])<<8;} uint32_t r32(const uint8_t*b,size_t p){uint32_t v=0;for(int i=3;i>=0;i--)v=(v<<8)|b[p+i];return v;} uint64_t r64(const uint8_t*b,size_t p){uint64_t v=0;for(int i=7;i>=0;i--)v=(v<<8)|b[p+i];return v;} void cp(std::vector<uint8_t>&b,size_t p,const void*x,size_t n){std::memcpy(b.data()+p,x,n);} bool head(const uint8_t*p,size_t n,const char*m,size_t z,std::string*d){if(!p||n!=z){if(d)*d="size";return false;}if(std::memcmp(p,m,4)||r16(p,4)!=1||r16(p,6)!=z||r32(p,8)!=z||r32(p,12)!=0){if(d)*d="header";return false;}return true;} }
std::vector<uint8_t> EncodeSblrSecAlterUserRequestV1(const SblrSecAlterUserRequestV1&v){std::vector<uint8_t>b(64);cp(b,0,"SAUQ",4);w16(b,4,1);w16(b,6,64);w32(b,8,64);cp(b,16,v.receipt.data(),16);cp(b,32,v.frame.data(),16);w64(b,48,v.frame_generation);w64(b,56,v.occurrence);return b;}
bool DecodeSblrSecAlterUserRequestV1(const uint8_t*p,size_t n,SblrSecAlterUserRequestV1*o,std::string*d){if(!o||!head(p,n,"SAUQ",64,d))return false;std::memcpy(o->receipt.data(),p+16,16);std::memcpy(o->frame.data(),p+32,16);o->frame_generation=r64(p,48);o->occurrence=r64(p,56);return o->occurrence!=0;}
std::vector<uint8_t> EncodeSblrSecAlterUserDescriptorV1(const SblrSecAlterUserDescriptorV1&v,bool operand){std::vector<uint8_t>b(488);cp(b,0,operand?"SAUO":"SAUD",4);w16(b,4,1);w16(b,6,488);w32(b,8,488);cp(b,16,v.user_uuid.data(),16);w64(b,32,v.expected_generation);w64(b,40,v.option_mask);b[48]=v.authentication_method;b[49]=v.account_state;b[50]=v.password_present;b[51]=v.default_role_present;cp(b,56,v.password_digest.data(),32);cp(b,88,v.secret_evidence.data(),32);cp(b,120,v.default_role_uuid.data(),16);cp(b,136,v.security_snapshot_uuid.data(),16);cp(b,152,v.policy_snapshot_uuid.data(),16);w64(b,168,v.catalog_generation);w64(b,176,v.security_generation);cp(b,184,v.descriptor_evidence.data(),32);w64(b,216,v.availability);return b;}
bool DecodeSblrSecAlterUserDescriptorV1(const uint8_t*p,size_t n,SblrSecAlterUserDescriptorV1*o,std::string*d,bool operand){if(!o||!head(p,n,operand?"SAUO":"SAUD",488,d))return false;std::memcpy(o->user_uuid.data(),p+16,16);o->expected_generation=r64(p,32);o->option_mask=r64(p,40);o->authentication_method=p[48];o->account_state=p[49];o->password_present=p[50];o->default_role_present=p[51];std::memcpy(o->password_digest.data(),p+56,32);std::memcpy(o->secret_evidence.data(),p+88,32);std::memcpy(o->default_role_uuid.data(),p+120,16);std::memcpy(o->security_snapshot_uuid.data(),p+136,16);std::memcpy(o->policy_snapshot_uuid.data(),p+152,16);o->catalog_generation=r64(p,168);o->security_generation=r64(p,176);std::memcpy(o->descriptor_evidence.data(),p+184,32);o->availability=r64(p,216);return true;}
std::vector<uint8_t> EncodeSblrSecAlterUserResultV1(const SblrSecAlterUserResultV1&v){std::vector<uint8_t>b(320);cp(b,0,"SAUR",4);w16(b,4,1);w16(b,6,320);w32(b,8,320);b[16]=v.status;b[17]=v.publication_barrier;cp(b,24,v.user_uuid.data(),16);w64(b,40,v.generation);w64(b,48,v.security_generation);cp(b,56,v.effect_evidence.data(),32);w64(b,88,v.availability);return b;}
bool DecodeSblrSecAlterUserResultV1(const uint8_t*p,size_t n,SblrSecAlterUserResultV1*o,std::string*d){if(!o||!head(p,n,"SAUR",320,d))return false;o->status=p[16];o->publication_barrier=p[17];std::memcpy(o->user_uuid.data(),p+24,16);o->generation=r64(p,40);o->security_generation=r64(p,48);std::memcpy(o->effect_evidence.data(),p+56,32);o->availability=r64(p,88);return true;}}
