#include "engine/sblr/sblr_system_config_get_runtime.hpp"
#include <algorithm>
namespace scratchbird::engine::sblr { namespace { void p(std::vector<uint8_t>&o,uint64_t v,size_t n){for(size_t i=0;i<n;i++)o.push_back(uint8_t(v>>(8*i)));} uint64_t g(const uint8_t*b,size_t n){uint64_t v=0;for(size_t i=0;i<n;i++)v|=uint64_t(b[i])<<(8*i);return v;} template<class T>bool nz(const T&a){return std::any_of(a.begin(),a.end(),[](auto v){return v!=0;});} bool h(const uint8_t*b,size_t n,const char*m,size_t z){return b&&n==z&&std::equal(b,b+4,m)&&g(b+4,2)==1&&g(b+6,2)==8;} }
std::vector<uint8_t> EncodeSblrSystemConfigGetRequestV1(const SblrSystemConfigGetRequestV1&v){if(!nz(v.operation)||!nz(v.receipt))return{};std::vector<uint8_t>o={'S','C','G','Q'};p(o,1,2);p(o,8,2);p(o,7543,4);p(o,530,4);o.insert(o.end(),v.operation.begin(),v.operation.end());o.insert(o.end(),v.receipt.begin(),v.receipt.end());o.insert(o.end(),16,0);return o;}
bool DecodeSblrSystemConfigGetRequestV1(const uint8_t*b,size_t n,SblrSystemConfigGetRequestV1*out,std::string*d){if(!out||!h(b,n,"SCGQ",64)){if(d)*d="SCGQ invalid";return false;}std::copy_n(b+16,16,out->operation.begin());std::copy_n(b+32,16,out->receipt.begin());return true;}
std::vector<uint8_t> EncodeSblrSystemConfigGetDescriptorV1(const SblrSystemConfigGetDescriptorV1&v){if(!nz(v.operation)||!nz(v.receipt)||!nz(v.scope)||!v.scope_generation||!nz(v.snapshot)||!v.snapshot_generation||!nz(v.projection)||!nz(v.redaction_policy)||!v.policy_generation||!nz(v.security_context)||!nz(v.transaction)||!nz(v.route_evidence))return{};std::vector<uint8_t>o={'S','L','G','C'};p(o,1,2);p(o,8,2);o.insert(o.end(),v.operation.begin(),v.operation.end());o.insert(o.end(),v.receipt.begin(),v.receipt.end());o.insert(o.end(),v.scope.begin(),v.scope.end());p(o,v.scope_generation,8);o.insert(o.end(),v.snapshot.begin(),v.snapshot.end());p(o,v.snapshot_generation,8);o.insert(o.end(),v.projection.begin(),v.projection.end());o.insert(o.end(),v.redaction_policy.begin(),v.redaction_policy.end());p(o,v.policy_generation,8);o.insert(o.end(),v.security_context.begin(),v.security_context.end());o.insert(o.end(),v.transaction.begin(),v.transaction.end());o.insert(o.end(),v.route_evidence.begin(),v.route_evidence.end());o.insert(o.end(),72,0);o.resize(256);return o;}
bool DecodeSblrSystemConfigGetDescriptorV1(const uint8_t*b,size_t n,SblrSystemConfigGetDescriptorV1*out,std::string*d){if(!out||!h(b,n,"SLGC",256)){if(d)*d="SLGC invalid";return false;}std::copy_n(b+8,16,out->operation.begin());std::copy_n(b+24,16,out->receipt.begin());std::copy_n(b+40,16,out->scope.begin());out->scope_generation=g(b+56,8);std::copy_n(b+64,16,out->snapshot.begin());out->snapshot_generation=g(b+80,8);std::copy_n(b+88,16,out->projection.begin());std::copy_n(b+104,16,out->redaction_policy.begin());out->policy_generation=g(b+120,8);std::copy_n(b+136,16,out->security_context.begin());std::copy_n(b+152,16,out->transaction.begin());std::copy_n(b+168,16,out->route_evidence.begin());return true;}
std::vector<uint8_t> EncodeSblrSystemConfigGetResultV1(const SblrSystemConfigGetResultV1&v){if(!nz(v.operation)||!nz(v.scope)||!v.scope_generation||!nz(v.snapshot)||!v.snapshot_generation||v.status<1||v.status>2||!nz(v.evidence)||!nz(v.recovery_evidence))return{};std::vector<uint8_t>o={'S','L','G','R'};p(o,1,2);p(o,8,2);o.insert(o.end(),v.operation.begin(),v.operation.end());o.insert(o.end(),v.scope.begin(),v.scope.end());p(o,v.scope_generation,8);o.insert(o.end(),v.snapshot.begin(),v.snapshot.end());p(o,v.snapshot_generation,8);p(o,v.redaction_class,4);p(o,v.status,4);o.insert(o.end(),v.evidence.begin(),v.evidence.end());o.insert(o.end(),32,0);o.insert(o.end(),v.recovery_evidence.begin(),v.recovery_evidence.end());p(o,v.projection_length,4);o.insert(o.end(),v.projection.begin(),v.projection.end());o.resize(512);return o;}
bool DecodeSblrSystemConfigGetResultV1(const uint8_t*b,size_t n,SblrSystemConfigGetResultV1*out,std::string*d){if(!out||!h(b,n,"SLGR",512)){if(d)*d="SLGR invalid";return false;}std::copy_n(b+8,16,out->operation.begin());std::copy_n(b+24,16,out->scope.begin());out->scope_generation=g(b+40,8);std::copy_n(b+48,16,out->snapshot.begin());out->snapshot_generation=g(b+64,8);out->redaction_class=g(b+72,4);out->status=g(b+76,4);std::copy_n(b+80,16,out->evidence.begin());std::copy_n(b+128,16,out->recovery_evidence.begin());out->projection_length=g(b+144,4);std::copy_n(b+148,284,out->projection.begin());return true;}
}
