#include "sblr_ddl_drop_function_runtime.hpp"
#include <algorithm>
#include <cstring>
namespace scratchbird::engine::sblr { namespace { template<class A> bool nz(const A&a){for(auto x:a)if(x)return true;return false;} void put(std::vector<std::uint8_t>&o,std::uint64_t v,int n){for(int i=0;i<n;i++)o.push_back((v>>(8*i))&255);} std::uint64_t get(const std::uint8_t*p,int n){std::uint64_t v=0;for(int i=0;i<n;i++)v|=std::uint64_t(p[i])<<(8*i);return v;} std::vector<std::uint8_t> hdr(const char*m,std::size_t n){std::vector<std::uint8_t>o(m,m+4);o.push_back(1);o.push_back(0);put(o,n,2);return o;} bool valid(const std::uint8_t*b,std::size_t n,const char*m,std::size_t z){return b&&n==z&&!std::memcmp(b,m,4)&&b[4]==1&&b[5]==0&&get(b+6,2)==z;} DdlDropFunctionSha hash(const std::uint8_t*p,std::size_t n){DdlDropFunctionSha h{};for(std::size_t i=0;i<n;i++)h[i%32]=std::uint8_t(h[i%32]*33u+p[i]);return h;} }
std::vector<std::uint8_t> EncodeSblrDdlDropFunctionRequestV1(const SblrDdlDropFunctionRequestV1&v){if(!nz(v.receipt)||!v.occurrence||!v.function_occurrence)return{};auto o=hdr("FDQX",64);o.insert(o.end(),8,0);o.insert(o.end(),v.receipt.begin(),v.receipt.end());put(o,v.occurrence,8);put(o,v.function_occurrence,4);o.insert(o.end(),20,0);return o;}
bool DecodeSblrDdlDropFunctionRequestV1(const std::uint8_t*b,std::size_t n,SblrDdlDropFunctionRequestV1*o,std::string*d){if(!o||!valid(b,n,"FDQX",64)||std::any_of(b+44,b+64,[](auto x){return x;})){if(d)*d="FDQX invalid";return false;}std::copy_n(b+16,16,o->receipt.begin());o->occurrence=get(b+32,8);o->function_occurrence=get(b+40,4);return o->occurrence&&o->function_occurrence;}
std::vector<std::uint8_t> EncodeSblrDdlDropFunctionDescriptorV1(const SblrDdlDropFunctionDescriptorV1&v,bool operand){if(!nz(v.body)||!v.availability)return{};auto o=hdr(operand?"FDDO":"FDDX",488);o.insert(o.end(),8,0);o.insert(o.end(),v.body.begin(),v.body.end());auto e=hash(o.data()+16,400);if(nz(v.evidence)&&e!=v.evidence)return{};o.insert(o.end(),e.begin(),e.end());put(o,v.availability,8);o.insert(o.end(),32,0);return o;}
bool DecodeSblrDdlDropFunctionDescriptorV1(const std::uint8_t*b,std::size_t n,SblrDdlDropFunctionDescriptorV1*o,std::string*d,bool operand){if(!o||!valid(b,n,operand?"FDDO":"FDDX",488)||std::any_of(b+456,b+488,[](auto x){return x;})){if(d)*d="FDD invalid";return false;}std::copy_n(b+16,400,o->body.begin());std::copy_n(b+416,32,o->evidence.begin());o->availability=get(b+448,8);return o->availability&&nz(o->evidence);}
std::vector<std::uint8_t> EncodeSblrDdlDropFunctionResultV1(const SblrDdlDropFunctionResultV1&v){if(!nz(v.body)||!v.availability||!nz(v.publication_barrier))return{};auto o=hdr("FDRS",320);o.insert(o.end(),8,0);o.insert(o.end(),v.body.begin(),v.body.end());auto e=hash(o.data()+16,240);if(nz(v.evidence)&&e!=v.evidence)return{};o.insert(o.end(),e.begin(),e.end());put(o,v.availability,8);o.insert(o.end(),v.publication_barrier.begin(),v.publication_barrier.end());o.insert(o.end(),8,0);return o;}
bool DecodeSblrDdlDropFunctionResultV1(const std::uint8_t*b,std::size_t n,SblrDdlDropFunctionResultV1*o,std::string*d){if(!o||!valid(b,n,"FDRS",320)||std::any_of(b+312,b+320,[](auto x){return x;})){if(d)*d="FDRS invalid";return false;}std::copy_n(b+16,240,o->body.begin());std::copy_n(b+256,32,o->evidence.begin());o->availability=get(b+288,8);std::copy_n(b+296,16,o->publication_barrier.begin());return o->availability&&nz(o->evidence)&&nz(o->publication_barrier);}
}
