#include "sblr_savepoint_runtime.hpp"
#include "hash_digest.hpp"
#include <algorithm>
#include <string_view>
namespace scratchbird::engine::sblr{namespace{void p16(std::vector<std::uint8_t>&o,unsigned v){o.push_back(v);o.push_back(v>>8);}void p32(std::vector<std::uint8_t>&o,unsigned v){for(int i=0;i<4;i++)o.push_back(v>>(8*i));}void p64(std::vector<std::uint8_t>&o,std::uint64_t v){for(int i=0;i<8;i++)o.push_back(v>>(8*i));}unsigned u16(const std::uint8_t*p){return unsigned(p[0])|(unsigned(p[1])<<8);}unsigned u32(const std::uint8_t*p){unsigned v=0;for(int i=0;i<4;i++)v|=unsigned(p[i])<<(8*i);return v;}std::uint64_t u64(const std::uint8_t*p){std::uint64_t v=0;for(int i=0;i<8;i++)v|=std::uint64_t(p[i])<<(8*i);return v;}template<class A>void put(std::vector<std::uint8_t>&o,const A&a){o.insert(o.end(),a.begin(),a.end());}template<class A>bool nz(const A&a){return std::any_of(a.begin(),a.end(),[](auto x){return x;});}SpSha h(std::string_view d,const std::uint8_t*p,size_t n){std::vector<std::uint8_t>x(d.begin(),d.end());x.insert(x.end(),p,p+n);return scratchbird::core::hash::ComputeSha256Digest(x).digest;}template<class A>void get(const std::uint8_t*p,A&a){std::copy_n(p,a.size(),a.begin());}}
std::vector<std::uint8_t> EncodeSblrSavepointDescriptorV1(const SblrSavepointDescriptorV1&v){if(!nz(v.descriptor_uuid)||!v.descriptor_generation||!nz(v.savepoint_uuid)||!v.savepoint_generation||!nz(v.transaction_uuid)||!v.local_transaction_id||!v.transaction_ordinal||!nz(v.descriptor_evidence_sha256))return{};std::vector<std::uint8_t>o{'S','P','D','O'};p16(o,1);p16(o,128);p32(o,128);p32(o,0);put(o,v.descriptor_uuid);p64(o,v.descriptor_generation);put(o,v.savepoint_uuid);p64(o,v.savepoint_generation);put(o,v.transaction_uuid);p64(o,v.local_transaction_id);p64(o,v.transaction_ordinal);put(o,v.descriptor_evidence_sha256);return o;}
bool DecodeSblrSavepointDescriptorV1(const std::uint8_t*b,std::size_t n,SblrSavepointDescriptorV1*out,std::string*d){if(!b||!out||n!=128||!std::equal(b,b+4,"SPDO")||b[4]!=1||std::any_of(b+12,b+16,[](auto x){return x;})){if(d)*d="SPDO invalid";return false;}SblrSavepointDescriptorV1 v;get(b+16,v.descriptor_uuid);v.descriptor_generation=u64(b+32);get(b+40,v.savepoint_uuid);v.savepoint_generation=u64(b+56);get(b+64,v.transaction_uuid);v.local_transaction_id=u64(b+80);v.transaction_ordinal=u64(b+88);get(b+96,v.descriptor_evidence_sha256);if(EncodeSblrSavepointDescriptorV1(v).empty())return false;*out=v;return true;}
std::vector<std::uint8_t> EncodeSblrSavepointHandleV1(const SblrSavepointHandleV1&v){if(!nz(v.savepoint_uuid)||!v.savepoint_generation||!nz(v.transaction_uuid)||!v.local_transaction_id||!v.transaction_ordinal||!v.stack_generation||v.lifecycle_state!=1||!v.executor_availability_generation)return{};std::vector<std::uint8_t>o{'S','P','H','D'};p16(o,1);p16(o,144);p32(o,144);p32(o,0);put(o,v.savepoint_uuid);p64(o,v.savepoint_generation);put(o,v.transaction_uuid);p64(o,v.local_transaction_id);p64(o,v.transaction_ordinal);p64(o,v.stack_generation);o.push_back(1);o.insert(o.end(),7,0);auto e=h("ScratchBird.SblrSavepointHandle.V1",o.data(),o.size());if(nz(v.savepoint_evidence_sha256)&&v.savepoint_evidence_sha256!=e)return{};put(o,e);p64(o,v.executor_availability_generation);o.insert(o.end(),16,0);return o;}
bool DecodeSblrSavepointHandleV1(const std::uint8_t*b,std::size_t n,SblrSavepointHandleV1*out,std::string*d){if(!b||!out||n!=144||!std::equal(b,b+4,"SPHD")||b[4]!=1||std::any_of(b+12,b+16,[](auto x){return x;})||std::any_of(b+81,b+88,[](auto x){return x;})||std::any_of(b+128,b+144,[](auto x){return x;})){if(d)*d="SPHD invalid";return false;}SblrSavepointHandleV1 v;get(b+16,v.savepoint_uuid);v.savepoint_generation=u64(b+32);get(b+40,v.transaction_uuid);v.local_transaction_id=u64(b+56);v.transaction_ordinal=u64(b+64);v.stack_generation=u64(b+72);v.lifecycle_state=b[80];get(b+88,v.savepoint_evidence_sha256);v.executor_availability_generation=u64(b+120);if(EncodeSblrSavepointHandleV1(v).empty())return false;*out=v;return true;}}
namespace scratchbird::engine::sblr {
std::vector<std::uint8_t> EncodeSblrSavepointReleaseOperandV1(const SblrSavepointReleaseOperandV1&v){if(!nz(v.savepoint_uuid)||!v.savepoint_generation||!nz(v.transaction_uuid)||!v.local_transaction_id||!v.transaction_ordinal||!v.admitted_stack_generation||!nz(v.admitted_savepoint_evidence_sha256)||!v.executor_availability_generation)return{};std::vector<std::uint8_t>o{'S','P','R','L'};p16(o,1);p16(o,128);p32(o,128);p32(o,0);put(o,v.savepoint_uuid);p64(o,v.savepoint_generation);put(o,v.transaction_uuid);p64(o,v.local_transaction_id);p64(o,v.transaction_ordinal);p64(o,v.admitted_stack_generation);put(o,v.admitted_savepoint_evidence_sha256);p64(o,v.executor_availability_generation);o.insert(o.end(),8,0);return o;}
bool DecodeSblrSavepointReleaseOperandV1(const std::uint8_t*b,std::size_t n,SblrSavepointReleaseOperandV1*out,std::string*d){if(!b||!out||n!=128||!std::equal(b,b+4,"SPRL")||u16(b+4)!=1||u16(b+6)!=128||u32(b+8)!=128||std::any_of(b+12,b+16,[](auto x){return x;})||std::any_of(b+120,b+128,[](auto x){return x;})){if(d)*d="SPRL invalid";return false;}SblrSavepointReleaseOperandV1 v;get(b+16,v.savepoint_uuid);v.savepoint_generation=u64(b+32);get(b+40,v.transaction_uuid);v.local_transaction_id=u64(b+56);v.transaction_ordinal=u64(b+64);v.admitted_stack_generation=u64(b+72);get(b+80,v.admitted_savepoint_evidence_sha256);v.executor_availability_generation=u64(b+112);if(EncodeSblrSavepointReleaseOperandV1(v).empty())return false;*out=v;return true;}
std::vector<std::uint8_t> EncodeSblrSavepointReleaseResultV1(const SblrSavepointReleaseResultV1&v){if(!nz(v.transaction_uuid)||!v.local_transaction_id||!nz(v.released_savepoint_uuid)||!v.released_savepoint_generation||!v.transaction_ordinal||!v.resulting_stack_generation||!v.executor_availability_generation)return{};std::vector<std::uint8_t>o{'S','P','R','R'};p16(o,1);p16(o,120);p32(o,120);p32(o,0);put(o,v.transaction_uuid);p64(o,v.local_transaction_id);put(o,v.released_savepoint_uuid);p64(o,v.released_savepoint_generation);p64(o,v.transaction_ordinal);p64(o,v.resulting_stack_generation);auto e=h("ScratchBird.SblrSavepointReleaseResult.V1",o.data(),o.size());if(nz(v.release_evidence_sha256)&&v.release_evidence_sha256!=e)return{};put(o,e);p64(o,v.executor_availability_generation);return o;}
bool DecodeSblrSavepointReleaseResultV1(const std::uint8_t*b,std::size_t n,SblrSavepointReleaseResultV1*out,std::string*d){if(!b||!out||n!=120||!std::equal(b,b+4,"SPRR")||u16(b+4)!=1||u16(b+6)!=120||u32(b+8)!=120||std::any_of(b+12,b+16,[](auto x){return x;})){if(d)*d="SPRR invalid";return false;}SblrSavepointReleaseResultV1 v;get(b+16,v.transaction_uuid);v.local_transaction_id=u64(b+32);get(b+40,v.released_savepoint_uuid);v.released_savepoint_generation=u64(b+56);v.transaction_ordinal=u64(b+64);v.resulting_stack_generation=u64(b+72);get(b+80,v.release_evidence_sha256);v.executor_availability_generation=u64(b+112);if(EncodeSblrSavepointReleaseResultV1(v).empty())return false;*out=v;return true;}}
namespace scratchbird::engine::sblr {
std::vector<std::uint8_t> EncodeSblrSavepointRollbackOperandV1(const SblrSavepointRollbackOperandV1&v){SblrSavepointReleaseOperandV1 x;x.savepoint_uuid=v.savepoint_uuid;x.savepoint_generation=v.savepoint_generation;x.transaction_uuid=v.transaction_uuid;x.local_transaction_id=v.local_transaction_id;x.transaction_ordinal=v.transaction_ordinal;x.admitted_stack_generation=v.admitted_stack_generation;x.admitted_savepoint_evidence_sha256=v.admitted_savepoint_evidence_sha256;x.executor_availability_generation=v.executor_availability_generation;auto o=EncodeSblrSavepointReleaseOperandV1(x);if(o.empty())return{};o[2]='R';o[3]='O';return o;}
bool DecodeSblrSavepointRollbackOperandV1(const std::uint8_t*b,std::size_t n,SblrSavepointRollbackOperandV1*out,std::string*d){if(!b||n!=128||!std::equal(b,b+4,"SPRO")){if(d)*d="SPRO invalid";return false;}auto x=std::vector<std::uint8_t>(b,b+n);x[2]='R';x[3]='L';SblrSavepointReleaseOperandV1 v;if(!DecodeSblrSavepointReleaseOperandV1(x.data(),x.size(),&v,d))return false;out->savepoint_uuid=v.savepoint_uuid;out->savepoint_generation=v.savepoint_generation;out->transaction_uuid=v.transaction_uuid;out->local_transaction_id=v.local_transaction_id;out->transaction_ordinal=v.transaction_ordinal;out->admitted_stack_generation=v.admitted_stack_generation;out->admitted_savepoint_evidence_sha256=v.admitted_savepoint_evidence_sha256;out->executor_availability_generation=v.executor_availability_generation;return true;}
std::vector<std::uint8_t> EncodeSblrSavepointRollbackResultV1(const SblrSavepointRollbackResultV1&v){if(!nz(v.transaction_uuid)||!v.local_transaction_id||!nz(v.target_savepoint_uuid)||!v.target_savepoint_generation||!v.transaction_ordinal||!v.resulting_stack_generation||!v.rollback_sequence||v.target_lifecycle_state!=1||!nz(v.refreshed_savepoint_evidence_sha256)||!v.executor_availability_generation)return{};std::vector<std::uint8_t>o{'S','P','R','B'};p16(o,1);p16(o,168);p32(o,168);p32(o,0);put(o,v.transaction_uuid);p64(o,v.local_transaction_id);put(o,v.target_savepoint_uuid);p64(o,v.target_savepoint_generation);p64(o,v.transaction_ordinal);p64(o,v.resulting_stack_generation);p64(o,v.rollback_sequence);o.push_back(1);o.insert(o.end(),7,0);put(o,v.refreshed_savepoint_evidence_sha256);auto e=h("ScratchBird.SblrSavepointRollbackResult.V1",o.data(),o.size());if(nz(v.rollback_evidence_sha256)&&v.rollback_evidence_sha256!=e)return{};put(o,e);p64(o,v.executor_availability_generation);return o;}
bool DecodeSblrSavepointRollbackResultV1(const std::uint8_t*b,std::size_t n,SblrSavepointRollbackResultV1*out,std::string*d){if(!b||!out||n!=168||!std::equal(b,b+4,"SPRB")||u16(b+4)!=1||u16(b+6)!=168||u32(b+8)!=168||std::any_of(b+12,b+16,[](auto x){return x;})||std::any_of(b+89,b+96,[](auto x){return x;})){if(d)*d="SPRB invalid";return false;}SblrSavepointRollbackResultV1 v;get(b+16,v.transaction_uuid);v.local_transaction_id=u64(b+32);get(b+40,v.target_savepoint_uuid);v.target_savepoint_generation=u64(b+56);v.transaction_ordinal=u64(b+64);v.resulting_stack_generation=u64(b+72);v.rollback_sequence=u64(b+80);v.target_lifecycle_state=b[88];get(b+96,v.refreshed_savepoint_evidence_sha256);get(b+128,v.rollback_evidence_sha256);v.executor_availability_generation=u64(b+160);if(EncodeSblrSavepointRollbackResultV1(v).empty())return false;*out=v;return true;}}

namespace scratchbird::engine::sblr {
std::vector<std::uint8_t> EncodeSblrSavepointCoordinationRequestV1(const SblrSavepointCoordinationRequestV1&v){if(!nz(v.preliminary_receipt_uuid)||!nz(v.transaction_uuid)||!v.local_transaction_id||!nz(v.transaction_handle_evidence_sha256)||!v.symbol_occurrence_id||!nz(v.canonical_symbol_sha256))return{};std::vector<std::uint8_t>o{'S','P','C','R'};p16(o,1);p16(o,128);p32(o,128);p32(o,0);put(o,v.preliminary_receipt_uuid);put(o,v.transaction_uuid);p64(o,v.local_transaction_id);put(o,v.transaction_handle_evidence_sha256);p64(o,v.symbol_occurrence_id);put(o,v.canonical_symbol_sha256);return o;}
bool DecodeSblrSavepointCoordinationRequestV1(const std::uint8_t*b,std::size_t n,SblrSavepointCoordinationRequestV1*out,std::string*d){if(!b||!out||n!=128||!std::equal(b,b+4,"SPCR")||u16(b+4)!=1||u16(b+6)!=128||u32(b+8)!=128||std::any_of(b+12,b+16,[](auto x){return x;})){if(d)*d="SPCR invalid";return false;}SblrSavepointCoordinationRequestV1 v;get(b+16,v.preliminary_receipt_uuid);get(b+32,v.transaction_uuid);v.local_transaction_id=u64(b+48);get(b+56,v.transaction_handle_evidence_sha256);v.symbol_occurrence_id=u64(b+88);get(b+96,v.canonical_symbol_sha256);if(EncodeSblrSavepointCoordinationRequestV1(v).empty())return false;*out=v;return true;}
std::vector<std::uint8_t> EncodeSblrSavepointCoordinationResultV1(const SblrSavepointCoordinationResultV1&v){if(!nz(v.preliminary_receipt_uuid)||!nz(v.descriptor_uuid)||!v.descriptor_generation||!nz(v.savepoint_uuid)||!v.savepoint_generation||!v.transaction_ordinal||!v.symbol_occurrence_id||!nz(v.canonical_symbol_sha256))return{};std::vector<std::uint8_t>o{'S','P','C','D'};p16(o,1);p16(o,160);p32(o,160);p32(o,0);put(o,v.preliminary_receipt_uuid);put(o,v.descriptor_uuid);p64(o,v.descriptor_generation);put(o,v.savepoint_uuid);p64(o,v.savepoint_generation);p64(o,v.transaction_ordinal);p64(o,v.symbol_occurrence_id);put(o,v.canonical_symbol_sha256);auto e=h("ScratchBird.SblrSavepointCoordination.V1",o.data(),o.size());if(nz(v.descriptor_evidence_sha256)&&v.descriptor_evidence_sha256!=e)return{};put(o,e);return o;}
bool DecodeSblrSavepointCoordinationResultV1(const std::uint8_t*b,std::size_t n,SblrSavepointCoordinationResultV1*out,std::string*d){if(!b||!out||n!=160||!std::equal(b,b+4,"SPCD")||u16(b+4)!=1||u16(b+6)!=160||u32(b+8)!=160||std::any_of(b+12,b+16,[](auto x){return x;})){if(d)*d="SPCD invalid";return false;}SblrSavepointCoordinationResultV1 v;get(b+16,v.preliminary_receipt_uuid);get(b+32,v.descriptor_uuid);v.descriptor_generation=u64(b+48);get(b+56,v.savepoint_uuid);v.savepoint_generation=u64(b+72);v.transaction_ordinal=u64(b+80);v.symbol_occurrence_id=u64(b+88);get(b+96,v.canonical_symbol_sha256);get(b+128,v.descriptor_evidence_sha256);if(EncodeSblrSavepointCoordinationResultV1(v).empty())return false;*out=v;return true;}
}
