#include "sblr_sec_create_group_mapping_runtime.hpp"
#include <cstring>
namespace scratchbird::engine::sblr { namespace { void w16(std::vector<uint8_t>&b,size_t o,uint16_t v){b[o]=v;b[o+1]=v>>8;} void w32(std::vector<uint8_t>&b,size_t o,uint32_t v){for(int i=0;i<4;i++)b[o+i]=v>>(8*i);} void w64(std::vector<uint8_t>&b,size_t o,uint64_t v){for(int i=0;i<8;i++)b[o+i]=v>>(8*i);} uint64_t r64(const uint8_t*p,size_t o){uint64_t v=0;for(int i=0;i<8;i++)v|=uint64_t(p[o+i])<<(8*i);return v;} void cp(std::vector<uint8_t>&b,size_t o,const void*p,size_t n){std::memcpy(b.data()+o,p,n);} bool nz(const uint8_t*p,size_t n){for(size_t i=0;i<n;i++)if(p[i])return true;return false;} bool head(const uint8_t*p,size_t n,const char*m,size_t z,std::string*d){if(!p||n!=z||std::memcmp(p,m,4)||p[4]!=1||p[6]!=z||((uint32_t(p[8])|(uint32_t(p[9])<<8)|(uint32_t(p[10])<<16)|(uint32_t(p[11])<<24))!=z)){if(d)*d="SGM fixed-size header invalid";return false;}return true;} }
std::vector<uint8_t> EncodeSblrSecCreateGroupMappingRequestV1(const SblrSecCreateGroupMappingRequestV1&v){if(!nz(v.receipt.data(),16)||!v.occurrence)return{};std::vector<uint8_t>b(64);cp(b,0,"SGMQ",4);w16(b,4,1);w16(b,6,64);w32(b,8,64);cp(b,16,v.receipt.data(),16);w64(b,32,v.occurrence);return b;}
bool DecodeSblrSecCreateGroupMappingRequestV1(const uint8_t*p,size_t n,SblrSecCreateGroupMappingRequestV1*o,std::string*d){if(!o||!head(p,n,"SGMQ",64,d)||!nz(p+16,16)||!r64(p,32))return false;std::memcpy(o->receipt.data(),p+16,16);o->occurrence=r64(p,32);return true;}
std::vector<uint8_t> EncodeSblrSecCreateGroupMappingDescriptorV1(const SblrSecCreateGroupMappingDescriptorV1&v,bool op){if(!nz(v.group_uuid.data(),16)||!nz(v.principal_uuid.data(),16)||!v.generation||!v.security_generation||!v.availability)return{};std::vector<uint8_t>b(128);cp(b,0,op?"SGMO":"SGMD",4);w16(b,4,1);w16(b,6,128);w32(b,8,128);cp(b,16,v.group_uuid.data(),16);cp(b,32,v.principal_uuid.data(),16);w64(b,48,v.generation);w64(b,56,v.security_generation);w64(b,64,v.availability);cp(b,72,v.descriptor_evidence.data(),16);return b;}
bool DecodeSblrSecCreateGroupMappingDescriptorV1(const uint8_t*p,size_t n,SblrSecCreateGroupMappingDescriptorV1*o,std::string*d,bool op){if(!o||!head(p,n,op?"SGMO":"SGMD",128,d)||!nz(p+16,32)||!r64(p,48)||!r64(p,56)||!r64(p,64)||!nz(p+72,16))return false;std::memcpy(o->group_uuid.data(),p+16,16);std::memcpy(o->principal_uuid.data(),p+32,16);o->generation=r64(p,48);o->security_generation=r64(p,56);o->availability=r64(p,64);std::memcpy(o->descriptor_evidence.data(),p+72,16);return true;}
std::vector<uint8_t> EncodeSblrSecCreateGroupMappingResultV1(const SblrSecCreateGroupMappingResultV1&v){if(!nz(v.group_uuid.data(),16)||!nz(v.principal_uuid.data(),16)||!v.generation||!v.security_generation||!v.availability||!v.status||!v.publication_barrier)return{};std::vector<uint8_t>b(128);cp(b,0,"SGMR",4);w16(b,4,1);w16(b,6,128);w32(b,8,128);b[16]=v.status;b[17]=v.publication_barrier;cp(b,24,v.group_uuid.data(),16);cp(b,40,v.principal_uuid.data(),16);w64(b,56,v.generation);w64(b,64,v.security_generation);w64(b,72,v.availability);cp(b,80,v.effect_evidence.data(),32);return b;}
bool DecodeSblrSecCreateGroupMappingResultV1(const uint8_t*p,size_t n,SblrSecCreateGroupMappingResultV1*o,std::string*d){if(!o||!head(p,n,"SGMR",128,d)||!p[16]||!p[17]||!nz(p+24,32)||!r64(p,56)||!r64(p,64)||!r64(p,72)||!nz(p+80,32))return false;o->status=p[16];o->publication_barrier=p[17];std::memcpy(o->group_uuid.data(),p+24,16);std::memcpy(o->principal_uuid.data(),p+40,16);o->generation=r64(p,56);o->security_generation=r64(p,64);o->availability=r64(p,72);std::memcpy(o->effect_evidence.data(),p+80,32);return true;}
}
