#include "sblr_admin_register_external_relation_resolver_runtime.hpp"
#include <algorithm>
#include <cstring>
namespace scratchbird::engine::sblr { namespace { template<class A> bool nonzero(const A&a){for(auto x:a)if(x)return true;return false;} void put(std::vector<std::uint8_t>&o,std::uint64_t v,int n){for(int i=0;i<n;++i)o.push_back(std::uint8_t(v>>(8*i)));} std::uint64_t get(const std::uint8_t*b,int n){std::uint64_t v=0;for(int i=0;i<n;++i)v|=std::uint64_t(b[i])<<(8*i);return v;} std::vector<std::uint8_t> head(const char*m,int n){std::vector<std::uint8_t>o(m,m+4);o.push_back(1);o.push_back(0);put(o,n,2);o.insert(o.end(),8,0);return o;} bool valid(const std::uint8_t*b,std::size_t n,const char*m,int z){return b&&n==std::size_t(z)&&!std::memcmp(b,m,4)&&b[4]==1&&b[5]==0&&get(b+6,2)==std::size_t(z)&&std::all_of(b+8,b+16,[](auto x){return !x;});} std::array<std::uint8_t,32> digest(const std::uint8_t*b,std::size_t n){std::array<std::uint8_t,32> a{};for(std::size_t i=0;i<n;++i)a[i%32]=std::uint8_t(a[i%32]*33u+b[i]);return a;} }
std::vector<std::uint8_t> EncodeSblrAdminRegisterExternalRelationResolverRequestV1(const SblrAdminRegisterExternalRelationResolverRequestV1&x){if(!nonzero(x.receipt)||!x.occurrence||!x.resolver_occurrence)return{};auto o=head("ERRQ",64);o.insert(o.end(),x.receipt.begin(),x.receipt.end());put(o,x.occurrence,8);put(o,x.resolver_occurrence,4);o.insert(o.end(),20,0);return o;}
bool DecodeSblrAdminRegisterExternalRelationResolverRequestV1(const std::uint8_t*b,std::size_t n,SblrAdminRegisterExternalRelationResolverRequestV1*x,std::string*q){if(!x||!valid(b,n,"ERRQ",64)){if(q)*q="ERRQ invalid";return false;}std::copy_n(b+16,16,x->receipt.begin());x->occurrence=get(b+32,8);x->resolver_occurrence=get(b+40,4);return x->occurrence&&x->resolver_occurrence;}
std::vector<std::uint8_t> EncodeSblrAdminRegisterExternalRelationResolverDescriptorV1(const SblrAdminRegisterExternalRelationResolverDescriptorV1&x,bool operand){if(!nonzero(x.body)||!x.availability)return{};auto o=head(operand?"ERDO":"ERDD",488);o.insert(o.end(),x.body.begin(),x.body.end());auto e=digest(o.data()+16,400);if(nonzero(x.evidence)&&e!=x.evidence)return{};o.insert(o.end(),e.begin(),e.end());put(o,x.availability,8);o.insert(o.end(),32,0);return o;}
bool DecodeSblrAdminRegisterExternalRelationResolverDescriptorV1(const std::uint8_t*b,std::size_t n,SblrAdminRegisterExternalRelationResolverDescriptorV1*x,std::string*q,bool operand){if(!x||!valid(b,n,operand?"ERDO":"ERDD",488)||std::any_of(b+456,b+488,[](auto v){return v;})){if(q)*q="ERDO/ERDD invalid";return false;}std::copy_n(b+16,400,x->body.begin());std::copy_n(b+416,32,x->evidence.begin());x->availability=get(b+448,8);return x->availability&&nonzero(x->evidence);}
std::vector<std::uint8_t> EncodeSblrAdminRegisterExternalRelationResolverResultV1(const SblrAdminRegisterExternalRelationResolverResultV1&x){if(!nonzero(x.body)||!x.availability||!nonzero(x.publication_barrier))return{};auto o=head("ERRS",320);o.insert(o.end(),x.body.begin(),x.body.end());auto e=digest(o.data()+16,248);if(nonzero(x.evidence)&&e!=x.evidence)return{};o.insert(o.end(),e.begin(),e.end());put(o,x.availability,8);o.insert(o.end(),x.publication_barrier.begin(),x.publication_barrier.end());return o;}
bool DecodeSblrAdminRegisterExternalRelationResolverResultV1(const std::uint8_t*b,std::size_t n,SblrAdminRegisterExternalRelationResolverResultV1*x,std::string*q){if(!x||!valid(b,n,"ERRS",320)){if(q)*q="ERRS invalid";return false;}std::copy_n(b+16,248,x->body.begin());std::copy_n(b+264,32,x->evidence.begin());x->availability=get(b+296,8);std::copy_n(b+304,16,x->publication_barrier.begin());return x->availability&&nonzero(x->evidence)&&nonzero(x->publication_barrier);}
}
