#include "sblr_ddl_drop_continuous_view_runtime.hpp"
#include <cstring>
namespace scratchbird::engine::sblr {
std::vector<std::uint8_t> EncodeSblrDdlDropContinuousViewRequestV1(const SblrDdlDropContinuousViewRequestV1&v){auto b=EncodeSblrDdlCreateContinuousViewRequestV1(v);if(b.size()>=4)std::memcpy(b.data(),"DVRQ",4);return b;}
bool DecodeSblrDdlDropContinuousViewRequestV1(const std::uint8_t*p,std::size_t n,SblrDdlDropContinuousViewRequestV1*o,std::string*d){if(!p||n!=64||!o||std::memcmp(p,"DVRQ",4)!=0){if(d)*d="request magic";return false;}std::memcpy(o->receipt.data(),p+16,16);auto get=[&](std::size_t off){std::uint64_t v=0;for(int i=0;i<8;i++)v|=std::uint64_t(p[off+i])<<(i*8);return v;};o->occurrence=get(32);o->view_occurrence=get(40);return o->occurrence&&o->view_occurrence;}
std::vector<std::uint8_t> EncodeSblrDdlDropContinuousViewDescriptorV1(const SblrDdlDropContinuousViewDescriptorV1&v,bool operand){auto b=EncodeSblrDdlCreateContinuousViewDescriptorV1(v,operand);if(b.size()>=4)std::memcpy(b.data(),operand?"DVDO":"DVDD",4);return b;}
bool DecodeSblrDdlDropContinuousViewDescriptorV1(const std::uint8_t*p,std::size_t n,SblrDdlDropContinuousViewDescriptorV1*o,std::string*d,bool operand){if(!p||n!=488||!o||std::memcmp(p,operand?"DVDO":"DVDD",4)!=0){if(d)*d="descriptor magic";return false;}std::memcpy(o->body.data()+16,p+16,400);std::memcpy(o->evidence.data(),p+416,32);std::uint64_t v=0;for(int i=0;i<8;i++)v|=std::uint64_t(p[448+i])<<(i*8);o->availability=v;return o->availability!=0;}
std::vector<std::uint8_t> EncodeSblrDdlDropContinuousViewResultV1(const SblrDdlDropContinuousViewResultV1&v){auto b=EncodeSblrDdlCreateContinuousViewResultV1(v);if(b.size()>=4)std::memcpy(b.data(),"DVRS",4);return b;}
bool DecodeSblrDdlDropContinuousViewResultV1(const std::uint8_t*p,std::size_t n,SblrDdlDropContinuousViewResultV1*o,std::string*d){if(!p||n!=320||!o||std::memcmp(p,"DVRS",4)!=0){if(d)*d="result magic";return false;}std::memcpy(o->body.data(),p+16,240);std::memcpy(o->evidence.data(),p+256,32);std::uint64_t v=0;for(int i=0;i<8;i++)v|=std::uint64_t(p[288+i])<<(i*8);o->availability=v;std::memcpy(o->publication_barrier.data(),p+296,16);return o->availability!=0;}
}
