#include "sblr_sec_create_policy_runtime.hpp"
#include <cstring>
namespace scratchbird::engine::sblr { static void w16(std::vector<uint8_t>&b,size_t o,uint16_t v){b[o]=v;b[o+1]=v>>8;} static void w32(std::vector<uint8_t>&b,size_t o,uint32_t v){for(int i=0;i<4;i++)b[o+i]=v>>(8*i);} static void w64(std::vector<uint8_t>&b,size_t o,uint64_t v){for(int i=0;i<8;i++)b[o+i]=v>>(8*i);} static uint64_t r64(const uint8_t*p,size_t o){uint64_t v=0;for(int i=0;i<8;i++)v|=uint64_t(p[o+i])<<(8*i);return v;} static void cp(std::vector<uint8_t>&b,size_t o,const void*p,size_t n){std::memcpy(b.data()+o,p,n);} static bool head(const uint8_t*p,size_t n,const char*m,size_t z,std::string*d){if(!p||n!=z||std::memcmp(p,m,4)||p[4]!=1||p[6]!=z||(uint32_t(p[8])|(uint32_t(p[9])<<8)|(uint32_t(p[10])<<16)|(uint32_t(p[11])<<24))!=z){if(d)*d="SCP fixed-size header invalid";return false;}return true;}
std::vector<uint8_t> EncodeSblrSecCreatePolicyRequestV1(const SblrSecCreatePolicyRequestV1&v){std::vector<uint8_t>b(64);cp(b,0,"SCPQ",4);w16(b,4,1);w16(b,6,64);w32(b,8,64);cp(b,16,v.receipt.data(),16);w64(b,32,v.occurrence);return b;}
bool DecodeSblrSecCreatePolicyRequestV1(const uint8_t*p,size_t n,SblrSecCreatePolicyRequestV1*o,std::string*d){if(!head(p,n,"SCPQ",64,d))return false;std::memcpy(o->receipt.data(),p+16,16);o->occurrence=r64(p,32);return o->occurrence!=0;}
std::vector<uint8_t> EncodeSblrSecCreatePolicyDescriptorV1(const SblrSecCreatePolicyDescriptorV1&v,bool op){std::vector<uint8_t>b(488);cp(b,0,op?"SCPO":"SCPD",4);w16(b,4,1);w16(b,6,488);w32(b,8,488);cp(b,16,v.body.data(),400);cp(b,416,v.evidence.data(),32);w64(b,448,v.expected_generation);w64(b,456,v.catalog_generation);w64(b,464,v.security_generation);w64(b,472,v.availability);return b;}
bool DecodeSblrSecCreatePolicyDescriptorV1(const uint8_t*p,size_t n,SblrSecCreatePolicyDescriptorV1*o,std::string*d,bool op){if(!head(p,n,op?"SCPO":"SCPD",488,d))return false;std::memcpy(o->body.data(),p+16,400);std::memcpy(o->evidence.data(),p+416,32);o->expected_generation=r64(p,448);o->catalog_generation=r64(p,456);o->security_generation=r64(p,464);o->availability=r64(p,472);return o->availability!=0;}
std::vector<uint8_t> EncodeSblrSecCreatePolicyResultV1(const SblrSecCreatePolicyResultV1&v){std::vector<uint8_t>b(64);cp(b,0,"SCPR",4);w16(b,4,1);w16(b,6,64);w32(b,8,64);b[16]=v.status;b[17]=v.publication_barrier;w64(b,24,v.generation);w64(b,32,v.security_generation);w64(b,40,v.availability);cp(b,48,v.effect_evidence.data(),16);return b;}
bool DecodeSblrSecCreatePolicyResultV1(const uint8_t*p,size_t n,SblrSecCreatePolicyResultV1*o,std::string*d){if(!head(p,n,"SCPR",64,d))return false;o->status=p[16];o->publication_barrier=p[17];o->generation=r64(p,24);o->security_generation=r64(p,32);o->availability=r64(p,40);std::memcpy(o->effect_evidence.data(),p+48,16);return true;}}
