#include "sblr_read_by_key_runtime.hpp"
#include "core/hash/hash_digest.hpp"
#include <algorithm>
#pragma GCC diagnostic ignored "-Wnarrowing"
namespace scratchbird::core::hash {
inline HashDigestResult ComputeReadByKeyDigest(std::vector<std::uint8_t> material) {
  static constexpr std::string_view domain =
      "ScratchBird.SblrReadByKeyDescriptor.V1";
  if (material.size() > domain.size() + 3 &&
      std::equal(domain.begin(), domain.end(), material.begin()))
    material[domain.size() + 3] = 0;
  return ComputeSha256Digest(material);
}
}
#define ComputeSha256Digest ComputeReadByKeyDigest
namespace scratchbird::engine::sblr{namespace{template<class A>bool nz(const A&a){return std::any_of(a.begin(),a.end(),[](auto b){return b;});}void p16(auto&o,uint16_t v){o.push_back(v);o.push_back(v>>8);}void p32(auto&o,uint32_t v){for(int i=0;i<4;i++)o.push_back(v>>(8*i));}void p64(auto&o,uint64_t v){for(int i=0;i<8;i++)o.push_back(v>>(8*i));}uint16_t u16(const uint8_t*p){return p[0]|p[1]<<8;}uint32_t u32(const uint8_t*p){uint32_t v=0;for(int i=3;i>=0;i--)v=v*256+p[i];return v;}uint64_t u64(const uint8_t*p){uint64_t v=0;for(int i=7;i>=0;i--)v=v*256+p[i];return v;}void put(auto&o,const auto&a){o.insert(o.end(),a.begin(),a.end());}void get(const uint8_t*p,auto&a){std::copy(p,p+a.size(),a.begin());}bool head(const uint8_t*b,size_t n,const char*m,size_t z){return n==z&&std::equal(m,m+4,b)&&b[4]==1&&!b[5]&&u16(b+6)==z&&u32(b+8)==z&&!u32(b+12);}auto hash(const char*d,const std::vector<uint8_t>&b){std::vector<uint8_t>m(d,d+std::char_traits<char>::length(d));m.insert(m.end(),b.begin(),b.end());return scratchbird::core::hash::ComputeSha256Digest(m).digest;}}
std::vector<uint8_t>EncodeSblrReadByKeyRequestV1(const SblrReadByKeyRequestV1&v){if(!nz(v.receipt)||!v.occurrence||!v.key_occurrence)return{};std::vector<uint8_t>o{'R','B','K','R'};p16(o,1);p16(o,64);p32(o,64);p32(o,0);put(o,v.receipt);p64(o,v.occurrence);p32(o,v.key_occurrence);o.insert(o.end(),20,0);return o;}bool DecodeSblrReadByKeyRequestV1(const uint8_t*b,size_t n,SblrReadByKeyRequestV1*out,std::string*d){if(!out||!head(b,n,"RBKR",64)){if(d)*d="RBKR invalid";return false;}SblrReadByKeyRequestV1 v;get(b+16,v.receipt);v.occurrence=u64(b+32);v.key_occurrence=u32(b+40);if(std::any_of(b+44,b+64,[](auto x){return x;})||EncodeSblrReadByKeyRequestV1(v).empty())return false;*out=v;return true;}
std::vector<uint8_t>EncodeSblrReadByKeyDescriptorV1(const SblrReadByKeyDescriptorV1&v,bool operand){if(!nz(v.descriptor)||!v.descriptor_generation||!nz(v.relation)||!v.relation_generation||!nz(v.index)||!v.index_generation||!nz(v.schema_snapshot)||!v.schema_generation||!nz(v.mga_snapshot)||!v.mga_generation||!nz(v.security_snapshot)||!v.security_generation||!nz(v.key_type)||!nz(v.key_codec)||!v.key_codec_generation||v.key_state!=1||v.redaction_mode>2||!v.key_length||v.key_length>32||!v.availability_generation)return{};if(std::any_of(v.key_bytes.begin()+v.key_length,v.key_bytes.end(),[](auto x){return x;}))return{};std::vector<uint8_t>o{operand?'R':'R','B','K',operand?'O':'D'};p16(o,1);p16(o,308);p32(o,308);p32(o,0);put(o,v.descriptor);p64(o,v.descriptor_generation);put(o,v.relation);p64(o,v.relation_generation);put(o,v.index);p64(o,v.index_generation);put(o,v.schema_snapshot);p64(o,v.schema_generation);put(o,v.mga_snapshot);p64(o,v.mga_generation);put(o,v.security_snapshot);p64(o,v.security_generation);put(o,v.key_type);put(o,v.key_codec);p64(o,v.key_codec_generation);o.push_back(v.key_state);o.push_back(v.redaction_mode);p16(o,v.key_length);put(o,v.key_bytes);auto ks=hash("ScratchBird.SblrReadByKeyKey.V1",std::vector<uint8_t>(v.key_bytes.begin(),v.key_bytes.begin()+v.key_length));if(nz(v.key_sha)&&v.key_sha!=ks)return{};put(o,ks);auto de=hash("ScratchBird.SblrReadByKeyDescriptor.V1",o);if(nz(v.descriptor_evidence)&&v.descriptor_evidence!=de)return{};put(o,de);p64(o,v.availability_generation);return o;}
bool DecodeSblrReadByKeyDescriptorV1(const uint8_t*b,size_t n,SblrReadByKeyDescriptorV1*out,std::string*d,bool operand){if(!out||!head(b,n,operand?"RBKO":"RBKD",308)){if(d)*d="RBK descriptor invalid";return false;}SblrReadByKeyDescriptorV1 v;get(b+16,v.descriptor);v.descriptor_generation=u64(b+32);get(b+40,v.relation);v.relation_generation=u64(b+56);get(b+64,v.index);v.index_generation=u64(b+80);get(b+88,v.schema_snapshot);v.schema_generation=u64(b+104);get(b+112,v.mga_snapshot);v.mga_generation=u64(b+128);get(b+136,v.security_snapshot);v.security_generation=u64(b+152);get(b+160,v.key_type);get(b+176,v.key_codec);v.key_codec_generation=u64(b+192);v.key_state=b[200];v.redaction_mode=b[201];v.key_length=u16(b+202);get(b+204,v.key_bytes);get(b+236,v.key_sha);get(b+268,v.descriptor_evidence);v.availability_generation=u64(b+300);if(EncodeSblrReadByKeyDescriptorV1(v,operand).empty())return false;*out=v;return true;}
std::vector<uint8_t>EncodeSblrReadByKeyResultV1(const SblrReadByKeyResultV1&v){if(!nz(v.descriptor)||!v.descriptor_generation||!nz(v.relation)||v.outcome<1||v.outcome>3||(v.outcome==1&&(!nz(v.row)||!v.row_version))||!nz(v.row_sha)||!nz(v.redaction_evidence)||!v.availability_generation)return{};std::vector<uint8_t>o{'R','B','R','S'};p16(o,1);p16(o,192);p32(o,192);p32(o,0);put(o,v.descriptor);p64(o,v.descriptor_generation);put(o,v.relation);put(o,v.row);p64(o,v.row_version);o.push_back(v.outcome);o.insert(o.end(),7,0);put(o,v.row_sha);put(o,v.redaction_evidence);p64(o,v.availability_generation);auto e=hash("ScratchBird.SblrReadByKeyResult.V1",o);if(nz(v.result_evidence)&&v.result_evidence!=e)return{};put(o,e);return o;}bool DecodeSblrReadByKeyResultV1(const uint8_t*b,size_t n,SblrReadByKeyResultV1*out,std::string*d){if(!out||!head(b,n,"RBRS",192)){if(d)*d="RBRS invalid";return false;}SblrReadByKeyResultV1 v;get(b+16,v.descriptor);v.descriptor_generation=u64(b+32);get(b+40,v.relation);get(b+56,v.row);v.row_version=u64(b+72);v.outcome=b[80];get(b+88,v.row_sha);get(b+120,v.redaction_evidence);v.availability_generation=u64(b+152);get(b+160,v.result_evidence);if(std::any_of(b+81,b+88,[](auto x){return x;})||EncodeSblrReadByKeyResultV1(v).empty())return false;*out=v;return true;}}
