#include "sblr_dml_async_insert_status_runtime.hpp"
#include <cstring>
namespace scratchbird::engine::sblr { namespace { void put(std::vector<std::uint8_t>& b,std::size_t o,std::uint64_t v){for(int i=0;i<8;i++)b[o+i]=std::uint8_t(v>>(i*8));} std::uint64_t get(const std::uint8_t*p,std::size_t o){std::uint64_t v=0;for(int i=0;i<8;i++)v|=std::uint64_t(p[o+i])<<(i*8);return v;} bool ok(const std::uint8_t*p,std::size_t n,const char*m,std::size_t z,std::string*d){if(!p||n!=z||std::memcmp(p,m,4)!=0){if(d)*d="status wire invalid";return false;}return true;} }
std::vector<std::uint8_t> EncodeSblrDmlAsyncInsertStatusRequestV1(const SblrDmlAsyncInsertStatusRequestV1&v){std::vector<std::uint8_t>b(64);std::memcpy(b.data(),"AITQ",4);std::memcpy(b.data()+16,v.receipt.data(),16);put(b,32,v.occurrence);put(b,40,v.status_occurrence);return b;}
bool DecodeSblrDmlAsyncInsertStatusRequestV1(const std::uint8_t*p,std::size_t n,SblrDmlAsyncInsertStatusRequestV1*o,std::string*d){if(!o||!ok(p,n,"AITQ",64,d))return false;std::memcpy(o->receipt.data(),p+16,16);o->occurrence=get(p,32);o->status_occurrence=get(p,40);return o->occurrence&&o->status_occurrence;}
std::vector<std::uint8_t> EncodeSblrDmlAsyncInsertStatusDescriptorV1(const SblrDmlAsyncInsertStatusDescriptorV1&v,bool operand){std::vector<std::uint8_t>b(488);std::memcpy(b.data(),operand?"AITO":"AITD",4);std::memcpy(b.data()+16,v.body.data(),400);std::memcpy(b.data()+416,v.evidence.data(),32);put(b,448,v.availability);return b;}
bool DecodeSblrDmlAsyncInsertStatusDescriptorV1(const std::uint8_t*p,std::size_t n,SblrDmlAsyncInsertStatusDescriptorV1*o,std::string*d,bool operand){if(!o||!ok(p,n,operand?"AITO":"AITD",488,d))return false;std::memcpy(o->body.data(),p+16,400);std::memcpy(o->evidence.data(),p+416,32);o->availability=get(p,448);return o->availability!=0;}
std::vector<std::uint8_t> EncodeSblrDmlAsyncInsertStatusResultV1(const SblrDmlAsyncInsertStatusResultV1&v){std::vector<std::uint8_t>b(320);std::memcpy(b.data(),"AITR",4);std::memcpy(b.data()+16,v.body.data(),240);std::memcpy(b.data()+256,v.evidence.data(),32);put(b,288,v.availability);std::memcpy(b.data()+296,v.publication_barrier.data(),16);return b;}
bool DecodeSblrDmlAsyncInsertStatusResultV1(const std::uint8_t*p,std::size_t n,SblrDmlAsyncInsertStatusResultV1*o,std::string*d){if(!o||!ok(p,n,"AITR",320,d))return false;std::memcpy(o->body.data(),p+16,240);std::memcpy(o->evidence.data(),p+256,32);o->availability=get(p,288);std::memcpy(o->publication_barrier.data(),p+296,16);return o->availability!=0;}
}
