#include "sblr_ddl_drop_timeseries_value_cache_runtime.hpp"
#include <cstring>
namespace scratchbird::engine::sblr { namespace { void put(std::vector<std::uint8_t>&v,std::size_t o,const void*p,std::size_t n){std::memcpy(v.data()+o,p,n);} bool zero(const std::uint8_t*p,std::size_t n){for(std::size_t i=0;i<n;i++)if(p[i])return false;return true;} }
std::vector<std::uint8_t> EncodeSblrDdlDropTimeseriesValueCacheRequestV1(const SblrDdlDropTimeseriesValueCacheRequestV1&q){std::vector<std::uint8_t>v(64,0);std::memcpy(v.data(),"VARQ",4);v[4]=1;put(v,16,q.receipt.data(),16);put(v,32,&q.occurrence,8);put(v,40,&q.cache_occurrence,8);return v;}
bool DecodeSblrDdlDropTimeseriesValueCacheRequestV1(const std::uint8_t*p,std::size_t n,SblrDdlDropTimeseriesValueCacheRequestV1*q,std::string*d){if(n!=64||std::memcmp(p,"VARQ",4)||p[4]!=1||!zero(p+48,16)){if(d)*d="invalid_request";return false;}std::memcpy(q->receipt.data(),p+16,16);std::memcpy(&q->occurrence,p+32,8);std::memcpy(&q->cache_occurrence,p+40,8);return q->occurrence&&q->cache_occurrence;}
std::vector<std::uint8_t> EncodeSblrDdlDropTimeseriesValueCacheDescriptorV1(const SblrDdlDropTimeseriesValueCacheDescriptorV1&q,bool operand){std::vector<std::uint8_t>v(488,0);std::memcpy(v.data(),operand?"VDOO":"VDDD",4);v[4]=1;put(v,16,q.body.data(),400);put(v,408,q.evidence.data(),32);put(v,440,&q.availability,8);return v;}
bool DecodeSblrDdlDropTimeseriesValueCacheDescriptorV1(const std::uint8_t*p,std::size_t n,SblrDdlDropTimeseriesValueCacheDescriptorV1*q,std::string*d,bool operand){if(n!=488||std::memcmp(p,operand?"VDOO":"VDDD",4)||p[4]!=1||!zero(p+448,40)){if(d)*d="invalid_descriptor";return false;}std::memcpy(q->body.data(),p+16,400);std::memcpy(q->evidence.data(),p+408,32);std::memcpy(&q->availability,p+440,8);return q->availability!=0;}
std::vector<std::uint8_t> EncodeSblrDdlDropTimeseriesValueCacheResultV1(const SblrDdlDropTimeseriesValueCacheResultV1&q){std::vector<std::uint8_t>v(320,0);std::memcpy(v.data(),"VDRR",4);v[4]=1;put(v,16,q.body.data(),240);put(v,256,q.evidence.data(),32);put(v,288,&q.availability,8);put(v,296,q.publication_barrier.data(),16);return v;}
bool DecodeSblrDdlDropTimeseriesValueCacheResultV1(const std::uint8_t*p,std::size_t n,SblrDdlDropTimeseriesValueCacheResultV1*q,std::string*d){if(n!=320||std::memcmp(p,"VDRR",4)||p[4]!=1||!zero(p+312,8)||!p[296]){if(d)*d="invalid_result";return false;}std::memcpy(q->body.data(),p+16,240);std::memcpy(q->evidence.data(),p+256,32);std::memcpy(&q->availability,p+288,8);std::memcpy(q->publication_barrier.data(),p+296,16);return q->availability!=0;}
}

