#include "sblr_dml_async_insert_submit_runtime.hpp"
#include <cstring>
namespace scratchbird::engine::sblr { namespace { void put(std::vector<std::uint8_t>&b,std::size_t o,std::uint64_t v){for(int i=0;i<8;i++)b[o+i]=std::uint8_t(v>>(i*8));} std::uint64_t get(const std::uint8_t*p,std::size_t o){std::uint64_t v=0;for(int i=0;i<8;i++)v|=std::uint64_t(p[o+i])<<(i*8);return v;} }
std::vector<std::uint8_t> EncodeSblrDmlAsyncInsertSubmitRequestV1(const SblrDmlAsyncInsertSubmitRequestV1&v){std::vector<std::uint8_t>b(64);std::memcpy(b.data(),"AISQ",4);std::memcpy(b.data()+16,v.receipt.data(),16);put(b,32,v.occurrence);put(b,40,v.submission_occurrence);return b;}
bool DecodeSblrDmlAsyncInsertSubmitRequestV1(const std::uint8_t*p,std::size_t n,SblrDmlAsyncInsertSubmitRequestV1*o,std::string*d){if(!p||n!=64||!o||std::memcmp(p,"AISQ",4)!=0){if(d)*d="request invalid";return false;}std::memcpy(o->receipt.data(),p+16,16);o->occurrence=get(p,32);o->submission_occurrence=get(p,40);return o->occurrence&&o->submission_occurrence;}
std::vector<std::uint8_t> EncodeSblrDmlAsyncInsertSubmitDescriptorV1(const SblrDmlAsyncInsertSubmitDescriptorV1&v,bool operand){std::vector<std::uint8_t>b(488);std::memcpy(b.data(),operand?"AIDO":"AIDD",4);std::memcpy(b.data()+16,v.body.data(),400);std::memcpy(b.data()+416,v.evidence.data(),32);put(b,448,v.availability);return b;}
bool DecodeSblrDmlAsyncInsertSubmitDescriptorV1(const std::uint8_t*p,std::size_t n,SblrDmlAsyncInsertSubmitDescriptorV1*o,std::string*d,bool operand){if(!p||n!=488||!o||std::memcmp(p,operand?"AIDO":"AIDD",4)!=0){if(d)*d="descriptor invalid";return false;}std::memcpy(o->body.data(),p+16,400);std::memcpy(o->evidence.data(),p+416,32);o->availability=get(p,448);return o->availability!=0;}
std::vector<std::uint8_t> EncodeSblrDmlAsyncInsertSubmitResultV1(const SblrDmlAsyncInsertSubmitResultV1&v){std::vector<std::uint8_t>b(320);std::memcpy(b.data(),"AIRS",4);std::memcpy(b.data()+16,v.body.data(),240);std::memcpy(b.data()+256,v.evidence.data(),32);put(b,288,v.availability);std::memcpy(b.data()+296,v.publication_barrier.data(),16);return b;}
bool DecodeSblrDmlAsyncInsertSubmitResultV1(const std::uint8_t*p,std::size_t n,SblrDmlAsyncInsertSubmitResultV1*o,std::string*d){if(!p||n!=320||!o||std::memcmp(p,"AIRS",4)!=0){if(d)*d="result invalid";return false;}std::memcpy(o->body.data(),p+16,240);std::memcpy(o->evidence.data(),p+256,32);o->availability=get(p,288);std::memcpy(o->publication_barrier.data(),p+296,16);return o->availability!=0;}
}
