#include "sblr_error_vector_runtime.hpp"
#include "hash_digest.hpp"
#include <algorithm>
#include <string_view>
namespace scratchbird::engine::sblr {namespace{
void P16(std::vector<std::uint8_t>*o,std::uint16_t v){o->push_back(v);o->push_back(v>>8);}void P32(std::vector<std::uint8_t>*o,std::uint32_t v){for(int i=0;i<4;++i)o->push_back(v>>(8*i));}void P64(std::vector<std::uint8_t>*o,std::uint64_t v){for(int i=0;i<8;++i)o->push_back(v>>(8*i));}std::uint16_t U16(const std::uint8_t*p){return p[0]|std::uint16_t(p[1])<<8;}std::uint32_t U32(const std::uint8_t*p){std::uint32_t v=0;for(int i=0;i<4;++i)v|=std::uint32_t(p[i])<<(8*i);return v;}std::uint64_t U64(const std::uint8_t*p){std::uint64_t v=0;for(int i=0;i<8;++i)v|=std::uint64_t(p[i])<<(8*i);return v;}template<class A>void Put(std::vector<std::uint8_t>*o,const A&a){o->insert(o->end(),a.begin(),a.end());}template<class A>void Get(const std::uint8_t*p,A*a){std::copy_n(p,a->size(),a->begin());}template<class A>bool Nz(const A&a){return std::any_of(a.begin(),a.end(),[](auto x){return x;});}SblrErrorSha256V1 H(std::string_view d,const std::vector<std::uint8_t>&b){std::vector<std::uint8_t>m(d.begin(),d.end());m.insert(m.end(),b.begin(),b.end());return scratchbird::core::hash::ComputeSha256Digest(m).digest;}
bool Shape(const SblrErrorVectorEntryV1&e,std::uint64_t n){return e.occurrence_ordinal==n&&e.precedence_ordinal==n&&Nz(e.diagnostic_uuid)&&e.diagnostic_generation&&e.severity_code>=1&&e.severity_code<=4&&e.redaction_class<=4&&Nz(e.safe_fields_sha256);}
std::vector<std::uint8_t> EB(SblrErrorVectorEntryV1*e){std::vector<std::uint8_t>o;P64(&o,e->occurrence_ordinal);Put(&o,e->diagnostic_uuid);P64(&o,e->diagnostic_generation);P32(&o,e->precedence_ordinal);o.push_back(e->severity_code);o.push_back(e->redaction_class);P16(&o,0);P32(&o,e->safe_field_count);P32(&o,0);Put(&o,e->safe_fields_sha256);e->entry_sha256=H("ScratchBird.SblrErrorVectorEntry.V1",o);Put(&o,e->entry_sha256);o.resize(128,0);return o;}
bool DE(const std::uint8_t*p,std::uint64_t n,SblrErrorVectorEntryV1*e){e->occurrence_ordinal=U64(p);Get(p+8,&e->diagnostic_uuid);e->diagnostic_generation=U64(p+24);e->precedence_ordinal=U32(p+32);e->severity_code=p[36];e->redaction_class=p[37];e->safe_field_count=U32(p+40);Get(p+48,&e->safe_fields_sha256);Get(p+80,&e->entry_sha256);if(U16(p+38)||U32(p+44)||std::any_of(p+112,p+128,[](auto x){return x;})||!Shape(*e,n))return false;auto c=*e;EB(&c);return c.entry_sha256==e->entry_sha256;}
}
std::vector<std::uint8_t> EncodeSblrErrorVectorDescriptorV1(SblrErrorVectorDescriptorV1*v){if(!v||v->entries.empty()||v->entries.size()>4096||!Nz(v->descriptor_uuid)||!v->descriptor_generation||!Nz(v->registry_snapshot_uuid)||!v->registry_generation||!Nz(v->statement_receipt_uuid)||!Nz(v->diagnostic_registry_snapshot_uuid)||!v->diagnostic_registry_generation)return{};std::vector<std::uint8_t>r;for(size_t i=0;i<v->entries.size();++i){if(!Shape(v->entries[i],i+1))return{};auto b=EB(&v->entries[i]);r.insert(r.end(),b.begin(),b.end());}v->vector_sha256=H("ScratchBird.SblrErrorVectorDescriptorVector.V1",r);std::vector<std::uint8_t>o{'E','R','V','D'};P16(&o,1);P16(&o,152);P32(&o,152+r.size());P32(&o,0);Put(&o,v->descriptor_uuid);P64(&o,v->descriptor_generation);Put(&o,v->registry_snapshot_uuid);P64(&o,v->registry_generation);Put(&o,v->statement_receipt_uuid);Put(&o,v->diagnostic_registry_snapshot_uuid);P64(&o,v->diagnostic_registry_generation);P32(&o,v->entries.size());P32(&o,128);Put(&o,v->vector_sha256);P64(&o,0);o.insert(o.end(),r.begin(),r.end());return o;}
bool DecodeSblrErrorVectorDescriptorV1(const std::uint8_t*b,std::size_t z,SblrErrorVectorDescriptorV1*out,std::string*d){if(!b||!out||z<152||z>524440||!std::equal(b,b+4,"ERVD")||U16(b+4)!=1||U16(b+6)!=152||U32(b+8)!=z||U32(b+12)||U32(b+108)!=128||U64(b+144)){if(d)*d="ERVD header invalid";return false;}auto n=U32(b+104);if(!n||n>4096||152+std::uint64_t(n)*128!=z)return false;SblrErrorVectorDescriptorV1 v;Get(b+16,&v.descriptor_uuid);v.descriptor_generation=U64(b+32);Get(b+40,&v.registry_snapshot_uuid);v.registry_generation=U64(b+56);Get(b+64,&v.statement_receipt_uuid);Get(b+80,&v.diagnostic_registry_snapshot_uuid);v.diagnostic_registry_generation=U64(b+96);Get(b+112,&v.vector_sha256);for(std::uint32_t i=0;i<n;++i){SblrErrorVectorEntryV1 e;if(!DE(b+152+i*128,i+1,&e))return false;v.entries.push_back(e);}auto c=v;auto x=EncodeSblrErrorVectorDescriptorV1(&c);if(x.size()!=z||!std::equal(x.begin(),x.end(),b))return false;*out=std::move(v);return true;}
std::vector<std::uint8_t> EncodeSblrErrorVectorIssueRequestV1(SblrErrorVectorIssueRequestV1*v){if(!v||v->entries.empty()||v->entries.size()>4096||!Nz(v->statement_receipt_uuid)||!Nz(v->registry_snapshot_uuid)||!v->registry_generation||!Nz(v->diagnostic_registry_snapshot_uuid)||!v->diagnostic_registry_generation)return{};std::vector<std::uint8_t>r;for(size_t i=0;i<v->entries.size();++i){if(!Shape(v->entries[i],i+1))return{};auto b=EB(&v->entries[i]);r.insert(r.end(),b.begin(),b.end());}v->entries_sha256=H("ScratchBird.SblrErrorVectorIssueRequest.V1",r);std::vector<std::uint8_t>o{'E','V','R','Q'};P16(&o,1);P16(&o,120);P32(&o,120+r.size());P32(&o,0);Put(&o,v->statement_receipt_uuid);Put(&o,v->registry_snapshot_uuid);P64(&o,v->registry_generation);Put(&o,v->diagnostic_registry_snapshot_uuid);P64(&o,v->diagnostic_registry_generation);P32(&o,v->entries.size());P32(&o,128);Put(&o,v->entries_sha256);o.insert(o.end(),r.begin(),r.end());return o;}
bool DecodeSblrErrorVectorIssueRequestV1(const std::uint8_t*b,std::size_t z,SblrErrorVectorIssueRequestV1*out,std::string*d){if(!b||!out||z<120||z>524408||!std::equal(b,b+4,"EVRQ")||U16(b+4)!=1||U16(b+6)!=120||U32(b+8)!=z||U32(b+12)||U32(b+84)!=128)return false;auto n=U32(b+80);if(!n||n>4096||120+std::uint64_t(n)*128!=z)return false;SblrErrorVectorIssueRequestV1 v;Get(b+16,&v.statement_receipt_uuid);Get(b+32,&v.registry_snapshot_uuid);v.registry_generation=U64(b+48);Get(b+56,&v.diagnostic_registry_snapshot_uuid);v.diagnostic_registry_generation=U64(b+72);Get(b+88,&v.entries_sha256);for(std::uint32_t i=0;i<n;++i){SblrErrorVectorEntryV1 e;if(!DE(b+120+i*128,i+1,&e))return false;v.entries.push_back(e);}auto c=v;auto x=EncodeSblrErrorVectorIssueRequestV1(&c);if(x.size()!=z||!std::equal(x.begin(),x.end(),b))return false;*out=std::move(v);return true;}
std::vector<std::uint8_t> EncodeSblrErrorVectorIssueResultV1(const SblrErrorVectorIssueResultV1&v){if(!Nz(v.descriptor_uuid)||!v.descriptor_generation||!v.registry_generation||v.canonical_ervd.empty()||64+v.canonical_ervd.size()>524504)return{};std::vector<std::uint8_t>o{'E','V','R','S'};P16(&o,1);P16(&o,64);P32(&o,64+v.canonical_ervd.size());P32(&o,0);Put(&o,v.descriptor_uuid);P64(&o,v.descriptor_generation);P64(&o,v.registry_generation);P32(&o,v.canonical_ervd.size());P32(&o,0);P64(&o,0);o.insert(o.end(),v.canonical_ervd.begin(),v.canonical_ervd.end());return o;}
bool DecodeSblrErrorVectorIssueResultV1(const std::uint8_t*b,std::size_t z,SblrErrorVectorIssueResultV1*out,std::string*d){if(!b||!out||z<64||z>524504||!std::equal(b,b+4,"EVRS")||U16(b+4)!=1||U16(b+6)!=64||U32(b+8)!=z||U32(b+12)||U32(b+52)||U64(b+56)||64+U32(b+48)!=z)return false;SblrErrorVectorIssueResultV1 v;Get(b+16,&v.descriptor_uuid);v.descriptor_generation=U64(b+32);v.registry_generation=U64(b+40);v.canonical_ervd.assign(b+64,b+z);SblrErrorVectorDescriptorV1 x;if(!DecodeSblrErrorVectorDescriptorV1(v.canonical_ervd.data(),v.canonical_ervd.size(),&x,d)||x.descriptor_uuid!=v.descriptor_uuid||x.descriptor_generation!=v.descriptor_generation||x.registry_generation!=v.registry_generation)return false;*out=std::move(v);return true;}
}
