#include "sblr_ddl_create_macro_runtime.hpp"
#include <algorithm>
#include <cstring>
namespace scratchbird::engine::sblr { namespace { template<class A>bool nz(const A&a){for(auto x:a)if(x)return true;return false;} void put(std::vector<std::uint8_t>&o,std::uint64_t v,int n){for(int i=0;i<n;++i)o.push_back(static_cast<std::uint8_t>(v>>(8*i)));} std::uint64_t get(const std::uint8_t*p,int n){std::uint64_t v=0;for(int i=0;i<n;++i)v|=std::uint64_t(p[i])<<(8*i);return v;} std::vector<std::uint8_t> h(const char*m,std::size_t n){std::vector<std::uint8_t>o(m,m+4);o.push_back(1);o.push_back(0);put(o,n,2);o.insert(o.end(),8,0);return o;} bool valid(const std::uint8_t*b,std::size_t n,const char*m,std::size_t z){return b&&n==z&&!std::memcmp(b,m,4)&&b[4]==1&&b[5]==0&&get(b+6,2)==z&&std::all_of(b+8,b+16,[](auto x){return x==0;});} std::array<std::uint8_t,32>d(const std::uint8_t*p,std::size_t n){std::array<std::uint8_t,32>a{};for(std::size_t i=0;i<n;++i)a[i%32]=std::uint8_t(a[i%32]*33u+p[i]);return a;} }
std::vector<std::uint8_t> EncodeSblrDdlCreateMacroRequestV1(const SblrDdlCreateMacroRequestV1&v){if(!nz(v.receipt)||!v.occurrence||!v.macro_occurrence)return{};auto o=h("MCRQ",64);o.insert(o.end(),v.receipt.begin(),v.receipt.end());put(o,v.occurrence,8);put(o,v.macro_occurrence,4);o.insert(o.end(),20,0);return o;}
bool DecodeSblrDdlCreateMacroRequestV1(const std::uint8_t*b,std::size_t n,SblrDdlCreateMacroRequestV1*o,std::string*x){if(!o||!valid(b,n,"MCRQ",64)){if(x)*x="MCRQ invalid";return false;}std::copy_n(b+16,16,o->receipt.begin());o->occurrence=get(b+32,8);o->macro_occurrence=get(b+40,4);return o->occurrence&&o->macro_occurrence;}
std::vector<std::uint8_t> EncodeSblrDdlCreateMacroDescriptorV1(const SblrDdlCreateMacroDescriptorV1&v,bool operand){if(!nz(v.body)||!v.availability)return{};auto o=h(operand?"MCRO":"MCDD",488);o.insert(o.end(),v.body.begin(),v.body.end());auto e=d(o.data()+16,400);if(nz(v.evidence)&&e!=v.evidence)return{};o.insert(o.end(),e.begin(),e.end());put(o,v.availability,8);o.insert(o.end(),32,0);return o;}
bool DecodeSblrDdlCreateMacroDescriptorV1(const std::uint8_t*b,std::size_t n,SblrDdlCreateMacroDescriptorV1*o,std::string*x,bool operand){if(!o||!valid(b,n,operand?"MCRO":"MCDD",488)||std::any_of(b+456,b+488,[](auto v){return v;})){if(x)*x="MCRO/MCDD invalid";return false;}std::copy_n(b+16,400,o->body.begin());std::copy_n(b+416,32,o->evidence.begin());o->availability=get(b+448,8);return o->availability&&nz(o->evidence);}
std::vector<std::uint8_t> EncodeSblrDdlCreateMacroResultV1(const SblrDdlCreateMacroResultV1&v){if(!nz(v.body)||!v.availability||!nz(v.publication_barrier))return{};auto o=h("MCRS",320);o.insert(o.end(),v.body.begin(),v.body.end());auto e=d(o.data()+16,248);if(nz(v.evidence)&&e!=v.evidence)return{};o.insert(o.end(),e.begin(),e.end());put(o,v.availability,8);o.insert(o.end(),v.publication_barrier.begin(),v.publication_barrier.end());return o;}
bool DecodeSblrDdlCreateMacroResultV1(const std::uint8_t*b,std::size_t n,SblrDdlCreateMacroResultV1*o,std::string*x){if(!o||!valid(b,n,"MCRS",320)){if(x)*x="MCRS invalid";return false;}std::copy_n(b+16,248,o->body.begin());std::copy_n(b+264,32,o->evidence.begin());o->availability=get(b+296,8);std::copy_n(b+304,16,o->publication_barrier.begin());return o->availability&&nz(o->evidence)&&nz(o->publication_barrier);}
}
