#include "sblr_transaction_rollback_runtime.hpp"
#include "hash_digest.hpp"
#include <algorithm>
#include <string_view>
namespace scratchbird::engine::sblr {namespace{void P16(std::vector<std::uint8_t>*o,std::uint16_t v){o->push_back(v);o->push_back(v>>8);}void P32(std::vector<std::uint8_t>*o,std::uint32_t v){for(int i=0;i<4;++i)o->push_back(v>>(8*i));}void P64(std::vector<std::uint8_t>*o,std::uint64_t v){for(int i=0;i<8;++i)o->push_back(v>>(8*i));}std::uint16_t U16(const std::uint8_t*p){return p[0]|std::uint16_t(p[1])<<8;}std::uint32_t U32(const std::uint8_t*p){std::uint32_t v=0;for(int i=0;i<4;++i)v|=std::uint32_t(p[i])<<(8*i);return v;}std::uint64_t U64(const std::uint8_t*p){std::uint64_t v=0;for(int i=0;i<8;++i)v|=std::uint64_t(p[i])<<(8*i);return v;}template<class A>void Put(std::vector<std::uint8_t>*o,const A&a){o->insert(o->end(),a.begin(),a.end());}template<class A>void Get(const std::uint8_t*p,A*a){std::copy_n(p,a->size(),a->begin());}template<class A>bool Nz(const A&a){return std::any_of(a.begin(),a.end(),[](auto x){return x;});}SblrTxnRollbackShaV1 H(std::string_view d,const std::uint8_t*p,size_t z){std::vector<std::uint8_t>m(d.begin(),d.end());m.insert(m.end(),p,p+z);return scratchbird::core::hash::ComputeSha256Digest(m).digest;}}
std::vector<std::uint8_t> EncodeSblrTransactionRollbackOptionsV1(SblrTransactionRollbackOptionsV1*v){if(!v||!Nz(v->transaction_uuid)||!v->local_transaction_id||!Nz(v->admitted_handle_evidence_sha256)||v->rollback_mode!=1||v->authority_scope<1||v->authority_scope>2||v->wait_policy<1||v->wait_policy>2)return{};std::vector<std::uint8_t>o{'T','X','R','O'};P16(&o,1);P16(&o,120);P32(&o,120);P32(&o,0);Put(&o,v->transaction_uuid);P64(&o,v->local_transaction_id);Put(&o,v->admitted_handle_evidence_sha256);o.push_back(v->rollback_mode);o.push_back(v->authority_scope);o.push_back(v->wait_policy);o.insert(o.end(),5,0);P64(&o,v->deadline_monotonic_ns);v->options_sha256=H("ScratchBird.SblrTransactionRollbackOptions.V1",o.data(),o.size());Put(&o,v->options_sha256);return o;}
bool DecodeSblrTransactionRollbackOptionsV1(const std::uint8_t*b,std::size_t z,SblrTransactionRollbackOptionsV1*out,std::string*d){if(!b||!out||z!=120||!std::equal(b,b+4,"TXRO")||U16(b+4)!=1||U16(b+6)!=120||U32(b+8)!=120||U32(b+12)||std::any_of(b+75,b+80,[](auto x){return x;})){if(d)*d="TXRO invalid";return false;}SblrTransactionRollbackOptionsV1 v;Get(b+16,&v.transaction_uuid);v.local_transaction_id=U64(b+32);Get(b+40,&v.admitted_handle_evidence_sha256);v.rollback_mode=b[72];v.authority_scope=b[73];v.wait_policy=b[74];v.deadline_monotonic_ns=U64(b+80);Get(b+88,&v.options_sha256);auto c=v;auto e=EncodeSblrTransactionRollbackOptionsV1(&c);if(e.size()!=z||!std::equal(e.begin(),e.end(),b))return false;*out=v;return true;}
std::vector<std::uint8_t> EncodeSblrTransactionRollbackResultV1(const SblrTransactionRollbackResultV1&v){if(!Nz(v.transaction_uuid)||!v.local_transaction_id||!v.rollback_sequence||!Nz(v.rollback_policy_snapshot_uuid)||!v.rollback_policy_generation||v.lifecycle_state!=3||v.authority_scope<1||v.authority_scope>2||!v.executor_availability_generation)return{};std::vector<std::uint8_t>o{'T','X','R','R'};P16(&o,1);P16(&o,120);P32(&o,120);P32(&o,0);Put(&o,v.transaction_uuid);P64(&o,v.local_transaction_id);P64(&o,v.rollback_sequence);Put(&o,v.rollback_policy_snapshot_uuid);P64(&o,v.rollback_policy_generation);o.push_back(v.lifecycle_state);o.push_back(v.authority_scope);o.insert(o.end(),6,0);auto h=H("ScratchBird.SblrTransactionRollbackResult.V1",o.data(),o.size());if(Nz(v.rollback_evidence_sha256)&&v.rollback_evidence_sha256!=h)return{};Put(&o,h);P64(&o,v.executor_availability_generation);return o;}
bool DecodeSblrTransactionRollbackResultV1(const std::uint8_t*b,std::size_t z,SblrTransactionRollbackResultV1*out,std::string*d){if(!b||!out||z!=120||!std::equal(b,b+4,"TXRR")||U16(b+4)!=1||U16(b+6)!=120||U32(b+8)!=120||U32(b+12)||std::any_of(b+74,b+80,[](auto x){return x;})){if(d)*d="TXRR invalid";return false;}SblrTransactionRollbackResultV1 v;Get(b+16,&v.transaction_uuid);v.local_transaction_id=U64(b+32);v.rollback_sequence=U64(b+40);Get(b+48,&v.rollback_policy_snapshot_uuid);v.rollback_policy_generation=U64(b+64);v.lifecycle_state=b[72];v.authority_scope=b[73];Get(b+80,&v.rollback_evidence_sha256);v.executor_availability_generation=U64(b+112);if(EncodeSblrTransactionRollbackResultV1(v).empty())return false;*out=v;return true;}}
