#include "sblr_ddl_drop_continuous_view_runtime.hpp"
#include "core/hash/hash_digest.hpp"
#include <algorithm>
#include <cstring>
namespace scratchbird::engine::sblr {
namespace { std::array<std::uint8_t,32> hash(const char*d,const std::uint8_t*p,std::size_t n){std::vector<std::uint8_t>x(d,d+std::strlen(d));x.insert(x.end(),p,p+n);std::array<std::uint8_t,32>h{};auto e=scratchbird::core::hash::ComputeSha256Digest(x);if(e.ok())std::copy(e.digest.begin(),e.digest.end(),h.begin());return h;} }
std::vector<std::uint8_t> EncodeSblrDdlDropContinuousViewRequestV1(const SblrDdlDropContinuousViewRequestV1&v){auto b=EncodeSblrDdlCreateContinuousViewRequestV1(v);if(b.size()>=4)std::memcpy(b.data(),"DVRQ",4);return b;}
bool DecodeSblrDdlDropContinuousViewRequestV1(const std::uint8_t*p,std::size_t n,SblrDdlDropContinuousViewRequestV1*o,std::string*d){if(!p||n!=64||!o||std::memcmp(p,"DVRQ",4)!=0){if(d)*d="request magic";return false;}std::memcpy(o->receipt.data(),p+16,16);auto get=[&](std::size_t off){std::uint64_t v=0;for(int i=0;i<8;i++)v|=std::uint64_t(p[off+i])<<(i*8);return v;};o->occurrence=get(32);o->view_occurrence=get(40);return o->occurrence&&o->view_occurrence;}
std::vector<std::uint8_t> EncodeSblrDdlDropContinuousViewDescriptorV1(const SblrDdlDropContinuousViewDescriptorV1&v,bool operand){auto base=v;base.evidence={};auto b=EncodeSblrDdlCreateContinuousViewDescriptorV1(base,operand);if(b.size()>=4){std::memcpy(b.data(),operand?"DVDO":"DVDD",4);auto e=hash("ScratchBird.SblrDdlDropContinuousViewDescriptor.V1",b.data()+16,400);std::copy(e.begin(),e.end(),b.begin()+416);}return b;}
bool DecodeSblrDdlDropContinuousViewDescriptorV1(const std::uint8_t*p,std::size_t n,SblrDdlDropContinuousViewDescriptorV1*o,std::string*d,bool operand){if(!p||n!=488||!o||std::memcmp(p,operand?"DVDO":"DVDD",4)!=0){if(d)*d="descriptor magic";return false;}auto b=std::vector<std::uint8_t>(p,p+n);std::uint32_t cm=operand?0x4356444fu:0x43564444u;std::memcpy(b.data(),&cm,4);auto ce=hash("ScratchBird.SblrDdlCreateContinuousViewDescriptor.V1",p+16,400);std::copy(ce.begin(),ce.end(),b.begin()+416);if(!DecodeSblrDdlCreateContinuousViewDescriptorV1(b.data(),b.size(),o,d,operand))return false;std::copy(p+416,p+448,o->evidence.begin());return o->availability&&hash("ScratchBird.SblrDdlDropContinuousViewDescriptor.V1",p+16,400)==o->evidence;}
std::vector<std::uint8_t> EncodeSblrDdlDropContinuousViewResultV1(const SblrDdlDropContinuousViewResultV1&v){auto base=v;base.evidence={};auto b=EncodeSblrDdlCreateContinuousViewResultV1(base);if(b.size()>=4){std::memcpy(b.data(),"DVRS",4);auto e=hash("ScratchBird.SblrDdlDropContinuousViewResult.V1",b.data()+16,240);std::copy(e.begin(),e.end(),b.begin()+256);}return b;}
bool DecodeSblrDdlDropContinuousViewResultV1(const std::uint8_t*p,std::size_t n,SblrDdlDropContinuousViewResultV1*o,std::string*d){if(!p||n!=320||!o||std::memcmp(p,"DVRS",4)!=0){if(d)*d="result magic";return false;}auto b=std::vector<std::uint8_t>(p,p+n);std::uint32_t cm=0x43565253u;std::memcpy(b.data(),&cm,4);auto ce=hash("ScratchBird.SblrDdlCreateContinuousViewResult.V1",p+16,240);std::copy(ce.begin(),ce.end(),b.begin()+256);if(!DecodeSblrDdlCreateContinuousViewResultV1(b.data(),b.size(),o,d))return false;std::copy(p+256,p+288,o->evidence.begin());return o->availability&&hash("ScratchBird.SblrDdlDropContinuousViewResult.V1",p+16,240)==o->evidence;}
}
