#include "sblr_ddl_validate_constraint_runtime.hpp"
#include "core/hash/hash_digest.hpp"
#include <algorithm>
#include <cstring>
namespace scratchbird::engine::sblr { namespace {
void put(std::vector<std::uint8_t>& o,std::uint64_t v,std::size_t n){for(std::size_t i=0;i<n;++i)o.push_back(static_cast<std::uint8_t>(v>>(8*i)));}
std::uint64_t get(const std::uint8_t* b,std::size_t n){std::uint64_t v=0;for(std::size_t i=0;i<n;++i)v|=std::uint64_t(b[i])<<(8*i);return v;}
template<class T> bool nonzero(const T& x){return std::any_of(x.begin(),x.end(),[](auto v){return v!=0;});}
std::vector<std::uint8_t> header(const char* m,std::size_t n){std::vector<std::uint8_t> o(m,m+4);put(o,1,2);put(o,n,2);put(o,n,4);put(o,0,4);return o;}
bool valid_header(const std::uint8_t* b,std::size_t n,const char* m,std::size_t z){return b&&n==z&&std::equal(b,b+4,m)&&get(b+4,2)==1&&get(b+6,2)==z&&get(b+8,4)==z&&std::all_of(b+12,b+16,[](auto v){return v==0;});}
std::array<std::uint8_t,32> digest(const char* domain,const std::uint8_t* b,std::size_t n){std::vector<std::uint8_t> x(domain,domain+std::strlen(domain));x.insert(x.end(),b,b+n);return scratchbird::core::hash::ComputeSha256Digest(x).digest;}
}
std::vector<std::uint8_t> EncodeSblrDdlValidateConstraintRequestV1(const SblrDdlValidateConstraintRequestV1& v){if(!nonzero(v.receipt)||!v.occurrence||!v.constraint_occurrence)return{};auto o=header("CVLQ",64);o.insert(o.end(),v.receipt.begin(),v.receipt.end());put(o,v.occurrence,8);put(o,v.constraint_occurrence,4);o.insert(o.end(),20,0);return o;}
bool DecodeSblrDdlValidateConstraintRequestV1(const std::uint8_t* b,std::size_t n,SblrDdlValidateConstraintRequestV1* o,std::string* d){if(!o||!valid_header(b,n,"CVLQ",64)||std::any_of(b+44,b+64,[](auto v){return v;})){if(d)*d="CVLQ invalid";return false;}SblrDdlValidateConstraintRequestV1 v;std::copy_n(b+16,16,v.receipt.begin());v.occurrence=get(b+32,8);v.constraint_occurrence=get(b+40,4);*o=v;return !EncodeSblrDdlValidateConstraintRequestV1(v).empty();}
std::vector<std::uint8_t> EncodeSblrDdlValidateConstraintDescriptorV1(const SblrDdlValidateConstraintDescriptorV1& v,bool operand){if(!nonzero(v.body)||!v.availability)return{};auto o=header(operand?"CVLO":"CVLD",488);o.insert(o.end(),v.body.begin(),v.body.end());auto e=digest("ScratchBird.SblrDdlValidateConstraintDescriptor.V1",o.data()+16,400);if(nonzero(v.evidence)&&e!=v.evidence)return{};o.insert(o.end(),e.begin(),e.end());put(o,v.availability,8);o.insert(o.end(),32,0);return o;}
bool DecodeSblrDdlValidateConstraintDescriptorV1(const std::uint8_t* b,std::size_t n,SblrDdlValidateConstraintDescriptorV1* o,std::string* d,bool operand){if(!o||!valid_header(b,n,operand?"CVLO":"CVLD",488)||std::any_of(b+456,b+488,[](auto v){return v;})){if(d)*d="CVL descriptor invalid";return false;}SblrDdlValidateConstraintDescriptorV1 v;std::copy_n(b+16,400,v.body.begin());std::copy_n(b+416,32,v.evidence.begin());v.availability=get(b+448,8);*o=v;return !EncodeSblrDdlValidateConstraintDescriptorV1(v,operand).empty();}
std::vector<std::uint8_t> EncodeSblrDdlValidateConstraintResultV1(const SblrDdlValidateConstraintResultV1& v){if(!nonzero(v.body)||v.body[24]!=1||!v.availability||!nonzero(v.publication_barrier))return{};auto o=header("CVLS",320);o.insert(o.end(),v.body.begin(),v.body.end());auto e=digest("ScratchBird.SblrDdlValidateConstraintResult.V1",o.data()+16,240);if(nonzero(v.evidence)&&e!=v.evidence)return{};o.insert(o.end(),e.begin(),e.end());put(o,v.availability,8);o.insert(o.end(),v.publication_barrier.begin(),v.publication_barrier.end());o.insert(o.end(),8,0);return o;}
bool DecodeSblrDdlValidateConstraintResultV1(const std::uint8_t* b,std::size_t n,SblrDdlValidateConstraintResultV1* o,std::string* d){if(!o||!valid_header(b,n,"CVLS",320)||std::any_of(b+312,b+320,[](auto v){return v;})){if(d)*d="CVLS invalid";return false;}SblrDdlValidateConstraintResultV1 v;std::copy_n(b+16,240,v.body.begin());std::copy_n(b+256,32,v.evidence.begin());v.availability=get(b+288,8);std::copy_n(b+296,16,v.publication_barrier.begin());*o=v;return !EncodeSblrDdlValidateConstraintResultV1(v).empty();}
}
