#include "sblr_ddl_create_index_runtime.hpp"
#include "core/hash/hash_digest.hpp"
#include <algorithm>
#include <cstring>
namespace scratchbird::engine::sblr { namespace {
void p(std::vector<uint8_t>&o,uint64_t v,size_t n){for(size_t i=0;i<n;i++)o.push_back(uint8_t(v>>(8*i)));} uint64_t g(const uint8_t*b,size_t n){uint64_t v=0;for(size_t i=0;i<n;i++)v|=uint64_t(b[i])<<(8*i);return v;} template<class T>bool nz(const T&x){return std::any_of(x.begin(),x.end(),[](auto v){return v!=0;});} std::vector<uint8_t> h(const char*m,size_t n){std::vector<uint8_t>o(m,m+4);p(o,1,2);p(o,n,2);p(o,n,4);p(o,0,4);return o;} bool vh(const uint8_t*b,size_t n,const char*m,size_t z){return b&&n==z&&std::equal(b,b+4,m)&&g(b+4,2)==1&&g(b+6,2)==z&&g(b+8,4)==z&&std::all_of(b+12,b+16,[](auto v){return v==0;});} DdlCreateIndexSha sha(const char*d,const uint8_t*b,size_t n){std::vector<uint8_t>x(d,d+strlen(d));x.insert(x.end(),b,b+n);return scratchbird::core::hash::ComputeSha256Digest(x).digest;}
}
std::vector<uint8_t> EncodeSblrDdlCreateIndexRequestV1(const SblrDdlCreateIndexRequestV1&v){if(!nz(v.receipt)||!v.occurrence||!v.index_occurrence)return{};auto o=h("CIQX",64);o.insert(o.end(),v.receipt.begin(),v.receipt.end());p(o,v.occurrence,8);p(o,v.index_occurrence,4);o.insert(o.end(),20,0);return o;}
bool DecodeSblrDdlCreateIndexRequestV1(const uint8_t*b,size_t n,SblrDdlCreateIndexRequestV1*out,std::string*d){if(!out||!vh(b,n,"CIQX",64)||std::any_of(b+44,b+64,[](auto v){return v;})){if(d)*d="CIQX invalid";return false;} SblrDdlCreateIndexRequestV1 v;std::copy_n(b+16,16,v.receipt.begin());v.occurrence=g(b+32,8);v.index_occurrence=g(b+40,4);if(EncodeSblrDdlCreateIndexRequestV1(v).empty())return false;*out=v;return true;}
std::vector<uint8_t> EncodeSblrDdlCreateIndexDescriptorV1(const SblrDdlCreateIndexDescriptorV1&v,bool op){if(!nz(v.body)||!v.availability)return{};auto o=h(op?"CIDO":"CIDX",488);o.insert(o.end(),v.body.begin(),v.body.end());auto e=sha("ScratchBird.SblrDdlCreateIndexDescriptor.V1",o.data()+16,400);if(nz(v.evidence)&&e!=v.evidence)return{};o.insert(o.end(),e.begin(),e.end());p(o,v.availability,8);o.insert(o.end(),32,0);return o;}
bool DecodeSblrDdlCreateIndexDescriptorV1(const uint8_t*b,size_t n,SblrDdlCreateIndexDescriptorV1*out,std::string*d,bool op){if(!out||!vh(b,n,op?"CIDO":"CIDX",488)||std::any_of(b+456,b+488,[](auto v){return v;})){if(d)*d="KVD invalid";return false;} SblrDdlCreateIndexDescriptorV1 v;std::copy_n(b+16,400,v.body.begin());std::copy_n(b+416,32,v.evidence.begin());v.availability=g(b+448,8);if(EncodeSblrDdlCreateIndexDescriptorV1(v,op).empty())return false;*out=v;return true;}
std::vector<uint8_t> EncodeSblrDdlCreateIndexResultV1(const SblrDdlCreateIndexResultV1&v){if(!nz(v.body)||v.body[24]!=1||v.body[25]>1||!g(v.body.data()+56,8)||!v.availability||!nz(v.publication_barrier))return{};auto o=h("CIRS",320);o.insert(o.end(),v.body.begin(),v.body.end());auto e=sha("ScratchBird.SblrDdlCreateIndexExecutorEvidence.V1",o.data()+16,240);if(nz(v.evidence)&&e!=v.evidence)return{};o.insert(o.end(),e.begin(),e.end());p(o,v.availability,8);o.insert(o.end(),v.publication_barrier.begin(),v.publication_barrier.end());o.insert(o.end(),8,0);return o;}
bool DecodeSblrDdlCreateIndexResultV1(const uint8_t*b,size_t n,SblrDdlCreateIndexResultV1*out,std::string*d){if(!out||!vh(b,n,"CIRS",320)||std::any_of(b+312,b+320,[](auto v){return v;})){if(d)*d="CIRS invalid";return false;} SblrDdlCreateIndexResultV1 v;std::copy_n(b+16,240,v.body.begin());std::copy_n(b+256,32,v.evidence.begin());v.availability=g(b+288,8);std::copy_n(b+296,16,v.publication_barrier.begin());if(EncodeSblrDdlCreateIndexResultV1(v).empty())return false;*out=v;return true;}
}
