#include "sblr_insert_runtime.hpp"
#include "core/hash/hash_digest.hpp"
#include <algorithm>
#include <cstring>
namespace scratchbird::engine::sblr { namespace {
void u16(std::vector<uint8_t>&o,uint16_t v){o.push_back(v);o.push_back(v>>8);}void u32(std::vector<uint8_t>&o,uint32_t v){for(int i=0;i<4;i++)o.push_back(v>>(8*i));}void u64(std::vector<uint8_t>&o,uint64_t v){for(int i=0;i<8;i++)o.push_back(v>>(8*i));}uint32_t g32(const uint8_t*p){uint32_t v=0;for(int i=0;i<4;i++)v|=uint32_t(p[i])<<(8*i);return v;}uint64_t g64(const uint8_t*p){uint64_t v=0;for(int i=0;i<8;i++)v|=uint64_t(p[i])<<(8*i);return v;}bool nz(const auto&a){return std::any_of(a.begin(),a.end(),[](uint8_t x){return x;});}bool head(const uint8_t*b,size_t n,const char*m,size_t z){return b&&n==z&&!std::memcmp(b,m,4)&&b[4]==1&&!b[5]&&b[6]==(z&255)&&b[7]==(z>>8)&&g32(b+8)==z&&!g32(b+12);}auto sha(const char*d,const uint8_t*b,size_t n){std::vector<uint8_t>x(d,d+std::strlen(d));x.insert(x.end(),b,b+n);return scratchbird::core::hash::ComputeSha256Digest(x).digest;}
}
std::vector<uint8_t>EncodeSblrInsertRequestV1(const SblrInsertRequestV1&v){if(!nz(v.receipt)||!v.occurrence||!v.insert_occurrence)return{};std::vector<uint8_t>o{'I','N','S','R'};u16(o,1);u16(o,64);u32(o,64);u32(o,0);o.insert(o.end(),v.receipt.begin(),v.receipt.end());u64(o,v.occurrence);u32(o,v.insert_occurrence);o.insert(o.end(),20,0);return o;}
bool DecodeSblrInsertRequestV1(const uint8_t*b,size_t n,SblrInsertRequestV1*out,std::string*d){if(!out||!head(b,n,"INSR",64)){if(d)*d="INSR invalid";return false;}SblrInsertRequestV1 v;std::copy_n(b+16,16,v.receipt.begin());v.occurrence=g64(b+32);v.insert_occurrence=g32(b+40);if(std::any_of(b+44,b+64,[](uint8_t x){return x;})||EncodeSblrInsertRequestV1(v).empty())return false;*out=v;return true;}
std::vector<uint8_t>EncodeSblrInsertDescriptorV1(const SblrInsertDescriptorV1&v,bool op){if(!v.availability_generation||!nz(v.canonical_body))return{};std::vector<uint8_t>o=op?std::vector<uint8_t>{'I','N','S','O'}:std::vector<uint8_t>{'I','N','S','D'};u16(o,1);u16(o,440);u32(o,440);u32(o,0);o.insert(o.end(),v.canonical_body.begin(),v.canonical_body.end());auto e=sha("ScratchBird.SblrInsertDescriptor.V1",o.data()+16,384);if(nz(v.evidence)&&v.evidence!=e)return{};o.insert(o.end(),e.begin(),e.end());u64(o,v.availability_generation);return o;}
bool DecodeSblrInsertDescriptorV1(const uint8_t*b,size_t n,SblrInsertDescriptorV1*out,std::string*d,bool op){if(!out||!head(b,n,op?"INSO":"INSD",440)){if(d)*d="insert descriptor invalid";return false;}SblrInsertDescriptorV1 v;std::copy_n(b+16,384,v.canonical_body.begin());std::copy_n(b+400,32,v.evidence.begin());v.availability_generation=g64(b+432);if(EncodeSblrInsertDescriptorV1(v,op).empty())return false;*out=v;return true;}
std::vector<uint8_t>EncodeSblrInsertResultV1(const SblrInsertResultV1&v){if(!v.availability_generation||!nz(v.canonical_body))return{};std::vector<uint8_t>o{'I','N','R','S'};u16(o,1);u16(o,192);u32(o,192);u32(o,0);o.insert(o.end(),v.canonical_body.begin(),v.canonical_body.end());auto e=sha("ScratchBird.SblrInsertResult.V1",o.data()+16,136);if(nz(v.evidence)&&v.evidence!=e)return{};o.insert(o.end(),e.begin(),e.end());u64(o,v.availability_generation);return o;}
bool DecodeSblrInsertResultV1(const uint8_t*b,size_t n,SblrInsertResultV1*out,std::string*d){if(!out||!head(b,n,"INRS",192)){if(d)*d="insert result invalid";return false;}SblrInsertResultV1 v;std::copy_n(b+16,136,v.canonical_body.begin());std::copy_n(b+152,32,v.evidence.begin());v.availability_generation=g64(b+184);if(EncodeSblrInsertResultV1(v).empty())return false;*out=v;return true;}
}
