#include "sblr_ddl_create_table_as_query_runtime.hpp"
#include "core/hash/hash_digest.hpp"
#include <algorithm>
#include <cstring>
namespace scratchbird::engine::sblr { namespace {
using B=std::vector<std::uint8_t>; std::uint32_t Crc(const std::uint8_t*p,size_t n){std::uint32_t c=~0u;for(size_t i=0;i<n;i++){c^=p[i];for(int j=0;j<8;j++)c=(c>>1)^(0x82f63b78u&-(c&1));}return ~c;} void p32(B&b,std::uint32_t v){for(int i=0;i<4;i++)b.push_back(v>>(i*8));} void put32(B&b,size_t o,std::uint32_t v){for(int i=0;i<4;i++)b[o+i]=v>>(i*8);} std::uint16_t u16(const std::uint8_t*p){return p[0]|std::uint16_t(p[1])<<8;} std::uint32_t u32(const std::uint8_t*p){std::uint32_t v=0;for(int i=0;i<4;i++)v|=std::uint32_t(p[i])<<(i*8);return v;} std::uint64_t u64(const std::uint8_t*p){std::uint64_t v=0;for(int i=0;i<8;i++)v|=std::uint64_t(p[i])<<(i*8);return v;} template<class A>bool nz(const A&a){return std::any_of(a.begin(),a.end(),[](auto x){return x!=0;});} template<class A>void put(B&b,const A&a){b.insert(b.end(),a.begin(),a.end());} template<class A>void get(const std::uint8_t*p,A&a){std::copy_n(p,a.size(),a.begin());} bool zero(const std::uint8_t*p,size_t n){return std::all_of(p,p+n,[](auto x){return x==0;});} bool crc(const std::uint8_t*p,size_t n){return Crc(p,n-4)==u32(p+n-4);}
}
std::vector<std::uint8_t> EncodeSblrCreateTableAsQueryRequestV1(const SblrCreateTableAsQueryRequestV1&v){if(!nz(v.receipt)||!nz(v.occurrence)||(v.flags&~1u))return{};B b;b.reserve(64);put(b,v.receipt);put(b,v.occurrence);p32(b,v.occurrence_ordinal);p32(b,v.flags);for(int i=0;i<8;i++){b.push_back(v.catalog_epoch>>(8*i));}for(int i=0;i<8;i++){b.push_back(v.authority_generation>>(8*i));}p32(b,0);p32(b,Crc(b.data(),60));return b;}
bool DecodeSblrCreateTableAsQueryRequestV1(const std::uint8_t*p,size_t n,SblrCreateTableAsQueryRequestV1*out,std::string*e){if(!p||!out||n!=64||!crc(p,n)||u32(p+56)!=(0u)||(u32(p+36)&~1u)){if(e)*e="CTAS request invalid";return false;}SblrCreateTableAsQueryRequestV1 v;get(p,v.receipt);get(p+16,v.occurrence);v.occurrence_ordinal=u32(p+32);v.flags=u32(p+36);v.catalog_epoch=u64(p+40);v.authority_generation=u64(p+48);if(!nz(v.receipt)||!nz(v.occurrence)){if(e)*e="CTAS identity invalid";return false;}*out=v;return true;}
std::vector<std::uint8_t> EncodeSblrCreateTableAsQueryDescriptorV1(const SblrCreateTableAsQueryDescriptorV1&v){if((v.opcode!=1669&&v.opcode!=1670)||(v.flags&~1u)||v.query_plan.size()>440||v.columns.size()%16||v.columns.size()+v.authority_proof.size()>444-v.query_plan.size())return{};B b(512,0);std::memcpy(b.data(),"CTAQ",4);b[4]=1;b[8]=v.opcode;b[9]=v.opcode>>8;b[10]=v.flags;b[11]=v.flags>>8;std::copy(v.table_uuid.begin(),v.table_uuid.end(),b.begin()+12);std::copy(v.query_plan_uuid.begin(),v.query_plan_uuid.end(),b.begin()+28);for(int i=0;i<8;i++)b[44+i]=v.catalog_epoch>>(8*i);put32(b,52,v.columns.size()/16);for(int i=0;i<8;i++)b[56+i]=v.query_plan.size()>>(8*i);std::copy(v.query_plan.begin(),v.query_plan.end(),b.begin()+64);auto pos=64+v.query_plan.size();std::copy(v.columns.begin(),v.columns.end(),b.begin()+pos);pos+=v.columns.size();std::copy(v.authority_proof.begin(),v.authority_proof.end(),b.begin()+pos);put32(b,508,Crc(b.data(),508));return b;}
bool DecodeSblrCreateTableAsQueryDescriptorV1(const std::uint8_t*p,size_t n,SblrCreateTableAsQueryDescriptorV1*out,std::string*e){if(!p||!out||n!=512||std::memcmp(p,"CTAQ",4)||p[4]!=1||p[5]||p[6]||p[7]||!crc(p,n)){if(e)*e="CTAS descriptor invalid";return false;}auto op=u16(p+8);auto q=u64(p+56);auto c=u32(p+52);if((op!=1669&&op!=1670)||u16(p+10)&~1u||q>440||c>27||64+q+size_t(c)*16>508){if(e)*e="CTAS descriptor bounds invalid";return false;}SblrCreateTableAsQueryDescriptorV1 v;v.opcode=op;v.flags=u16(p+10);get(p+12,v.table_uuid);get(p+28,v.query_plan_uuid);v.catalog_epoch=u64(p+44);v.query_plan.assign(p+64,p+64+q);v.columns.assign(p+64+q,p+64+q+size_t(c)*16);v.authority_proof.assign(p+64+q+size_t(c)*16,p+508);*out=std::move(v);return true;}
std::vector<std::uint8_t> EncodeSblrCreateTableAsQueryResultV1(const SblrCreateTableAsQueryResultV1&v){if(v.status>3||v.materialization>1||v.flags)return{};B b(488,0);std::memcpy(b.data(),"CTAR",4);b[4]=1;b[8]=v.status;b[9]=v.materialization;std::copy(v.table_uuid.begin(),v.table_uuid.end(),b.begin()+12);std::copy(v.publication_uuid.begin(),v.publication_uuid.end(),b.begin()+28);for(int i=0;i<8;i++){b[44+i]=v.catalog_epoch>>(8*i);b[52+i]=v.row_count>>(8*i);}std::copy(v.result_hash.begin(),v.result_hash.end(),b.begin()+60);std::copy(v.diagnostic_hash.begin(),v.diagnostic_hash.end(),b.begin()+92);put32(b,484,Crc(b.data(),484));return b;}
bool DecodeSblrCreateTableAsQueryResultV1(const std::uint8_t*p,size_t n,SblrCreateTableAsQueryResultV1*out,std::string*e){if(!p||!out||n!=488||std::memcmp(p,"CTAR",4)||p[4]!=1||p[5]||p[6]||p[7]||!crc(p,n)||!zero(p+124,360)){if(e)*e="CTAS result invalid";return false;}SblrCreateTableAsQueryResultV1 v;v.status=p[8];v.materialization=p[9];v.flags=u16(p+10);if(v.status>3||v.materialization>1||v.flags){if(e)*e="CTAS result fields invalid";return false;}get(p+12,v.table_uuid);get(p+28,v.publication_uuid);v.catalog_epoch=u64(p+44);v.row_count=u64(p+52);get(p+60,v.result_hash);get(p+92,v.diagnostic_hash);*out=std::move(v);return true;}
}
