#include "sblr_ddl_alter_continuous_view_runtime.hpp"
#include "core/hash/hash_digest.hpp"
#include <algorithm>
#include <cstring>
namespace scratchbird::engine::sblr { namespace { std::vector<std::uint8_t> magic(const std::uint8_t*p,std::size_t n,std::uint32_t m){std::vector<std::uint8_t>b(p,p+n);if(b.size()>=4)std::memcpy(b.data(),&m,4);return b;} std::array<std::uint8_t,32> hash(const char*d,const std::uint8_t*p,std::size_t n){std::vector<std::uint8_t>x(d,d+std::strlen(d));x.insert(x.end(),p,p+n);std::array<std::uint8_t,32>h{};const auto e=scratchbird::core::hash::ComputeSha256Digest(x);if(e.ok())std::copy(e.digest.begin(),e.digest.end(),h.begin());return h;} }
std::vector<std::uint8_t> EncodeSblrDdlAlterContinuousViewRequestV1(const SblrDdlAlterContinuousViewRequestV1&v){auto b=EncodeSblrDdlCreateContinuousViewRequestV1(v);if(b.size()>=4)std::memcpy(b.data(),"AVRQ",4);return b;}
bool DecodeSblrDdlAlterContinuousViewRequestV1(const std::uint8_t*p,std::size_t n,SblrDdlAlterContinuousViewRequestV1*o,std::string*d){auto b=magic(p,n,0x43565251u);return DecodeSblrDdlCreateContinuousViewRequestV1(b.data(),b.size(),o,d);}
std::vector<std::uint8_t> EncodeSblrDdlAlterContinuousViewDescriptorV1(const SblrDdlAlterContinuousViewDescriptorV1&v,bool operand){auto base=v;base.evidence={};auto b=EncodeSblrDdlCreateContinuousViewDescriptorV1(base,operand);if(b.size()>=4){std::memcpy(b.data(),operand?"AVDO":"AVDD",4);auto e=hash("ScratchBird.SblrDdlAlterContinuousViewDescriptor.V1",b.data()+16,400);std::copy(e.begin(),e.end(),b.begin()+416);}return b;}
bool DecodeSblrDdlAlterContinuousViewDescriptorV1(const std::uint8_t*p,std::size_t n,SblrDdlAlterContinuousViewDescriptorV1*o,std::string*d,bool operand){if(!p||n!=488||!o)return false;auto b=magic(p,n,operand?0x4356444fu:0x43564444u);auto ce=hash("ScratchBird.SblrDdlCreateContinuousViewDescriptor.V1",p+16,400);std::copy(ce.begin(),ce.end(),b.begin()+416);if(!DecodeSblrDdlCreateContinuousViewDescriptorV1(b.data(),b.size(),o,d,operand))return false;std::copy(p+416,p+448,o->evidence.begin());return o->availability&&hash("ScratchBird.SblrDdlAlterContinuousViewDescriptor.V1",p+16,400)==o->evidence;}
std::vector<std::uint8_t> EncodeSblrDdlAlterContinuousViewResultV1(const SblrDdlAlterContinuousViewResultV1&v){auto base=v;base.evidence={};auto b=EncodeSblrDdlCreateContinuousViewResultV1(base);if(b.size()>=4){std::memcpy(b.data(),"AVRS",4);auto e=hash("ScratchBird.SblrDdlAlterContinuousViewResult.V1",b.data()+16,240);std::copy(e.begin(),e.end(),b.begin()+256);}return b;}
bool DecodeSblrDdlAlterContinuousViewResultV1(const std::uint8_t*p,std::size_t n,SblrDdlAlterContinuousViewResultV1*o,std::string*d){if(!p||n!=320||!o)return false;auto b=magic(p,n,0x43565253u);auto ce=hash("ScratchBird.SblrDdlCreateContinuousViewResult.V1",p+16,240);std::copy(ce.begin(),ce.end(),b.begin()+256);if(!DecodeSblrDdlCreateContinuousViewResultV1(b.data(),b.size(),o,d))return false;std::copy(p+256,p+288,o->evidence.begin());return o->availability&&hash("ScratchBird.SblrDdlAlterContinuousViewResult.V1",p+16,240)==o->evidence;}
}
