#include "sblr_transaction_begin_runtime.hpp"
#include "hash_digest.hpp"
#include <algorithm>
#include <string_view>
namespace scratchbird::engine::sblr {namespace{
void P16(std::vector<std::uint8_t>*o,std::uint16_t v){o->push_back(v);o->push_back(v>>8);}void P32(std::vector<std::uint8_t>*o,std::uint32_t v){for(int i=0;i<4;++i)o->push_back(v>>(8*i));}void P64(std::vector<std::uint8_t>*o,std::uint64_t v){for(int i=0;i<8;++i)o->push_back(v>>(8*i));}std::uint16_t U16(const std::uint8_t*p){return p[0]|std::uint16_t(p[1])<<8;}std::uint32_t U32(const std::uint8_t*p){std::uint32_t v=0;for(int i=0;i<4;++i)v|=std::uint32_t(p[i])<<(8*i);return v;}std::uint64_t U64(const std::uint8_t*p){std::uint64_t v=0;for(int i=0;i<8;++i)v|=std::uint64_t(p[i])<<(8*i);return v;}template<class A>void Put(std::vector<std::uint8_t>*o,const A&a){o->insert(o->end(),a.begin(),a.end());}template<class A>void Get(const std::uint8_t*p,A*a){std::copy_n(p,a->size(),a->begin());}template<class A>bool Nz(const A&a){return std::any_of(a.begin(),a.end(),[](auto x){return x;});}SblrTxnShaV1 H(std::string_view d,const std::uint8_t*p,size_t z){std::vector<std::uint8_t>m(d.begin(),d.end());m.insert(m.end(),p,p+z);return scratchbird::core::hash::ComputeSha256Digest(m).digest;}
}
std::vector<std::uint8_t> EncodeSblrTransactionBeginOptionsV1(SblrTransactionBeginOptionsV1*v){if(!v||!Nz(v->isolation_profile_uuid)||!v->isolation_profile_generation||!Nz(v->transaction_policy_snapshot_uuid)||!v->transaction_policy_generation||v->read_mode<1||v->read_mode>2||v->authority_scope<1||v->authority_scope>2||v->wait_policy<1||v->wait_policy>2)return{};std::vector<std::uint8_t>o{'T','X','B','O'};P16(&o,1);P16(&o,112);P32(&o,112);P32(&o,0);Put(&o,v->isolation_profile_uuid);P64(&o,v->isolation_profile_generation);o.push_back(v->read_mode);o.push_back(v->authority_scope);o.push_back(v->wait_policy);o.insert(o.end(),5,0);Put(&o,v->transaction_policy_snapshot_uuid);P64(&o,v->transaction_policy_generation);P64(&o,v->deadline_monotonic_ns);v->options_sha256=H("ScratchBird.SblrTransactionBeginOptions.V1",o.data(),o.size());Put(&o,v->options_sha256);return o;}
bool DecodeSblrTransactionBeginOptionsV1(const std::uint8_t*b,std::size_t z,SblrTransactionBeginOptionsV1*out,std::string*d){if(!b||!out||z!=112||!std::equal(b,b+4,"TXBO")||U16(b+4)!=1||U16(b+6)!=112||U32(b+8)!=112||U32(b+12)||std::any_of(b+43,b+48,[](auto x){return x;})){if(d)*d="TXBO header invalid";return false;}SblrTransactionBeginOptionsV1 v;Get(b+16,&v.isolation_profile_uuid);v.isolation_profile_generation=U64(b+32);v.read_mode=b[40];v.authority_scope=b[41];v.wait_policy=b[42];Get(b+48,&v.transaction_policy_snapshot_uuid);v.transaction_policy_generation=U64(b+64);v.deadline_monotonic_ns=U64(b+72);Get(b+80,&v.options_sha256);auto c=v;auto encoded=EncodeSblrTransactionBeginOptionsV1(&c);if(encoded.size()!=z||!std::equal(encoded.begin(),encoded.end(),b))return false;*out=v;return true;}
std::vector<std::uint8_t> EncodeSblrTransactionHandleV1(const SblrTransactionHandleV1&v){if(!Nz(v.transaction_uuid)||!v.local_transaction_id||!Nz(v.snapshot_uuid)||!Nz(v.isolation_profile_uuid)||!v.isolation_profile_generation||!Nz(v.transaction_policy_snapshot_uuid)||!v.transaction_policy_generation||v.read_mode<1||v.read_mode>2||v.lifecycle_state!=1||v.authority_scope<1||v.authority_scope>2||!v.executor_availability_generation)return{};std::vector<std::uint8_t>o{'T','X','B','H'};P16(&o,1);P16(&o,152);P32(&o,152);P32(&o,0);Put(&o,v.transaction_uuid);P64(&o,v.local_transaction_id);Put(&o,v.snapshot_uuid);Put(&o,v.isolation_profile_uuid);P64(&o,v.isolation_profile_generation);Put(&o,v.transaction_policy_snapshot_uuid);P64(&o,v.transaction_policy_generation);o.push_back(v.read_mode);o.push_back(v.lifecycle_state);o.push_back(v.authority_scope);o.insert(o.end(),5,0);const auto evidence=H("ScratchBird.SblrTransactionHandle.V1",o.data(),o.size());if(Nz(v.handle_evidence_sha256)&&v.handle_evidence_sha256!=evidence)return{};Put(&o,evidence);P64(&o,v.executor_availability_generation);return o;}
bool DecodeSblrTransactionHandleV1(const std::uint8_t*b,std::size_t z,SblrTransactionHandleV1*out,std::string*d){if(!b||!out||z!=152||!std::equal(b,b+4,"TXBH")||U16(b+4)!=1||U16(b+6)!=152||U32(b+8)!=152||U32(b+12)||std::any_of(b+107,b+112,[](auto x){return x;})){if(d)*d="TXBH invalid";return false;}SblrTransactionHandleV1 v;Get(b+16,&v.transaction_uuid);v.local_transaction_id=U64(b+32);Get(b+40,&v.snapshot_uuid);Get(b+56,&v.isolation_profile_uuid);v.isolation_profile_generation=U64(b+72);Get(b+80,&v.transaction_policy_snapshot_uuid);v.transaction_policy_generation=U64(b+96);v.read_mode=b[104];v.lifecycle_state=b[105];v.authority_scope=b[106];Get(b+112,&v.handle_evidence_sha256);v.executor_availability_generation=U64(b+144);if(EncodeSblrTransactionHandleV1(v).empty())return false;*out=v;return true;}
}
