#include "sblr_session_setting_set_runtime.hpp"
#include <cstring>
namespace scratchbird::engine::sblr { namespace { template<class T> void put(std::vector<uint8_t>&b,const T&v){auto*p=(const uint8_t*)&v;b.insert(b.end(),p,p+sizeof(T));} template<class T> bool get(const uint8_t*d,size_t n,size_t&o,T&v){if(o+sizeof(T)>n)return false;std::memcpy(&v,d+o,sizeof(T));o+=sizeof(T);return true;} }
std::vector<uint8_t> EncodeSblrSessionSettingSetRequestV1(const SblrSessionSettingSetRequestV1&v){std::vector<uint8_t>b; b.insert(b.end(),v.receipt.begin(),v.receipt.end());put(b,v.occurrence);return b;}
bool DecodeSblrSessionSettingSetRequestV1(const uint8_t*d,size_t n,SblrSessionSettingSetRequestV1*v,std::string*e){if(!d||!v||n!=24){if(e)*e="request length";return false;}std::memcpy(v->receipt.data(),d,16);size_t o=16;return get(d,n,o,v->occurrence);}
std::vector<uint8_t> EncodeSblrSessionSettingSetDescriptorV1(const SblrSessionSettingSetDescriptorV1&v,bool){std::vector<uint8_t>b;b.insert(b.end(),v.receipt.begin(),v.receipt.end());b.insert(b.end(),v.key.begin(),v.key.end());b.insert(b.end(),v.value.begin(),v.value.end());put(b,v.expected_generation);put(b,v.availability);return b;}
bool DecodeSblrSessionSettingSetDescriptorV1(const uint8_t*d,size_t n,SblrSessionSettingSetDescriptorV1*v,std::string*e,bool){if(!d||!v||n!=128){if(e)*e="descriptor length";return false;}std::memcpy(v->receipt.data(),d,16);std::memcpy(v->key.data(),d+16,32);std::memcpy(v->value.data(),d+48,64);size_t o=112;return get(d,n,o,v->expected_generation)&&get(d,n,o,v->availability);}
std::vector<uint8_t> EncodeSblrSessionSettingSetResultV1(const SblrSessionSettingSetResultV1&v){std::vector<uint8_t>b;b.insert(b.end(),v.key.begin(),v.key.end());put(b,v.generation);put(b,v.availability);b.push_back(v.status);b.push_back(v.publication_barrier);b.insert(b.end(),v.effect_evidence.begin(),v.effect_evidence.end());return b;}
bool DecodeSblrSessionSettingSetResultV1(const uint8_t*d,size_t n,SblrSessionSettingSetResultV1*v,std::string*e){if(!d||!v||n!=82){if(e)*e="result length";return false;}std::memcpy(v->key.data(),d,32);size_t o=32;if(!get(d,n,o,v->generation)||!get(d,n,o,v->availability)||!get(d,n,o,v->status)||!get(d,n,o,v->publication_barrier)){if(e)*e="result fields";return false;}std::memcpy(v->effect_evidence.data(),d+50,32);return true;}
}
