# Copyright (c) 2026 ScratchBird Software Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0

# CRP-PRODUCTION-BUILD-SAFETY-GATE-MATRIX: CTest-visible proof that the
# commercial production build gate accepts a clean release-complete profile and
# refuses fixture, seed, forced-hook, stub-provider, debug, trace, and unsupported
# cluster-claim paths.

set(_sb_gate_script "${CMAKE_CURRENT_LIST_DIR}/CommercialReadinessProductionBuildGate.cmake")

function(_sb_crp_gate_case case_name expected_success)
  execute_process(
    COMMAND "${CMAKE_COMMAND}" ${ARGN} -P "${_sb_gate_script}"
    RESULT_VARIABLE _sb_result
    OUTPUT_VARIABLE _sb_output
    ERROR_VARIABLE _sb_error)

  if(expected_success)
    if(NOT _sb_result EQUAL 0)
      message(SEND_ERROR
        "${case_name}: expected success but gate failed: ${_sb_output}${_sb_error}")
    endif()
  else()
    if(_sb_result EQUAL 0)
      message(SEND_ERROR
        "${case_name}: expected failure but gate passed: ${_sb_output}${_sb_error}")
    endif()
  endif()
endfunction()

set(_sb_base_args
  -DSB_COMMERCIAL_READINESS_PRODUCTION_BUILD=ON
  -DSB_AGENT_ALLOW_FIXTURE_AUTH_IN_PRODUCTION=OFF
  -DSB_AGENT_ALLOW_FIXTURE_POLICY_IN_PRODUCTION=OFF
  -DSB_AGENT_ALLOW_RELAXED_METRICS_IN_PRODUCTION=OFF
  -DSB_AGENT_ALLOW_TEST_SEEDS_IN_PRODUCTION=OFF
  -DSB_AGENT_ALLOW_FORCED_COLLISION_HOOKS_IN_PRODUCTION=OFF
  -DSB_AGENT_ALLOW_SIDECAR_STATE_IN_PRODUCTION=OFF
  -DSB_AGENT_ALLOW_SIMULATED_ACTUATORS_IN_PRODUCTION=OFF
  -DSB_AGENT_ALLOW_DEBUG_ONLY_PATHS_IN_PRODUCTION=OFF
  -DSB_AGENT_CLUSTER_STUB_LIVE_CLAIMS=OFF
  -DSB_OPTIMIZER_ALLOW_FIXTURE_STATS_IN_PRODUCTION=OFF
  -DSB_OPTIMIZER_ALLOW_LOCAL_DEFAULT_STATS_IN_PRODUCTION=OFF
  -DSB_OPTIMIZER_ALLOW_POLICY_DEFAULT_STATS_IN_PRODUCTION=OFF
  -DSB_OPTIMIZER_ALLOW_RELAXED_METRICS_IN_PRODUCTION=OFF
  -DSB_OPTIMIZER_ALLOW_PLACEHOLDER_RUNTIME_EVIDENCE_IN_PRODUCTION=OFF
  -DSB_OPTIMIZER_ALLOW_DONOR_AUTHORITY_IN_PRODUCTION=OFF
  -DSB_OPTIMIZER_ALLOW_PARSER_SHORTCUTS_IN_PRODUCTION=OFF
  -DSB_OPTIMIZER_ALLOW_CLUSTER_STUB_LIVE_CLAIMS=OFF
  -DSB_OPTIMIZER_ALLOW_DEBUG_ONLY_PATHS_IN_PRODUCTION=OFF
  -DSB_OPTIMIZER_ALLOW_SYNTHETIC_FEEDBACK_IN_PRODUCTION=OFF
  -DSB_COMMERCIAL_ALLOW_FIXTURE_AUTH_IN_PRODUCTION=OFF
  -DSB_COMMERCIAL_ALLOW_TEST_SEEDS_IN_PRODUCTION=OFF
  -DSB_COMMERCIAL_ALLOW_FORCED_COLLISION_HOOKS_IN_PRODUCTION=OFF
  -DSB_COMMERCIAL_ALLOW_STUB_PROVIDERS_IN_PRODUCTION=OFF
  -DSB_COMMERCIAL_ALLOW_DEBUG_CREDENTIALS_IN_PRODUCTION=OFF
  -DSB_COMMERCIAL_ALLOW_DEBUG_ONLY_AUTHORITY_PATHS_IN_PRODUCTION=OFF
  -DSB_COMMERCIAL_ALLOW_NO_CLUSTER_PRODUCTION_CLAIMS=OFF
  -DSB_COMMERCIAL_CLUSTER_PRODUCTION_CLAIMS=OFF
  -DSB_ENABLE_CLUSTER_PROVIDER=OFF
  -DSB_CLUSTER_PROVIDER_STUB=OFF
  -DSB_CLUSTER_PROVIDER_EXTERNAL_LIBRARY=
  -DSCRATCHBIRD_ENABLE_DEBUG_LOGS=OFF
  -DSCRATCHBIRD_ENABLE_HOTPATH_TRACE=OFF
  -DSCRATCHBIRD_ENABLE_EXEC_PROFILE_TRACE=OFF
  -DSCRATCHBIRD_ENABLE_PREPARED_TRACE=OFF
)

_sb_crp_gate_case(clean_release TRUE ${_sb_base_args})
_sb_crp_gate_case(fixture_auth FALSE
  ${_sb_base_args} -DSB_COMMERCIAL_ALLOW_FIXTURE_AUTH_IN_PRODUCTION=ON)
_sb_crp_gate_case(agent_fixture_auth FALSE
  ${_sb_base_args} -DSB_AGENT_ALLOW_FIXTURE_AUTH_IN_PRODUCTION=ON)
_sb_crp_gate_case(agent_fixture_policy FALSE
  ${_sb_base_args} -DSB_AGENT_ALLOW_FIXTURE_POLICY_IN_PRODUCTION=ON)
_sb_crp_gate_case(test_seeds FALSE
  ${_sb_base_args} -DSB_COMMERCIAL_ALLOW_TEST_SEEDS_IN_PRODUCTION=ON)
_sb_crp_gate_case(agent_test_seeds FALSE
  ${_sb_base_args} -DSB_AGENT_ALLOW_TEST_SEEDS_IN_PRODUCTION=ON)
_sb_crp_gate_case(forced_collision_hooks FALSE
  ${_sb_base_args} -DSB_COMMERCIAL_ALLOW_FORCED_COLLISION_HOOKS_IN_PRODUCTION=ON)
_sb_crp_gate_case(agent_forced_collision_hooks FALSE
  ${_sb_base_args} -DSB_AGENT_ALLOW_FORCED_COLLISION_HOOKS_IN_PRODUCTION=ON)
_sb_crp_gate_case(stub_providers FALSE
  ${_sb_base_args} -DSB_COMMERCIAL_ALLOW_STUB_PROVIDERS_IN_PRODUCTION=ON)
_sb_crp_gate_case(debug_credentials FALSE
  ${_sb_base_args} -DSB_COMMERCIAL_ALLOW_DEBUG_CREDENTIALS_IN_PRODUCTION=ON)
_sb_crp_gate_case(debug_authority FALSE
  ${_sb_base_args} -DSB_COMMERCIAL_ALLOW_DEBUG_ONLY_AUTHORITY_PATHS_IN_PRODUCTION=ON)
_sb_crp_gate_case(agent_debug_paths FALSE
  ${_sb_base_args} -DSB_AGENT_ALLOW_DEBUG_ONLY_PATHS_IN_PRODUCTION=ON)
_sb_crp_gate_case(optimizer_debug_paths FALSE
  ${_sb_base_args} -DSB_OPTIMIZER_ALLOW_DEBUG_ONLY_PATHS_IN_PRODUCTION=ON)
_sb_crp_gate_case(agent_relaxed_metrics FALSE
  ${_sb_base_args} -DSB_AGENT_ALLOW_RELAXED_METRICS_IN_PRODUCTION=ON)
_sb_crp_gate_case(optimizer_relaxed_metrics FALSE
  ${_sb_base_args} -DSB_OPTIMIZER_ALLOW_RELAXED_METRICS_IN_PRODUCTION=ON)
_sb_crp_gate_case(agent_sidecar_state FALSE
  ${_sb_base_args} -DSB_AGENT_ALLOW_SIDECAR_STATE_IN_PRODUCTION=ON)
_sb_crp_gate_case(agent_simulated_actuator FALSE
  ${_sb_base_args} -DSB_AGENT_ALLOW_SIMULATED_ACTUATORS_IN_PRODUCTION=ON)
_sb_crp_gate_case(optimizer_fixture_stats FALSE
  ${_sb_base_args} -DSB_OPTIMIZER_ALLOW_FIXTURE_STATS_IN_PRODUCTION=ON)
_sb_crp_gate_case(optimizer_local_default_stats FALSE
  ${_sb_base_args} -DSB_OPTIMIZER_ALLOW_LOCAL_DEFAULT_STATS_IN_PRODUCTION=ON)
_sb_crp_gate_case(optimizer_policy_default_stats FALSE
  ${_sb_base_args} -DSB_OPTIMIZER_ALLOW_POLICY_DEFAULT_STATS_IN_PRODUCTION=ON)
_sb_crp_gate_case(optimizer_placeholder_runtime_evidence FALSE
  ${_sb_base_args} -DSB_OPTIMIZER_ALLOW_PLACEHOLDER_RUNTIME_EVIDENCE_IN_PRODUCTION=ON)
_sb_crp_gate_case(optimizer_donor_authority FALSE
  ${_sb_base_args} -DSB_OPTIMIZER_ALLOW_DONOR_AUTHORITY_IN_PRODUCTION=ON)
_sb_crp_gate_case(optimizer_parser_shortcuts FALSE
  ${_sb_base_args} -DSB_OPTIMIZER_ALLOW_PARSER_SHORTCUTS_IN_PRODUCTION=ON)
_sb_crp_gate_case(optimizer_synthetic_feedback FALSE
  ${_sb_base_args} -DSB_OPTIMIZER_ALLOW_SYNTHETIC_FEEDBACK_IN_PRODUCTION=ON)
_sb_crp_gate_case(agent_cluster_stub_live_claim FALSE
  ${_sb_base_args} -DSB_AGENT_CLUSTER_STUB_LIVE_CLAIMS=ON)
_sb_crp_gate_case(optimizer_cluster_stub_live_claim FALSE
  ${_sb_base_args} -DSB_OPTIMIZER_ALLOW_CLUSTER_STUB_LIVE_CLAIMS=ON)
_sb_crp_gate_case(cluster_stub_link TRUE
  ${_sb_base_args} -DSB_CLUSTER_PROVIDER_STUB=ON)
_sb_crp_gate_case(no_cluster_claim FALSE
  ${_sb_base_args} -DSB_COMMERCIAL_CLUSTER_PRODUCTION_CLAIMS=ON)
_sb_crp_gate_case(no_cluster_claim_allowed_flag FALSE
  ${_sb_base_args} -DSB_COMMERCIAL_CLUSTER_PRODUCTION_CLAIMS=ON -DSB_COMMERCIAL_ALLOW_NO_CLUSTER_PRODUCTION_CLAIMS=ON)
_sb_crp_gate_case(cluster_stub_claim FALSE
  ${_sb_base_args} -DSB_ENABLE_CLUSTER_PROVIDER=ON -DSB_CLUSTER_PROVIDER_STUB=ON -DSB_COMMERCIAL_CLUSTER_PRODUCTION_CLAIMS=ON)
_sb_crp_gate_case(no_external_provider_claim FALSE
  ${_sb_base_args} -DSB_ENABLE_CLUSTER_PROVIDER=ON -DSB_COMMERCIAL_CLUSTER_PRODUCTION_CLAIMS=ON)
_sb_crp_gate_case(external_provider_claim TRUE
  ${_sb_base_args} -DSB_ENABLE_CLUSTER_PROVIDER=ON -DSB_COMMERCIAL_CLUSTER_PRODUCTION_CLAIMS=ON -DSB_CLUSTER_PROVIDER_EXTERNAL_LIBRARY=/opt/scratchbird/lib/libsb_cluster_provider.so)
_sb_crp_gate_case(debug_logs FALSE
  ${_sb_base_args} -DSCRATCHBIRD_ENABLE_DEBUG_LOGS=ON)
_sb_crp_gate_case(hotpath_trace FALSE
  ${_sb_base_args} -DSCRATCHBIRD_ENABLE_HOTPATH_TRACE=ON)
_sb_crp_gate_case(exec_profile_trace FALSE
  ${_sb_base_args} -DSCRATCHBIRD_ENABLE_EXEC_PROFILE_TRACE=ON)
_sb_crp_gate_case(prepared_trace FALSE
  ${_sb_base_args} -DSCRATCHBIRD_ENABLE_PREPARED_TRACE=ON)
_sb_crp_gate_case(non_production_bootstrap TRUE
  -DSB_COMMERCIAL_READINESS_PRODUCTION_BUILD=OFF
  -DSB_NONCLUSTER_ENGINE_PROFILE=bootstrap
  -DSB_AGENT_ALLOW_FIXTURE_AUTH_IN_PRODUCTION=ON
  -DSB_AGENT_ALLOW_FIXTURE_POLICY_IN_PRODUCTION=ON
  -DSB_AGENT_ALLOW_RELAXED_METRICS_IN_PRODUCTION=ON
  -DSB_AGENT_ALLOW_TEST_SEEDS_IN_PRODUCTION=ON
  -DSB_AGENT_ALLOW_FORCED_COLLISION_HOOKS_IN_PRODUCTION=ON
  -DSB_AGENT_ALLOW_SIDECAR_STATE_IN_PRODUCTION=ON
  -DSB_AGENT_ALLOW_SIMULATED_ACTUATORS_IN_PRODUCTION=ON
  -DSB_AGENT_ALLOW_DEBUG_ONLY_PATHS_IN_PRODUCTION=ON
  -DSB_AGENT_CLUSTER_STUB_LIVE_CLAIMS=ON
  -DSB_OPTIMIZER_ALLOW_FIXTURE_STATS_IN_PRODUCTION=ON
  -DSB_OPTIMIZER_ALLOW_LOCAL_DEFAULT_STATS_IN_PRODUCTION=ON
  -DSB_OPTIMIZER_ALLOW_POLICY_DEFAULT_STATS_IN_PRODUCTION=ON
  -DSB_OPTIMIZER_ALLOW_RELAXED_METRICS_IN_PRODUCTION=ON
  -DSB_OPTIMIZER_ALLOW_PLACEHOLDER_RUNTIME_EVIDENCE_IN_PRODUCTION=ON
  -DSB_OPTIMIZER_ALLOW_DONOR_AUTHORITY_IN_PRODUCTION=ON
  -DSB_OPTIMIZER_ALLOW_PARSER_SHORTCUTS_IN_PRODUCTION=ON
  -DSB_OPTIMIZER_ALLOW_CLUSTER_STUB_LIVE_CLAIMS=ON
  -DSB_OPTIMIZER_ALLOW_DEBUG_ONLY_PATHS_IN_PRODUCTION=ON
  -DSB_OPTIMIZER_ALLOW_SYNTHETIC_FEEDBACK_IN_PRODUCTION=ON
  -DSB_COMMERCIAL_ALLOW_FIXTURE_AUTH_IN_PRODUCTION=ON
  -DSB_COMMERCIAL_ALLOW_TEST_SEEDS_IN_PRODUCTION=ON
  -DSB_COMMERCIAL_ALLOW_FORCED_COLLISION_HOOKS_IN_PRODUCTION=ON
  -DSB_COMMERCIAL_ALLOW_STUB_PROVIDERS_IN_PRODUCTION=ON
  -DSB_COMMERCIAL_ALLOW_DEBUG_CREDENTIALS_IN_PRODUCTION=ON
  -DSB_COMMERCIAL_ALLOW_DEBUG_ONLY_AUTHORITY_PATHS_IN_PRODUCTION=ON
  -DSB_COMMERCIAL_ALLOW_NO_CLUSTER_PRODUCTION_CLAIMS=ON
  -DSB_COMMERCIAL_CLUSTER_PRODUCTION_CLAIMS=ON
  -DSB_ENABLE_CLUSTER_PROVIDER=ON
  -DSB_CLUSTER_PROVIDER_STUB=ON
  -DSCRATCHBIRD_ENABLE_DEBUG_LOGS=ON
  -DSCRATCHBIRD_ENABLE_HOTPATH_TRACE=ON
  -DSCRATCHBIRD_ENABLE_EXEC_PROFILE_TRACE=ON
  -DSCRATCHBIRD_ENABLE_PREPARED_TRACE=ON)

message(STATUS "commercial_readiness_production_build_cmake_gate=passed")
