# Copyright (c) 2026 ScratchBird Software Inc.
# SPDX-License-Identifier: MPL-2.0

# Type Name        ID GECOS                         Home                    Shell
g      scratchbird -
u      scratchbird -  "ScratchBird service account" /var/lib/scratchbird /usr/sbin/nologin
m      scratchbird scratchbird
