# Copyright (c) 2026 ScratchBird Software Inc.
# SPDX-License-Identifier: MPL-2.0

d /var/lib/scratchbird              0750 root        scratchbird -
d /var/lib/scratchbird/data         0750 scratchbird scratchbird -
d /var/lib/scratchbird/install      0750 root        scratchbird -
d /var/log/scratchbird              0750 scratchbird scratchbird -
d /run/scratchbird                  0750 scratchbird scratchbird -
d /run/scratchbird/control          0750 scratchbird scratchbird -
d /run/scratchbird/runtime          0750 scratchbird scratchbird -
d /run/scratchbird/listener         0750 scratchbird scratchbird -
d /run/scratchbird/listener/control 0750 scratchbird scratchbird -
d /run/scratchbird/listener/runtime 0750 scratchbird scratchbird -
d /run/scratchbird/manager          0750 scratchbird scratchbird -
d /run/scratchbird/manager/control  0750 scratchbird scratchbird -
d /run/scratchbird/manager/runtime  0750 scratchbird scratchbird -
