// Copyright (c) 2026 ScratchBird Software Inc.
// SPDX-License-Identifier: MPL-2.0
#include "datatype_interval_projection.hpp"
#include <array>
#include <cstdlib>
#include <iostream>
#include <memory>
#include <string_view>
namespace dt=scratchbird::core::datatypes;namespace p=scratchbird::core::platform;
namespace{unsigned checks;void Check(bool v,std::string_view m){++checks;if(!v){std::cerr<<"FAIL "<<m<<'\n';std::exit(EXIT_FAILURE);}}p::Uuid Uuid(p::byte tail){std::array<p::byte,16>b{};b[0]=1;b[6]=0x70;b[8]=0x80;b[15]=tail;return p::Uuid(b);}p::Uuid D710(){auto x=Uuid(0x10);x.bytes[1]=0x9d;x.bytes[14]=0xd7;return x;}std::shared_ptr<const dt::IntervalValidatedProfileHandleV3> Profile(){auto x=dt::BuildCurrentIntervalValidatedProfileHandleV3(D710());Check(x.ok(),"profile");return std::make_shared<const dt::IntervalValidatedProfileHandleV3>(std::move(x.profile));}dt::IntervalOwnedValueV3 Value(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& p){auto x=dt::ConstructIntervalV3(p,-7,11,-13);Check(x.ok(),"value");return std::move(x.value);}
void IndexFamilies(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& profile){constexpr std::array<dt::IntervalIndexDispositionV3,16>want{{dt::IntervalIndexDispositionV3::not_applicable,dt::IntervalIndexDispositionV3::admitted_with_recheck,dt::IntervalIndexDispositionV3::not_applicable,dt::IntervalIndexDispositionV3::not_applicable,dt::IntervalIndexDispositionV3::not_applicable,dt::IntervalIndexDispositionV3::admitted_payload_only,dt::IntervalIndexDispositionV3::not_applicable,dt::IntervalIndexDispositionV3::conditional,dt::IntervalIndexDispositionV3::not_applicable,dt::IntervalIndexDispositionV3::not_applicable,dt::IntervalIndexDispositionV3::admitted_with_recheck,dt::IntervalIndexDispositionV3::conditional,dt::IntervalIndexDispositionV3::not_applicable,dt::IntervalIndexDispositionV3::not_applicable,dt::IntervalIndexDispositionV3::conditional,dt::IntervalIndexDispositionV3::not_applicable}};auto value=Value(profile);for(unsigned n=0;n<16;++n){auto family=static_cast<dt::IntervalIndexFamilyV3>(n);auto identity=dt::LookupIntervalIndexCompatibilityIdentityV3(family);auto admitted=dt::AdmitIntervalIndexCompatibilityV3(identity);auto resolution=dt::ResolveIntervalIndexFamilyV3(family);Check(admitted.admitted&&resolution.compatibility_uuid==identity.compatibility_uuid&&identity.compatibility_generation==1,"16 authenticated compatibility identities");Check(resolution.disposition==want[n],"16 exact index dispositions");for(auto op:{dt::IntervalIndexPredicateOperationV3::range,dt::IntervalIndexPredicateOperationV3::order,dt::IntervalIndexPredicateOperationV3::prune_range,dt::IntervalIndexPredicateOperationV3::overlap,dt::IntervalIndexPredicateOperationV3::exclusion}){auto p=dt::ResolveIntervalIndexPredicateV3({identity,op,nullptr});Check(!p.admitted&&p.diagnostic=="CTI.TEMPORAL.ORDERING_REFUSED","ordered predicate refused");}}
 for(auto f:{dt::IntervalIndexFamilyV3::bitmap,dt::IntervalIndexFamilyV3::hash}){dt::IntervalIndexProjectionRequestV3 q;q.compatibility=dt::LookupIntervalIndexCompatibilityIdentityV3(f);q.mode=dt::IntervalProjectionModeV3::equality_hash;q.value=&value;auto projected=dt::ProjectIntervalIndexValueV3(q);Check(projected.ok()&&projected.bytes.size()==160,"SBINIH01 equality candidate");auto fact=dt::ClassifyIntervalIndexCandidateV3(dt::IntervalIndexPredicateFactV3::requires_exact_state_component_recheck_never_final_match,true,true,true);Check(fact.final_match&&fact.disposition==dt::IntervalIndexCandidateDispositionV3::exact_match,"exact component recheck makes final match");auto collision=dt::ClassifyIntervalIndexCandidateV3(dt::IntervalIndexPredicateFactV3::requires_exact_state_component_recheck_never_final_match,true,false,true);Check(!collision.final_match&&collision.exact_state_component_recheck_required&&collision.disposition==dt::IntervalIndexCandidateDispositionV3::exact_state_component_recheck_required,"hash candidate requires exact component recheck");}
 auto covering=dt::EncodeIntervalCoveringValueV3(value);Check(covering.ok()&&covering.bytes.size()==17,"covering value extent");auto decoded=dt::DecodeIntervalCoveringValueNoAllocV3(*profile,true,covering.bytes);Check(decoded.ok()&&decoded.value.months==-7&&decoded.value.civil_days==11&&decoded.value.fixed_nanoseconds==-13,"covering roundtrip");}
void Statistics(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& profile){auto v=Value(profile);auto hashed=dt::HashIntervalValueV3(v);Check(hashed.ok(),"value hash");auto evidence=std::make_shared<dt::IntervalStatisticsProviderEvidenceHandleV3>();evidence->provider_evidence_uuid=Uuid(1);evidence->source_object_uuid=Uuid(2);evidence->authenticated_population=true;evidence->source_authorized=true;evidence->privacy_admitted=true;evidence->schema_epoch=3;evidence->collection_epoch=4;evidence->security_epoch=5;evidence->row_count=10;evidence->null_count=2;evidence->value_count=8;evidence->equality_distinct_estimate=1;dt::IntervalStatisticsMcvRecordV3 record;std::copy(hashed.bytes.begin(),hashed.bytes.end(),record.value_hash.begin());record.frequency=8;record.rank=1;record.flags=1;evidence->mcv.push_back(record);dt::IntervalStatisticsProjectionV3 projection;projection.profile=profile;projection.provider_evidence=evidence;projection.statistics_snapshot_uuid=Uuid(6);projection.source_object_uuid=evidence->source_object_uuid;projection.schema_epoch=3;projection.collection_epoch=4;projection.security_epoch=5;projection.row_count=10;projection.null_count=2;projection.value_count=8;projection.equality_distinct_estimate=1;projection.mcv=evidence->mcv;auto encoded=dt::EncodeIntervalStatisticsProjectionV3(projection);Check(encoded.ok()&&encoded.bytes.size()==496,"SBINTS01 one MCV extent");dt::IntervalStatisticsReceivingFactsV3 facts;facts.security_visible=true;facts.privacy_admitted=true;facts.source_object_uuid=Uuid(2);facts.provider_evidence_uuid=Uuid(1);facts.schema_epoch=3;facts.collection_epoch=4;facts.security_epoch=5;auto decoded=dt::DecodeIntervalStatisticsProjectionV3(profile,encoded.bytes,facts);Check(decoded.ok()&&decoded.statistics.row_count==10&&decoded.statistics.null_count==2&&decoded.statistics.value_count==8&&decoded.statistics.mcv.size()==1,"equality statistics decode");auto admitted=dt::AdmitIntervalStatisticsReadV3(profile,encoded.bytes,facts);Check(admitted.ok()&&admitted.receiving_owner_enforcement_required,"statistics owner enforcement");facts.privacy_admitted=false;auto denied=dt::AdmitIntervalStatisticsReadV3(profile,encoded.bytes,facts);Check(!denied.ok()&&!denied.decode_attempted&&denied.mcv_records_read==0,"privacy denial before decode");facts.privacy_admitted=true;facts.schema_epoch=99;Check(!dt::AdmitIntervalStatisticsReadV3(profile,encoded.bytes,facts).ok(),"schema epoch mismatch");facts.schema_epoch=3;facts.provider_evidence_uuid=Uuid(9);Check(!dt::AdmitIntervalStatisticsReadV3(profile,encoded.bytes,facts).ok(),"provider evidence mismatch");}
}
int main(){auto profile=Profile();IndexFamilies(profile);Statistics(profile);std::cout<<"PASS checks="<<checks<<" index_families=16 ordered_statistics=false equality_only=true\n";}
