// Copyright (c) 2026 ScratchBird Software Inc.
// SPDX-License-Identifier: MPL-2.0
#include "datatype_interval_projection.hpp"
#include <array>
#include <atomic>
#include <cstdlib>
#include <iostream>
#include <memory>
#include <string_view>
#include <thread>
#include <vector>
namespace dt=scratchbird::core::datatypes;namespace p=scratchbird::core::platform;
namespace{unsigned checks;void Check(bool v,std::string_view m){++checks;if(!v){std::cerr<<"FAIL "<<m<<'\n';std::exit(EXIT_FAILURE);}}p::Uuid Uuid(p::byte tail){std::array<p::byte,16>b{};b[0]=1;b[6]=0x70;b[8]=0x80;b[15]=tail;return p::Uuid(b);}p::Uuid D710(){auto x=Uuid(0x10);x.bytes[1]=0x9d;x.bytes[14]=0xd7;return x;}std::shared_ptr<const dt::IntervalValidatedProfileHandleV3> Profile(){auto x=dt::BuildCurrentIntervalValidatedProfileHandleV3(D710());Check(x.ok(),"profile");return std::make_shared<const dt::IntervalValidatedProfileHandleV3>(std::move(x.profile));}dt::IntervalOwnedValueV3 Value(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& p){auto x=dt::ConstructIntervalV3(p,3,-5,7);Check(x.ok(),"value");return std::move(x.value);}
void Wire(){for(unsigned n=0;n<27;++n){auto r=dt::ResolveIntervalWireLaneV3(static_cast<dt::IntervalWireLaneV3>(n));Check(!r.admitted&&r.receiving_owner_handoff&&r.diagnostic=="CTI.TRANSPORT.UNSUPPORTED","27 lanes refused");Check(r.component_mapping_complete==(n<3),"native component mapping only");Check(r.disposition==(n<3?"unsupported_current_outer_version_unallocated":"unsupported_no_manifest_listed_compatibility_profile"),"wire disposition");}}
void Protection(const dt::IntervalValidatedProfileHandleV3& profile){for(unsigned n=0;n<10;++n){auto r=dt::ResolveIntervalProtectionV3(static_cast<dt::IntervalProtectionCellV3>(n));Check(r.datatype_admitted==(n==0),"protection cells");}for(unsigned s=0;s<4;++s)for(unsigned w=0;w<4;++w)for(unsigned i=0;i<2;++i){auto r=dt::AdmitIntervalProtectionCombinationV3(profile,static_cast<dt::IntervalProtectionModeV3>(s),static_cast<dt::IntervalProtectionModeV3>(w),static_cast<dt::IntervalProtectionIndexModeV3>(i));Check(r.admitted==(s==0&&w==0),"only clear/clear protection admitted");if(!r.admitted)Check(r.diagnostic=="CTI.TEMPORAL.PROTECTION_UNSUPPORTED","protection diagnostic");}}
void Metrics(const dt::IntervalValidatedProfileHandleV3& profile){auto types=dt::IntervalMetricEvidenceTypesV3();auto routes=dt::IntervalDiagnosticMetricRoutesV3();Check(types.size()==5,"five metric evidence types");Check(routes.size()==37,"37 diagnostic routes");Check(dt::ValidateIntervalDiagnosticMetricRouteTableV3(routes)==dt::IntervalDiagnosticMetricRouteDispositionV3::admitted,"route table exact");for(const auto&t:types){Check(!t.evidence_type_uuid.is_nil()&&!t.metric_uuid.is_nil()&&t.generation==1,"metric identity");for(auto banned:{"component_value","canonical_text","encoded_bytes","raw_bytes","hash_preimage","secret","address","diagnostic_prose","reference_engine_name"})Check(t.closed_label_schema.find(banned)==std::string_view::npos,"closed labels redact payload/prose");}
 const auto& route=routes.front();dt::IntervalMetricClosedLabelTupleV3 labels;bool found=false;for(unsigned op=0;op<15&&!found;++op)for(unsigned source=0;source<6&&!found;++source)for(unsigned state=0;state<4&&!found;++state){labels.operation=static_cast<dt::IntervalMetricOperationV3>(op);labels.source_family=static_cast<dt::IntervalMetricSourceFamilyV3>(source);labels.state=static_cast<dt::IntervalMetricStateV3>(state);labels.reason=route.reason;found=dt::IsIntervalMetricLabelTupleAdmittedV3(route,labels);}Check(found,"one closed label tuple");dt::IntervalMetricEvidenceProductionRequestV3 request;request.selected_final_diagnostic=route.key;request.source_event_uuid=Uuid(20);request.database_uuid=Uuid(21);request.node_uuid=Uuid(22);request.process_epoch=4;request.event_sequence=5;request.monotonic_timestamp_ns=6;request.operation=labels.operation;request.source_family=labels.source_family;request.state=labels.state;auto produced=dt::ProduceIntervalMetricEvidenceV3(profile,request);Check(produced.ok()&&produced.receiving_owner_evidence_handoff_ready&&!produced.metric_mutation_admitted,"typed evidence handoff only");auto evidence=produced.evidence;evidence.outcome_committed=true;dt::IntervalMetricEvidenceValidationContextV3 context{4,0};auto valid=dt::ValidateIntervalMetricEvidenceV3(profile,route.key,evidence,context);Check(valid.ok()&&valid.receiving_owner_update_admitted,"owner may apply once");auto replay=dt::ClassifyIntervalMetricReplayV3(evidence,evidence);Check(replay.disposition==dt::IntervalMetricReplayDispositionV3::exact_duplicate_idempotent&&replay.idempotent_without_increment&&!replay.second_emission_admitted,"exact replay idempotent");}
void PinnedReaders(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& profile){auto value=Value(profile);std::atomic<unsigned> failures{0};std::vector<std::thread> readers;for(unsigned t=0;t<8;++t)readers.emplace_back([&,profile,value]{for(unsigned n=0;n<4096;++n){auto valid=dt::ValidateIntervalProfileHandleV3(*profile);auto hash=dt::HashIntervalValueV3(value);if(!valid.ok()||!hash.ok()||hash.bytes.size()!=32)++failures;}});for(auto&thread:readers)thread.join();Check(failures==0,"eight immutable readers x 4096");}
void ObserveScrub(void* context,dt::IntervalScrubClassV3 which,const p::byte*,p::u64) noexcept{auto* seen=static_cast<std::array<bool,static_cast<unsigned>(dt::IntervalScrubClassV3::count)>*>(context);(*seen)[static_cast<unsigned>(which)]=true;}
void Cleanup(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& profile){auto value=Value(profile);std::array<bool,static_cast<unsigned>(dt::IntervalScrubClassV3::count)> seen{};dt::IntervalExecutionControlV3 control;control.observe_scrubbed=ObserveScrub;control.scrub_observer_context=&seen;auto hash=dt::HashIntervalValueV3(value,control);Check(hash.ok(),"hash with cleanup observer");Check(seen[static_cast<unsigned>(dt::IntervalScrubClassV3::hash_preimage)]&&seen[static_cast<unsigned>(dt::IntervalScrubClassV3::hash_digest)],"hash scratch scrubbed");}
void AtomicFailures(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& profile){auto value=Value(profile);std::array<p::byte,32> output;output.fill(0xa5);auto before=output;auto shortwrite=dt::HashIntervalValueIntoNoAllocV3(value,output.data(),31);Check(!shortwrite.ok()&&output==before&&shortwrite.bytes_written==0,"one-byte-short hash unchanged");for(unsigned n=0;n<4096;++n){auto encoded=dt::EncodeCanonicalIntervalComponentV3(value);Check(encoded.ok()&&encoded.bytes.size()==16,"4096 publish handoff cycles");auto decoded=dt::DecodeCanonicalIntervalComponentNoAllocV3(*profile,dt::IntervalValueStateV3::value,true,encoded.bytes);Check(decoded.ok()&&decoded.value.profile==profile.get(),"pinned profile handoff");}}
}
int main(){auto profile=Profile();Wire();Protection(*profile);Metrics(*profile);PinnedReaders(profile);Cleanup(profile);AtomicFailures(profile);std::cout<<"PASS checks="<<checks<<" wire_lanes=27 reader_threads=8 reads_per_thread=4096 publication_cycles=4096 metric_routes=37\n";}
