// Copyright (c) 2026 ScratchBird Software Inc.
// SPDX-License-Identifier: MPL-2.0
#include "datatype_interval.hpp"
#include <array>
#include <cstdlib>
#include <iostream>
#include <memory>
#include <string_view>
namespace dt=scratchbird::core::datatypes; namespace p=scratchbird::core::platform;
namespace {unsigned checks;void Check(bool v,std::string_view m){++checks;if(!v){std::cerr<<"FAIL "<<m<<'\n';std::exit(EXIT_FAILURE);}}p::Uuid D710(){return p::Uuid(std::array<p::byte,16>{1,0x9d,0,0,0,0,0x70,0,0x80,0,0,0,0,0,0xd7,0x10});}std::shared_ptr<const dt::IntervalValidatedProfileHandleV3> Profile(){auto x=dt::BuildCurrentIntervalValidatedProfileHandleV3(D710());Check(x.ok(),"profile");return std::make_shared<const dt::IntervalValidatedProfileHandleV3>(std::move(x.profile));}bool Cancel(void*) noexcept{return true;}
void Classification(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& p){auto v=dt::ConstructIntervalV3(p,1,-2,3);Check(v.ok(),"value");for(unsigned n=0;n<13;++n){auto op=static_cast<dt::IntervalIntrinsicOperationV3>(n);auto disposition=dt::ClassifyIntervalIntrinsicOperationV3(op);Check(disposition==(n<7?dt::IntervalIntrinsicDispositionV3::admitted:dt::IntervalIntrinsicDispositionV3::registered_refused),"closed intrinsic classifier");if(n>=7){auto r=dt::RefuseIntervalIntrinsicOperationV3(v.value.view(),op);Check(!r.ok(),"registered intrinsic refuses");if(n==7)Check(r.diagnostic.diagnostic_code=="CTI.INTERVAL.CALENDAR_OPERATION_REFUSED","calendar refusal");else Check(r.diagnostic.diagnostic_code=="CTI.TEMPORAL.ORDERING_REFUSED","no-order refusal");}}Check(dt::ClassifyIntervalIntrinsicOperationV3(static_cast<dt::IntervalIntrinsicOperationV3>(255))==dt::IntervalIntrinsicDispositionV3::unknown,"unknown intrinsic");}
void RefusalApiAdmittedOperationMisuse(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& p){auto v=dt::ConstructIntervalV3(p,1,-2,3);Check(v.ok(),"refusal API misuse value");for(unsigned n=0;n<7;++n){auto r=dt::RefuseIntervalIntrinsicOperationV3(v.value.view(),static_cast<dt::IntervalIntrinsicOperationV3>(n));Check(!r.ok()&&r.diagnostic.diagnostic_code=="SBLR.OPERAND_INVALID","admitted operation refused as API misuse");}}
void ExactOperations(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& p){auto v=dt::ConstructIntervalV3(p,-12,34,-56);Check(v.ok(),"construct present");auto d=dt::DecomposeIntervalV3(v.value.view());Check(d.ok()&&!d.is_null&&d.component.months==-12&&d.component.civil_days==34&&d.component.fixed_nanoseconds==-56,"decompose");auto m=dt::ExtractIntervalMonthsV3(v.value.view()),days=dt::ExtractIntervalCivilDaysV3(v.value.view()),ns=dt::ExtractIntervalFixedNanosecondsV3(v.value.view());Check(m.ok()&&m.kind==dt::IntervalScalarKindV3::months_i32&&m.signed_i32_value==-12&&m.signed_i64_value==0,"months extraction width");Check(days.ok()&&days.kind==dt::IntervalScalarKindV3::civil_days_i32&&days.signed_i32_value==34&&days.signed_i64_value==0,"day extraction width");Check(ns.ok()&&ns.kind==dt::IntervalScalarKindV3::fixed_nanoseconds_i64&&ns.signed_i32_value==0&&ns.signed_i64_value==-56,"nanoseconds extraction width");auto neg=dt::NegateIntervalCheckedV3(v.value);Check(neg.ok()&&neg.value.months==12&&neg.value.civil_days==-34&&neg.value.fixed_nanoseconds==56,"checked negate");auto min32=dt::ConstructIntervalV3(p,INT32_MIN,0,0),min64=dt::ConstructIntervalV3(p,0,0,INT64_MIN);Check(!dt::NegateIntervalCheckedV3(min32.value).ok()&&!dt::NegateIntervalCheckedV3(min64.value).ok(),"negate signed minima refuses");auto max=dt::ConstructIntervalV3(p,INT32_MAX,INT32_MAX,INT64_MAX),one=dt::ConstructIntervalV3(p,1,1,1);Check(!dt::AddIntervalCheckedV3(max.value,one.value).ok(),"add component overflow atomic");auto min=dt::ConstructIntervalV3(p,INT32_MIN,INT32_MIN,INT64_MIN);Check(!dt::SubtractIntervalCheckedV3(min.value,one.value).ok(),"subtract component overflow atomic");}
void NullPropagation(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& p){dt::IntervalOwnedValueV3 n{p,dt::IntervalValueStateV3::sql_null,0,0,0};Check(dt::ValidateIntervalValueViewV3(n.view(),true).ok(),"NULL validate");Check(dt::CanonicalizeIntervalIdentityV3(n,true).ok(),"NULL canonicalize");Check(dt::DecomposeIntervalV3(n.view(),true).ok(),"NULL decompose");Check(dt::NegateIntervalCheckedV3(n,true).ok(),"NULL negate");Check(dt::AddIntervalCheckedV3(n,n,true).ok(),"NULL add");Check(dt::SubtractIntervalCheckedV3(n,n,true).ok(),"NULL subtract");Check(dt::ExtractIntervalMonthsV3(n.view(),true).is_null,"NULL months");Check(dt::ExtractIntervalCivilDaysV3(n.view(),true).is_null,"NULL days");Check(dt::ExtractIntervalFixedNanosecondsV3(n.view(),true).is_null,"NULL nanoseconds");Check(dt::EqualIntervalValuesV3(n.view(),n.view()).fact==dt::IntervalEqualityFactV3::unordered_null,"NULL equality unordered");Check(dt::HashIntervalValueV3(n).ok(),"NULL hash defined");for(unsigned x=7;x<13;++x){auto r=dt::RefuseIntervalIntrinsicOperationV3(n.view(),static_cast<dt::IntervalIntrinsicOperationV3>(x));Check(!r.ok(),"NULL does not admit refused intrinsic");}}
void NullAndControl(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& p){dt::IntervalOperandV3 operand;operand.profile=p;operand.state=dt::IntervalValueStateV3::sql_null;auto admitted=dt::AdmitIntervalOperandV3(operand,true);Check(admitted.ok()&&admitted.value.state==dt::IntervalValueStateV3::sql_null,"clean NULL admitted");Check(!dt::AdmitIntervalOperandV3(operand,false).ok(),"NULL not admitted");auto present=dt::ConstructIntervalV3(p,1,2,3);dt::IntervalExecutionControlV3 c;c.cancelled=Cancel;auto before=dt::RenderCanonicalIntervalV3(present.value,c);Check(!before.ok()&&before.text.empty(),"cancellation before publication");c={};c.maximum_allocation_bytes=0;auto allocation=dt::RenderCanonicalIntervalV3(present.value,c);Check(!allocation.ok()&&allocation.text.empty(),"allocation refusal no partial text");}
void CancellationMatrix(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& p){auto value=dt::ConstructIntervalV3(p,1,2,3);Check(value.ok(),"cancellation value");dt::IntervalExecutionControlV3 c;c.cancelled=Cancel;Check(!dt::ConstructIntervalV3(p,1,2,3,true,c).ok(),"construct cancellation");Check(!dt::CanonicalizeIntervalIdentityV3(value.value,true,c).ok(),"canonicalize cancellation");Check(!dt::DecomposeIntervalV3(value.value.view(),true,c).ok(),"decompose cancellation");Check(!dt::NegateIntervalCheckedV3(value.value,true,c).ok(),"negate cancellation");Check(!dt::AddIntervalCheckedV3(value.value,value.value,true,c).ok(),"add cancellation");Check(!dt::SubtractIntervalCheckedV3(value.value,value.value,true,c).ok(),"subtract cancellation");Check(!dt::ExtractIntervalMonthsV3(value.value.view(),true,c).ok(),"months cancellation");Check(!dt::ExtractIntervalCivilDaysV3(value.value.view(),true,c).ok(),"days cancellation");Check(!dt::ExtractIntervalFixedNanosecondsV3(value.value.view(),true,c).ok(),"nanoseconds cancellation");Check(!dt::EqualIntervalValuesV3(value.value.view(),value.value.view(),c).ok(),"equality cancellation");Check(!dt::DistinctIntervalValuesV3(value.value.view(),value.value.view(),c).ok(),"distinct cancellation");}
}
int main(){auto p=Profile();Classification(p);RefusalApiAdmittedOperationMisuse(p);ExactOperations(p);NullPropagation(p);NullAndControl(p);CancellationMatrix(p);std::cout<<"PASS checks="<<checks<<" intrinsic_rows=13 present_and_null=true no_order=true calendar_application=false\n";}
