// Copyright (c) 2026 ScratchBird Software Inc.
// SPDX-License-Identifier: MPL-2.0
#include "datatype_interval.hpp"
#include "datatype_interval_projection.hpp"
#include <array>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <memory>
#include <string_view>
#include <vector>
namespace dt=scratchbird::core::datatypes; namespace p=scratchbird::core::platform;
namespace {unsigned checks;constexpr p::u64 kMalformedSeed=0x5342494e46415a5aull;constexpr std::string_view kMalformedMapping="base.interval.malformed.frames.v1";void Check(bool v,std::string_view m){++checks;if(!v){std::cerr<<"FAIL "<<m<<'\n';std::exit(EXIT_FAILURE);}}void Malformed(bool v,std::string_view m,p::u64 n){++checks;if(!v){std::cerr<<"FAIL "<<m<<" mapping="<<kMalformedMapping<<" seed=0x"<<std::hex<<kMalformedSeed<<std::dec<<" ordinal="<<n<<'\n';std::exit(EXIT_FAILURE);}}p::u64 Next(p::u64& x){x+=0x9e3779b97f4a7c15ull;p::u64 z=x;z=(z^(z>>30))*0xbf58476d1ce4e5b9ull;z=(z^(z>>27))*0x94d049bb133111ebull;return z^(z>>31);}
p::Uuid D710(){return p::Uuid(std::array<p::byte,16>{1,0x9d,0,0,0,0,0x70,0,0x80,0,0,0,0,0,0xd7,0x10});}std::shared_ptr<const dt::IntervalValidatedProfileHandleV3> Profile(){auto x=dt::BuildCurrentIntervalValidatedProfileHandleV3(D710());Check(x.ok(),"profile");return std::make_shared<const dt::IntervalValidatedProfileHandleV3>(std::move(x.profile));}dt::IntervalOwnedValueV3 Value(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& p,dt::IntervalValueStateV3 s=dt::IntervalValueStateV3::value){auto x=dt::ConstructIntervalV3(p,-17,29,-43);Check(x.ok(),"value");if(s==dt::IntervalValueStateV3::sql_null){dt::IntervalOperandV3 o;o.profile=p;o.state=s;auto n=dt::AdmitIntervalOperandV3(o,true);Check(n.ok(),"null");return {p,s,0,0,0};}return std::move(x.value);}
void Frames(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& p){for(auto state:{dt::IntervalValueStateV3::value,dt::IntervalValueStateV3::sql_null}){auto v=Value(p,state);auto a=dt::EncodeIntervalSbdvalComposedV3(v,true),b=dt::EncodeIntervalSbdpvComposedV3(v,true);Check(a.ok()&&a.bytes.size()==(state==dt::IntervalValueStateV3::value?48:32),"SBDVAL01 extent");Check(b.ok()&&b.bytes.size()==(state==dt::IntervalValueStateV3::value?40:24),"SBDPV001 extent");auto ad=dt::DecodeIntervalSbdvalComposedNoAllocV3(*p,true,a.bytes),bd=dt::DecodeIntervalSbdpvComposedNoAllocV3(*p,true,b.bytes);Check(ad.ok()&&bd.ok()&&ad.value.state==state&&bd.value.state==state,"composed roundtrip");for(std::size_t n=0;n<a.bytes.size();++n)Check(!dt::DecodeIntervalSbdvalComposedNoAllocV3(*p,true,std::span<const p::byte>(a.bytes.data(),n)).ok(),"SBDVAL truncation boundary");for(std::size_t n=0;n<b.bytes.size();++n)Check(!dt::DecodeIntervalSbdpvComposedNoAllocV3(*p,true,std::span<const p::byte>(b.bytes.data(),n)).ok(),"SBDPV truncation boundary");}}
void OpaqueCloseReopen(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& p){auto v=Value(p);auto encoded=dt::EncodeIntervalSbdpvComposedV3(v,true);Check(encoded.ok(),"physical encode");auto path=std::filesystem::temp_directory_path()/"scratchbird_base_interval_d710_component.bin";{std::ofstream out(path,std::ios::binary|std::ios::trunc);out.write(reinterpret_cast<const char*>(encoded.bytes.data()),static_cast<std::streamsize>(encoded.bytes.size()));Check(bool(out),"component persist");}{std::ifstream in(path,std::ios::binary);std::vector<p::byte> reopened((std::istreambuf_iterator<char>(in)),{});Check(reopened==encoded.bytes,"opaque close reopen bytes");auto decoded=dt::DecodeIntervalSbdpvComposedNoAllocV3(*p,true,reopened);Check(decoded.ok()&&decoded.value.months==-17&&decoded.value.civil_days==29&&decoded.value.fixed_nanoseconds==-43,"opaque close reopen decode");}std::filesystem::remove(path);}
void Batches(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& p){for(p::u64 n:{0ull,1ull,7ull,8ull,9ull,1024ull,65536ull}){p::u64 exact=n*16+(n+7)/8;auto extent=dt::ComputeIntervalBatchExtentsV3(n,exact);Check(extent.ok()&&extent.combined_bytes==exact,"batch exact extent formula");if(exact)Check(!dt::ComputeIntervalBatchExtentsV3(n,exact-1).ok(),"batch one byte short");std::vector<std::int32_t> m(n,1),d(n,-2);std::vector<std::int64_t> ns(n,3);std::vector<p::byte> bits((n+7)/8,0);dt::IntervalExecutionControlV3 c;c.maximum_allocation_bytes=exact;auto batch=dt::MaterializeIntervalBatchV3(p,m,d,ns,bits,c);Check(batch.ok()&&batch.batch.months.size()==n&&batch.batch.profile==p,"batch atomic materialization");if(exact){c.maximum_allocation_bytes=exact-1;auto refused=dt::MaterializeIntervalBatchV3(p,m,d,ns,bits,c);Check(!refused.ok()&&refused.batch.months.empty()&&refused.batch.profile==nullptr,"batch one-short atomic refusal");}}}
void BackupAndMalformed(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& p){auto v=Value(p),n=Value(p,dt::IntervalValueStateV3::sql_null);auto present=dt::EncodeIntervalBackupTupleV3(v),nullv=dt::EncodeIntervalBackupTupleV3(n);Check(present.ok()&&present.bytes.size()==376,"SBINBK01 present extent");Check(nullv.ok()&&nullv.bytes.size()==360,"SBINBK01 null extent");Check(dt::DecodeIntervalBackupTupleNoAllocV3(*p,true,present.bytes).ok()&&dt::DecodeIntervalBackupTupleNoAllocV3(*p,true,nullv.bytes).ok(),"backup roundtrip");for(std::size_t off=360;off<376;++off){auto bad=present.bytes;bad[off]^=1;Check(!dt::DecodeIntervalBackupTupleNoAllocV3(*p,true,bad).ok(),"backup component digest coverage");}for(std::size_t off=328;off<360;++off){auto bad=present.bytes;bad[off]^=1;Check(!dt::DecodeIntervalBackupTupleNoAllocV3(*p,true,bad).ok(),"backup digest corruption");}
 auto frame=dt::EncodeIntervalSbdvalComposedV3(v,true);p::u64 random=kMalformedSeed;for(p::u64 ordinal=0;ordinal<8192;++ordinal){std::size_t extent=Next(random)%frame.bytes.size();Malformed(!dt::DecodeIntervalSbdvalComposedNoAllocV3(*p,true,std::span<const p::byte>(frame.bytes.data(),extent)).ok(),"deterministic malformed truncation",ordinal);}}
}
int main(){auto p=Profile();Frames(p);OpaqueCloseReopen(p);Batches(p);BackupAndMalformed(p);std::cout<<"PASS checks="<<checks<<" malformed_mapping="<<kMalformedMapping<<" malformed_seed=0x"<<std::hex<<kMalformedSeed<<std::dec<<" malformed_cases=8192 max_batch_bytes=1056768\n";}
