// Copyright (c) 2026 ScratchBird Software Inc.
// SPDX-License-Identifier: MPL-2.0
#include "datatype_interval.hpp"
#include <array>
#include <algorithm>
#include <cstdlib>
#include <iostream>
#include <limits>
#include <memory>
#include <string_view>
namespace dt=scratchbird::core::datatypes; namespace p=scratchbird::core::platform;
namespace { unsigned checks; constexpr p::u64 kSeed=0x5342494e54455256ull; constexpr std::string_view kMapping="base.interval.property.splitmix64.v1";
void Check(bool v,std::string_view m){++checks;if(!v){std::cerr<<"FAIL "<<m<<'\n';std::exit(EXIT_FAILURE);}}
void Property(bool v,std::string_view m,p::u64 ordinal){++checks;if(!v){std::cerr<<"FAIL "<<m<<" mapping="<<kMapping<<" seed=0x"<<std::hex<<kSeed<<std::dec<<" ordinal="<<ordinal<<'\n';std::exit(EXIT_FAILURE);}}
p::u64 Next(p::u64& x){x+=0x9e3779b97f4a7c15ull;p::u64 z=x;z=(z^(z>>30))*0xbf58476d1ce4e5b9ull;z=(z^(z>>27))*0x94d049bb133111ebull;return z^(z>>31);}
p::Uuid D710(){return p::Uuid(std::array<p::byte,16>{1,0x9d,0,0,0,0,0x70,0,0x80,0,0,0,0,0,0xd7,0x10});}
std::shared_ptr<const dt::IntervalValidatedProfileHandleV3> Profile(){auto p=dt::BuildCurrentIntervalValidatedProfileHandleV3(D710());Check(p.ok(),"profile");return std::make_shared<const dt::IntervalValidatedProfileHandleV3>(std::move(p.profile));}
const dt::DatatypeTypeCodecIdentityRowV3* Identity(dt::CanonicalTypeId type){for(const auto& row:dt::CurrentDatatypeTypeCodecIdentityRowsV3())if(row.legacy_fields.canonical_binary_type_code==static_cast<p::u32>(type)&&row.legacy_fields.catalog_snapshot_uuid==D710()&&row.legacy_fields.catalog_generation==10&&row.legacy_fields.registry_generation==10)return &row;return nullptr;}
scratchbird::engine::ExecutionTypeDescriptor Descriptor(dt::CanonicalTypeId type){auto m=dt::LoadCurrentCoreDatatypeCatalogManifest();Check(m.ok(),"catalog manifest");auto row=dt::LookupDatatypeCatalogRow(m.manifest,type);Check(row.ok()&&row.manifest.descriptor_rows.size()==1,"descriptor row");dt::CatalogExecutionTypeMetadata md;md.descriptor_uuid=row.manifest.descriptor_rows.front().descriptor_uuid;md.descriptor_epoch=row.manifest.descriptor_rows.front().descriptor_epoch;auto d=dt::LookupExecutionTypeDescriptorFromCatalog(type,md);Check(d.ok(),"execution descriptor");return d.descriptor;}
dt::IntervalOwnedValueV3 Value(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& p,std::int32_t m,std::int32_t d,std::int64_t n){auto x=dt::ConstructIntervalV3(p,m,d,n);Check(x.ok(),"construct");return std::move(x.value);}
void CastAudit(){using C=dt::DatatypeCastContext;for(p::u32 row=1;row<=221;++row){for(C c:{C::implicit,C::assignment,C::explicit_cast}){auto got=dt::ClassifyIntervalCastPolicyRowV3(row,c);auto want=dt::IntervalCastPolicyDispositionV3::forbidden;if(row==158)want=dt::IntervalCastPolicyDispositionV3::contextual_null;else if(row==39||row==100||row==210)want=dt::IntervalCastPolicyDispositionV3::identity;else if(row==124&&c==C::explicit_cast)want=dt::IntervalCastPolicyDispositionV3::explicit_character_to_interval;else if(row==13&&c==C::explicit_cast)want=dt::IntervalCastPolicyDispositionV3::explicit_interval_to_character;Check(got==want,"all 663 cast decisions");}}
 Check(dt::ClassifyIntervalCastPolicyRowV3(0,C::explicit_cast)==dt::IntervalCastPolicyDispositionV3::forbidden,"row zero refused");Check(dt::ClassifyIntervalCastPolicyRowV3(222,C::explicit_cast)==dt::IntervalCastPolicyDispositionV3::forbidden,"row 222 refused");}
void Properties(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& profile){p::u64 random=kSeed;for(p::u64 ordinal=0;ordinal<4096;++ordinal){auto m=static_cast<std::int32_t>(Next(random));auto d=static_cast<std::int32_t>(Next(random));auto n=static_cast<std::int64_t>(Next(random));auto value=Value(profile,m,d,n);auto encoded=dt::EncodeCanonicalIntervalComponentV3(value);Property(encoded.ok()&&encoded.bytes.size()==16,"encode",ordinal);auto decoded=dt::DecodeCanonicalIntervalComponentNoAllocV3(*profile,dt::IntervalValueStateV3::value,true,encoded.bytes);Property(decoded.ok()&&decoded.value.months==m&&decoded.value.civil_days==d&&decoded.value.fixed_nanoseconds==n,"LE16 identity",ordinal);auto text=dt::RenderCanonicalIntervalV3(value);auto parsed=dt::ParseCanonicalIntervalV3(profile,text.text);Property(text.ok()&&parsed.ok()&&parsed.value.months==m&&parsed.value.civil_days==d&&parsed.value.fixed_nanoseconds==n,"render parse identity",ordinal);auto hash1=dt::HashIntervalValueV3(value),hash2=dt::HashIntervalValueV3(value);Property(hash1.ok()&&hash1.bytes==hash2.bytes&&hash1.bytes.size()==32,"deterministic hash",ordinal);auto eq=dt::EqualIntervalValuesV3(value.view(),value.view());Property(eq.ok()&&eq.fact==dt::IntervalEqualityFactV3::equal&&eq.grouping_equivalent,"equality reflexivity",ordinal);
 auto om=static_cast<std::int32_t>(Next(random)),od=static_cast<std::int32_t>(Next(random));auto on=static_cast<std::int64_t>(Next(random));auto other=Value(profile,om,od,on);__int128 wm=static_cast<__int128>(m)+om,wd=static_cast<__int128>(d)+od,wn=static_cast<__int128>(n)+on;bool addok=wm>=INT32_MIN&&wm<=INT32_MAX&&wd>=INT32_MIN&&wd<=INT32_MAX&&wn>=INT64_MIN&&wn<=INT64_MAX;auto add=dt::AddIntervalCheckedV3(value,other);Property(add.ok()==addok,"checked add disposition",ordinal);if(addok)Property(add.value.months==wm&&add.value.civil_days==wd&&add.value.fixed_nanoseconds==wn,"checked add oracle and no carry",ordinal);__int128 sm=static_cast<__int128>(m)-om,sd=static_cast<__int128>(d)-od,sn=static_cast<__int128>(n)-on;bool subok=sm>=INT32_MIN&&sm<=INT32_MAX&&sd>=INT32_MIN&&sd<=INT32_MAX&&sn>=INT64_MIN&&sn<=INT64_MAX;auto sub=dt::SubtractIntervalCheckedV3(value,other);Property(sub.ok()==subok,"checked subtract disposition",ordinal);if(subok)Property(sub.value.months==sm&&sub.value.civil_days==sd&&sub.value.fixed_nanoseconds==sn,"checked subtract oracle",ordinal);}}
void CastExecution(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& profile){
 auto source=Value(profile,-12,34,-56);dt::IntervalCastRequestV3 request;request.interval_source=&source;request.interval_target=&profile;
 for(auto row:{39u,100u,210u})for(auto c:{dt::DatatypeCastContext::implicit,dt::DatatypeCastContext::assignment,dt::DatatypeCastContext::explicit_cast}){request.one_based_policy_row=row;request.context=c;auto r=dt::CastIntervalValueV3(request);Check(r.ok()&&r.produced_interval&&r.interval_value.months==-12&&r.interval_value.civil_days==34&&r.interval_value.fixed_nanoseconds==-56,"three alias identity rows use no converter");}
 request.one_based_policy_row=1;auto refused=dt::CastIntervalValueV3(request);Check(!refused.ok()&&!refused.produced_interval&&refused.interval_value.profile==nullptr,"forbidden cast atomic");
 auto character=Identity(dt::CanonicalTypeId::character);Check(character,"current character identity");auto character_descriptor=Descriptor(dt::CanonicalTypeId::character);auto interval_descriptor=Descriptor(dt::CanonicalTypeId::interval);
 dt::DatatypeOperationValue text; text.type_id=dt::CanonicalTypeId::character;text.is_null=false;text.encoded_value="SBINTERVAL1:M=-12;D=34;NS=-56";text.descriptor=character_descriptor;
 dt::IntervalCastRequestV3 incoming;incoming.one_based_policy_row=124;incoming.context=dt::DatatypeCastContext::explicit_cast;incoming.scalar_source=&text;incoming.scalar_source_identity=character;incoming.interval_target=&profile;incoming.interval_target_descriptor=&interval_descriptor;auto parsed=dt::CastIntervalValueV3(incoming);Check(parsed.ok()&&parsed.produced_interval&&parsed.interval_value.months==-12&&parsed.interval_value.civil_days==34&&parsed.interval_value.fixed_nanoseconds==-56,"explicit character to interval");
 for(auto context:{dt::DatatypeCastContext::implicit,dt::DatatypeCastContext::assignment}){incoming.context=context;auto r=dt::CastIntervalValueV3(incoming);Check(!r.ok()&&!r.produced_interval&&r.diagnostic.diagnostic_code=="DATATYPE.CAST_FORBIDDEN","implicit and assignment character input forbidden");}
 incoming.context=dt::DatatypeCastContext::explicit_cast;auto wrong_text=*character;wrong_text.legacy_fields.type_generation++;incoming.scalar_source_identity=&wrong_text;Check(!dt::CastIntervalValueV3(incoming).ok(),"character identity mutation refused");incoming.scalar_source_identity=character;auto wrong_descriptor=interval_descriptor;wrong_descriptor.descriptor_epoch++;incoming.interval_target_descriptor=&wrong_descriptor;Check(!dt::CastIntervalValueV3(incoming).ok(),"interval descriptor mutation refused");
 dt::IntervalCastRequestV3 outgoing;outgoing.one_based_policy_row=13;outgoing.context=dt::DatatypeCastContext::explicit_cast;outgoing.interval_source=&source;outgoing.scalar_target=dt::CanonicalTypeId::character;outgoing.scalar_target_identity=character;outgoing.scalar_target_descriptor=character_descriptor;std::array<char,63> output;output.fill(char(0xa5));outgoing.use_character_output_buffer=true;outgoing.character_output=output.data();outgoing.character_output_capacity=output.size();auto rendered=dt::CastIntervalValueV3(outgoing);Check(rendered.ok()&&rendered.used_character_output_buffer&&std::string_view(output.data(),rendered.bytes_written)==text.encoded_value,"explicit interval to character");
 output.fill(char(0xa5));auto before=output;outgoing.character_output_capacity=text.encoded_value.size()-1;auto short_result=dt::CastIntervalValueV3(outgoing);Check(!short_result.ok()&&short_result.bytes_written==0&&output==before,"short cast output unchanged");
 for(auto context:{dt::DatatypeCastContext::implicit,dt::DatatypeCastContext::assignment}){outgoing.context=context;auto r=dt::CastIntervalValueV3(outgoing);Check(!r.ok()&&!r.used_character_output_buffer,"implicit and assignment character output forbidden");}
 dt::DatatypeOperationValue null_source;null_source.type_id=dt::CanonicalTypeId::null_type;null_source.is_null=true;dt::IntervalCastRequestV3 contextual;contextual.one_based_policy_row=158;contextual.context=dt::DatatypeCastContext::implicit;contextual.scalar_source=&null_source;contextual.interval_target=&profile;contextual.interval_target_descriptor=&interval_descriptor;auto null_result=dt::CastIntervalValueV3(contextual);Check(null_result.ok()&&null_result.interval_value.state==dt::IntervalValueStateV3::sql_null,"contextual NULL cast");contextual.target_null_allowed=false;Check(!dt::CastIntervalValueV3(contextual).ok(),"contextual NULL respects target nullability");
}
}
int main(){auto p=Profile();CastAudit();CastExecution(p);Properties(p);std::cout<<"PASS checks="<<checks<<" mapping="<<kMapping<<" seed=0x"<<std::hex<<kSeed<<std::dec<<" property_cases=4096 cast_decisions=663\n";}
