// Copyright (c) 2026 ScratchBird Software Inc.
// SPDX-License-Identifier: MPL-2.0
#include "datatype_interval.hpp"
#include <array>
#include <cstdlib>
#include <iostream>
#include <limits>
#include <memory>
#include <string_view>
namespace dt=scratchbird::core::datatypes; namespace p=scratchbird::core::platform;
namespace { unsigned checks; constexpr p::u64 kSeed=0x5342494e54455256ull; constexpr std::string_view kMapping="base.interval.property.splitmix64.v1";
void Check(bool v,std::string_view m){++checks;if(!v){std::cerr<<"FAIL "<<m<<'\n';std::exit(EXIT_FAILURE);}}
void Property(bool v,std::string_view m,p::u64 ordinal){++checks;if(!v){std::cerr<<"FAIL "<<m<<" mapping="<<kMapping<<" seed=0x"<<std::hex<<kSeed<<std::dec<<" ordinal="<<ordinal<<'\n';std::exit(EXIT_FAILURE);}}
p::u64 Next(p::u64& x){x+=0x9e3779b97f4a7c15ull;p::u64 z=x;z=(z^(z>>30))*0xbf58476d1ce4e5b9ull;z=(z^(z>>27))*0x94d049bb133111ebull;return z^(z>>31);}
p::Uuid D710(){return p::Uuid(std::array<p::byte,16>{1,0x9d,0,0,0,0,0x70,0,0x80,0,0,0,0,0,0xd7,0x10});}
std::shared_ptr<const dt::IntervalValidatedProfileHandleV3> Profile(){auto p=dt::BuildCurrentIntervalValidatedProfileHandleV3(D710());Check(p.ok(),"profile");return std::make_shared<const dt::IntervalValidatedProfileHandleV3>(std::move(p.profile));}
dt::IntervalOwnedValueV3 Value(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& p,std::int32_t m,std::int32_t d,std::int64_t n){auto x=dt::ConstructIntervalV3(p,m,d,n);Check(x.ok(),"construct");return std::move(x.value);}
void CastAudit(){using C=dt::DatatypeCastContext;for(p::u32 row=1;row<=221;++row){for(C c:{C::implicit,C::assignment,C::explicit_cast}){auto got=dt::ClassifyIntervalCastPolicyRowV3(row,c);auto want=dt::IntervalCastPolicyDispositionV3::forbidden;if(row==158)want=dt::IntervalCastPolicyDispositionV3::contextual_null;else if(row==39||row==100||row==210)want=dt::IntervalCastPolicyDispositionV3::identity;else if(row==124&&c==C::explicit_cast)want=dt::IntervalCastPolicyDispositionV3::explicit_character_to_interval;else if(row==13&&c==C::explicit_cast)want=dt::IntervalCastPolicyDispositionV3::explicit_interval_to_character;Check(got==want,"all 663 cast decisions");}}
 Check(dt::ClassifyIntervalCastPolicyRowV3(0,C::explicit_cast)==dt::IntervalCastPolicyDispositionV3::forbidden,"row zero refused");Check(dt::ClassifyIntervalCastPolicyRowV3(222,C::explicit_cast)==dt::IntervalCastPolicyDispositionV3::forbidden,"row 222 refused");}
void Properties(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& profile){p::u64 random=kSeed;for(p::u64 ordinal=0;ordinal<4096;++ordinal){auto m=static_cast<std::int32_t>(Next(random));auto d=static_cast<std::int32_t>(Next(random));auto n=static_cast<std::int64_t>(Next(random));auto value=Value(profile,m,d,n);auto encoded=dt::EncodeCanonicalIntervalComponentV3(value);Property(encoded.ok()&&encoded.bytes.size()==16,"encode",ordinal);auto decoded=dt::DecodeCanonicalIntervalComponentNoAllocV3(*profile,dt::IntervalValueStateV3::value,true,encoded.bytes);Property(decoded.ok()&&decoded.value.months==m&&decoded.value.civil_days==d&&decoded.value.fixed_nanoseconds==n,"LE16 identity",ordinal);auto text=dt::RenderCanonicalIntervalV3(value);auto parsed=dt::ParseCanonicalIntervalV3(profile,text.text);Property(text.ok()&&parsed.ok()&&parsed.value.months==m&&parsed.value.civil_days==d&&parsed.value.fixed_nanoseconds==n,"render parse identity",ordinal);auto hash1=dt::HashIntervalValueV3(value),hash2=dt::HashIntervalValueV3(value);Property(hash1.ok()&&hash1.bytes==hash2.bytes&&hash1.bytes.size()==32,"deterministic hash",ordinal);auto eq=dt::EqualIntervalValuesV3(value.view(),value.view());Property(eq.ok()&&eq.fact==dt::IntervalEqualityFactV3::equal&&eq.grouping_equivalent,"equality reflexivity",ordinal);
 auto om=static_cast<std::int32_t>(Next(random)),od=static_cast<std::int32_t>(Next(random));auto on=static_cast<std::int64_t>(Next(random));auto other=Value(profile,om,od,on);__int128 wm=static_cast<__int128>(m)+om,wd=static_cast<__int128>(d)+od,wn=static_cast<__int128>(n)+on;bool addok=wm>=INT32_MIN&&wm<=INT32_MAX&&wd>=INT32_MIN&&wd<=INT32_MAX&&wn>=INT64_MIN&&wn<=INT64_MAX;auto add=dt::AddIntervalCheckedV3(value,other);Property(add.ok()==addok,"checked add disposition",ordinal);if(addok)Property(add.value.months==wm&&add.value.civil_days==wd&&add.value.fixed_nanoseconds==wn,"checked add oracle and no carry",ordinal);__int128 sm=static_cast<__int128>(m)-om,sd=static_cast<__int128>(d)-od,sn=static_cast<__int128>(n)-on;bool subok=sm>=INT32_MIN&&sm<=INT32_MAX&&sd>=INT32_MIN&&sd<=INT32_MAX&&sn>=INT64_MIN&&sn<=INT64_MAX;auto sub=dt::SubtractIntervalCheckedV3(value,other);Property(sub.ok()==subok,"checked subtract disposition",ordinal);if(subok)Property(sub.value.months==sm&&sub.value.civil_days==sd&&sub.value.fixed_nanoseconds==sn,"checked subtract oracle",ordinal);}}
void CastExecution(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& profile){auto source=Value(profile,-12,34,-56);dt::IntervalCastRequestV3 request;request.one_based_policy_row=39;request.interval_source=&source;request.interval_target=&profile;for(auto c:{dt::DatatypeCastContext::implicit,dt::DatatypeCastContext::assignment,dt::DatatypeCastContext::explicit_cast}){request.context=c;auto r=dt::CastIntervalValueV3(request);Check(r.ok()&&r.produced_interval&&r.interval_value.months==-12&&r.interval_value.civil_days==34&&r.interval_value.fixed_nanoseconds==-56,"identity cast no conversion");}request.one_based_policy_row=1;auto refused=dt::CastIntervalValueV3(request);Check(!refused.ok()&&!refused.produced_interval,"forbidden cast atomic");}
}
int main(){auto p=Profile();CastAudit();CastExecution(p);Properties(p);std::cout<<"PASS checks="<<checks<<" mapping="<<kMapping<<" seed=0x"<<std::hex<<kSeed<<std::dec<<" property_cases=4096 cast_decisions=663\n";}
