// Copyright (c) 2026 ScratchBird Software Inc.
// SPDX-License-Identifier: MPL-2.0
#include "datatype_interval_projection.hpp"
#include <algorithm>
#include <array>
#include <atomic>
#include <cstdlib>
#include <iostream>
#include <memory>
#include <new>
#include <string_view>
#include <thread>
#include <vector>
namespace allocation_probe { bool fail_next=false; }
void* operator new(std::size_t bytes){if(allocation_probe::fail_next){allocation_probe::fail_next=false;throw std::bad_alloc();}if(auto* result=std::malloc(bytes?bytes:1))return result;throw std::bad_alloc();}
void* operator new[](std::size_t bytes){return ::operator new(bytes);}
void operator delete(void* value) noexcept{std::free(value);}
void operator delete[](void* value) noexcept{std::free(value);}
void operator delete(void* value,std::size_t) noexcept{std::free(value);}
void operator delete[](void* value,std::size_t) noexcept{std::free(value);}
namespace dt=scratchbird::core::datatypes;namespace p=scratchbird::core::platform;
namespace{unsigned checks;void Check(bool v,std::string_view m){++checks;if(!v){std::cerr<<"FAIL "<<m<<'\n';std::exit(EXIT_FAILURE);}}p::Uuid Uuid(p::byte tail){std::array<p::byte,16>b{};b[0]=1;b[6]=0x70;b[8]=0x80;b[15]=tail;return p::Uuid(b);}p::Uuid D710(){auto x=Uuid(0x10);x.bytes[1]=0x9d;x.bytes[14]=0xd7;return x;}std::shared_ptr<const dt::IntervalValidatedProfileHandleV3> Profile(){auto x=dt::BuildCurrentIntervalValidatedProfileHandleV3(D710());Check(x.ok(),"profile");return std::make_shared<const dt::IntervalValidatedProfileHandleV3>(std::move(x.profile));}dt::IntervalOwnedValueV3 Value(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& p){auto x=dt::ConstructIntervalV3(p,3,-5,7);Check(x.ok(),"value");return std::move(x.value);}
void Wire(){for(unsigned n=0;n<27;++n){auto r=dt::ResolveIntervalWireLaneV3(static_cast<dt::IntervalWireLaneV3>(n));Check(!r.admitted&&r.receiving_owner_handoff&&r.diagnostic=="CTI.TRANSPORT.UNSUPPORTED","27 wire lanes refuse");Check(r.component_mapping_complete==(n<3),"native component mapping only");Check(r.disposition==(n<3?"unsupported_current_outer_version_unallocated":"unsupported_no_manifest_listed_compatibility_profile"),"wire disposition");Check(r.lane==static_cast<dt::IntervalWireLaneV3>(n),"wire lane identity stable");}auto unknown=dt::ResolveIntervalWireLaneV3(static_cast<dt::IntervalWireLaneV3>(255));Check(!unknown.admitted&&!unknown.component_mapping_complete&&unknown.receiving_owner_handoff&&unknown.diagnostic=="CTI.TRANSPORT.UNSUPPORTED","unknown wire lane fails closed");}
void Protection(const dt::IntervalValidatedProfileHandleV3& profile){for(unsigned n=0;n<10;++n){auto r=dt::ResolveIntervalProtectionV3(static_cast<dt::IntervalProtectionCellV3>(n));Check(r.datatype_admitted==(n==0),"protection cells");bool handoff=n>=3&&n<=8;Check(r.receiving_owner_handoff==handoff,"protection owner handoff matrix");if(n==1||n==2||n==9)Check(r.diagnostic=="CTI.TEMPORAL.PROTECTION_UNSUPPORTED","inner/protected-index refusal");else Check(r.diagnostic.empty(),"admitted or outer-owner cell has no datatype failure");}for(unsigned storage=0;storage<4;++storage)for(unsigned stream=0;stream<4;++stream)for(unsigned indexed=0;indexed<2;++indexed){auto r=dt::AdmitIntervalProtectionCombinationV3(profile,static_cast<dt::IntervalProtectionModeV3>(storage),static_cast<dt::IntervalProtectionModeV3>(stream),static_cast<dt::IntervalProtectionIndexModeV3>(indexed));Check(r.admitted==(storage==0&&stream==0),"32 protection combinations");if(!r.admitted)Check(r.diagnostic=="CTI.TEMPORAL.PROTECTION_UNSUPPORTED","protection diagnostic");}}
void Metrics(const dt::IntervalValidatedProfileHandleV3& profile){auto types=dt::IntervalMetricEvidenceTypesV3();auto routes=dt::IntervalDiagnosticMetricRoutesV3();Check(types.size()==5,"five metric evidence types");Check(routes.size()==37,"37 diagnostic routes");Check(dt::ValidateIntervalDiagnosticMetricRouteTableV3(routes)==dt::IntervalDiagnosticMetricRouteDispositionV3::admitted,"route table exact");for(const auto&t:types){Check(!t.evidence_type_uuid.is_nil()&&!t.metric_uuid.is_nil()&&t.generation==1,"metric identity");for(auto banned:{"component_value","canonical_text","encoded_bytes","raw_bytes","hash_preimage","secret","address","diagnostic_prose","reference_engine_name"})Check(t.closed_label_schema.find(banned)==std::string_view::npos,"closed labels redact payload/prose");}
 for(std::size_t route_index=0;route_index<routes.size();++route_index){const auto& route=routes[route_index];for(unsigned op=0;op<15;++op)for(unsigned source=0;source<6;++source)for(unsigned state=0;state<4;++state)for(unsigned reason=0;reason<15;++reason){dt::IntervalMetricClosedLabelTupleV3 candidate{static_cast<dt::IntervalMetricOperationV3>(op),static_cast<dt::IntervalMetricSourceFamilyV3>(source),static_cast<dt::IntervalMetricStateV3>(state),static_cast<dt::IntervalMetricReasonV3>(reason)};bool expected=reason!=0&&reason==static_cast<unsigned>(route.reason)&&(route.permitted_operation_mask&(1u<<op))&&(route.permitted_source_family_mask&(1u<<source))&&(route.permitted_state_mask&(1u<<state));Check(dt::IsIntervalMetricLabelTupleAdmittedV3(route,candidate)==expected,"complete closed metric label matrix");}dt::IntervalMetricClosedLabelTupleV3 labels;bool found=false;for(unsigned op=0;op<15&&!found;++op)for(unsigned source=0;source<6&&!found;++source)for(unsigned state=0;state<4&&!found;++state){labels.operation=static_cast<dt::IntervalMetricOperationV3>(op);labels.source_family=static_cast<dt::IntervalMetricSourceFamilyV3>(source);labels.state=static_cast<dt::IntervalMetricStateV3>(state);labels.reason=route.reason;found=dt::IsIntervalMetricLabelTupleAdmittedV3(route,labels);}Check(found,"each diagnostic route has a closed label tuple");dt::IntervalMetricEvidenceProductionRequestV3 request;request.selected_final_diagnostic=route.key;request.source_event_uuid=Uuid(static_cast<p::byte>(20+route_index));request.database_uuid=Uuid(100);request.node_uuid=Uuid(101);request.process_epoch=4;request.event_sequence=route_index+1;request.monotonic_timestamp_ns=route_index+6;request.operation=labels.operation;request.source_family=labels.source_family;request.state=labels.state;auto produced=dt::ProduceIntervalMetricEvidenceV3(profile,request);Check(produced.ok()&&produced.receiving_owner_evidence_handoff_ready&&!produced.metric_mutation_admitted,"all routes produce typed evidence handoff only");auto evidence=produced.evidence;evidence.outcome_committed=true;dt::IntervalMetricEvidenceValidationContextV3 context{4,0};auto valid=dt::ValidateIntervalMetricEvidenceV3(profile,route.key,evidence,context);Check(valid.ok()&&valid.receiving_owner_update_admitted,"owner may apply every route once");auto replay=dt::ClassifyIntervalMetricReplayV3(evidence,evidence);Check(replay.disposition==dt::IntervalMetricReplayDispositionV3::exact_duplicate_idempotent&&replay.idempotent_without_increment&&!replay.second_emission_admitted,"exact replay idempotent");}}

void PinnedReaders(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& profile){auto value=Value(profile);std::atomic<unsigned> failures{0};std::vector<std::thread> readers;for(unsigned t=0;t<8;++t)readers.emplace_back([&,profile,value]{for(unsigned n=0;n<4096;++n){auto valid=dt::ValidateIntervalProfileHandleV3(*profile);auto hash=dt::HashIntervalValueV3(value);if(!valid.ok()||!hash.ok()||hash.bytes.size()!=32)++failures;}});for(auto&thread:readers)thread.join();Check(failures==0,"eight immutable readers x 4096");}
void ObserveScrub(void* context,dt::IntervalScrubClassV3 which,const p::byte*,p::u64) noexcept{auto* seen=static_cast<std::array<bool,static_cast<unsigned>(dt::IntervalScrubClassV3::count)>*>(context);(*seen)[static_cast<unsigned>(which)]=true;}
struct CancelState{unsigned calls=0,at=0;};bool CancelAt(void* context) noexcept{auto& state=*static_cast<CancelState*>(context);return ++state.calls==state.at;}
void Cleanup(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& profile){auto value=Value(profile);std::array<bool,static_cast<unsigned>(dt::IntervalScrubClassV3::count)> seen{};dt::IntervalExecutionControlV3 base;base.observe_scrubbed=ObserveScrub;base.scrub_observer_context=&seen;
 Check(dt::ValidateIntervalProfileHandleV3(*profile,base).ok(),"profile cleanup classes");auto component=dt::EncodeCanonicalIntervalComponentV3(value,base);Check(component.ok(),"component cleanup source");Check(dt::DecodeCanonicalIntervalComponentNoAllocV3(*profile,dt::IntervalValueStateV3::value,true,component.bytes,base).ok(),"component decode cleanup");Check(dt::RenderCanonicalIntervalV3(value,base).ok(),"render cleanup");Check(dt::HashIntervalValueV3(value,base).ok(),"hash cleanup");auto sbdval=dt::EncodeIntervalSbdvalComposedV3(value,true,base);auto sbdpv=dt::EncodeIntervalSbdpvComposedV3(value,true,base);Check(sbdval.ok()&&sbdpv.ok(),"composed cleanup sources");Check(dt::DecodeIntervalSbdvalComposedNoAllocV3(*profile,true,sbdval.bytes,base).ok()&&dt::DecodeIntervalSbdpvComposedNoAllocV3(*profile,true,sbdpv.bytes,base).ok(),"composed decode cleanup");auto covering=dt::EncodeIntervalCoveringValueV3(value,base);Check(covering.ok()&&dt::DecodeIntervalCoveringValueNoAllocV3(*profile,true,covering.bytes,base).ok(),"covering cleanup");dt::IntervalIndexProjectionRequestV3 iq;iq.compatibility=dt::LookupIntervalIndexCompatibilityIdentityV3(dt::IntervalIndexFamilyV3::hash);iq.mode=dt::IntervalProjectionModeV3::equality_hash;iq.value=&value;iq.control=base;Check(dt::ProjectIntervalIndexValueV3(iq).ok(),"projection cleanup");auto backup=dt::EncodeIntervalBackupTupleV3(value,base);Check(backup.ok()&&dt::DecodeIntervalBackupTupleNoAllocV3(*profile,true,backup.bytes,base).ok(),"backup cleanup");
 std::array<std::int32_t,1> m{1},d{2};std::array<std::int64_t,1> ns{3};std::array<p::byte,1> bits{0};for(unsigned at=1;at<=6;++at){CancelState state{0,at};auto c=base;c.cancelled=CancelAt;c.cancellation_context=&state;(void)dt::MaterializeIntervalBatchV3(profile,m,d,ns,bits,c);}for(unsigned at=1;at<=8;++at){CancelState state{0,at};auto c=base;c.cancelled=CancelAt;c.cancellation_context=&state;(void)dt::EncodeCanonicalIntervalComponentV3(value,c);state={0,at};(void)dt::EncodeIntervalSbdvalComposedV3(value,true,c);state={0,at};(void)dt::EncodeIntervalSbdpvComposedV3(value,true,c);iq.control=c;(void)dt::ProjectIntervalIndexValueV3(iq);}
 auto hashed=dt::HashIntervalValueV3(value);auto evidence=std::make_shared<dt::IntervalStatisticsProviderEvidenceHandleV3>();evidence->provider_evidence_uuid=Uuid(1);evidence->source_object_uuid=Uuid(2);evidence->authenticated_population=true;evidence->source_authorized=true;evidence->privacy_admitted=true;evidence->schema_epoch=1;evidence->collection_epoch=1;evidence->security_epoch=1;evidence->row_count=1;evidence->value_count=1;evidence->equality_distinct_estimate=1;dt::IntervalStatisticsMcvRecordV3 record;std::copy(hashed.bytes.begin(),hashed.bytes.end(),record.value_hash.begin());record.frequency=1;record.rank=1;record.flags=1;evidence->mcv.push_back(record);dt::IntervalStatisticsProjectionV3 projection;projection.profile=profile;projection.provider_evidence=evidence;projection.statistics_snapshot_uuid=Uuid(3);projection.source_object_uuid=Uuid(2);projection.schema_epoch=1;projection.collection_epoch=1;projection.security_epoch=1;projection.row_count=1;projection.value_count=1;projection.equality_distinct_estimate=1;projection.mcv=evidence->mcv;auto stats=dt::EncodeIntervalStatisticsProjectionV3(projection,base);Check(stats.ok(),"statistics cleanup source");dt::IntervalStatisticsReceivingFactsV3 facts;facts.security_visible=true;facts.privacy_admitted=true;facts.source_object_uuid=Uuid(2);facts.provider_evidence_uuid=Uuid(1);facts.schema_epoch=1;facts.collection_epoch=1;facts.security_epoch=1;facts.statistics_snapshot_uuid=Uuid(3);facts.authenticated_population=true;facts.row_count=1;facts.value_count=1;facts.equality_distinct_estimate=1;facts.mcv=evidence->mcv;Check(dt::DecodeIntervalStatisticsProjectionV3(profile,stats.bytes,facts,base).ok(),"statistics decode cleanup");
 unsigned observed=0;for(bool v:seen)observed+=v;Check(observed==static_cast<unsigned>(dt::IntervalScrubClassV3::count),"all 31 registered scratch classes observed");}
void AtomicFailures(const std::shared_ptr<const dt::IntervalValidatedProfileHandleV3>& profile){auto value=Value(profile);
 allocation_probe::fail_next=true;auto allocation_failure=dt::EncodeCanonicalIntervalComponentV3(value);Check(!allocation_failure.ok()&&allocation_failure.bytes.empty()&&!allocation_probe::fail_next,"injected owning allocation failure publishes no bytes");
 std::array<p::byte,32> hash;hash.fill(0xa5);auto hash_before=hash;auto short_hash=dt::HashIntervalValueIntoNoAllocV3(value,hash.data(),31);Check(!short_hash.ok()&&hash==hash_before&&short_hash.bytes_written==0&&short_hash.bytes_required==32,"one-byte-short hash unchanged");auto exact_hash=dt::HashIntervalValueIntoNoAllocV3(value,hash.data(),hash.size());Check(exact_hash.ok()&&exact_hash.bytes_written==32,"exact hash capacity");
 std::array<p::byte,16> component;component.fill(0xa5);auto component_before=component;auto short_component=dt::EncodeCanonicalIntervalComponentIntoNoAllocV3(value,component.data(),15);Check(!short_component.ok()&&component==component_before&&short_component.bytes_written==0&&short_component.bytes_required==16,"one-byte-short component unchanged");Check(dt::EncodeCanonicalIntervalComponentIntoNoAllocV3(value,component.data(),16).ok(),"exact component capacity");
 std::array<char,63> text;text.fill(char(0xa5));auto text_before=text;auto rendered=dt::RenderCanonicalIntervalV3(value);Check(rendered.ok(),"render extent source");auto short_text=dt::RenderCanonicalIntervalIntoNoAllocV3(value,text.data(),rendered.text.size()-1);Check(!short_text.ok()&&text==text_before&&short_text.bytes_written==0&&short_text.bytes_required==rendered.text.size(),"one-byte-short text unchanged");Check(dt::RenderCanonicalIntervalIntoNoAllocV3(value,text.data(),rendered.text.size()).ok(),"exact text capacity");
 auto overlap_component=dt::EncodeCanonicalIntervalComponentIntoNoAllocV3(value,reinterpret_cast<p::byte*>(&value),16);Check(!overlap_component.ok()&&overlap_component.bytes_written==0,"complete overlap refused before publication");auto overlap_hash=dt::HashIntervalValueIntoNoAllocV3(value,reinterpret_cast<p::byte*>(&value)+1,32);Check(!overlap_hash.ok()&&overlap_hash.bytes_written==0,"partial overlap refused before publication");
 for(unsigned n=0;n<4096;++n){auto encoded=dt::EncodeCanonicalIntervalComponentV3(value);Check(encoded.ok()&&encoded.bytes.size()==16,"4096 publish handoff cycles");auto decoded=dt::DecodeCanonicalIntervalComponentNoAllocV3(*profile,dt::IntervalValueStateV3::value,true,encoded.bytes);Check(decoded.ok()&&decoded.value.profile==profile.get(),"pinned profile handoff");}}

}
int main(){auto profile=Profile();Wire();Protection(*profile);Metrics(*profile);PinnedReaders(profile);Cleanup(profile);AtomicFailures(profile);std::cout<<"PASS checks="<<checks<<" wire_lanes=27 reader_threads=8 reads_per_thread=4096 publication_cycles=4096 metric_routes=37\n";}
