// Copyright (c) 2026 ScratchBird Software Inc.
// SPDX-License-Identifier: MPL-2.0
#include "catalog_value_codec.hpp"

#include <array>
#include <iostream>
#include <limits>
#include <string>
#include <utility>

namespace c = scratchbird::core::catalog;
namespace p = scratchbird::core::platform;
using T = c::CatalogValueType;
using E = c::CatalogValueError;
unsigned checks = 0, failures = 0;
void Check(bool ok, const char* message) {
  ++checks;
  if (!ok && ++failures < 20) std::cerr << "FAIL " << message << '\n';
}
std::vector<p::byte> Hex(const std::string& text) {
  std::vector<p::byte> bytes;
  int high = -1;
  for (char ch : text) {
    if (ch == ' ') continue;
    const unsigned nibble = ch <= '9' ? ch - '0' : ch - 'a' + 10;
    if (high < 0) high = nibble;
    else { bytes.push_back(static_cast<p::byte>(high * 16 + nibble)); high = -1; }
  }
  return bytes;
}
p::Uuid Id(const std::string& hex) {
  p::Uuid id;
  const auto bytes = Hex(hex);
  for (unsigned i = 0; i < 16; ++i) id.bytes[i] = bytes[i];
  return id;
}
const auto first = Id("00112233445576778899aabbccddeeff");
const auto second = Id("102132435465768798a9bacbdcedfe0f");
const auto user = Id("ffeeddccbbaa19888766554433221100");
c::CatalogValueSchema Schema(T type, p::u32 maximum, p::UuidKind kind = p::UuidKind::unknown) {
  return {0x01020304, 2, {{1, type, true, maximum, kind}}};
}
void Refused(const c::CatalogValueEncodeResult& r) {
  Check(!r.ok() && r.error != E::none, "encode accepted invalid input");
  Check(r.bytes.empty(), "failed encode returned partial bytes");
}
void Refused(const c::CatalogValueDecodeResult& r) {
  Check(!r.ok() && r.error != E::none, "decode accepted invalid input");
  Check(r.fields.empty(), "failed decode returned partial authority");
}
void Roundtrip(const c::CatalogValueSchema& schema, const std::vector<c::CatalogValueField>& fields) {
  const auto encoded = c::EncodeCatalogValueBlock(schema, fields);
  Check(encoded.ok(), "valid encode refused");
  if (!encoded.ok()) return;
  const auto decoded = c::DecodeCatalogValueBlock(schema, encoded.bytes);
  Check(decoded.ok(), "valid decode refused");
  if (!decoded.ok()) return;
  const auto again = c::EncodeCatalogValueBlock(schema, decoded.fields);
  Check(again.ok() && again.bytes == encoded.bytes, "canonical bytes changed on reencode");
}
void Golden() {
  const c::CatalogValueSchema schema{0x01020304, 2, {
    {1,T::unsigned_integer,true,8}, {2,T::boolean,true,1}, {3,T::utf8_text,true,6},
    {4,T::opaque_bytes,true,3}, {5,T::engine_identity,true,16,p::UuidKind::object},
    {6,T::user_uuid_data,true,16}, {7,T::engine_identity_list,true,32,p::UuidKind::schema}}};
  const std::vector<c::CatalogValueField> fields{
    {1,p::u64{0x0102030405060708}}, {2,true}, {3,std::string("a\n\r\0=?",6)},
    {4,Hex("00ff80")}, {5,p::TypedUuid{p::UuidKind::object,first}},
    {6,user}, {7,std::vector<p::TypedUuid>{{p::UuidKind::schema,first},{p::UuidKind::schema,second}}}};
  // Independently transcribed from Core offsets/types; never generated by the codec.
  const auto bytes = Hex(
    "53424356 0100 1800 a2000000 07000000 04030201 0200 0000 "
    "0100 01 00 08000000 0807060504030201 "
    "0200 02 00 01000000 01 "
    "0300 03 00 06000000 610a0d003d3f "
    "0400 04 00 03000000 00ff80 "
    "0500 05 00 10000000 00112233445576778899aabbccddeeff "
    "0600 06 00 10000000 ffeeddccbbaa19888766554433221100 "
    "0700 07 00 20000000 00112233445576778899aabbccddeeff102132435465768798a9bacbdcedfe0f");
  Check(bytes.size() == 162, "golden fixture size");
  const auto encoded = c::EncodeCatalogValueBlock(schema, fields);
  Check(encoded.ok() && encoded.bytes == bytes, "independent complete golden bytes differ");
  const auto decoded = c::DecodeCatalogValueBlock(schema, bytes);
  Check(decoded.ok() && decoded.fields.size() == 7, "independent golden decode");
  if (decoded.ok() && decoded.fields.size() == 7) {
    Check(std::get<p::u64>(decoded.fields[0].value) == 0x0102030405060708, "integer endian");
    Check(std::get<bool>(decoded.fields[1].value), "boolean value");
    Check(std::get<std::string>(decoded.fields[2].value) == std::string("a\n\r\0=?",6), "text loss");
    Check(std::get<std::vector<p::byte>>(decoded.fields[3].value) == Hex("00ff80"), "opaque bytes loss");
    const auto id = std::get<p::TypedUuid>(decoded.fields[4].value);
    Check(id.kind == p::UuidKind::object && id.value == first, "identity kind/bytes loss");
    Check(std::get<p::Uuid>(decoded.fields[5].value) == user, "older user UUID changed");
    const auto& ids = std::get<std::vector<p::TypedUuid>>(decoded.fields[6].value);
    Check(ids.size() == 2 && ids[0].kind == p::UuidKind::schema &&
          ids[1].kind == p::UuidKind::schema && ids[0].value == first &&
          ids[1].value == second, "identity list kind/order loss");
  }
  Roundtrip(schema, fields);
  for (std::size_t n = 0; n < bytes.size(); ++n)
    Refused(c::DecodeCatalogValueBlock(schema, {bytes.begin(),bytes.begin()+n}));
  auto malformed = bytes;
  malformed.push_back(0); Refused(c::DecodeCatalogValueBlock(schema, malformed));
  malformed[8]++; Refused(c::DecodeCatalogValueBlock(schema, malformed));
  // Every possible one-byte change in fixed header and each field header.
  std::vector<std::size_t> positions;
  for (unsigned n=0;n<24;++n) positions.push_back(n);
  for (unsigned offset : {24,40,49,63,74,98,122})
    for (unsigned n=0;n<8;++n) positions.push_back(offset+n);
  for (auto offset : positions) for (unsigned n=0;n<256;++n) {
    if (bytes[offset] == n) continue;
    malformed = bytes; malformed[offset] = n;
    Refused(c::DecodeCatalogValueBlock(schema, malformed));
  }
  for (unsigned n=2;n<256;++n) {
    malformed = bytes; malformed[48]=n;
    Refused(c::DecodeCatalogValueBlock(schema, malformed));
  }
  auto optional = schema; optional.fields[1].required = false;
  auto missing = fields; missing.erase(missing.begin()+1);
  Roundtrip(optional, missing);
  Refused(c::EncodeCatalogValueBlock(schema, missing));
  auto absent_encoded = c::EncodeCatalogValueBlock(optional, missing);
  Refused(c::DecodeCatalogValueBlock(schema, absent_encoded.bytes));
  auto duplicate = fields; duplicate[1].id = 1; Refused(c::EncodeCatalogValueBlock(schema, duplicate));
  std::swap(duplicate[0],duplicate[2]); Refused(c::EncodeCatalogValueBlock(schema, duplicate));
  auto unknown = fields; unknown.back().id = 65535; Refused(c::EncodeCatalogValueBlock(schema, unknown));
  auto wrong = fields; wrong[4].value = std::string("00112233-4455-7677-8899-aabbccddeeff");
  Refused(c::EncodeCatalogValueBlock(schema, wrong));
  auto wrong_kind = fields; wrong_kind[4].value = p::TypedUuid{p::UuidKind::schema,first};
  Refused(c::EncodeCatalogValueBlock(schema, wrong_kind));
}
void IdentityMatrix() {
  for (unsigned raw = 0; raw < 256; ++raw) {
    const auto kind = static_cast<p::UuidKind>(raw);
    // Independent Core kind table, deliberately not the implementation's classifier.
    const bool durable = raw <= 7 || raw == 9;
    for (unsigned version = 0; version < 16; ++version) for (unsigned variant=0;variant<4;++variant) {
      auto id = first;
      id.bytes[6] = static_cast<p::byte>(version << 4 | 6);
      id.bytes[8] = static_cast<p::byte>(variant << 6 | 8);
      for (const auto type : {T::engine_identity,T::engine_identity_list}) {
        const auto schema = Schema(type,16,kind);
        const c::CatalogValue value = type == T::engine_identity
          ? c::CatalogValue(p::TypedUuid{kind,id})
          : c::CatalogValue(std::vector<p::TypedUuid>{{kind,id}});
        const auto encoded = c::EncodeCatalogValueBlock(schema,{{1,value}});
        // Independent one-field binary fixture for decoder negatives as well.
        auto bytes = Hex("5342435601001800300000000100000004030201020000000100050010000000");
        bytes[26] = static_cast<p::byte>(type);
        bytes.insert(bytes.end(),id.bytes.begin(),id.bytes.end());
        const auto decoded = c::DecodeCatalogValueBlock(schema,bytes);
        if (durable && version == 7 && variant == 2) {
          Check(encoded.ok() && encoded.bytes == bytes, "identity matrix encode bytes");
          Check(decoded.ok(), "identity matrix decode");
          if (decoded.ok()) {
            const auto actual = type == T::engine_identity
              ? std::get<p::TypedUuid>(decoded.fields[0].value)
              : std::get<std::vector<p::TypedUuid>>(decoded.fields[0].value)[0];
            Check(actual.kind == kind && actual.value == id, "matrix kind or UUID changed");
          }
        } else { Refused(encoded); Refused(decoded); }
      }
      // User UUID bits are not subjected to engine identity version/variant policy.
      if (raw == 0) {
        const auto schema = Schema(T::user_uuid_data,16);
        const auto encoded = c::EncodeCatalogValueBlock(schema,{{1,id}});
        Check(encoded.ok(), "user UUID bits refused");
        const auto decoded = c::DecodeCatalogValueBlock(schema,encoded.bytes);
        Check(decoded.ok() && std::get<p::Uuid>(decoded.fields[0].value) == id, "user UUID bits changed");
      }
    }
  }
  Refused(c::EncodeCatalogValueBlock(Schema(T::engine_identity,16,p::UuidKind::object),
                                    {{1,p::TypedUuid{p::UuidKind::object,{}}}}));
  auto schema = Schema(T::engine_identity_list,32,p::UuidKind::object);
  Refused(c::EncodeCatalogValueBlock(schema,{{1,std::vector<p::TypedUuid>{
      {p::UuidKind::object,first},{p::UuidKind::schema,second}}}}));
  auto bytes = c::EncodeCatalogValueBlock(schema,{{1,std::vector<p::TypedUuid>{
      {p::UuidKind::object,first},{p::UuidKind::object,second}}}}).bytes;
  bytes[54] = 0x46; Refused(c::DecodeCatalogValueBlock(schema,bytes)); // bad second element
  Roundtrip(schema,{{1,std::vector<p::TypedUuid>{}}});
  Roundtrip(Schema(T::user_uuid_data,16),{{1,p::Uuid{}}});
}
void TextAndBounds() {
  const auto schema = Schema(T::utf8_text,32);
  for (unsigned n = 0; n < 256; ++n) {
    std::string text(1,static_cast<char>(n));
    auto encoded = c::EncodeCatalogValueBlock(schema,{{1,text}});
    auto bytes = Hex("5342435601001800210000000100000004030201020000000100030001000000");
    bytes.push_back(n);
    if (n < 128) {
      Check(encoded.ok() && encoded.bytes == bytes, "ASCII/control not preserved");
      Check(c::DecodeCatalogValueBlock(schema,bytes).ok(), "ASCII decode");
    } else { Refused(encoded); Refused(c::DecodeCatalogValueBlock(schema,bytes)); }
  }
  for (const auto& hex : {"c280","dfbf","e0a080","ed9fbf","ee8080","efbfbf","f0908080","f48fbfbf"}) {
    const auto raw = Hex(hex);
    Roundtrip(schema,{{1,std::string(raw.begin(),raw.end())}});
  }
  for (const auto& hex : {"c080","c180","e08080","eda080","edbfbf","f0808080","f4908080",
                         "f5808080","fe","ff","c2","e0a0","f09080","e04180","80"}) {
    const auto raw = Hex(hex);
    Refused(c::EncodeCatalogValueBlock(schema,{{1,std::string(raw.begin(),raw.end())}}));
    auto bytes = Hex("5342435601001800200000000100000004030201020000000100030000000000");
    bytes[8] += raw.size(); bytes[28] = raw.size(); bytes.insert(bytes.end(),raw.begin(),raw.end());
    Refused(c::DecodeCatalogValueBlock(schema,bytes));
  }
  const auto maximum = static_cast<p::u32>(131072-24-8);
  auto large = Schema(T::opaque_bytes,maximum);
  std::vector<p::byte> data(maximum,0xff);
  auto encoded = c::EncodeCatalogValueBlock(large,{{1,data}});
  Check(encoded.ok() && encoded.bytes.size() == 131072, "exact block maximum refused");
  Roundtrip(large,{{1,data}});
  data.push_back(0); Refused(c::EncodeCatalogValueBlock(large,{{1,data}}));
  encoded.bytes.push_back(0); Refused(c::DecodeCatalogValueBlock(large,encoded.bytes));
  // Individually bounded values can still exceed the total block bound.
  large.fields.push_back({2,T::opaque_bytes,false,0});
  data.pop_back(); Refused(c::EncodeCatalogValueBlock(large,{{1,data},{2,std::vector<p::byte>{}}}));
  Roundtrip(Schema(T::opaque_bytes,0),{{1,std::vector<p::byte>{}}});
  Roundtrip(Schema(T::utf8_text,0),{{1,std::string{}}});
  Roundtrip(Schema(T::unsigned_integer,8),{{1,std::numeric_limits<p::u64>::max()}});
  Roundtrip(Schema(T::boolean,1),{{1,false}});
  c::CatalogValueSchema empty{1,1,{}};
  Roundtrip(empty,{});
  // Count/id high bytes and the exact all-empty-field block boundary.
  c::CatalogValueSchema many{1,1,{}};
  std::vector<c::CatalogValueField> many_values;
  for (unsigned id=1;id<=16381;++id) {
    many.fields.push_back({static_cast<p::u16>(id),T::opaque_bytes,true,0});
    many_values.push_back({static_cast<p::u16>(id),std::vector<p::byte>{}});
  }
  const auto many_encoded = c::EncodeCatalogValueBlock(many,many_values);
  Check(many_encoded.ok() && many_encoded.bytes.size()==131072 &&
        many_encoded.bytes[12]==0xfd && many_encoded.bytes[13]==0x3f,
        "maximum field count/endian boundary");
  Roundtrip(many,many_values);
  many.fields.push_back({16382,T::opaque_bytes,true,0});
  many_values.push_back({16382,std::vector<p::byte>{}});
  Refused(c::EncodeCatalogValueBlock(many,many_values));
  auto highest=Schema(T::opaque_bytes,0); highest.fields[0].id=65535;
  Roundtrip(highest,{{65535,std::vector<p::byte>{}}});
  Refused(c::EncodeCatalogValueBlock(Schema(T::opaque_bytes,0),{}));
  const auto empty_bytes = c::EncodeCatalogValueBlock(empty,{}).bytes;
  for (auto offset : {8,12}) {
    auto bytes = empty_bytes;
    for (int n=0;n<4;++n) bytes[offset+n]=0xff;
    Refused(c::DecodeCatalogValueBlock(empty,bytes));
  }
}
void SchemaAndTypes() {
  auto valid = Schema(T::unsigned_integer,8);
  const auto bytes = c::EncodeCatalogValueBlock(valid,{{1,p::u64{1}}}).bytes;
  std::vector<c::CatalogValueSchema> invalid;
  auto s=valid;s.id=0;invalid.push_back(s);
  s=valid;s.version=0;invalid.push_back(s);
  s=valid;s.fields[0].id=0;invalid.push_back(s);
  s=valid;s.fields.push_back(s.fields[0]);invalid.push_back(s);
  s=valid;s.fields[0].maximum_bytes=7;invalid.push_back(s);
  s=valid;s.fields[0].maximum_bytes=131041;invalid.push_back(s);
  s=valid;s.fields[0].identity_kind=p::UuidKind::object;invalid.push_back(s);
  for (unsigned tag=0;tag<256;++tag) if (tag==0 || tag>8) {
    s=valid;s.fields[0].type=static_cast<T>(tag);invalid.push_back(s);
  }
  for (const auto& schema : invalid) {
    auto encoded=c::EncodeCatalogValueBlock(schema,{{1,p::u64{1}}});
    auto decoded=c::DecodeCatalogValueBlock(schema,bytes);
    Refused(encoded); Refused(decoded);
    Check(encoded.error==E::invalid_schema && decoded.error==E::invalid_schema, "invalid schema category");
  }
  const std::vector<c::CatalogValue> values{p::u64{1},true,std::string{},std::vector<p::byte>{},
      p::TypedUuid{p::UuidKind::object,first},user,std::vector<p::TypedUuid>{{p::UuidKind::object,first}},
      std::vector<std::string>{"one", "two"}};
  for (unsigned tag=1;tag<=8;++tag) {
    const auto type=static_cast<T>(tag);
    const auto schema=Schema(type,32,tag==5||tag==7?p::UuidKind::object:p::UuidKind::unknown);
    for (unsigned value=0;value<8;++value) {
      if (value+1==tag) Roundtrip(schema,{{1,values[value]}});
      else Refused(c::EncodeCatalogValueBlock(schema,{{1,values[value]}}));
    }
  }
  // Physically bounded but invalid scalar/list widths must be rejected.
  for (unsigned tag : {1,2,5,6,7}) for (unsigned width : {0,1,2,7,8,15,16,17,31,32}) {
    const bool valid_width = tag==1?width==8:tag==2?width==1:tag==7?width%16==0:width==16;
    if (valid_width) continue;
    auto schema=Schema(static_cast<T>(tag),32,tag==5||tag==7?p::UuidKind::object:p::UuidKind::unknown);
    auto malformed=Hex("5342435601001800200000000100000004030201020000000100010000000000");
    malformed[8]+=width; malformed[26]=tag;malformed[28]=width;malformed.resize(32+width,0);
    Refused(c::DecodeCatalogValueBlock(schema,malformed));
  }
}
void TextLists() {
  const auto schema = Schema(T::utf8_text_list, 131040);
  const std::vector<std::string> values{"", std::string("a,\n\0=?", 6), "\xf0\x9f\x98\x80"};
  // Independently transcribed count, lengths, UTF8 and fixed Core offsets.
  const auto golden = Hex(
      "53424356 0100 1800 3a000000 01000000 04030201 0200 0000 "
      "0100 08 00 1a000000 03000000 00000000 06000000 612c0a003d3f "
      "04000000 f09f9880");
  Check(golden.size() == 58, "text list independent golden size");
  const auto encoded = c::EncodeCatalogValueBlock(schema, {{1, values}});
  Check(encoded.ok() && encoded.bytes == golden, "text list complete golden bytes");
  const auto decoded = c::DecodeCatalogValueBlock(schema, golden);
  Check(decoded.ok() && decoded.fields.size() == 1, "text list golden decode");
  if (decoded.ok() && decoded.fields.size() == 1)
    Check(std::get<std::vector<std::string>>(decoded.fields[0].value) == values,
          "text list lost empty elements, order, delimiters or UTF8");
  Roundtrip(schema, {{1, values}});
  Roundtrip(schema, {{1, std::vector<std::string>{"same", "same", ""}}});
  const auto empty = c::EncodeCatalogValueBlock(Schema(T::utf8_text_list, 4),
      {{1, std::vector<std::string>{}}});
  Check(empty.ok() && empty.bytes == Hex(
      "53424356 0100 1800 24000000 01000000 04030201 0200 0000 0100 08 00 04000000 00000000"),
      "empty text list is not canonical four-byte zero count");
  Roundtrip(Schema(T::utf8_text_list, 8), {{1, std::vector<std::string>{""}}});
  for (unsigned maximum = 0; maximum < 4; ++maximum) {
    const auto invalid = c::EncodeCatalogValueBlock(Schema(T::utf8_text_list, maximum),
        {{1, std::vector<std::string>{}}});
    Check(invalid.error == E::invalid_schema && invalid.bytes.empty(), "list schema missing count capacity");
  }
  Refused(c::EncodeCatalogValueBlock(Schema(T::utf8_text_list, 4), {{1, std::vector<std::string>{""}}}));
  Refused(c::EncodeCatalogValueBlock(Schema(T::utf8_text_list, 25), {{1, values}}));
  Roundtrip(Schema(T::utf8_text_list, 26), {{1, values}});
  for (const auto& text : {std::string("\xc0\x80"), std::string("\xed\xa0\x80"),
                           std::string("\xf4\x90\x80\x80"), std::string("\xe2\x82")})
    Refused(c::EncodeCatalogValueBlock(schema, {{1, std::vector<std::string>{"valid", text}}}));
  for (std::size_t n = 0; n < golden.size(); ++n) {
    auto cut = std::vector<p::byte>(golden.begin(), golden.begin() + n);
    Refused(c::DecodeCatalogValueBlock(schema, cut));
    if (n >= 32) {
      cut[8] = static_cast<p::byte>(n);
      cut[28] = static_cast<p::byte>(n - 32);
      Refused(c::DecodeCatalogValueBlock(schema, cut));
    }
  }
  for (unsigned offset : {32, 36, 40, 50}) {
    auto corrupt = golden;
    for (unsigned i = 0; i < 4; ++i) corrupt[offset + i] = 0xff;
    Refused(c::DecodeCatalogValueBlock(schema, corrupt));
  }
  for (unsigned count : {0, 1, 2, 4, 255}) {
    auto corrupt = golden; corrupt[32] = static_cast<p::byte>(count);
    Refused(c::DecodeCatalogValueBlock(schema, corrupt));
  }
  auto late_invalid = golden; late_invalid.back() = 0xff;
  Refused(c::DecodeCatalogValueBlock(schema, late_invalid));
  auto trailing = golden; trailing.push_back(0); ++trailing[8]; ++trailing[28];
  Refused(c::DecodeCatalogValueBlock(schema, trailing));
  // The complete block bound includes the list count and element length.
  Roundtrip(schema, {{1, std::vector<std::string>{std::string(131032, 'x')}}});
  Refused(c::EncodeCatalogValueBlock(schema,
      {{1, std::vector<std::string>{std::string(131033, 'x')}}}));
}
int main() {
  Golden(); IdentityMatrix(); TextAndBounds(); SchemaAndTypes(); TextLists();
  std::cout << "catalog binary value codec: checks=" << checks << " failures=" << failures << '\n';
  return failures ? 1 : 0;
}
