# Copyright (c) 2026 ScratchBird Software Inc.
# SPDX-License-Identifier: MPL-2.0

if(NOT EXISTS "${SB_NM}" OR NOT EXISTS "${SB_OBJECT_FILE}")
  message(FATAL_ERROR "Actual object and configured symbol inspector are required")
endif()
execute_process(COMMAND "${SB_NM}" --undefined-only "${SB_OBJECT_FILE}"
  RESULT_VARIABLE result OUTPUT_VARIABLE symbols ERROR_VARIABLE errors TIMEOUT 20)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Cannot inspect actual ABI reference object: ${errors}")
endif()
string(REPLACE "\n" ";" lines "${symbols}")
set(observed)
foreach(line IN LISTS lines)
  if(line MATCHES "sb_cluster_gateway")
    string(REGEX REPLACE "^.*[ \t]([^ \t]+)$" "\\1" symbol "${line}")
    list(APPEND observed "${symbol}")
  endif()
endforeach()
set(expected)
foreach(suffix IN ITEMS get_descriptor open dispatch poll cancel close)
  list(APPEND expected "sb_cluster_gateway_abi_v1_${suffix}")
endforeach()
list(SORT observed)
list(SORT expected)
if(NOT observed STREQUAL expected)
  message(FATAL_ERROR "Canonical C references differ: ${observed}; expected ${expected}")
endif()
message(STATUS "PASS six exact unmangled C references; not runtime export evidence")
