// Copyright (c) 2026 ScratchBird Software Inc.
// SPDX-License-Identifier: MPL-2.0
#include "sblr_parameter_runtime.hpp"
#include "sblr_engine_envelope.hpp"
#include "hash_digest.hpp"
#include <cstdlib>
#include <iostream>
namespace sblr=scratchbird::engine::sblr;
[[noreturn]]void Fail(const char*m){std::cerr<<m<<'\n';std::exit(EXIT_FAILURE);}void Require(bool v,const char*m){if(!v)Fail(m);}
int main(){
 // CSC-TEST-002330: malformed SBLR_PARAMETER operands and carriers refuse
 // deterministically; canonical SBPN/kind19/SBPV/SBPR/SBPG/SBPF/SBPA/SBPT
 // round-trip without accepting trailing, reserved, or duplicate authority.
 Require(sblr::EncodeSblrParameterNodeTableV1({}).empty(),"empty SBPN encoded");
 std::vector<std::uint8_t> malformed_over_sbpn(426120);
 auto malformed_over=sblr::DecodeSblrParameterNodeTableV1(malformed_over_sbpn.data(),malformed_over_sbpn.size());
 Require(!malformed_over.ok&&malformed_over.diagnostic_id=="SBLR.OPERAND_INVALID","malformed oversized SBPN precedence drifted");
 auto exact_over_sbpn=malformed_over_sbpn;std::copy_n("SBPN",4,exact_over_sbpn.begin());exact_over_sbpn[4]=1;exact_over_sbpn[6]=32;exact_over_sbpn[8]=1;exact_over_sbpn[9]=16;exact_over_sbpn[16]=136;exact_over_sbpn[17]=128;exact_over_sbpn[18]=6;exact_over_sbpn[24]=32;
 for(std::uint32_t i=0;i<4097;++i){const auto o=32+std::size_t(i)*104;auto p32=[&](std::size_t at,std::uint32_t v){for(unsigned j=0;j<4;++j)exact_over_sbpn[at+j]=v>>(8*j);};auto p64=[&](std::size_t at,std::uint64_t v){for(unsigned j=0;j<8;++j)exact_over_sbpn[at+j]=v>>(8*j);};p32(o,104);p64(o+4,i+1);p32(o+12,i+1);p32(o+16,i);exact_over_sbpn[o+20]=1;p64(o+36,1);exact_over_sbpn[o+44]=2;p64(o+60,1);exact_over_sbpn[o+68]=19;std::copy_n("engine.op.parameter",19,exact_over_sbpn.begin()+o+70);exact_over_sbpn[o+89]=11;std::copy_n("typed_value",11,exact_over_sbpn.begin()+o+91);exact_over_sbpn[o+102]=1;}
 auto over_decoded=sblr::DecodeSblrParameterNodeTableV1(exact_over_sbpn.data(),exact_over_sbpn.size());
 Require(!over_decoded.ok&&over_decoded.diagnostic_id=="RESOURCE.BUDGET_EXCEEDED","exact oversized SBPN resource precedence drifted");
 sblr::SblrParameterNodeV1 n;n.node_id=7;n.parent_operand_ordinal=1;n.slot_ordinal=0;n.parameter_set_descriptor_uuid[0]=1;n.parameter_set_generation=2;n.datatype_descriptor_uuid[0]=3;n.datatype_descriptor_generation=4;sblr::SblrParameterNodeTableV1 t;t.nodes.push_back(n);auto sbpn=sblr::EncodeSblrParameterNodeTableV1(t);Require(sbpn.size()==136,"SBPN extent");auto td=sblr::DecodeSblrParameterNodeTableV1(sbpn.data(),sbpn.size());Require(td.ok&&td.canonical_bytes==sbpn,"SBPN roundtrip");
 std::vector<std::uint8_t> hash_material{'S','c','r','a','t','c','h','B','i','r','d','.','S','b','l','r','P','a','r','a','m','e','t','e','r','N','o','d','e','T','a','b','l','e','.','V','1'};hash_material.insert(hash_material.end(),sbpn.begin(),sbpn.end());auto sha=scratchbird::core::hash::ComputeSha256Digest(hash_material).digest;sblr::SblrParameterNodeReferenceV1 r;r.occurrence_ordinal=1;r.node_id=7;r.table_sha256=sha;r.parameter_set_descriptor_uuid=n.parameter_set_descriptor_uuid;r.parameter_set_generation=2;r.slot_ordinal=0;auto ref=sblr::EncodeSblrParameterNodeReferenceV1(r);Require(ref.size()==80,"kind19 extent");sblr::SblrParameterNodeReferenceV1 rd;Require(sblr::DecodeSblrParameterNodeReferenceV1(ref.data(),ref.size(),&rd)&&sblr::ValidateSblrParameterReferenceBijectionV1(td,{rd}),"kind19 bijection");auto bad_ref=ref;bad_ref[76]=1;Require(!sblr::DecodeSblrParameterNodeReferenceV1(bad_ref.data(),bad_ref.size(),&rd),"kind19 reserve admitted");
 sblr::SblrOperationEnvelope carrier;carrier.operation_id="query.execute";carrier.opcode="SBLR_QUERY_EXECUTE";carrier.opcode_code=0x1207;carrier.operation_version_major=1;carrier.result_shape="query_execute_result.v1";carrier.diagnostic_shape="engine.diagnostic.v1";carrier.trace_key="parameter-test";carrier.parser_package_uuid="019dffbb-f000-7000-8000-000000000001";carrier.registry_snapshot_uuid="019dffbb-f000-7000-8000-000000000002";sblr::SblrOperand table;table.ordinal=1;table.type="expression.parameter_node_table.v1";table.name="parameter_nodes";table.value_kind=sblr::SblrValueKind::parameter_node_table;table.value_body=sbpn;carrier.operands.push_back(table);sblr::SblrOperand reference;reference.ordinal=2;reference.type="relational_expression_v1";reference.name="7";reference.value_kind=sblr::SblrValueKind::parameter_node_ref;reference.value_body=ref;carrier.operands.push_back(reference);Require(sblr::ValidateSblrEnvelope(carrier).ok,"parameter carrier refused");auto missing=carrier;missing.operands.erase(missing.operands.begin());missing.operands.front().ordinal=1;Require(!sblr::ValidateSblrEnvelope(missing).ok,"kind19 without SBPN admitted");auto duplicate=carrier;duplicate.operands.push_back(table);duplicate.operands.back().ordinal=3;Require(!sblr::ValidateSblrEnvelope(duplicate).ok,"duplicate SBPN admitted");carrier.operation_id="engine.op.parameter";carrier.opcode="SBLR_PARAMETER";carrier.opcode_code=4;Require(!sblr::ValidateSblrEnvelope(carrier).ok,"top-level parameter admitted");
 sblr::SblrParameterValueSetV1 values;values.parameter_set_descriptor_uuid=n.parameter_set_descriptor_uuid;values.descriptor_generation=2;values.execution_uuid[0]=5;values.statement_receipt_uuid[0]=6;sblr::SblrParameterValueRecordV1 v;v.slot_ordinal=0;v.slot_uuid[0]=7;v.datatype_descriptor_uuid=n.datatype_descriptor_uuid;v.datatype_descriptor_generation=4;v.direction=sblr::SblrParameterDirectionV1::in;v.state=sblr::SblrParameterValueStateV1::value;v.canonical_value_bytes={1,0,0,0,0,0,0,0};values.records.push_back(v);auto sbpv=sblr::EncodeSblrParameterValueSetV1(values);Require(sbpv.size()==176,"SBPV extent");auto vd=sblr::DecodeSblrParameterValueSetV1(sbpv.data(),sbpv.size());Require(vd.ok&&vd.canonical_bytes==sbpv,"SBPV roundtrip");for(auto offset:{0u,4u,6u,8u,12u,76u,80u,112u,160u}){auto b=sbpv;b[offset]^=1;Require(!sblr::DecodeSblrParameterValueSetV1(b.data(),b.size()).ok,"malformed SBPV admitted");}auto trailing=sbpv;trailing.push_back(0);Require(!sblr::DecodeSblrParameterValueSetV1(trailing.data(),trailing.size()).ok,"SBPV trailing admitted");
 auto out=values;out.records[0].direction=sblr::SblrParameterDirectionV1::out;out.records[0].state=sblr::SblrParameterValueStateV1::unbound;out.records[0].canonical_value_bytes.clear();Require(!sblr::EncodeSblrParameterValueSetV1(out).empty(),"OUT unbound refused");out.records[0].canonical_value_bytes={1};Require(sblr::EncodeSblrParameterValueSetV1(out).empty(),"OUT payload admitted");
 sblr::SblrParameterNegotiateRequestV1 nr;nr.preliminary_receipt_uuid[0]=1;nr.catalog_generation=1;nr.mga_snapshot_uuid[0]=2;sblr::SblrParameterDemandV1 demand;demand.occurrence_id=7;demand.marker_ordinal=1;demand.context_code=1;demand.requested_direction=1;nr.demands.push_back(demand);nr.demand_sha256=sblr::ComputeSblrParameterDemandSha256V1(nr.demands);auto sbpr=sblr::EncodeSblrParameterNegotiateRequestV1(nr);sblr::SblrParameterNegotiateRequestV1 nrd;std::string detail;Require(sbpr.size()==136&&sblr::DecodeSblrParameterNegotiateRequestV1(sbpr.data(),sbpr.size(),&nrd,&detail),"SBPR roundtrip");
 sblr::SblrParameterNegotiateResultV1 ng;ng.preliminary_receipt_uuid=nr.preliminary_receipt_uuid;ng.parameter_set_descriptor_uuid=n.parameter_set_descriptor_uuid;ng.descriptor_generation=2;ng.execution_uuid[0]=3;sblr::SblrParameterMappingV1 mapping;mapping.occurrence_id=7;mapping.slot_ordinal=0;mapping.slot_uuid[0]=4;mapping.datatype_descriptor_uuid=n.datatype_descriptor_uuid;mapping.datatype_descriptor_generation=4;mapping.direction=1;ng.mappings.push_back(mapping);ng.mapping_sha256=sblr::ComputeSblrParameterMappingSha256V1(ng.mappings);auto sbpg=sblr::EncodeSblrParameterNegotiateResultV1(ng);sblr::SblrParameterNegotiateResultV1 ngd;Require(sbpg.size()==168&&sblr::DecodeSblrParameterNegotiateResultV1(sbpg.data(),sbpg.size(),&ngd,&detail),"SBPG roundtrip");
 sblr::SblrParameterFinalizeRequestV1 nf;nf.preliminary_receipt_uuid=nr.preliminary_receipt_uuid;nf.parameter_set_descriptor_uuid=ng.parameter_set_descriptor_uuid;nf.descriptor_generation=2;nf.execution_uuid=ng.execution_uuid;nf.demand_sha256=nr.demand_sha256;nf.mapping_sha256=ng.mapping_sha256;nf.canonical_sbpn=sbpn;std::vector<std::uint8_t> pm{'S','c','r','a','t','c','h','B','i','r','d','.','S','b','l','r','P','a','r','a','m','e','t','e','r','N','o','d','e','T','a','b','l','e','.','V','1'};pm.insert(pm.end(),sbpn.begin(),sbpn.end());nf.sbpn_sha256=scratchbird::core::hash::ComputeSha256Digest(pm).digest;auto sbpf=sblr::EncodeSblrParameterFinalizeRequestV1(nf);sblr::SblrParameterFinalizeRequestV1 nfd;Require(sbpf.size()==312&&sblr::DecodeSblrParameterFinalizeRequestV1(sbpf.data(),sbpf.size(),&nfd,&detail),"SBPF roundtrip");
 sblr::SblrParameterAdmissionV1 na;na.final_receipt_uuid[0]=5;na.admission_token_uuid[0]=6;na.parameter_set_descriptor_uuid=ng.parameter_set_descriptor_uuid;na.descriptor_generation=2;na.execution_uuid=ng.execution_uuid;auto sbpa=sblr::EncodeSblrParameterAdmissionV1(&na);sblr::SblrParameterAdmissionV1 nad;Require(sbpa.size()==192&&sblr::DecodeSblrParameterAdmissionV1(sbpa.data(),sbpa.size(),&nad,&detail),"SBPA roundtrip");
 sblr::SblrParameterNegotiateRequestV1 empty_request=nr;empty_request.demands.clear();empty_request.demand_sha256={};Require(sblr::EncodeSblrParameterNegotiateRequestV1(empty_request).empty(),"empty SBPR refused");
 std::vector<std::uint8_t> exact_over_sbpr(112+4097*24);auto put32=[&](std::size_t at,std::uint32_t value){for(unsigned i=0;i<4;++i)exact_over_sbpr[at+i]=value>>(8*i);};auto put64=[&](std::size_t at,std::uint64_t value){for(unsigned i=0;i<8;++i)exact_over_sbpr[at+i]=value>>(8*i);};std::copy_n("SBPR",4,exact_over_sbpr.begin());exact_over_sbpr[4]=1;exact_over_sbpr[6]=112;put32(8,exact_over_sbpr.size());exact_over_sbpr[16]=1;put64(32,1);exact_over_sbpr[56]=2;put32(72,4097);put32(76,24);exact_over_sbpr[80]=1;for(std::uint32_t i=0;i<4097;++i){const auto o=112+std::size_t(i)*24;put64(o,i+1);put32(o+8,i+1);exact_over_sbpr[o+12]=1;exact_over_sbpr[o+14]=1;}Require(sblr::PrevalidateSblrParameterNegotiateRequestV1(exact_over_sbpr.data(),exact_over_sbpr.size())==sblr::SblrParameterWirePrevalidationV1::resource_exceeded,"exact oversized SBPR resource precedence drifted");exact_over_sbpr[112+14]=2;Require(sblr::PrevalidateSblrParameterNegotiateRequestV1(exact_over_sbpr.data(),exact_over_sbpr.size())==sblr::SblrParameterWirePrevalidationV1::operand_invalid,"malformed oversized SBPR operand precedence drifted");
 auto bad_demands=nr.demands;bad_demands.push_back(demand);bad_demands.back().occurrence_id=8;bad_demands.back().marker_ordinal=3;Require(sblr::ComputeSblrParameterDemandSha256V1(bad_demands)==std::array<std::uint8_t,32>{},"non-dense parameter markers refused");
 auto bad_mappings=ng.mappings;bad_mappings.push_back(mapping);bad_mappings.back().occurrence_id=8;bad_mappings.back().slot_ordinal=2;Require(sblr::ComputeSblrParameterMappingSha256V1(bad_mappings)==std::array<std::uint8_t,32>{},"non-dense parameter slots refused");
 auto bad_admission=na;bad_admission.prepared_uuid[0]=9;Require(sblr::EncodeSblrParameterAdmissionV1(&bad_admission).empty(),"partial prepared identity refused");bad_admission.prepared_generation=1;bad_admission.dynamic_uuid[0]=10;bad_admission.dynamic_generation=1;Require(sblr::EncodeSblrParameterAdmissionV1(&bad_admission).empty(),"prepared dynamic matrix refused");
 sblr::SblrPreparedParameterTemplateV1 pt;pt.public_coordination_uuid[0]=1;pt.operation_uuid[0]=2;pt.provisional_prepared_uuid[0]=3;pt.provisional_prepared_generation=4;pt.parameter_set_descriptor_uuid=ng.parameter_set_descriptor_uuid;pt.descriptor_generation=2;pt.canonical_schema4015={1,2,3,4};pt.canonical_sbpa=sbpa;pt.sbpn_sha256=nf.sbpn_sha256;pt.executor_availability_generation=5;pt.catalog_generation=6;pt.mga_snapshot_uuid[0]=7;auto sbpt=sblr::EncodeSblrPreparedParameterTemplateV1(&pt);Require(sbpt.size()==476,"SBPT exact extent");auto ptd=sblr::DecodeSblrPreparedParameterTemplateV1(sbpt.data(),sbpt.size());Require(ptd.ok&&ptd.canonical_bytes==sbpt,"SBPT roundtrip");for(auto offset:{0u,4u,6u,8u,12u,96u,100u,104u,168u,248u}){auto malformed=sbpt;malformed[offset]^=1;Require(!sblr::DecodeSblrPreparedParameterTemplateV1(malformed.data(),malformed.size()).ok,"malformed SBPT admitted");}return EXIT_SUCCESS;
}
