#include "engine/sblr/sblr_source_map_runtime.hpp"
#include <cstdlib>
#include <iostream>
namespace s=scratchbird::engine::sblr;void R(bool v,const char*m){if(!v){std::cerr<<m<<'\n';std::exit(1);}}
int main(){s::SblrSourceMapDescriptorVectorV1 v;v.descriptor_uuid[0]=1;v.descriptor_generation=1;v.registry_snapshot_uuid[0]=2;v.registry_generation=3;v.statement_receipt_uuid[0]=4;v.bound_ast_sha256[0]=5;s::SblrSourceMapEntryV1 e;e.node_id=7;e.source_artifact_uuid[0]=6;e.source_artifact_generation=1;e.byte_length=2;e.line=1;e.column=1;v.entries.push_back(e);auto b=s::EncodeSblrSourceMapDescriptorVectorV1(&v);R(b.size()==256,"SMVD extent");auto d=s::DecodeSblrSourceMapDescriptorVectorV1(b.data(),b.size());R(d.status==s::SblrSourceMapDecodeStatusV1::ok&&d.canonical_bytes==b,"SMVD roundtrip");for(auto o:{0u,4u,6u,8u,12u,116u,120u,218u,224u}){auto m=b;m[o]^=1;R(s::DecodeSblrSourceMapDescriptorVectorV1(m.data(),m.size()).status==s::SblrSourceMapDecodeStatusV1::operand_invalid,"SMVD mutation admitted");}
  s::SblrSourceMapBoundAstV1 ast;ast.statement_receipt_uuid=v.statement_receipt_uuid;ast.nodes.push_back({7,0,1});auto ab=s::EncodeSblrSourceMapBoundAstV1(&ast);R(ab.size()==96,"SMBA extent");s::SblrSourceMapBoundAstV1 ad;std::string detail;R(s::DecodeSblrSourceMapBoundAstV1(ab.data(),ab.size(),&ad,&detail),"SMBA roundtrip");
  s::SblrSourceMapIssueRequestV1 q;q.statement_receipt_uuid=v.statement_receipt_uuid;q.registry_snapshot_uuid=v.registry_snapshot_uuid;q.registry_generation=3;q.canonical_bound_ast=ab;q.entries={e};auto qb=s::EncodeSblrSourceMapIssueRequestV1(&q);R(qb.size()==336,"SMRQ extent");s::SblrSourceMapIssueRequestV1 qd;R(s::DecodeSblrSourceMapIssueRequestV1(qb.data(),qb.size(),&qd,&detail),"SMRQ roundtrip");auto qm=qb;qm[92]^=1;R(!s::DecodeSblrSourceMapIssueRequestV1(qm.data(),qm.size(),&qd,&detail),"SMRQ mutation admitted");auto coverage=q;coverage.entries[0].node_id=8;R(s::EncodeSblrSourceMapIssueRequestV1(&coverage).empty(),"SMRQ node coverage mismatch admitted");
  s::SblrSourceMapIssueResultV1 rs;rs.descriptor_uuid=v.descriptor_uuid;rs.descriptor_generation=1;rs.registry_generation=3;rs.canonical_smvd=b;auto rb=s::EncodeSblrSourceMapIssueResultV1(rs);R(rb.size()==320,"SMRS extent");s::SblrSourceMapIssueResultV1 rd;R(s::DecodeSblrSourceMapIssueResultV1(rb.data(),rb.size(),&rd,&detail),"SMRS roundtrip");auto rm=rb;rm[52]=1;R(!s::DecodeSblrSourceMapIssueResultV1(rm.data(),rm.size(),&rd,&detail),"SMRS mutation admitted");
  auto absent=v;absent.entries[0].redaction_class=4;absent.entries[0].source_artifact_uuid={};absent.entries[0].source_artifact_generation=0;absent.entries[0].byte_length=0;absent.entries[0].line=0;absent.entries[0].column=0;R(!s::EncodeSblrSourceMapDescriptorVectorV1(&absent).empty(),"SMVD absent redaction refused");return 0;}
