// Copyright (c) 2026 ScratchBird Software Inc.
// SPDX-License-Identifier: MPL-2.0
#include "sblr_variable_frame_coordinator.hpp"
#include "uuid.hpp"

#include <cassert>
#include <chrono>
#include <filesystem>

using namespace scratchbird::engine::internal_api;
namespace {
std::string Id(scratchbird::core::platform::UuidKind kind){static auto n=static_cast<std::uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count());auto v=scratchbird::core::uuid::GenerateEngineIdentityV7(kind,++n);assert(v.ok());return scratchbird::core::uuid::UuidToString(v.value.value);}
EngineRequestContext Context(const std::filesystem::path&base){EngineRequestContext c;c.database_path=base.string();c.database_uuid.canonical=Id(scratchbird::core::platform::UuidKind::database);c.session_uuid.canonical=Id(scratchbird::core::platform::UuidKind::object);c.transaction_uuid.canonical=Id(scratchbird::core::platform::UuidKind::object);c.statement_uuid.canonical=Id(scratchbird::core::platform::UuidKind::object);c.catalog_epoch_uuid.canonical="019d0000-0000-7000-8000-00000000d701";c.catalog_generation_id=1;c.security_context_present=true;c.statement_metadata_snapshot_engine_owned=true;c.trace_tags={"private_variable_frame_coordination"};return c;}
SblrVariableFrameDemand Demand(std::uint64_t occurrence,bool nullable=false){return {occurrence,1,nullable,SblrVariableMutability::mutable_value,nullable?SblrVariableValueState::null_value:SblrVariableValueState::uninitialized,"sha256:"+std::string(64,occurrence==1?'a':'b')};}
}
int main(){const auto base=std::filesystem::temp_directory_path()/"sb_variable_frame_coordinator_test";std::error_code ec;std::filesystem::remove(base.string()+".sb.sblr_variable_frame_coordinator.v1",ec);std::filesystem::remove(base.string()+".sb.sblr_variable_registry.v1",ec);auto c=Context(base);auto op=Id(scratchbird::core::platform::UuidKind::object);auto begin=BeginSblrVariableFrame(c,op,1000000,{Demand(1),Demand(2,true)});assert(begin.ok&&begin.snapshot.private_handle!=0&&begin.snapshot.mappings.size()==2);assert(begin.snapshot.mappings[0].descriptor.variable_ordinal==0&&begin.snapshot.mappings[1].descriptor.variable_ordinal==1);auto stale=AcquireSblrVariableFrame(c,begin.snapshot.public_coordination_uuid,op,begin.snapshot.coordinator_generation+1);assert(!stale.ok&&stale.diagnostic.code=="SBLR.VARIABLE.STALE");auto acquired=AcquireSblrVariableFrame(c,begin.snapshot.public_coordination_uuid,op,begin.snapshot.coordinator_generation);assert(acquired.ok&&acquired.snapshot.coordinator_generation>begin.snapshot.coordinator_generation&&acquired.snapshot.private_handle==begin.snapshot.private_handle);
  std::vector<SblrVariableAssignment> assignments;for(const auto&m:acquired.snapshot.mappings)assignments.push_back({m.descriptor.variable_descriptor_uuid,m.descriptor.variable_descriptor_generation,m.descriptor.value_generation,SblrVariableValueState::value,"assigned"});
  auto assigned=AssignSblrVariableFrameValues(c,acquired.snapshot.public_coordination_uuid,op,acquired.snapshot.statement_receipt_uuid,acquired.snapshot.coordinator_generation,acquired.snapshot.registry_generation,assignments);assert(assigned.ok&&assigned.snapshot.coordinator_generation>acquired.snapshot.coordinator_generation&&assigned.snapshot.registry_generation>acquired.snapshot.registry_generation&&assigned.snapshot.mappings[0].descriptor.value_generation==2&&assigned.snapshot.mappings[1].descriptor.value_generation==2);
  auto replay=AssignSblrVariableFrameValues(c,acquired.snapshot.public_coordination_uuid,op,acquired.snapshot.statement_receipt_uuid,acquired.snapshot.coordinator_generation,acquired.snapshot.registry_generation,assignments);assert(!replay.ok&&replay.diagnostic.code=="SBLR.VARIABLE.STALE");
  auto wrong=c;wrong.session_uuid.canonical=Id(scratchbird::core::platform::UuidKind::object);auto hidden=AcquireSblrVariableFrame(wrong,begin.snapshot.public_coordination_uuid,op,assigned.snapshot.coordinator_generation);assert(!hidden.ok&&hidden.diagnostic.code=="SECURITY.ACCESS_DENIED");auto admin=c;admin.trace_tags={"right:SBLR_VARIABLE_FRAME_ADMIN"};assert(RecoverSblrVariableFrameCoordinator(admin).code=="OK");hidden=AcquireSblrVariableFrame(c,begin.snapshot.public_coordination_uuid,op,assigned.snapshot.coordinator_generation);assert(!hidden.ok&&hidden.diagnostic.code=="SECURITY.ACCESS_DENIED");auto next=BeginSblrVariableFrame(c,Id(scratchbird::core::platform::UuidKind::object),1000000,{Demand(1)});assert(next.ok&&next.snapshot.coordinator_generation>assigned.snapshot.coordinator_generation);auto closed=CloseSblrVariableFrame(c,next.snapshot.public_coordination_uuid,next.snapshot.operation_uuid,next.snapshot.frame_generation,"frame.close");assert(closed.ok&&closed.snapshot.state==SblrVariableFrameState::revoked&&closed.snapshot.private_handle==0&&closed.snapshot.frame_generation>next.snapshot.frame_generation);std::filesystem::remove(base.string()+".sb.sblr_variable_frame_coordinator.v1",ec);std::filesystem::remove(base.string()+".sb.sblr_variable_registry.v1",ec);}
