// Copyright (c) 2026 ScratchBird Software Inc.
// SPDX-License-Identifier: MPL-2.0
#define SCRATCHBIRD_IA01_MISSING_EXECUTOR_FIXTURE_ONLY
#include "ia01_package_missing_executor_integration_test.cpp"
#include "ia01_variable_live_fixture.hpp"

int main(){auto fixture=CreateFixture();PublicSession session(fixture);std::atomic<unsigned> probes{0};
  auto context=BeginTransaction(fixture,&probes);context.query_cancellation_requested=[&probes]{return probes.fetch_add(1)+1==2;};
  auto live=variable_fixture::Build(fixture,session,&context);
  bridge::StatementPackageAdmissionReservationRequest rr;rr.receipt=live.receipt;rr.canonical_payload_bytes=live.submission.stream.data();rr.canonical_payload_size=live.submission.stream.size();rr.payload_kind=bridge::StatementSblrPayloadKind::kOpcodeStream;
  bridge::StatementPackageAdmissionReservationHandle reservation;bridge::StatementPackageAdmissionReservationView rv;sb_engine_result_t result=nullptr;
  Require(bridge::AcquireStatementPackageAdmissionReservation(&rr,&reservation,&rv,&result)==SB_ENGINE_STATUS_OK,"002336 reservation failed");if(result)(void)sb_engine_result_release(result);
  const auto parser_uuid=Text(NewUuid(platform::UuidKind::object,9363));server::ServerSblrAdmissionRequest a;a.encoded_sblr_container=live.submission.container;a.encoded_execution_envelope=live.submission.ingress;a.admitted_parser_package_uuid=parser_uuid;a.admitted_parser_package_version_major=1;a.admitted_registry_snapshot_uuid=live.view.catalog_epoch_uuid;a.authenticated_principal_uuid=Text(fixture.principal_uuid);a.catalog_snapshot_uuid=live.view.statement_metadata_snapshot_uuid;a.engine_mga_statement_uuid=live.view.statement_uuid;a.engine_mga_snapshot_uuid=live.view.statement_snapshot_uuid;a.catalog_epoch=live.view.catalog_generation_id;a.security_epoch=live.view.security_epoch;a.resource_epoch=live.view.resource_epoch;a.route_snapshot_uuid=live.view.optimizer_route_snapshot_uuid;a.route_epoch=live.view.optimizer_route_epoch;a.route_generation=live.view.optimizer_route_generation;a.security_snapshot_uuid=live.view.security_context_uuid;a.security_observation_generation=live.view.security_epoch;a.route_snapshot_engine_owned=true;a.security_snapshot_engine_owned=true;a.package_reservation_handle=reservation.opaque_id;a.reserved_payload_kind=server::ServerSblrPayloadKind::opcode_stream;a.reserved_payload_size=rv.payload_size;a.reserved_record_count=rv.record_count;a.reserved_resource_policy_generation=rv.resource_policy_generation;a.reserved_payload_sha256=rv.payload_sha256;
  a.admitted_parser_package_uuid=live.parser_uuid;const auto admitted=server::AdmitServerSblrEnvelope(a);Require(admitted.admitted&&admitted.admission_token,"002336 admission failed");auto dispatch=DispatchRequest(live.receipt,session.session,reservation,admitted.admission_token);dispatch.variable_execution_binding=live.sbve;
  result=nullptr;const auto status=bridge::DispatchStatementContextReceipt(&dispatch,&result);Require(status==SB_ENGINE_STATUS_TIMEOUT&&result,"002336 cancellation status drifted");sb_engine_diagnostic_set_view_t ds{};Require(sb_engine_result_diagnostics(result,&ds)==SB_ENGINE_STATUS_OK&&ds.diagnostic_count==1,"002336 diagnostic missing");const std::string code(ds.diagnostics[0].symbolic_code.data,ds.diagnostics[0].symbolic_code.size_bytes);const std::string key(ds.diagnostics[0].message_key.data,ds.diagnostics[0].message_key.size_bytes);Require(code=="PROCESS.CANCELLED"&&key=="sblr.variable.cancelled_before_node","002336 cancellation boundary drifted");Require(probes.load()==2,"002336 callback sequence drifted");sb_engine_execution_summary_view_v1_t summary{};Require(sb_engine_result_summary(result,&summary)!=SB_ENGINE_STATUS_OK||summary.rows_produced==0,"002336 published rows");(void)sb_engine_result_release(result);
  result=nullptr;Require(bridge::DispatchStatementContextReceipt(&dispatch,&result)==SB_ENGINE_STATUS_INVALID_HANDLE,"002336 token replay admitted");if(result)(void)sb_engine_result_release(result);Require(probes.load()==2,"002336 replay retried callback");Require(session.End()==SB_ENGINE_STATUS_OK,"002336 cleanup failed");Require(bridge::ReleaseStatementContextReceipt(live.receipt)==SB_ENGINE_STATUS_ALREADY_RELEASED,"002336 receipt cleanup drifted");api::EngineRollbackTransactionRequest rollback;rollback.context=context;Require(api::EngineRollbackTransaction(rollback).ok,"002336 rollback failed");return EXIT_SUCCESS;}
