#include "engine/internal_api/sblr_executor_availability_registry.hpp"
#include <cassert>
int main(){using namespace scratchbird::engine::internal_api;SblrExecutorAvailabilityRowIdentity r{kSblrSecurityCreateUserExecutorId,kSblrSecurityCreateUserOpcodeCode,kSblrSecurityCreateUserOpcodeVersion,kSblrSecurityCreateUserOperandDescriptorId,kSblrSecurityCreateUserResultDescriptorId,kSblrSecurityCreateUserResultDescriptorVersion};assert(IsAdmittedExecutorAvailabilityIdentity(r));return 0;}
