// Copyright (c) 2026 ScratchBird Software Inc.
// SPDX-License-Identifier: MPL-2.0
#include "native_retention_root.hpp"
#include "disk_device.hpp"
#include <openssl/sha.h>
#include <openssl/evp.h>
#include <algorithm>
#include <cerrno>
#include <cstdlib>
#include <filesystem>
#include <iostream>
#include <new>
#include <source_location>
#include <stdexcept>
#include <unistd.h>
namespace {long allocation_budget=-1;unsigned long allocations=0;bool count_allocations=false;unsigned reads=0,fail_read=0,hash_calls=0,fail_hash=0,full_calls=0,fail_full=0;}
void* operator new(std::size_t n){if(count_allocations)++allocations;if(allocation_budget==0){allocation_budget=-1;throw std::bad_alloc();}if(allocation_budget>0)--allocation_budget;if(auto* p=std::malloc(n?n:1))return p;throw std::bad_alloc();}
void* operator new[](std::size_t n){return ::operator new(n);}void operator delete(void* p) noexcept{std::free(p);}void operator delete[](void* p) noexcept{std::free(p);}void operator delete(void* p,std::size_t) noexcept{std::free(p);}void operator delete[](void* p,std::size_t) noexcept{std::free(p);}
extern "C" ssize_t __real_pread(int,void*,size_t,off_t);
extern "C" ssize_t __wrap_pread(int fd,void* p,size_t n,off_t o){++reads;if(fail_read==reads){errno=EIO;return -1;}return __real_pread(fd,p,n,o);}
extern "C" EVP_MD_CTX* __real_EVP_MD_CTX_new();
extern "C" EVP_MD_CTX* __wrap_EVP_MD_CTX_new(){++hash_calls;if(fail_hash==hash_calls)return nullptr;return __real_EVP_MD_CTX_new();}
extern "C" int __real_EVP_Digest(const void*,size_t,unsigned char*,unsigned int*,const EVP_MD*,ENGINE*);
extern "C" int __wrap_EVP_Digest(const void* b,size_t n,unsigned char* out,unsigned int* count,const EVP_MD* md,ENGINE* e){++full_calls;if(fail_full==full_calls)return 0;return __real_EVP_Digest(b,n,out,count,md,e);}
namespace {
namespace p=scratchbird::storage::page;namespace d=scratchbird::storage::disk;using namespace scratchbird::core::platform;using Bytes=std::vector<byte>;using E=p::NativeRetentionError;std::size_t checks=0;
void Check(bool good,const char* message,std::source_location at=std::source_location::current()){++checks;if(!good)throw std::runtime_error(std::string(message)+" line="+std::to_string(at.line()));}
Uuid Id(byte n){Uuid id;id.bytes[6]=0x70;id.bytes[8]=0x80;id.bytes[15]=n;return id;}
void Num(Bytes& b,std::size_t at,unsigned n,u64 v){for(unsigned i=0;i<n;++i)b[at+i]=static_cast<byte>(v>>(i*8));}
void Put(Bytes& b,std::size_t at,const Uuid& id){std::copy(id.bytes.begin(),id.bytes.end(),b.begin()+at);}
void Ref(Bytes& b,std::size_t at,const d::NativePageReference& r){Put(b,at,r.filespace_uuid);Num(b,at+16,8,r.page_number);Num(b,at+24,8,r.page_generation);Put(b,at+32,r.page_size_profile_uuid);}
std::array<byte,32> Hash(const Bytes& b){std::array<byte,32> h{};Check(SHA256(b.data(),b.size(),h.data())!=nullptr,"independent image hash");return h;}
void Seal(Bytes& b){std::fill(b.begin()+328,b.begin()+360,0);const auto h=Hash(b);std::copy(h.begin(),h.end(),b.begin()+328);}
Bytes Oracle(const p::NativeRetentionPage& v){const auto& h=v.header;Bytes b(h.page_size_bytes,0);std::copy_n("SBPGV002",8,b.begin());Num(b,8,4,128);Num(b,12,4,h.page_size_bytes);Num(b,16,4,h.page_type);Num(b,20,2,1);Num(b,22,2,1);Put(b,24,h.database_uuid);Put(b,40,h.filespace_uuid);Put(b,56,h.page_uuid);Num(b,72,8,h.page_number);Num(b,80,8,h.page_generation);Num(b,88,8,h.flags);Put(b,104,h.page_size_profile_uuid);Num(b,120,2,1);
  u64 fnv=14695981039346656037ull;for(unsigned i=0;i<128;++i){fnv^=b[i];fnv*=1099511628211ull;}Num(b,96,8,fnv);
  std::copy_n(h.page_type==0x303?"SBPIN001":"SBPINL01",8,b.begin()+128);Num(b,136,2,1);Num(b,138,2,256);Num(b,140,4,384+160*v.records.size());Put(b,144,v.object_uuid);Num(b,160,8,v.epoch);Put(b,168,v.creator_transaction_uuid);Num(b,184,8,v.creator_local_transaction_id);Num(b,192,8,v.flags);Num(b,200,8,v.total_pins);Num(b,208,8,v.first_record);Num(b,216,4,v.records.size());if(v.next)Ref(b,224,*v.next);std::copy(v.next_sha256.begin(),v.next_sha256.end(),b.begin()+272);Num(b,304,8,v.legal_hold_pins);Num(b,312,8,v.lowest_start);Num(b,320,8,v.highest_end);
  for(std::size_t i=0;i<v.records.size();++i){const auto at=384+i*160;const auto& r=v.records[i];Put(b,at,r.pin_uuid);Put(b,at+16,r.owner_uuid);Num(b,at+32,2,static_cast<u16>(r.kind));Num(b,at+34,2,static_cast<u16>(r.access));Num(b,at+36,4,r.flags);Num(b,at+40,8,r.start_local);Num(b,at+48,8,r.end_local);Put(b,at+56,r.timeline_uuid);Put(b,at+72,r.filespace_uuid);Num(b,at+88,8,r.retain_until_local);Num(b,at+96,8,r.retain_until_unix_ns);Num(b,at+104,8,r.blocked_operations);const auto digest=Hash(Bytes(b.begin()+at,b.begin()+at+160));std::copy(digest.begin(),digest.end(),b.begin()+at+112);}
  Seal(b);return b;
}
d::FilespacePageZero Zero(unsigned profile,byte fs){d::FilespacePageZero z;auto& b=z.bootstrap;const auto& registered=d::kCanonicalFilespacePageProfiles[profile];b.database_uuid=Id(1);b.filespace_uuid=Id(fs);b.page_size_profile_uuid=registered.uuid;b.page_size_bytes=registered.page_size_bytes;b.checksum_profile_uuid=d::kNativeBootstrapIntegrityProfile;b.filespace_role=1;b.lifecycle_state=1;z.page_uuid=Id(30+fs);z.creation_operation_uuid=Id(40+fs);z.writer_identity_uuid=Id(50+fs);z.page_generation=3;z.root_set_generation=5;z.total_pages=64;
  constexpr unsigned types[]={0,8,5,3,769,9,10,11,5,768};for(unsigned k=1;k<=9;++k)z.roots.push_back({static_cast<u16>(k),types[k],Id(fs),10+k,100+k,registered.uuid,Id(60+k)});return z;}
p::NativeRetentionPage Leaf(unsigned profile=0){const auto z=Zero(profile,2);p::NativeRetentionPage v;v.header={z.bootstrap.page_size_bytes,0x304,Id(1),Id(2),Id(81),41,141,0,z.bootstrap.page_size_profile_uuid};v.object_uuid=Id(120);v.epoch=3;v.creator_transaction_uuid=Id(91);v.creator_local_transaction_id=11;v.total_pins=1;p::NativeRetentionPin r;r.pin_uuid=Id(90);r.owner_uuid=Id(93);r.flags=1;r.start_local=4;r.end_local=9;r.timeline_uuid=Id(95);r.filespace_uuid=Id(2);r.retain_until_unix_ns=1;r.blocked_operations=3;v.records.push_back(r);return v;}
p::NativeRetentionPage Root(unsigned profile=0){auto v=Leaf(profile);v.header.page_type=0x303;v.header.page_uuid=Id(80);v.header.page_number=40;v.header.page_generation=140;v.lowest_start=4;v.highest_end=9;v.records.clear();v.next=d::NativePageReference{Id(2),41,141,v.header.page_size_profile_uuid};v.next_sha256.fill(1);return v;}
void Empty(const p::NativeRetentionPageResult& r){Check(!r.ok()&&!r.page&&r.bytes.empty(),"failed retention image has no prefix");}
void Empty(const p::NativeRetentionChainResult& r){Check(!r.ok()&&r.images.empty()&&!r.retained_image_bytes,"failed retention chain has no prefix");}
void Images(){for(unsigned profile=0;profile<5;++profile){auto root=Root(profile);Check(p::EncodeNativeRetentionPage(root).bytes==Oracle(root)&&p::DecodeNativeRetentionPage(Oracle(root)).ok(),"independent root image");root.total_pins=root.lowest_start=root.highest_end=0;root.next.reset();root.next_sha256.fill(0);Check(p::EncodeNativeRetentionPage(root).bytes==Oracle(root)&&p::DecodeNativeRetentionPage(Oracle(root)).ok(),"independent empty root image");
    for(unsigned kind=1;kind<=8;++kind)for(unsigned access=1;access<=6;++access){auto v=Leaf(profile);v.flags=1;v.records[0].kind=static_cast<p::NativeRetentionKind>(kind);v.records[0].access=static_cast<p::NativeRetentionAccess>(access);const auto bytes=Oracle(v);Check(p::EncodeNativeRetentionPage(v).bytes==bytes&&p::DecodeNativeRetentionPage(bytes).ok(),"all pin kinds access classes and profiles");}
    auto v=Leaf(profile);const auto capacity=(v.header.page_size_bytes-384)/160;auto pin=v.records[0];v.records.clear();v.total_pins=capacity;for(unsigned i=0;i<capacity;++i){pin.pin_uuid=Id(0);pin.pin_uuid.bytes[14]=i>>8;pin.pin_uuid.bytes[15]=i&255;v.records.push_back(pin);}const auto bytes=Oracle(v);Check(p::EncodeNativeRetentionPage(v).bytes==bytes&&p::DecodeNativeRetentionPage(bytes).ok(),"exact leaf capacity");v.records.push_back(pin);++v.total_pins;Empty(p::EncodeNativeRetentionPage(v));auto overflow=bytes;Num(overflow,216,4,capacity+1);Seal(overflow);Empty(p::DecodeNativeRetentionPage(overflow));}
  for(const auto v:{Root(),Leaf()}){const auto good=Oracle(v);for(std::size_t i=0;i<good.size();++i){auto bytes=good;bytes[i]^=1;Empty(p::DecodeNativeRetentionPage(bytes));}}
  for(unsigned n=0;n<27;++n){auto v=Leaf();auto& r=v.records[0];switch(n){case 0:v.object_uuid={};break;case 1:v.epoch=0;break;case 2:v.creator_transaction_uuid.bytes[6]=0x40;break;case 3:v.creator_local_transaction_id=0;break;case 4:v.flags=2;break;case 5:v.total_pins=0;break;case 6:v.first_record=1;break;case 7:v.legal_hold_pins=1;break;case 8:v.lowest_start=1;break;case 9:v.total_pins=2;break;case 10:r.pin_uuid={};break;case 11:r.owner_uuid={};break;case 12:r.timeline_uuid={};break;case 13:r.filespace_uuid.bytes[6]=0x40;break;case 14:r.kind=static_cast<p::NativeRetentionKind>(9);break;case 15:r.access=static_cast<p::NativeRetentionAccess>(7);break;case 16:r.start_local=0;break;case 17:r.end_local=r.start_local;break;case 18:r.flags=32;break;case 19:r.flags=7;break;case 20:r.flags=4;break;case 21:r.flags=9;break;case 22:r.blocked_operations=0;break;case 23:r.blocked_operations=32;break;case 24:r.blocked_operations=2;break;case 25:r.kind=p::NativeRetentionKind::cluster_replay;break;case 26:r.kind=p::NativeRetentionKind::detached_filespace;r.filespace_uuid={};break;}Empty(p::EncodeNativeRetentionPage(v));Empty(p::DecodeNativeRetentionPage(Oracle(v)));}
  for(unsigned n=0;n<7;++n){auto v=Root();if(n==0)v.total_pins=0;if(n==1)v.lowest_start=0;if(n==2)v.highest_end=4;if(n==3)v.legal_hold_pins=2;if(n==4)v.first_record=1;if(n==5)v.records=Leaf().records;if(n==6)v.next->page_number=40;Empty(p::EncodeNativeRetentionPage(v));Empty(p::DecodeNativeRetentionPage(Oracle(v)));}
  auto bytes=Oracle(Leaf());Put(bytes,400,Id(99));Seal(bytes);Empty(p::DecodeNativeRetentionPage(bytes));
  for(auto offset:{128u,136u,138u,140u,216u,220u,360u,544u}){auto b=Oracle(Leaf());b[offset]^=1;Seal(b);Empty(p::DecodeNativeRetentionPage(b));}
  auto legal=Leaf();legal.records[0].kind=p::NativeRetentionKind::legal_hold;legal.records[0].flags=3;Empty(p::EncodeNativeRetentionPage(legal));Empty(p::DecodeNativeRetentionPage(Oracle(legal)));
}
struct Fixture{std::filesystem::path root;Fixture(){std::string pattern=(std::filesystem::temp_directory_path()/"sb_retention.XXXXXX").string();Check(::mkdtemp(pattern.data())!=nullptr,"isolated retention fixture");root=pattern;}~Fixture(){std::error_code e;std::filesystem::remove_all(root,e);}};
void Chains(){for(unsigned profile=0;profile<5;++profile){const auto other=(profile+1)%5;Fixture fixture;d::FileDevice first,second;const auto path1=(fixture.root/"first").string(),path2=(fixture.root/"second").string();auto z1=Zero(profile,2),z2=Zero(other,7);Check(first.Open(path1,d::FileOpenMode::create_new).ok()&&second.Open(path2,d::FileOpenMode::create_new).ok(),"own actual retention filespaces");const byte pad=0;Check(first.WriteAt(z1.total_pages*z1.bootstrap.page_size_bytes-1,&pad,1).ok()&&second.WriteAt(z2.total_pages*z2.bootstrap.page_size_bytes-1,&pad,1).ok(),"actual retention filespace capacities");
  auto root=Root(profile),a=Leaf(profile),b=a;root.total_pins=a.total_pins=b.total_pins=2;root.legal_hold_pins=1;root.highest_end=0;a.records[0].start_local=8;a.records[0].end_local=12;b.records[0].pin_uuid=Id(92);b.records[0].kind=p::NativeRetentionKind::legal_hold;b.records[0].access=p::NativeRetentionAccess::legal_hold;b.records[0].end_local=0;b.first_record=1;b.header={z2.bootstrap.page_size_bytes,0x304,Id(1),Id(7),Id(82),42,142,0,z2.bootstrap.page_size_profile_uuid};a.next=d::NativePageReference{Id(7),42,142,z2.bootstrap.page_size_profile_uuid};
  const auto put=[&](auto& file,u64 page,unsigned size,const Bytes& bytes){const auto io=file.WriteAt(page*size,bytes.data(),bytes.size());Check(io.ok()&&io.bytes_transferred==bytes.size()&&file.Sync().ok(),"persist independent retention image");};
  const auto persist=[&](auto r,auto x,const auto& y){const auto last=Oracle(y);x.next_sha256=Hash(last);const auto middle=Oracle(x);if(r.next)r.next_sha256=Hash(middle);else r.next_sha256.fill(0);const auto first_zero=d::EncodeFilespacePageZero(z1),second_zero=d::EncodeFilespacePageZero(z2);Check(first_zero.ok()&&second_zero.ok(),"enclosing page-zero fixtures");put(first,0,z1.bootstrap.page_size_bytes,*first_zero.bytes);put(second,0,z2.bootstrap.page_size_bytes,*second_zero.bytes);put(first,40,z1.bootstrap.page_size_bytes,Oracle(r));put(first,41,z1.bootstrap.page_size_bytes,middle);put(second,42,z2.bootstrap.page_size_bytes,last);};
  const std::vector<d::NativeFilespaceDevice> devices{{Id(7),z2.bootstrap.page_size_profile_uuid,&second},{Id(2),z1.bootstrap.page_size_profile_uuid,&first}};const d::NativePageReference reference{Id(2),40,140,z1.bootstrap.page_size_profile_uuid};const u64 budget=2*z1.bootstrap.page_size_bytes+z2.bootstrap.page_size_bytes;const auto read=[&](u64 limit){return p::ReadNativeRetentionRootFromOpenDevices(Id(1),devices,Id(120),reference,limit);};
  persist(root,a,b);reads=hash_calls=full_calls=0;allocations=0;count_allocations=true;auto result=read(budget);count_allocations=false;const auto nr=reads,nh=hash_calls,nf=full_calls;const auto na=allocations;auto expected_a=a,expected_root=root;expected_a.next_sha256=Hash(Oracle(b));expected_root.next_sha256=Hash(Oracle(expected_a));
  const auto exact=[&](const auto& r){return r.ok()&&r.images.size()==3&&r.retained_image_bytes==budget&&r.images[0].bytes==Oracle(expected_root)&&r.images[1].bytes==Oracle(expected_a)&&r.images[2].bytes==Oracle(b);};Check(exact(result)&&result.images[1].page->records[0].retain_until_unix_ns==1,"actual complete pins including expired but unreleased retention");Empty(read(budget-1));Empty(read(0));
  for(unsigned n=1;n<=nr;++n){reads=0;fail_read=n;result=read(budget);fail_read=0;Empty(result);Check(result.error==E::io_failure,"actual retention read fault");}
  for(unsigned n=1;n<=nh;++n){hash_calls=0;fail_hash=n;result=read(budget);fail_hash=0;Empty(result);Check(result.error==E::hash_failure,"retention multipart provider fault");}
  for(unsigned n=1;n<=nf;++n){full_calls=0;fail_full=n;result=read(budget);fail_full=0;Empty(result);Check(result.error==E::hash_failure,"retention full digest provider fault");}
  if(profile==0){for(unsigned long n=0;n<=na;++n){allocation_budget=n;result=read(budget);allocation_budget=-1;if(result.ok())Check(exact(result),"exact retained images after allocation recovery");else Empty(result);if(n==na)Check(result.ok(),"retention allocation terminal success");}std::cout<<"retention allocation sites="<<na<<" reads="<<nr<<" part hashes="<<nh<<" full hashes="<<nf<<std::endl;}
  for(unsigned n=0;n<12;++n){auto r=root,x=a,y=b;if(n==0)r.legal_hold_pins=0;if(n==1)r.lowest_start=3;if(n==2)r.highest_end=12;if(n==3)y.epoch++;if(n==4)y.creator_transaction_uuid=Id(99);if(n==5)y.creator_local_transaction_id++;if(n==6)y.flags=1;if(n==7)y.records[0].pin_uuid=x.records[0].pin_uuid;if(n==8)y.header.page_uuid=x.header.page_uuid;if(n==9)y.header.page_uuid=z1.page_uuid;if(n==10)y.header.page_generation++;if(n==11)y.first_record=0;persist(r,x,y);result=read(budget);Empty(result);if(n<=2)Check(result.error==E::summary_mismatch,"actual complete pin summaries recomputed");}
  auto by_class=b;by_class.records[0].kind=p::NativeRetentionKind::backup_forward;persist(root,a,by_class);Check(read(budget).ok(),"legal count includes legal access class independently");
  auto by_kind=b;by_kind.records[0].access=p::NativeRetentionAccess::recovery_only;persist(root,a,by_kind);Check(read(budget).ok(),"legal count includes legal pin kind independently");
  auto finite_root=root,finite_leaf=b;finite_root.highest_end=20;finite_leaf.records[0].end_local=20;persist(finite_root,a,finite_leaf);Check(read(budget).ok(),"actual maximum finite exclusive end");
  auto cycle_root=root,cycle_a=a,cycle_b=b;cycle_root.total_pins=cycle_a.total_pins=cycle_b.total_pins=3;cycle_b.next=reference;cycle_b.next_sha256.fill(1);persist(cycle_root,cycle_a,cycle_b);result=read(2*budget);Empty(result);Check(result.error==E::chain_mismatch,"actual physical retention cycle");
  auto out_of_range=root;out_of_range.next->page_number=64;persist(out_of_range,a,b);result=read(budget);Empty(result);Check(result.error==E::invalid_filespace,"actual leaf capacity is enforced");
  persist(root,a,b);auto altered=b;altered.records[0].retain_until_unix_ns=2;put(second,42,z2.bootstrap.page_size_bytes,Oracle(altered));result=read(budget);Empty(result);Check(result.error==E::invalid_integrity,"resealed successor still requires actual full image hash");
  auto empty=root;empty.total_pins=empty.legal_hold_pins=empty.lowest_start=empty.highest_end=0;empty.next.reset();persist(empty,a,b);result=read(z1.bootstrap.page_size_bytes);Check(result.ok()&&result.images.size()==1&&result.retained_image_bytes==z1.bootstrap.page_size_bytes,"actual empty root without inferred missing leaves");z2.bootstrap.database_uuid=Id(4);persist(empty,a,b);Empty(read(budget));z2.bootstrap.database_uuid=Id(1);
  persist(root,a,b);auto duplicate=devices;duplicate.push_back(devices[0]);Empty(p::ReadNativeRetentionRootFromOpenDevices(Id(1),duplicate,Id(120),reference,budget));auto missing=devices;missing.erase(missing.begin());Empty(p::ReadNativeRetentionRootFromOpenDevices(Id(1),missing,Id(120),reference,budget));
  Check(first.Close().ok()&&second.Close().ok()&&first.Open(path1,d::FileOpenMode::open_existing_read_only).ok()&&second.Open(path2,d::FileOpenMode::open_existing_read_only).ok(),"actual retention readonly reopen");Check(exact(read(budget))&&first.read_only()&&second.read_only(),"reopened exact retention pin set");
}}
}
int main(){try{Images();Chains();std::cout<<"retention image/chain checks="<<checks<<" failures=0\n";return 0;}catch(const std::exception& e){allocation_budget=-1;std::cerr<<"FAIL "<<e.what()<<" checks="<<checks<<'\n';return 1;}}
